'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Service}=require('../../lib/chartbro/service'),{Journal}=require('../../lib/chartbro/journal');
const config={enabled:true,venues:['okx'],interval_ms:3600000,timeframes:['4h'],volume_cut:false,flow:false};
const provider={venues:['okx'],instruments:async()=>[{symbol:'BTCUSDT',tick:.01}],tickers:async()=>[{symbol:'BTCUSDT',priceChangePercent:1,quoteVolume:1}]};
test('scheduled scan creates one durable job per slot and resumes without duplicate creation',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cb-bg-'));try{let now=7200001;const s=new Service({provider,journal:new Journal({dir}),now:()=>now});await s.scheduleScans(config);await s.scheduleScans(config);assert.equal(s.journal.all('jobs').length,1);assert.equal(s.journal.all('jobs')[0].volume_cut,false);const reloaded=new Service({provider,journal:new Journal({dir}),now:()=>now});await reloaded.scheduleScans(config);assert.equal(reloaded.journal.all('jobs').length,1);now+=3600000;await reloaded.scheduleScans(config);assert.equal(reloaded.journal.all('jobs').length,1);assert.ok(reloaded.journal.all('scheduled_runs').some(r=>r.state==='SKIPPED_BUSY'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('ephemeral runtime refuses scheduled background writes',async()=>{const s=new Service({provider});await assert.rejects(s.scheduleScans(config),/durable/i);assert.equal(s.journal.all('jobs').length,0);});
test('one failed exchange does not suppress another scheduled universe',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cb-bg-'));try{const p={...provider,instruments:async q=>{if(q.venue==='binance')throw Error('HTTP 418');return[{symbol:'BTCUSDT',tick:.01}];}},s=new Service({provider:p,journal:new Journal({dir}),now:()=>7200001});await s.scheduleScans({...config,venues:['binance','okx']});assert.equal(s.journal.all('jobs').length,1);assert.equal(s.journal.all('scheduled_runs').find(r=>r.venue==='binance').state,'FAILED');assert.equal(s.journal.all('jobs')[0].venue,'okx');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('outcome polling deduplicates instruments and includes 24h pending candidates',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cb-bg-'));try{const s=new Service({provider,journal:new Journal({dir}),now:()=>30*3600000});for(const id of ['a','b']){s.journal.put('candidates',id,{id,instrument:{venue:'okx',market:'perpetual',symbol:'BTCUSDT'},timeframe:'4h',known_at:0,engine_version:'v',config_hash:'c'});s.journal.put('candidate_observations',id,{id,candidate_id:id,state:'TRIGGER_CONFIRMED',trigger_at:1,last_closed_bar_at:1,decision_at:2});}let calls=0;s.analysis=async q=>{calls++;assert.equal(q.venue,'okx');assert.equal(q.tf,'4h');return{};};await s.pollOutcomes({interval_ms:3600000,limit:2});await s.pollOutcomes({interval_ms:3600000,limit:2});assert.equal(calls,1);assert.equal(s.journal.all('outcome_polling').length,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
