'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Journal}=require('../../lib/chartbro/journal'),{Service}=require('../../lib/chartbro/service'),T=require('../../lib/chartbro/temporal');
function row(i){const t=Date.UTC(2026,0,1)+i*300000,c=100+Math.sin(i);return [t,c,c+1,c-1,c,10,t+299999,1000,1,5,500];}
function provider(){return {bars:async()=>Array.from({length:35},(_,i)=>row(i)),instruments:async()=>[{symbol:'BTCUSDT',tick:.01},{symbol:'ETHUSDT',tick:.01}],tickers:async()=>[{symbol:'BTCUSDT',quoteVolume:20000000,priceChangePercent:1}]};}
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cb-'));return {dir,journal:new Journal({dir}),cleanup:()=>fs.rmSync(dir,{recursive:true,force:true})};}
test('journal is append-only idempotent and reloads projections',()=>{const f=fixture();try{f.journal.put('x','a',{v:1});f.journal.put('x','a',{v:1});assert.equal(f.journal.all('x').length,1);assert.throws(()=>f.journal.put('x','a',{v:2}),/immutable/);assert.deepEqual(new Journal({dir:f.dir}).get('x','a'),{v:1});}finally{f.cleanup();}});
test('analysis snapshots remain immutable with complete instrument identity',async()=>{const f=fixture();try{const s=new Service({provider:provider(),journal:f.journal,now:()=>Date.UTC(2026,0,2)}),a=await s.analysis({symbol:'BTCUSDT',tf:'5m'}),b=await s.analysis({symbol:'BTCUSDT',tf:'5m',at:row(20)[6]});assert.notEqual(a.analysis_id,b.analysis_id);assert.ok(a.dataset_version);assert.equal(s.getAnalysis(a.analysis_id).decision_at,a.decision_at);}finally{f.cleanup();}});
test('cancel/resume checkpoints preserve results without duplicates',async()=>{const f=fixture();try{const s=new Service({provider:provider(),journal:f.journal,now:()=>Date.UTC(2026,0,2)}),j=await s.createJob({symbols:['BTCUSDT','ETHUSDT'],tf:'5m'});s.cancel(j.id);assert.equal((await s.stepJob(j.id)).state,'CANCELLED');s.resume(j.id);await s.stepJob(j.id);await s.stepJob(j.id);await s.stepJob(j.id);assert.equal(s.getJob(j.id).state,'COMPLETED');assert.equal(s.results(j.id).length,2);assert.equal(new Service({provider:provider(),journal:new Journal({dir:f.dir})}).results(j.id).length,2);}finally{f.cleanup();}});
test('all provider failures produce FAILED rather than zero-candidate success',async()=>{const f=fixture();try{const p=provider();p.bars=async()=>{throw new Error('HTTP 429')};const s=new Service({provider:p,journal:f.journal}),j=await s.createJob({symbols:['BTCUSDT'],tf:'5m'});await s.stepJob(j.id);await s.stepJob(j.id);assert.equal(s.getJob(j.id).state,'FAILED');assert.equal(s.getJob(j.id).success,0);assert.equal(s.getJob(j.id).failures,1);}finally{f.cleanup();}});
test('AMD honors range known_at and preserves failure',()=>{const range={lower:99,upper:101,known_at:100,id:'r'},bars=[{close_time:50,low:98,high:102,close:100},{close_time:200,low:98,high:101,close:100},{close_time:300,low:100,high:106,close:105}],events=[{type:'MSS',side:'long',known_at:300,id:'e'}];const x=T.pathModel(range,bars,events);assert.equal(x.events[0].known_at,200);assert.equal(x.state,'EXPANSION_CONFIRMED');});
test('matrix returns explicit partial data within its aggregate deadline',async()=>{const f=fixture();try{const p=provider();p.bars=async()=>new Promise(()=>{});const s=new Service({provider:p,journal:f.journal}),start=Date.now(),m=await s.matrix({symbol:'BTCUSDT',deadline_ms:30});assert.ok(Date.now()-start<300);assert.equal(m.partial,true);assert.ok(Object.keys(m.errors).length);}finally{f.cleanup();}});
test('request deadline includes queue waiting without starting abandoned fetch',async()=>{const {Provider}=require('../../lib/chartbro/provider');let count=0;const p=new Provider({pace_ms:0,fetchImpl:async(_,o)=>{count++;await new Promise((resolve,reject)=>{o.signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})));});}}),one=p.request('spot','/first',{deadline:40}).catch(()=>null),start=Date.now();await assert.rejects(p.request('spot','/second',{deadline:10}),/deadline/);assert.ok(Date.now()-start<100);await one;assert.equal(count,1);});
test('default full scan checkpoints independent timeframes before reporting a symbol',async()=>{const f=fixture();try{const s=new Service({provider:provider(),journal:f.journal,now:()=>Date.UTC(2026,0,2)}),j=await s.createJob({symbols:['BTCUSDT']});assert.deepEqual(j.timeframes,['1w','1d','12h','4h','1h','15m','5m']);await s.stepJob(j.id);assert.equal(s.getJob(j.id).processed,0);for(let i=0;i<8;i++)await s.stepJob(j.id);assert.equal(s.getJob(j.id).processed,1);assert.equal(s.results(j.id)[0].frames.length,7);}finally{f.cleanup();}});
test('candidate cohort preserves observed and invalidated setups rather than only successes',async()=>{const f=fixture();try{const s=new Service({provider:provider(),journal:f.journal});s.saveCandidates({analysis_id:'a',instrument:{symbol:'BTCUSDT'},engine_version:'v',dataset_version:'d',config_hash:'c',decision_at:100,setups:[{id:'s',episode_id:'e',known_at:10,state:'INVALIDATED',side:'long',range_id:'r',sweep_event_id:'sw',invalidation_level:95}],events:[]});assert.equal(f.journal.all('candidates').length,1);assert.equal(f.journal.all('candidate_observations')[0].state,'INVALIDATED');}finally{f.cleanup();}});
test('failed disk append never leaves a falsely durable in-memory record',()=>{const f=fixture();try{f.journal.file=path.join(f.dir,'nonexistent','events');assert.throws(()=>f.journal.put('x','bad',{v:1}),/ENOENT/);assert.equal(f.journal.get('x','bad'),null);}finally{f.cleanup();}});
test('exact historical cutoffs inside same minute never alias a cached snapshot',async()=>{const f=fixture();try{const s=new Service({provider:provider(),journal:f.journal,now:()=>Date.UTC(2026,0,2)}),end=row(20)[6],a=await s.analysis({symbol:'BTCUSDT',tf:'5m',at:end-999}),b=await s.analysis({symbol:'BTCUSDT',tf:'5m',at:end});assert.equal(b.bars.length,a.bars.length+1);}finally{f.cleanup();}});
