'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Provider}=require('../../lib/chartbro/provider'),{Service}=require('../../lib/chartbro/service'),{Journal}=require('../../lib/chartbro/journal');
const response=(status,body,after=null)=>({status,ok:status===200,headers:{get:k=>k==='retry-after'?after:null},json:async()=>body});
test('418 records Retry-After and suppresses queued/new requests until ban expires',async()=>{let now=100000,calls=0;const p=new Provider({pace_ms:0,now:()=>now,fetchImpl:async()=>{calls++;return calls===1?response(418,{msg:'banned until 130000'},'30'):response(200,[]);}});const one=p.request('perpetual','/first'),two=p.request('perpetual','/second');const results=await Promise.allSettled([one,two]);assert.ok(results.every(x=>x.status==='rejected'));assert.equal(calls,1);assert.equal(results[0].reason.retry_at,130000);assert.equal(results[0].reason.code,'BINANCE_COOLDOWN');now=130001;await p.request('perpetual','/third');assert.equal(calls,2);});
test('429 stops retries and honors the later body/header retry time',async()=>{const p=new Provider({pace_ms:0,now:()=>1700000000000,fetchImpl:async()=>response(429,{msg:'IP banned until 1700000120000'},'60')});await assert.rejects(p.request('perpetual','/first'),e=>e.code==='BINANCE_COOLDOWN'&&e.retry_at===1700000120000);});
test('requests within same closed bar share raw candles without historical future leakage',async()=>{let calls=0,url;const p=new Provider({pace_ms:0,fetchImpl:async u=>{calls++;url=u;return response(200,[]);}}),at=Date.UTC(2026,0,1,5,3);await p.bars({symbol:'BTCUSDT',tf:'4h',at});await p.bars({symbol:'BTCUSDT',tf:'4h',at:at+1000});assert.equal(calls,1);assert.equal(+new URL(url).searchParams.get('endTime'),Date.UTC(2026,0,1,4)-1);});
function row(i){const t=Date.UTC(2026,0,1)+i*300000;return[t,100,101,99,100,10,t+299999,1000,1,5,500];}
function fixture(){let now=Date.UTC(2026,0,1,5),calls=0,fail=false;const provider={instruments:async()=>{calls++;if(fail)throw Object.assign(Error('Binance cooldown'),{code:'BINANCE_COOLDOWN',retry_at:now+60000,upstream_status:418,statusCode:503});return[{symbol:'BTCUSDT',tick:.01}];},bars:async()=>Array.from({length:35},(_,i)=>row(i))};return {service:new Service({provider,journal:new Journal(),now:()=>now}),advance:(ms=40000)=>now+=ms,ban:()=>fail=true,get calls(){return calls;}};}
test('live refresh reuses snapshot while explicit historical cutoffs remain exact',async()=>{const f=fixture(),a=await f.service.analysis({symbol:'BTCUSDT',tf:'5m'});f.advance(1000);const b=await f.service.analysis({symbol:'BTCUSDT',tf:'5m'});assert.equal(a.analysis_id,b.analysis_id);assert.equal(f.calls,1);const h=await f.service.analysis({symbol:'BTCUSDT',tf:'5m',at:row(20)[6]-1});assert.equal(h.bars.length,20);});
test('blocked live request returns same-instrument last success as explicitly stale without mutating stored snapshot',async()=>{const f=fixture(),a=await f.service.analysis({symbol:'BTCUSDT',tf:'5m'});f.advance();f.ban();const b=await f.service.analysis({symbol:'BTCUSDT',tf:'5m'});assert.equal(b.analysis_id,a.analysis_id);assert.equal(b.stale,true);assert.equal(b.data_quality.price,'stale');assert.equal(b.operational.eligible_for_confirmation,false);assert.equal(f.service.getAnalysis(a.analysis_id).stale,undefined);await assert.rejects(f.service.analysis({symbol:'ETHUSDT',tf:'5m'}),/cooldown/);await assert.rejects(f.service.analysis({symbol:'BTCUSDT',tf:'5m',at:row(20)[6]}),/cooldown/);});
