(function(root,factory){const presentation=typeof module==='object'&&module.exports?require('../../multi-chart/ict-presentation'):root?.PulseIctPresentation;const collision=typeof module==='object'&&module.exports?require('../collision-policy'):root?.PulseCollisionPolicy;const shape=typeof module==='object'&&module.exports?require('../shape-overlay'):root?.PulseShapeOverlay;const api=factory(presentation,collision,shape);if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseIctPlugin=api;})(typeof globalThis!=='undefined'?globalThis:this,function(Presentation,CollisionPolicy,Shape){'use strict';
  function createIctPlugin(){let ctx=null,visible=true,series=[],markers=null,lastState=null;const sec=v=>{v=Number(v);return Math.trunc(v>1e12?v/1000:v)};
    function clear(){if(markers){try{markers.detach?.()}catch{}markers=null}for(const s of series){try{ctx?.chart?.removeSeries(s)}catch{}}series=[];try{Shape?.clearLayer?.(ctx,'ict')}catch{}}
    function zoneMatch(smc,event){const kind=String(event?.type||'').toUpperCase();const src=kind==='OB'?(smc?.orderBlocks||[]):kind==='BREAKER'?(smc?.breakers||[]):(smc?.fvgs||[]);if(!src.length)return null;const i=Number(event?.index);return src.filter(z=>!['violated','expired'].includes(z.state)).sort((a,b)=>Math.abs(Number(a.index)-i)-Math.abs(Number(b.index)-i))[0]||null}
    function drawBeginner(state,ict,p,candles){
      if(!Shape?.canDraw?.(ctx))return false;const layer=Shape.ensureLayer(ctx,'ict',7);if(!layer)return false;const svg=layer.svg,w=layer.w;
      Shape.setLayerOpacity(ctx,'ict',state.overlayFocus&&state.overlayFocus!=='ict'?.25:1);
      const startIndex=Math.max(0,candles.length-80),startTime=candles[startIndex]?.time,endTime=candles.at(-1)?.time;if(startTime==null||endTime==null)return true;
      const premium=p.bands.find(x=>x.kind==='PREMIUM'),discount=p.bands.find(x=>x.kind==='DISCOUNT'),ote=p.bands.find(x=>x.kind==='OTE');
      if(premium)Shape.zone(ctx,svg,startTime,endTime,premium.range[0],premium.range[1],{fill:'#ff6577',fillOpacity:.035,stroke:'#ff6577',strokeOpacity:.12,width:1});
      if(discount)Shape.zone(ctx,svg,startTime,endTime,discount.range[0],discount.range[1],{fill:'#35d69a',fillOpacity:.04,stroke:'#35d69a',strokeOpacity:.12,width:1});
      if(ote)Shape.zone(ctx,svg,startTime,endTime,ote.range[0],ote.range[1],{fill:'#9b7cf5',fillOpacity:.08,stroke:'#9b7cf5',strokeOpacity:.65,width:1,dash:'5 4'});
      const seq=(ict.sequences||[]).at(-1),events=seq?.events||[];if(!events.length)return true;
      const sweep=events.find(e=>String(e.type).toUpperCase()==='SWEEP');
      const impulse=events.find(e=>String(e.type).toUpperCase()==='DISPLACEMENT')||events.find(e=>String(e.type).toUpperCase()==='MSS');
      const zoneEv=events.find(e=>['FVG','OB','VOID','BREAKER'].includes(String(e.type).toUpperCase()));
      const mitigation=events.find(e=>String(e.type).toUpperCase()==='MITIGATION');
      const pts=[];
      function eventPoint(e,n,color){
        if(!e)return null;const i=Math.max(0,Number(e.index)||0),c=candles[i];if(!c)return null;const dir=String(e.direction||seq?.direction||'up').toLowerCase(),up=dir!=='down',x=Shape.xFor(ctx,c.time),price=up?(c.low??c.close):(c.high??c.close),y=Shape.yFor(ctx,price);if(x==null||y==null)return null;const by=y+(up?14:-14);Shape.badge(svg,x,by,n,{color,r:9});pts.push([x,by]);return{x,y,by,c,up};
      }
      const p1=eventPoint(sweep,1,'#67d9ff');if(p1){Shape.circle(svg,p1.x,p1.y,5,{fill:'#07101a',stroke:'#67d9ff',width:2});Shape.arrow(svg,p1.x,p1.y+(p1.up?12:-12),p1.x,p1.y+(p1.up?-18:18),{stroke:'#67d9ff',width:2.2})}
      const p2=eventPoint(impulse,2,'#35d69a');if(p2){Shape.candleBox(ctx,svg,p2.c,{fill:p2.up?'#35d69a':'#ff6577',opacity:.18});Shape.arrow(svg,p2.x-10,p2.y+(p2.up?8:-8),p2.x+10,p2.y+(p2.up?-14:14),{stroke:p2.up?'#35d69a':'#ff6577',width:2.2})}
      const p3=eventPoint(zoneEv,3,'#4f8cff'),zone=zoneMatch(state.smc,zoneEv);if(zone){const zi=Math.max(0,Number(zone.index)||0),zt=candles[zi]?.time||startTime;Shape.zone(ctx,svg,zt,endTime,zone.low,zone.high,{fill:'#4f8cff',fillOpacity:.12,stroke:'#4f8cff',strokeOpacity:.78,width:1.4,dash:'4 3'})}
      const p4=eventPoint(mitigation,4,'#ffc45f');if(p4)Shape.circle(svg,p4.x,p4.y,5,{fill:'#ffc45f',fillOpacity:.16,stroke:'#ffc45f',width:2});
      const current=Number(candles.at(-1)?.close),dir=String(seq.direction||impulse?.direction||'up').toLowerCase(),levels=(state.liquidity?.levels||[]).filter(l=>Number.isFinite(Number(l.price))&&(dir==='down'?Number(l.price)<current:Number(l.price)>current)).sort((a,b)=>Math.abs(Number(a.price)-current)-Math.abs(Number(b.price)-current));
      const target=levels[0];if(target){const color='#d88cff',y=Shape.yFor(ctx,target.price);Shape.priceBand(ctx,svg,target.price,{x1:w*.58,x2:w-8,height:9,fill:color,opacity:.12,stroke:color,dash:'5 4'});if(y!=null){Shape.badge(svg,w-18,y,5,{color,r:9});pts.push([w-18,y])}}
      if(pts.length>1)Shape.polyline(svg,pts,{stroke:'#9fb6cc',width:1.2,opacity:.5,dash:'4 5'});
      return true;
    }
    function line(value,start,end,width=1,style=2,color){if(!Number.isFinite(Number(value))||!start||!end)return;const s=ctx.addLineSeries({lineWidth:width,lineStyle:style,color});s.setData([{time:start,value:Number(value)},{time:end,value:Number(value)}]);series.push(s)}
    function candidatePrice(candles,a){const c=candles?.[a.barIndex]||{};return Number(a.side==='above'?(c.high??c.close):(c.low??c.close))||0}
    function layoutAnnotations(annotations,candles,state){if(!state?.viewportLevel||!CollisionPolicy?.layoutMarkerCandidates||!ctx?.chart?.timeScale||!ctx?.candlesSeries?.priceToCoordinate)return annotations;try{const prepared=annotations.map(a=>({...a,price:candidatePrice(candles,a),viewportLevel:state.viewportLevel,metadata:{...(a.metadata||{}),presentation:a}}));const result=CollisionPolicy.layoutMarkerCandidates(prepared,{mode:'ict',viewportLevel:state.viewportLevel,width:Number(ctx?.container?.clientWidth)||1024,height:Number(ctx?.container?.clientHeight)||480,xForBar:i=>{const t=sec(candles?.[i]?.time);const x=ctx.chart.timeScale().timeToCoordinate(t);return Number.isFinite(Number(x))?Number(x):i*10},yForPrice:p=>{const y=ctx.candlesSeries.priceToCoordinate(Number(p));return Number.isFinite(Number(y))?Number(y):Number(p)}});return result.visible.map(v=>v.metadata.presentation)}catch{return annotations}}
    return{id:'ict',version:'3.0.0',requiredData:['candles','ictContext'],mount(c){ctx=c},update(state={}){lastState=state;clear();if(!ctx||!visible)return;const ict=state.ictContext;if(!ict||!Presentation?.buildIctPresentation)return;const compact=(['clean','compact'].includes(state.smartOverlayMode)||state.viewportLevel==='compact')&&state.overlayFocus!=='ict',candles=state.rawCandles||state.candles||[],end=sec(candles.at(-1)?.time),start=sec(candles[Math.max(0,candles.length-80)]?.time||candles[0]?.time);if(!end||!start)return;const p=Presentation.buildIctPresentation(ict);if(drawBeginner(state,ict,p,candles))return;const premium=p.bands.find(x=>x.kind==='PREMIUM'),discount=p.bands.find(x=>x.kind==='DISCOUNT'),ote=p.bands.find(x=>x.kind==='OTE');if(!compact){if(premium){line(premium.range[1],start,end,1,2,'#ff6577');line(premium.range[0],start,end,1,3,'#8ba5c4')}if(discount)line(discount.range[0],start,end,1,2,'#4fd1c5')}if(ote){line(ote.range[0],start,end,1,3,'#9b7cf5');line(ote.range[1],start,end,1,3,'#9b7cf5')}
      if(ctx?.library?.createSeriesMarkers&&ctx.candlesSeries){let selected=layoutAnnotations(p.annotations,candles,state);if(compact)selected=selected.slice(-1);const marks=selected.filter(a=>candles?.[a.barIndex]).map(a=>({time:sec(candles[a.barIndex].time),position:a.side==='above'?'aboveBar':'belowBar',shape:'circle',text:a.label,color:a.label.startsWith('①')?'#f7c55f':a.label.startsWith('②')?'#4fd1c5':a.label.startsWith('③')?'#9b7cf5':a.label.startsWith('④')?'#6aa7ff':'#c4b5fd'}));if(marks.length)markers=ctx.library.createSeriesMarkers(ctx.candlesSeries,marks,{autoScale:false})}
    },setVisible(v){visible=!!v;if(!visible)clear();else if(lastState)this.update(lastState)},dispose(){clear();lastState=null;ctx=null}}}
  return{createIctPlugin};
});