(function(root,factory){const presentation=typeof module==='object'&&module.exports?require('../../multi-chart/ict-presentation'):root?.PulseIctPresentation;const collision=typeof module==='object'&&module.exports?require('../collision-policy'):root?.PulseCollisionPolicy;const api=factory(presentation,collision);if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseIctPlugin=api;})(typeof globalThis!=='undefined'?globalThis:this,function(Presentation,CollisionPolicy){'use strict';
  function createIctPlugin(){let ctx=null,visible=true,series=[],markers=null;const sec=v=>{v=Number(v);return Math.trunc(v>1e12?v/1000:v)};
    function clear(){if(markers){try{markers.detach?.()}catch{}markers=null}for(const s of series){try{ctx?.chart?.removeSeries(s)}catch{}}series=[]}
    function line(value,start,end,width=1,style=2,color){if(!Number.isFinite(Number(value))||!start||!end)return;const s=ctx.addLineSeries({lineWidth:width,lineStyle:style,color});s.setData([{time:start,value:Number(value)},{time:end,value:Number(value)}]);series.push(s)}
    function candidatePrice(candles,a){const c=candles?.[a.barIndex]||{};return Number(a.side==='above'?(c.high??c.close):(c.low??c.close))||0}
    function layoutAnnotations(annotations,candles,state){if(!state?.viewportLevel||!CollisionPolicy?.layoutMarkerCandidates||!ctx?.chart?.timeScale||!ctx?.candlesSeries?.priceToCoordinate)return annotations;try{const prepared=annotations.map(a=>({...a,price:candidatePrice(candles,a),viewportLevel:state.viewportLevel,metadata:{...(a.metadata||{}),presentation:a}}));const result=CollisionPolicy.layoutMarkerCandidates(prepared,{mode:'ict',viewportLevel:state.viewportLevel,width:Number(ctx?.container?.clientWidth)||1024,height:Number(ctx?.container?.clientHeight)||480,xForBar:i=>{const t=sec(candles?.[i]?.time);const x=ctx.chart.timeScale().timeToCoordinate(t);return Number.isFinite(Number(x))?Number(x):i*10},yForPrice:p=>{const y=ctx.candlesSeries.priceToCoordinate(Number(p));return Number.isFinite(Number(y))?Number(y):Number(p)}});return result.visible.map(v=>v.metadata.presentation)}catch{return annotations}}
    return{id:'ict',version:'2.0.0',requiredData:['candles','ictContext'],mount(c){ctx=c},update(state={}){clear();if(!ctx||!visible)return;const ict=state.ictContext;if(!ict||!Presentation?.buildIctPresentation)return;const candles=state.rawCandles||state.candles||[],end=sec(candles.at(-1)?.time),start=sec(candles[Math.max(0,candles.length-80)]?.time||candles[0]?.time);if(!end||!start)return;const p=Presentation.buildIctPresentation(ict);const premium=p.bands.find(x=>x.kind==='PREMIUM'),discount=p.bands.find(x=>x.kind==='DISCOUNT'),ote=p.bands.find(x=>x.kind==='OTE');if(premium){line(premium.range[1],start,end,1,2,'#ff6577');line(premium.range[0],start,end,1,3,'#8ba5c4')}if(discount)line(discount.range[0],start,end,1,2,'#4fd1c5');if(ote){line(ote.range[0],start,end,1,3,'#9b7cf5');line(ote.range[1],start,end,1,3,'#9b7cf5')}
      if(ctx?.library?.createSeriesMarkers&&ctx.candlesSeries){const selected=layoutAnnotations(p.annotations,candles,state);const marks=selected.filter(a=>candles?.[a.barIndex]).map(a=>({time:sec(candles[a.barIndex].time),position:a.side==='above'?'aboveBar':'belowBar',shape:'circle',text:a.label,color:a.label.startsWith('①')?'#f7c55f':a.label.startsWith('②')?'#4fd1c5':a.label.startsWith('③')?'#9b7cf5':a.label.startsWith('④')?'#6aa7ff':'#c4b5fd'}));if(marks.length)markers=ctx.library.createSeriesMarkers(ctx.candlesSeries,marks,{autoScale:false})}
    },setVisible(v){visible=!!v;if(!visible)clear()},dispose(){clear();ctx=null}}}
  return{createIctPlugin};
});