(function(root,factory){const api=factory(root?.PulseRenderPolicy);if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseSmcPlugin=api;})(typeof globalThis!=='undefined'?globalThis:this,function(RenderPolicy){
  function createSmcPlugin(){let ctx=null,visible=true,series=[],markers=null;const sec=v=>{v=Number(v);return Math.trunc(v>1e12?v/1000:v)};
    function clear(){if(markers){try{markers.detach?.()}catch{}markers=null}for(const s of series){try{ctx?.chart?.removeSeries(s)}catch{}}series=[]}
    function policyFor(preset){const w=typeof innerWidth==='number'?innerWidth:1024;if(RenderPolicy?.getRenderPolicy){const p=RenderPolicy.getRenderPolicy(preset?.id||'clean',w),explicit=Number(preset?.maxZones);return Number.isFinite(explicit)?{...p,maxZones:Math.min(p.maxZones,Math.max(0,explicit))}:p}return{maxZones:Number(preset?.maxZones)||3,maxSweeps:3,maxStructure:6,hideTerminal:preset?.id!=='full',mergeEqualLevels:true}}
    function center(z){return Number(z.ce??((Number(z.low)+Number(z.high))/2))}
    function pickZones(smc,preset,candles,policy){const price=Number(candles?.at(-1)?.close)||0,all=[...(smc?.orderBlocks||[]),...(smc?.fvgs||[]),...(smc?.breakers||[])];const ranked=RenderPolicy?.selectPriorityItems?RenderPolicy.selectPriorityItems(all,policy,price):all.filter(z=>!policy.hideTerminal||!['violated','expired'].includes(z.state)).sort((a,b)=>Number(b.index||0)-Number(a.index||0));return ranked.slice(0,Math.max(0,policy.maxZones||0))}
    function line(value,start,end,width=1,style=2){const s=ctx.addLineSeries({lineWidth:width,lineStyle:style});s.setData([{time:start,value:Number(value)},{time:end,value:Number(value)}]);series.push(s)}
    function renderMarkers(smc,candles,policy){if(!ctx?.library?.createSeriesMarkers||!ctx.candlesSeries)return;const mss=(smc?.mss||[]).slice(-2).map(x=>({i:x.index,priority:0,position:x.dir==='up'?'belowBar':'aboveBar',shape:x.dir==='up'?'arrowUp':'arrowDown',text:'MSS',color:x.dir==='up'?'#35d69a':'#ff6577'}));const sweeps=(smc?.sweeps||[]).slice(-Math.max(0,policy.maxSweeps||0)).map(x=>({i:x.index,priority:1,position:x.dir==='up'?'belowBar':'aboveBar',shape:'circle',text:x.dir==='up'?'S↑':'S↓',color:x.dir==='up'?'#4fd1c5':'#ffc45f'}));let eq=smc?.equalLevels||[];if(policy.mergeEqualLevels&&RenderPolicy?.mergeEqualLevels)eq=RenderPolicy.mergeEqualLevels(eq);eq=eq.slice(-2).map(x=>({i:x.lastIndex,priority:2,position:x.type==='EQH'?'aboveBar':'belowBar',shape:'circle',text:x.type,color:'#8ba5c4'}));const out=[...mss,...sweeps,...eq].filter(x=>candles?.[x.i]).sort((a,b)=>a.priority-b.priority||b.i-a.i).slice(0,Math.max(1,(policy.maxSweeps||0)+3)).sort((a,b)=>a.i-b.i).map(x=>({time:sec(candles[x.i].time),position:x.position,shape:x.shape,text:x.text,color:x.color}));markers=ctx.library.createSeriesMarkers(ctx.candlesSeries,out,{autoScale:false})}
    return{id:'smc',version:'2.1.1',requiredData:['candles','smc'],mount(c){ctx=c},update(state){clear();if(!ctx||!visible)return;const smc=state?.smc||{},preset=state?.preset||{id:'clean',maxZones:1},candles=state?.rawCandles||state?.candles||[];if(!['smc','full'].includes(preset.id))return;const policy=policyFor(preset),end=sec(candles.at(-1)?.time);if(!end)return;for(const z of pickZones(smc,preset,candles,policy)){const start=sec(candles[z.index]?.time);if(!start)continue;line(z.low,start,end,1,2);line(z.high,start,end,1,2);if(Number.isFinite(center(z))&&z.state==='active')line(center(z),start,end,1,3)}const pd=smc.pdOte;if(pd?.available){const start=sec(candles[Math.max(0,candles.length-80)]?.time||candles[0]?.time);line(pd.equilibrium,start,end,1,3);if(preset.id==='full'){line(pd.oteLow,start,end,1,3);line(pd.oteHigh,start,end,1,3)}}renderMarkers(smc,candles,policy)},setVisible(v){visible=!!v;if(!visible)clear()},dispose(){clear();ctx=null}}}
  return{createSmcPlugin};
});