(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseSmcPlugin=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  function createSmcPlugin(){let ctx=null,visible=true,series=[],markers=null;const sec=v=>{v=Number(v);return Math.trunc(v>1e12?v/1000:v)};
    function clear(){if(markers){try{markers.detach?.()}catch{}markers=null}for(const s of series){try{ctx?.chart?.removeSeries(s)}catch{}}series=[]}
    function stateRank(s){return({active:0,approaching:1,touched:2,mitigated:3,violated:4,expired:5})[s]??6}
    function pickZones(smc,preset,candles){const price=Number(candles?.at(-1)?.close)||0,max=Math.max(0,Number(preset?.maxZones)||3),all=[...(smc?.orderBlocks||[]),...(smc?.fvgs||[]),...(smc?.breakers||[])].filter(z=>preset?.id==='full'||!['violated','expired'].includes(z.state));return all.sort((a,b)=>(Number(b.index)-Number(a.index))||(Number(b.quality||0)-Number(a.quality||0))||(stateRank(a.state)-stateRank(b.state))||((Math.abs(((Number(a.ce)||((Number(a.low)+Number(a.high))/2))-price)/(price||1)))-(Math.abs(((Number(b.ce)||((Number(b.low)+Number(b.high))/2))-price)/(price||1))))).slice(0,max)}
    function line(value,start,end,width=1){const s=ctx.addLineSeries({lineWidth:width,lineStyle:2});s.setData([{time:start,value:Number(value)},{time:end,value:Number(value)}]);series.push(s)}
    function renderMarkers(smc,candles,budget){if(!ctx?.library?.createSeriesMarkers||!ctx.candlesSeries)return;const m=[];for(const x of smc?.mss||[])m.push({i:x.index,position:x.dir==='up'?'belowBar':'aboveBar',shape:x.dir==='up'?'arrowUp':'arrowDown',text:'MSS'});for(const x of smc?.sweeps||[])m.push({i:x.index,position:x.dir==='up'?'belowBar':'aboveBar',shape:'circle',text:'SWP'});for(const x of smc?.equalLevels||[])m.push({i:x.lastIndex,position:x.type==='EQH'?'aboveBar':'belowBar',shape:'circle',text:x.type});const out=m.filter(x=>candles?.[x.i]).sort((a,b)=>b.i-a.i).slice(0,Math.max(0,budget)).reverse().map(x=>({time:sec(candles[x.i].time),position:x.position,shape:x.shape,text:x.text}));markers=ctx.library.createSeriesMarkers(ctx.candlesSeries,out)}
    return{id:'smc',version:'2.0.0',requiredData:['candles','smc'],mount(c){ctx=c},update(state){clear();if(!ctx||!visible)return;const smc=state?.smc||{},preset=state?.preset||{id:'clean',maxZones:3},candles=state?.rawCandles||state?.candles||[];if(!['smc','full'].includes(preset.id))return;const end=sec(candles.at(-1)?.time);if(!end)return;for(const z of pickZones(smc,preset,candles)){const start=sec(candles[z.index]?.time);if(!start)continue;line(z.low,start,end,1);line(z.high,start,end,1);if(Number.isFinite(Number(z.ce)))line(z.ce,start,end,1)}const pd=smc.pdOte;if(pd?.available){const start=sec(candles[Math.max(0,candles.length-120)]?.time||candles[0]?.time);line(pd.equilibrium,start,end,1);line(pd.oteLow,start,end,1);line(pd.oteHigh,start,end,1)}renderMarkers(smc,candles,preset.maxZones)},setVisible(v){visible=!!v;if(!visible)clear()},dispose(){clear();ctx=null}}}
  return{createSmcPlugin};
});