(function(root,factory){const cp=typeof module==='object'&&module.exports?require('../collision-policy'):root?.PulseCollisionPolicy;const shape=typeof module==='object'&&module.exports?require('../shape-overlay'):root?.PulseShapeOverlay;const api=factory(root?.PulseRenderPolicy,cp,shape);if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseSmcPlugin=api;})(typeof globalThis!=='undefined'?globalThis:this,function(RenderPolicy,CollisionPolicy,Shape){
  function createSmcPlugin(){let ctx=null,visible=true,series=[],markers=null,lastState=null;const sec=v=>{v=Number(v);return Math.trunc(v>1e12?v/1000:v)};
    function clear(){if(markers){try{markers.detach?.()}catch{}markers=null}for(const s of series){try{ctx?.chart?.removeSeries(s)}catch{}}series=[];try{Shape?.clearLayer?.(ctx,'smc')}catch{}}
    function policyFor(preset){const w=typeof innerWidth==='number'?innerWidth:1024;if(RenderPolicy?.getRenderPolicy){const p=RenderPolicy.getRenderPolicy(preset?.id||'clean',w),explicit=Number(preset?.maxZones);return Number.isFinite(explicit)?{...p,maxZones:Math.min(p.maxZones,Math.max(0,explicit))}:p}return{maxZones:Number(preset?.maxZones)||3,maxSweeps:3,maxStructure:6,hideTerminal:preset?.id!=='full',mergeEqualLevels:true}}
    function center(z){return Number(z.ce??((Number(z.low)+Number(z.high))/2))}
    function pickZones(smc,preset,candles,policy){const price=Number(candles?.at(-1)?.close)||0,all=[...(smc?.orderBlocks||[]),...(smc?.fvgs||[]),...(smc?.breakers||[])];const ranked=RenderPolicy?.selectPriorityItems?RenderPolicy.selectPriorityItems(all,policy,price):all.filter(z=>!policy.hideTerminal||!['violated','expired'].includes(z.state)).sort((a,b)=>Number(b.index||0)-Number(a.index||0));return ranked.slice(0,Math.max(0,policy.maxZones||0))}
    function line(value,start,end,width=1,style=2){const s=ctx.addLineSeries({lineWidth:width,lineStyle:style});s.setData([{time:start,value:Number(value)},{time:end,value:Number(value)}]);series.push(s)}
    function eventIndexes(analysis,candles){const out=[];for(const e of (analysis?.events||[])){let i=Number(e.index??e.eventIndex);if(!Number.isFinite(i)){const t=sec(e.eventTime||e.time);i=(candles||[]).findIndex(c=>sec(c?.time)===t)}if(i>=0)out.push(i)}return out}
    function markerPrice(candles,i,position){const c=candles?.[i]||{};return Number(position==='aboveBar'?(c.high??c.close):(c.low??c.close))||0}
    function layoutMarkers(raw,candles,preset,state){const mobile=typeof innerWidth==='number'&&innerWidth<=760;const cap=Math.max(1,(preset.maxSweeps||0)+3);const legacyFallback=()=>{let candidates=raw.map(x=>x.legacy).filter(x=>candles?.[x.i]);if(CollisionPolicy?.selectNonCollidingMarkers)candidates=CollisionPolicy.selectNonCollidingMarkers(candidates,{minGapBars:mobile?1:0,maxItems:cap});else candidates=candidates.sort((a,b)=>a.priority-b.priority||b.i-a.i).slice(0,cap).sort((a,b)=>a.i-b.i);return candidates};if(!CollisionPolicy?.layoutMarkerCandidates||!ctx?.chart?.timeScale||!ctx?.candlesSeries?.priceToCoordinate)return legacyFallback();try{const viewport=state?.viewportLevel||((typeof innerWidth==='number'&&innerWidth<=620)?'compact':'normal');const candidates=raw.map(x=>({type:x.type,category:x.category,priority:x.layoutPriority,barIndex:x.legacy.i,price:markerPrice(candles,x.legacy.i,x.legacy.position),side:x.legacy.position==='aboveBar'?'above':'below',collisionGroup:'chart-label',allowOffset:true,maxOffset:24,viewportLevel:viewport,tf:state?.timeframe||state?.tf||'',sourceId:x.sourceId,width:x.width,height:18,metadata:{marker:x.legacy,crossGroupCollision:true}}));const result=CollisionPolicy.layoutMarkerCandidates(candidates,{mode:'smc',viewportLevel:viewport,width:Number(ctx?.container?.clientWidth)||1024,height:Number(ctx?.container?.clientHeight)||480,xForBar:i=>{const t=sec(candles?.[i]?.time);const x=ctx.chart.timeScale().timeToCoordinate(t);return Number.isFinite(Number(x))?Number(x):i*10},yForPrice:p=>{const y=ctx.candlesSeries.priceToCoordinate(Number(p));return Number.isFinite(Number(y))?Number(y):Number(p)}});return result.visible.map(v=>v.metadata.marker).slice(0,cap).sort((a,b)=>a.i-b.i)}catch{return legacyFallback()}}
    function renderMarkers(smc,candles,policy,analysis,state){if(!ctx?.library?.createSeriesMarkers||!ctx.candlesSeries)return;const mobile=typeof innerWidth==='number'&&innerWidth<=760,compact=['clean','compact'].includes(state?.smartOverlayMode)||state?.viewportLevel==='compact',reserved=mobile?eventIndexes(analysis,candles):[];const blocked=i=>reserved.some(r=>Math.abs(r-i)<=1);const raw=[];for(const x of (smc?.mss||[]).slice(compact?-1:-2)){const i=Number(x.index);if(blocked(i)||!candles?.[i])continue;const legacy={i,priority:0,position:x.dir==='up'?'belowBar':'aboveBar',shape:x.dir==='up'?'arrowUp':'arrowDown',text:'MSS',color:x.dir==='up'?'#35d69a':'#ff6577'};raw.push({type:'MSS',category:'smc',layoutPriority:24,sourceId:'smc:mss:'+i+':'+String(x.dir||''),width:34,legacy})}let sweepSrc=compact?[]:(smc?.sweeps||[]).slice(-Math.max(0,(policy.maxSweeps||0)*2));if(CollisionPolicy?.clusterDirectionalMarkers)sweepSrc=CollisionPolicy.clusterDirectionalMarkers(sweepSrc.map(x=>({i:Number(x.index),dir:x.dir})),{distanceBars:2});for(const x of sweepSrc.slice(-Math.max(0,policy.maxSweeps||0))){const i=Number(x.i??x.index);if(blocked(i)||!candles?.[i])continue;const legacy={i,priority:1,position:x.dir==='up'?'belowBar':'aboveBar',shape:'circle',text:x.label||(x.dir==='up'?'S↑':'S↓'),color:x.dir==='up'?'#4fd1c5':'#ffc45f'};raw.push({type:'SWEEP',category:'liquidity',layoutPriority:18,sourceId:'smc:sweep:'+i+':'+String(x.dir||''),width:Math.max(28,String(legacy.text).length*8),legacy})}let eq=compact?[]:(smc?.equalLevels||[]);if(policy.mergeEqualLevels&&RenderPolicy?.mergeEqualLevels)eq=RenderPolicy.mergeEqualLevels(eq);for(const x of eq.slice(-2)){const i=Number(x.lastIndex);if(blocked(i)||!candles?.[i])continue;const legacy={i,priority:2,position:x.type==='EQH'?'aboveBar':'belowBar',shape:'circle',text:x.type,color:'#8ba5c4'};raw.push({type:String(x.type||'EQH').toUpperCase(),category:'liquidity',layoutPriority:8,sourceId:'smc:eq:'+String(x.type||'')+':'+i,width:34,legacy})}const selected=layoutMarkers(raw,candles,policy,state);const out=selected.map(x=>({time:sec(candles[x.i].time),position:x.position,shape:x.shape,text:x.text,color:x.color}));markers=ctx.library.createSeriesMarkers(ctx.candlesSeries,out,{autoScale:false})}
    function drawBeginner(state,smc,candles,preset,policy,compact){
      if(!Shape?.canDraw?.(ctx))return false;const layer=Shape.ensureLayer(ctx,'smc',6);if(!layer)return false;const svg=layer.svg,endTime=candles.at(-1)?.time,startTime=candles[Math.max(0,candles.length-80)]?.time;if(endTime==null||startTime==null)return true;
      Shape.setLayerOpacity(ctx,'smc',state?.overlayFocus&&state.overlayFocus!=='smc'?.24:1);
      const pd=smc.pdOte;if(pd?.available){
        Shape.zone(ctx,svg,startTime,endTime,pd.equilibrium,pd.high,{fill:'#ff6577',fillOpacity:.025,stroke:'#ff6577',strokeOpacity:.08,width:1});
        Shape.zone(ctx,svg,startTime,endTime,pd.low,pd.equilibrium,{fill:'#35d69a',fillOpacity:.03,stroke:'#35d69a',strokeOpacity:.08,width:1});
        if(!compact)Shape.zone(ctx,svg,startTime,endTime,pd.oteLow,pd.oteHigh,{fill:'#9b7cf5',fillOpacity:.07,stroke:'#9b7cf5',strokeOpacity:.5,width:1,dash:'5 4'});
      }
      const zones=pickZones(smc,preset,candles,policy).slice(0,compact?2:5);
      for(const z of zones){const zi=Math.max(0,Number(z.index)||0),zt=candles[zi]?.time||startTime,kind=String(z.kind||z.id||'').toUpperCase(),up=String(z.dir||'up')!=='down';let color=up?'#35d69a':'#ff6577',fill=.09,dash=null;if(kind.includes('FVG')){color='#4f8cff';fill=.105;dash='4 3'}else if(kind.includes('BREAKER')||kind.includes('BRK')){color='#ffc45f';fill=.08;dash='6 4'}else if(kind.includes('OB')){color=up?'#2dd4bf':'#fb7185';fill=.10}Shape.zone(ctx,svg,zt,endTime,z.low,z.high,{fill,fillOpacity:fill,stroke:color,strokeOpacity:.78,width:1.2,dash})}
      const mss=(smc.mss||[]).slice(compact?-1:-2);for(const m of mss){const i=Math.max(0,Number(m.index)||0),pi=Math.max(0,Number(m.pivotIndex??i-5)||0),c=candles[i];if(!c)continue;const up=String(m.dir||'up')!=='down',color=up?'#35d69a':'#ff6577',level=Number(m.level);const x1=Shape.xFor(ctx,candles[pi]?.time),x2=Shape.xFor(ctx,c.time),y=Shape.yFor(ctx,level);if([x1,x2,y].every(v=>v!=null)){Shape.line(svg,x1,y,x2,y,{stroke:color,width:1.6,opacity:.85,dash:'5 4'});Shape.arrow(svg,x2-8,y+(up?10:-10),x2+5,y+(up?-8:8),{stroke:color,width:2,head:6})}}
      const sweeps=(smc.sweeps||[]).slice(compact?-1:-3);for(const sw of sweeps){const i=Math.max(0,Number(sw.index)||0),c=candles[i];if(!c)continue;const up=String(sw.dir||'')==='up',color=up?'#67d9ff':'#d88cff',x=Shape.xFor(ctx,c.time),price=up?(c.low??sw.level):(c.high??sw.level),y=Shape.yFor(ctx,price);if(x==null||y==null)continue;Shape.circle(svg,x,y,5.5,{fill:'#07101a',fillOpacity:.85,stroke:color,width:2});Shape.arrow(svg,x,y+(up?11:-11),x,y+(up?-15:15),{stroke:color,width:2,head:6})}
      const eq=compact?[]:(smc.equalLevels||[]).slice(-2);for(const q of eq){const i=Math.max(0,Number(q.lastIndex)||0),x2=Shape.xFor(ctx,candles[i]?.time),x1=Shape.xFor(ctx,candles[Math.max(0,i-10)]?.time),y=Shape.yFor(ctx,q.price??q.level);if([x1,x2,y].every(v=>v!=null)){const color=q.type==='EQH'?'#d88cff':'#67d9ff';Shape.line(svg,x1,y,x2,y,{stroke:color,width:1.5,opacity:.75,dash:'3 4'});Shape.circle(svg,x1,y,2.5,{fill:color,stroke:color,width:1});Shape.circle(svg,x2,y,2.5,{fill:color,stroke:color,width:1})}}
      return true;
    }
    return{id:'smc',version:'3.0.0',requiredData:['candles','smc'],mount(c){ctx=c},update(state){lastState=state;clear();if(!ctx||!visible)return;const smc=state?.smc||{},compact=(['clean','compact'].includes(state?.smartOverlayMode)||state?.viewportLevel==='compact')&&state?.overlayFocus!=='smc',basePreset=state?.preset||{id:'clean',maxZones:1},preset={...basePreset,id:basePreset.id==='clean'?'smc':basePreset.id,maxZones:compact?Math.max(2,Math.min(3,Number(basePreset.maxZones)||2)):(Number(basePreset.maxZones)||5)},candles=state?.rawCandles||state?.candles||[];const policy=policyFor(preset),end=sec(candles.at(-1)?.time);if(!end)return;if(drawBeginner(state,smc,candles,preset,policy,compact))return;for(const z of pickZones(smc,preset,candles,policy)){const start=sec(candles[z.index]?.time);if(!start)continue;line(z.low,start,end,1,2);line(z.high,start,end,1,2);if(Number.isFinite(center(z))&&z.state==='active')line(center(z),start,end,1,3)}const pd=smc.pdOte;if(pd?.available){const start=sec(candles[Math.max(0,candles.length-80)]?.time||candles[0]?.time);line(pd.equilibrium,start,end,1,3);if(preset.id==='full'){line(pd.oteLow,start,end,1,3);line(pd.oteHigh,start,end,1,3)}}renderMarkers(smc,candles,policy,state?.analysis,state)},setVisible(v){visible=!!v;if(!visible)clear();else if(lastState)this.update(lastState)},dispose(){clear();lastState=null;ctx=null}}}
  return{createSmcPlugin};
});