(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseChartData=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const finite=v=>Number.isFinite(Number(v));
  const sec=t=>{const n=Number(t);return Math.trunc(n>1e12?n/1000:n)};
  function cleanRows(rows){return (Array.isArray(rows)?rows:[]).filter(r=>r&&finite(r.time)&&finite(r.open)&&finite(r.high)&&finite(r.low)&&finite(r.close));}
  function normalizeCandles(rows){const valid=cleanRows(rows);return{candles:valid.map(r=>({time:sec(r.time),open:Number(r.open),high:Number(r.high),low:Number(r.low),close:Number(r.close)})),volume:valid.filter(r=>finite(r.volume)).map(r=>({time:sec(r.time),value:Number(r.volume)}))};}
  function emaValues(values,period){if(!Array.isArray(values)||!values.length||!Number.isInteger(period)||period<1)return[];const k=2/(period+1);let e=Number(values[0]);const out=[e];for(let i=1;i<values.length;i++){const v=Number(values[i]);e=v*k+e*(1-k);out.push(e)}return out;}
  function emaSeries(rows,period){const valid=cleanRows(rows);const vals=emaValues(valid.map(r=>Number(r.close)),period);return valid.map((r,i)=>({time:sec(r.time),value:vals[i]}));}
  function rsiValues(values,period=14){const out=Array(values.length).fill(null);if(values.length<=period)return out;let gain=0,loss=0;for(let i=1;i<=period;i++){const d=values[i]-values[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)}gain/=period;loss/=period;out[period]=loss===0?100:100-100/(1+gain/loss);for(let i=period+1;i<values.length;i++){const d=values[i]-values[i-1];gain=(gain*(period-1)+Math.max(d,0))/period;loss=(loss*(period-1)+Math.max(-d,0))/period;out[i]=loss===0?100:100-100/(1+gain/loss)}return out;}
  function rsiSeries(rows,period=14){const valid=cleanRows(rows),vals=rsiValues(valid.map(r=>Number(r.close)),period);return valid.flatMap((r,i)=>finite(vals[i])?[{time:sec(r.time),value:Number(vals[i])}]:[]);}
  function macdSeries(rows,fast=12,slow=26,signal=9){const valid=cleanRows(rows),closes=valid.map(r=>Number(r.close)),f=emaValues(closes,fast),s=emaValues(closes,slow),m=closes.map((_,i)=>f[i]-s[i]),sig=emaValues(m,signal),hist=m.map((v,i)=>v-sig[i]);const map=vals=>valid.map((r,i)=>({time:sec(r.time),value:vals[i]}));return{macd:map(m),signal:map(sig),histogram:map(hist)};}
  function smaNullable(values,period){const out=Array(values.length).fill(null);for(let i=0;i<values.length;i++){if(i<period-1)continue;const w=values.slice(i-period+1,i+1);if(w.some(v=>!finite(v)))continue;out[i]=w.reduce((a,b)=>a+Number(b),0)/period}return out;}
  function stochRsiSeries(rows,rsiPeriod=14,stochPeriod=14,kPeriod=3,dPeriod=3){const valid=cleanRows(rows),r=rsiValues(valid.map(x=>Number(x.close)),rsiPeriod),raw=Array(r.length).fill(null);for(let i=0;i<r.length;i++){if(i<rsiPeriod+stochPeriod-1||!finite(r[i]))continue;const w=r.slice(i-stochPeriod+1,i+1).filter(finite);if(w.length!==stochPeriod)continue;const lo=Math.min(...w),hi=Math.max(...w);raw[i]=hi===lo?50:(Number(r[i])-lo)/(hi-lo)*100}const kv=smaNullable(raw,kPeriod),dv=smaNullable(kv,dPeriod);const map=vals=>valid.flatMap((row,i)=>finite(vals[i])?[{time:sec(row.time),value:Number(vals[i])}]:[]);return{k:map(kv),d:map(dv)};}
  async function fetchStructure({symbol,interval,limit=500,fetchImpl,cacheBust=null}={}){const f=fetchImpl||(typeof fetch==='function'?fetch:null);if(!f)throw new Error('fetch unavailable');const s=String(symbol||'BTCUSDT').toUpperCase().replace(/[^A-Z0-9]/g,''),tf=String(interval||'1h'),n=Math.max(80,Math.min(1000,Number(limit)||500));let url=`/api/structure?symbol=${encodeURIComponent(s)}&interval=${encodeURIComponent(tf)}&limit=${n}`;if(cacheBust!=null)url+=`&refresh=${encodeURIComponent(String(cacheBust))}`;const res=await f(url,{cache:'no-store'});let data;try{data=await res.json()}catch{throw new Error('Structure response parse failed')}if(!res.ok||!data?.ok)throw new Error(data?.error||`Structure HTTP ${res.status}`);return data;}
  async function fetchLive({symbol,interval='1m',market='spot',fetchImpl}={}){const f=fetchImpl||(typeof fetch==='function'?fetch:null);if(!f)throw new Error('fetch unavailable');const s=String(symbol||'BTCUSDT').toUpperCase().replace(/[^A-Z0-9]/g,''),tf=String(interval||'1m'),m=String(market||'spot');const res=await f(`/api/structure?symbol=${encodeURIComponent(s)}&interval=${encodeURIComponent(tf)}&live=1&market=${encodeURIComponent(m)}`,{cache:'no-store'});let data;try{data=await res.json()}catch{throw new Error('Live response parse failed')}if(!res.ok||!data?.ok)throw new Error(data?.error||`Live HTTP ${res.status}`);return data;}
  async function fetchMarketMeta({symbol,market='spot',fetchImpl}={}){const f=fetchImpl||(typeof fetch==='function'?fetch:null);if(!f)throw new Error('fetch unavailable');const s=String(symbol||'BTCUSDT').toUpperCase().replace(/[^A-Z0-9]/g,''),m=String(market||'spot');const res=await f(`/api/structure?symbol=${encodeURIComponent(s)}&meta=1&market=${encodeURIComponent(m)}`,{cache:'no-store'});let data;try{data=await res.json()}catch{throw new Error('Market metadata parse failed')}if(!res.ok||!data?.ok)throw new Error(data?.error||`Meta HTTP ${res.status}`);return data;}
  function kdjSeries(rows,period=9){const valid=cleanRows(rows),K=[],D=[],J=[];let pk=50,pd=50;for(let i=0;i<valid.length;i++){const w=valid.slice(Math.max(0,i-period+1),i+1),lo=Math.min(...w.map(x=>Number(x.low))),hi=Math.max(...w.map(x=>Number(x.high))),rsv=hi===lo?50:(Number(valid[i].close)-lo)/(hi-lo)*100;pk=(2*pk+rsv)/3;pd=(2*pd+pk)/3;K.push(pk);D.push(pd);J.push(3*pk-2*pd)}const map=vals=>valid.map((r,i)=>({time:sec(r.time),value:vals[i]}));return{k:map(K),d:map(D),j:map(J)}}
  function obvSeries(rows){const valid=cleanRows(rows),vals=[0];for(let i=1;i<valid.length;i++)vals.push(vals[i-1]+(Number(valid[i].close)>Number(valid[i-1].close)?Number(valid[i].volume||0):Number(valid[i].close)<Number(valid[i-1].close)?-Number(valid[i].volume||0):0));return valid.map((r,i)=>({time:sec(r.time),value:vals[i]}))}
  return{normalizeCandles,emaSeries,rsiSeries,macdSeries,stochRsiSeries,kdjSeries,obvSeries,fetchStructure,fetchLive,fetchMarketMeta,_emaValues:emaValues,_rsiValues:rsiValues};
});