(function(root,factory){const sp=typeof module==='object'&&module.exports?require('./session-profile'):root?.PulseSessionProfile;const api=factory(sp);if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseLiquidityEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(SessionProfile){'use strict';
  const VERSION='LIQUIDITY_v1';
  const STATES=new Set(['active','probed','swept','consumed','expired']);
  function secOrMs(v){const n=Number(v);return n>1e12?n:n*1000;}
  function idFor(type,sourceId,price){return 'liq:'+String(type).toLowerCase()+':'+String(sourceId||'derived')+':'+Number(price);}
  function nyParts(time){if(!SessionProfile?.toNewYorkParts)throw new Error('PulseSessionProfile is required');return SessionProfile.toNewYorkParts(secOrMs(time));}
  function dayKey(time){const p=nyParts(time);return [p.year,String(p.month).padStart(2,'0'),String(p.day).padStart(2,'0')].join('-');}
  function weekKey(time){const p=nyParts(time);const d=new Date(Date.UTC(p.year,p.month-1,p.day));const dow=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()-(dow-1));return d.toISOString().slice(0,10);}
  function groupCandles(candles,keyFn){const groups=[];let current=null;for(let i=0;i<candles.length;i++){const c=candles[i],key=keyFn(c.time);if(!current||current.key!==key){current={key,high:Number(c.high),low:Number(c.low),startIndex:i,endIndex:i};groups.push(current);}else{current.high=Math.max(current.high,Number(c.high));current.low=Math.min(current.low,Number(c.low));current.endIndex=i;}}return groups;}
  function addLevel(levels,{type,side,price,startIndex=0,confirmedAt=0,sourceTf='',sourceId,state='active',quality=0,touches=0}){if(!Number.isFinite(Number(price)))return;const safeState=STATES.has(state)?state:'active';levels.push({id:idFor(type,sourceId,price),type,side,price:Number(price),startIndex:Number(startIndex)||0,confirmedAt:Number(confirmedAt)||0,sourceTf,sourceId:String(sourceId||idFor(type,'source',price)),state:safeState,quality:Number(quality)||0,touches:Number(touches)||0,distance:0,definitionVersion:VERSION});}
  function addPreviousRangeLevels(levels,candles,groups,hiType,loType,timeframe){if(groups.length<2)return;const prev=groups[groups.length-2];addLevel(levels,{type:hiType,side:'buy',price:prev.high,startIndex:prev.startIndex,confirmedAt:prev.endIndex,sourceTf:timeframe,sourceId:hiType.toLowerCase()+':'+prev.key,quality:1});addLevel(levels,{type:loType,side:'sell',price:prev.low,startIndex:prev.startIndex,confirmedAt:prev.endIndex,sourceTf:timeframe,sourceId:loType.toLowerCase()+':'+prev.key,quality:1});}
  function analyzeLiquidity(input={}){const source=Array.isArray(input.candles)?input.candles:[];const asOf=Number.isInteger(input.asOfIndex)?Math.max(-1,Math.min(input.asOfIndex,source.length-1)):source.length-1;const candles=source.slice(0,asOf+1);const tf=String(input.timeframe||'');const levels=[];
    for(const p of Array.isArray(input.pivots)?input.pivots:[]){const idx=Number(p.index??p.pivotIndex);if(Number.isFinite(idx)&&idx>asOf)continue;const isHigh=String(p.type||'').toUpperCase()==='H';const isLow=String(p.type||'').toUpperCase()==='L';if(!isHigh&&!isLow)continue;addLevel(levels,{type:isHigh?'SWING_HIGH':'SWING_LOW',side:isHigh?'buy':'sell',price:p.price,startIndex:idx,confirmedAt:idx,sourceTf:tf,sourceId:p.id||('pivot:'+idx+':'+p.type),quality:Number(p.quality)||0});}
    for(const eq of Array.isArray(input.equalLevels)?input.equalLevels:[]){const idx=Number(eq.lastIndex??eq.index);if(Number.isFinite(idx)&&idx>asOf)continue;const type=String(eq.type||'').toUpperCase();if(type!=='EQH'&&type!=='EQL')continue;addLevel(levels,{type,side:type==='EQH'?'buy':'sell',price:eq.price??eq.level,startIndex:Number(eq.index??idx)||0,confirmedAt:idx,sourceTf:tf,sourceId:eq.id||eq.sourceId||('eq:'+type+':'+idx),quality:Number(eq.quality)||0,touches:Number(eq.touches)||0});}
    if(candles.length){addPreviousRangeLevels(levels,candles,groupCandles(candles,dayKey),'PDH','PDL',tf);addPreviousRangeLevels(levels,candles,groupCandles(candles,weekKey),'PWH','PWL',tf);const last=Number(candles.at(-1)?.close)||0;for(const l of levels)l.distance=Math.abs(l.price-last);}
    return{levels,sweeps:[],voids:[],inducements:[],sessions:[],versions:{liquidity:VERSION,session:input.sessionProfile?.version||'SESSION_PROFILE_v1'}};
  }
  return{analyzeLiquidity,LIQUIDITY_v1:VERSION,LIFECYCLE_STATES:Array.from(STATES)};
});