(function(root,factory){const sp=typeof module==='object'&&module.exports?require('./session-profile'):root?.PulseSessionProfile;const api=factory(sp);if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseLiquidityEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(SessionProfile){'use strict';
  const VERSION='LIQUIDITY_v1';
  const STATES=new Set(['active','probed','swept','consumed','expired']);
  const SWEEP_PARAMS_V1=Object.freeze({sweepVersion:'SWEEP_v2',grabVersion:'GRAB_v1',minGrabPenetrationAtr:.15,confirmationWindowBars:2,maxGrabReclaimBars:1,minDisplacementQuality:60});
  const VOID_PARAMS_V1=Object.freeze({version:'VOID_v1',windowBars:3,minDisplacementToAvgRange:2,maxOverlapRatio:.25});
  const INDUCEMENT_PARAMS_V1=Object.freeze({version:'INDUCEMENT_CANDIDATE_v1',minProgressRatio:.25});
  function secOrMs(v){const n=Number(v);return n>1e12?n:n*1000;}
  function idFor(type,sourceId,price){return 'liq:'+String(type).toLowerCase()+':'+String(sourceId||'derived')+':'+Number(price);}
  function nyParts(time){if(!SessionProfile?.toNewYorkParts)throw new Error('PulseSessionProfile is required');return SessionProfile.toNewYorkParts(secOrMs(time));}
  function dayKey(time){const p=nyParts(time);return [p.year,String(p.month).padStart(2,'0'),String(p.day).padStart(2,'0')].join('-');}
  function weekKey(time){const p=nyParts(time);const d=new Date(Date.UTC(p.year,p.month-1,p.day));const dow=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()-(dow-1));return d.toISOString().slice(0,10);}
  function groupCandles(candles,keyFn){const groups=[];let current=null;for(let i=0;i<candles.length;i++){const c=candles[i],key=keyFn(c.time);if(!current||current.key!==key){current={key,high:Number(c.high),low:Number(c.low),startIndex:i,endIndex:i};groups.push(current);}else{current.high=Math.max(current.high,Number(c.high));current.low=Math.min(current.low,Number(c.low));current.endIndex=i;}}return groups;}
  function addLevel(levels,{type,side,price,startIndex=0,confirmedAt=0,sourceTf='',sourceId,state='active',quality=0,touches=0}){if(!Number.isFinite(Number(price)))return;const safeState=STATES.has(state)?state:'active';levels.push({id:idFor(type,sourceId,price),type,side,price:Number(price),startIndex:Number(startIndex)||0,confirmedAt:Number(confirmedAt)||0,sourceTf,sourceId:String(sourceId||idFor(type,'source',price)),state:safeState,quality:Number(quality)||0,touches:Number(touches)||0,distance:0,definitionVersion:VERSION});}
  function addPreviousRangeLevels(levels,candles,groups,hiType,loType,timeframe){if(groups.length<2)return;const prev=groups[groups.length-2];addLevel(levels,{type:hiType,side:'buy',price:prev.high,startIndex:prev.startIndex,confirmedAt:prev.endIndex,sourceTf:timeframe,sourceId:hiType.toLowerCase()+':'+prev.key,quality:1});addLevel(levels,{type:loType,side:'sell',price:prev.low,startIndex:prev.startIndex,confirmedAt:prev.endIndex,sourceTf:timeframe,sourceId:loType.toLowerCase()+':'+prev.key,quality:1});}
  function nearestLevel(levels,price,side){const p=Number(price);if(!Number.isFinite(p)||!levels.length)return null;let best=null,dist=Infinity;for(const l of levels){if(side&&l.side!==side)continue;const d=Math.abs(Number(l.price)-p);if(d<dist){dist=d;best=l;}}return best;}
  function nearestLevelId(levels,price){return nearestLevel(levels,price)?.id||null;}
  function enrichSweeps(input,levels,asOf){const sweeps=(Array.isArray(input.sweeps)?input.sweeps:[]).filter(x=>Number(x.index)<=asOf);const displacements=(Array.isArray(input.displacement)?input.displacement:[]).filter(x=>Number(x.index)<=asOf);const mss=(Array.isArray(input.mss)?input.mss:[]).filter(x=>Number(x.index)<=asOf);return sweeps.map((src,ordinal)=>{const index=Number(src.index),dir=String(src.dir||''),penetrationAtr=Number.isFinite(Number(src.excessAtr))?Number(src.excessAtr):Number(src.penetrationAtr)||0,reclaimBars=Math.max(0,Number(src.reclaimBars)||0),reclaimDistanceAtr=Number(src.reclaimDistanceAtr)||0,end=index+SWEEP_PARAMS_V1.confirmationWindowBars;const displacement=displacements.find(d=>String(d.dir||'')===dir&&Number(d.index)>=index&&Number(d.index)<=end&&Number(d.quality??100)>=SWEEP_PARAMS_V1.minDisplacementQuality);const structure=mss.find(m=>String(m.dir||'')===dir&&Number(m.index)>=index&&Number(m.index)<=end);const displacementConfirmed=!!displacement;const grab=penetrationAtr>=SWEEP_PARAMS_V1.minGrabPenetrationAtr&&reclaimBars<=SWEEP_PARAMS_V1.maxGrabReclaimBars&&displacementConfirmed;const quality=Math.max(0,Math.min(100,Math.round(35+Math.min(penetrationAtr,.5)/.5*30+(displacementConfirmed?25:0)+(structure?10:0))));const sourceSweepId=String(src.id||('sweep:'+index+':'+dir+':'+Number(src.level)+':'+ordinal));return{...src,id:'liq:'+sourceSweepId,sourceSweepId,baseType:'SWEEP',variant:grab?'GRAB':'NORMAL',levelId:nearestLevelId(levels,src.level),penetrationAtr,reclaimBars,reclaimDistanceAtr,displacementConfirmed,mssConfirmed:!!structure,quality,definitionVersion:SWEEP_PARAMS_V1.sweepVersion,...(grab?{grabDefinitionVersion:SWEEP_PARAMS_V1.grabVersion}:{})};});}
  function overlapRatio(a,b){const overlap=Math.max(0,Math.min(Number(a.high),Number(b.high))-Math.max(Number(a.low),Number(b.low)));const base=Math.max(1e-12,Math.min(Number(a.high)-Number(a.low),Number(b.high)-Number(b.low)));return overlap/base;}
  function detectVoids(candles){const out=[],w=VOID_PARAMS_V1.windowBars;for(let start=0;start+w<=candles.length;start++){const slice=candles.slice(start,start+w);const bullish=slice.every(x=>Number(x.close)>Number(x.open)),bearish=slice.every(x=>Number(x.close)<Number(x.open));if(!bullish&&!bearish)continue;const ranges=slice.map(x=>Math.max(0,Number(x.high)-Number(x.low))),avgRange=ranges.reduce((a,b)=>a+b,0)/ranges.length;if(!(avgRange>0))continue;const displacement=Math.abs(Number(slice.at(-1).close)-Number(slice[0].open)),displacementRatio=displacement/avgRange;let overlap=0;for(let i=1;i<slice.length;i++)overlap+=overlapRatio(slice[i-1],slice[i]);overlap/=Math.max(1,slice.length-1);if(displacementRatio<VOID_PARAMS_V1.minDisplacementToAvgRange||overlap>VOID_PARAMS_V1.maxOverlapRatio)continue;const dir=bullish?'up':'down',a=Number(slice[0].close),b=Number(slice.at(-1).open);out.push({id:'VOID-'+dir+'-'+start+'-'+(start+w-1),kind:'VOID',dir,startIndex:start,endIndex:start+w-1,low:Math.min(a,b),high:Math.max(a,b),displacementAtr:displacementRatio,overlapRatio:overlap,state:'active',definitionVersion:VOID_PARAMS_V1.version});}return out;}
  function detectInducements(levels,sweeps,candles){if(!candles.length)return[];const out=[],lastClose=Number(candles.at(-1).close),lastIndex=candles.length-1;for(const sw of sweeps){if(Number(sw.index)>=lastIndex)continue;const up=sw.dir==='up',smallSide=up?'sell':'buy',targetSide=up?'buy':'sell';const small=nearestLevel(levels,sw.level,smallSide);if(!small)continue;const targets=levels.filter(l=>l.side===targetSide&&(up?Number(l.price)>lastClose:Number(l.price)<lastClose));if(!targets.length)continue;targets.sort((a,b)=>Math.abs(Number(a.price)-lastClose)-Math.abs(Number(b.price)-lastClose)||String(a.id).localeCompare(String(b.id)));const target=targets[0],den=Math.abs(Number(target.price)-Number(sw.level));if(!(den>0))continue;const progress=up?(lastClose-Number(sw.level))/den:(Number(sw.level)-lastClose)/den;if(progress<INDUCEMENT_PARAMS_V1.minProgressRatio||progress>=1)continue;out.push({id:'IND-'+sw.sourceSweepId,type:'INDUCEMENT_CANDIDATE',label:'IND?',confidence:'candidate',direction:up?'up':'down',sourceSweepId:sw.sourceSweepId,smallLevelId:small.id,targetLevelId:target.id,sourceIds:[small.sourceId,sw.sourceSweepId,target.sourceId],progressRatio:progress,confirmed:false,definitionVersion:INDUCEMENT_PARAMS_V1.version});}return out;}
  function analyzeLiquidity(input={}){const source=Array.isArray(input.candles)?input.candles:[];const asOf=Number.isInteger(input.asOfIndex)?Math.max(-1,Math.min(input.asOfIndex,source.length-1)):source.length-1;const candles=source.slice(0,asOf+1);const tf=String(input.timeframe||'');const levels=[];
    for(const p of Array.isArray(input.pivots)?input.pivots:[]){const idx=Number(p.index??p.pivotIndex);if(Number.isFinite(idx)&&idx>asOf)continue;const isHigh=String(p.type||'').toUpperCase()==='H';const isLow=String(p.type||'').toUpperCase()==='L';if(!isHigh&&!isLow)continue;addLevel(levels,{type:isHigh?'SWING_HIGH':'SWING_LOW',side:isHigh?'buy':'sell',price:p.price,startIndex:idx,confirmedAt:idx,sourceTf:tf,sourceId:p.id||('pivot:'+idx+':'+p.type),quality:Number(p.quality)||0});}
    for(const eq of Array.isArray(input.equalLevels)?input.equalLevels:[]){const idx=Number(eq.lastIndex??eq.index);if(Number.isFinite(idx)&&idx>asOf)continue;const type=String(eq.type||'').toUpperCase();if(type!=='EQH'&&type!=='EQL')continue;addLevel(levels,{type,side:type==='EQH'?'buy':'sell',price:eq.price??eq.level,startIndex:Number(eq.index??idx)||0,confirmedAt:idx,sourceTf:tf,sourceId:eq.id||eq.sourceId||('eq:'+type+':'+idx),quality:Number(eq.quality)||0,touches:Number(eq.touches)||0});}
    if(candles.length){addPreviousRangeLevels(levels,candles,groupCandles(candles,dayKey),'PDH','PDL',tf);addPreviousRangeLevels(levels,candles,groupCandles(candles,weekKey),'PWH','PWL',tf);const last=Number(candles.at(-1)?.close)||0;for(const l of levels)l.distance=Math.abs(l.price-last);}
    const enrichedSweeps=enrichSweeps(input,levels,asOf),voids=detectVoids(candles),inducements=detectInducements(levels,enrichedSweeps,candles);
    return{levels,sweeps:enrichedSweeps,voids,inducements,sessions:[],versions:{liquidity:VERSION,sweep:SWEEP_PARAMS_V1.sweepVersion,grab:SWEEP_PARAMS_V1.grabVersion,void:VOID_PARAMS_V1.version,inducement:INDUCEMENT_PARAMS_V1.version,session:input.sessionProfile?.version||'SESSION_PROFILE_v1'}};
  }
  return{analyzeLiquidity,LIQUIDITY_v1:VERSION,LIFECYCLE_STATES:Array.from(STATES),SWEEP_PARAMS_V1,VOID_PARAMS_V1,INDUCEMENT_PARAMS_V1};
});