'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../lib/coin-scan/integrated-surge-engine.js');
const Audit=require('../ui/condition-audit.js');
const now=1800000000000;
function evidence(){return{asOf:now,extended:false,oi:{known:true,a:true,aPre:true,cRebuild:false,change15mPct:.2},setup4h:{valid:true},ready1h:{ready:true,aboveEma14:true,holdOrHl:true,flow:'FLOW-SUSTAIN'},gate15m:{passed:true,aligned:true,alignmentTransition:false,break:{confirmed:true},rvolIncreasing:true,flow:'FLOW-SUSTAIN'},gate5m:{passed:true,aboveAllEmas:true,holdOrHl:true,vwapConfirmed:true,mssProxy:true,takerReentry:true,rvol:1.3},coverage:{frames:Object.fromEntries(['4h','1h','15m','5m'].map(tf=>[tf,{available:true}]))},candleCloses:{'15m':now-1,'5m':now-1}}}
test('B is an alternative path even when A fails',()=>{const s=evidence();s.oi.a=false;s.oi.aPre=false;const r=Audit.evaluate(s,now);assert.equal(r.groups.candidate.status,'PASS');assert.equal(r.paths.A.status,'FAIL');assert.equal(r.paths.B.status,'PASS');assert.equal(r.executionReady,true)});
test('missing OI preserves flow candidate but prevents execution promotion',()=>{const s=evidence();s.oi={known:false};const r=Audit.evaluate(s,now);assert.equal(r.paths.B.status,'PASS');assert.equal(r.executionReady,false);assert.equal(r.groups.oi.status,'MISSING');assert(r.blockers.includes('OI 미조회·지연: 승격 보류'))});
test('stale snapshot expires without renewing from evaluation time',()=>{const s=evidence(),a=Audit.evaluate(s,now),b=Audit.evaluate(s,now+900000);assert.equal(a.validity.status,'ACTIVE');assert.equal(b.validity.status,'EXPIRED');assert.equal(b.executionReady,false);assert.equal(a.validity.expiresAt,b.validity.expiresAt)});
test('unknown candle timestamp does not manufacture an active signal',()=>{const s=evidence();s.candleCloses={};assert.equal(Audit.evaluate(s,now).validity.status,'MISSING')});
test('failed required condition cannot be outvoted by other conditions',()=>{const s=evidence();s.gate5m.holdOrHl=false;s.gate5m.passed=false;const r=Audit.evaluate(s,now);assert.equal(r.executionReady,false);assert(r.blockers.includes('5m 저점 유지'))});
test('missing frame reports unavailable instead of failed',()=>{const s=evidence();s.coverage.frames['15m'].available=false;const r=Audit.evaluate(s,now);assert.equal(r.groups.ignition.status,'MISSING');assert.equal(r.executionReady,false)});
test('integrated evaluator supplies audit and closed candle timestamps',()=>{const r=E.evaluate({asOf:now});assert(r.conditionAudit);assert.deepEqual(r.candleCloses,{});assert.equal(r.conditionAudit.executionReady,false)});
test('zone selection independently hides OB and FVG',()=>{const O=require('../ui/auto-chart/chart/overlays.js');assert.equal(typeof O.selectAdvancedZones,'function');const a={advanced:{fvg:[{kind:'FVG'}],orderBlocks:[{kind:'OB'}]}};assert.deepEqual(O.selectAdvancedZones(a,{fvg:true,ob:false}),[{kind:'FVG'}]);assert.deepEqual(O.selectAdvancedZones(a,{fvg:false,ob:true}),[{kind:'OB'}]);assert.deepEqual(O.selectAdvancedZones(a,{zones:false}),[])});
