(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseTraderAnalysis=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const finite=v=>Number.isFinite(Number(v)),n=(v,d=0)=>finite(v)?Number(v):d,clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
function rows(c){return(Array.isArray(c)?c:[]).filter(x=>x&&finite(x.close)&&finite(x.high)&&finite(x.low)).map(x=>({...x,open:n(x.open,x.close),high:n(x.high),low:n(x.low),close:n(x.close),volume:n(x.volume)}))}
function ema(vals,p){if(!vals.length)return[];const k=2/(p+1),o=[n(vals[0])];for(let i=1;i<vals.length;i++)o.push(n(vals[i])*k+o[i-1]*(1-k));return o}
function sma(vals,p){const o=Array(vals.length).fill(null);let s=0;for(let i=0;i<vals.length;i++){s+=n(vals[i]);if(i>=p)s-=n(vals[i-p]);if(i>=p-1)o[i]=s/p}return o}
function atr(c,p=14){c=rows(c);const tr=c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)):x.high-x.low),o=[];let prev=tr[0]||0;const k=2/(p+1);for(let i=0;i<tr.length;i++){prev=i?tr[i]*k+prev*(1-k):prev;o.push(prev)}return o}
function rsi(vals,p=14){const o=Array(vals.length).fill(null);if(vals.length<=p)return o;let g=0,l=0;for(let i=1;i<=p;i++){const d=n(vals[i])-n(vals[i-1]);g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;o[p]=l===0?100:100-100/(1+g/l);for(let i=p+1;i<vals.length;i++){const d=n(vals[i])-n(vals[i-1]);g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;o[i]=l===0?100:100-100/(1+g/l)}return o}
function macd(vals){const f=ema(vals,12),s=ema(vals,26),m=vals.map((_,i)=>f[i]-s[i]),sig=ema(m,9),hist=m.map((v,i)=>v-sig[i]);return{macd:m,signal:sig,histogram:hist}}
function stochRsi(vals,rp=14,sp=14,kp=3,dp=3){const rv=rsi(vals,rp),raw=Array(vals.length).fill(null);for(let i=0;i<vals.length;i++){if(i<rp+sp-1||!finite(rv[i]))continue;const w=rv.slice(i-sp+1,i+1).filter(finite);if(w.length!==sp)continue;const lo=Math.min(...w),hi=Math.max(...w);raw[i]=hi===lo?50:(rv[i]-lo)/(hi-lo)*100}return{k:sma(raw,kp),d:sma(sma(raw,kp),dp)}}
function kdj(c,p=9){c=rows(c);const K=[],D=[],J=[];let pk=50,pd=50;for(let i=0;i<c.length;i++){const w=c.slice(Math.max(0,i-p+1),i+1),lo=Math.min(...w.map(x=>x.low)),hi=Math.max(...w.map(x=>x.high)),rsv=hi===lo?50:(c[i].close-lo)/(hi-lo)*100;pk=(2*pk+rsv)/3;pd=(2*pd+pk)/3;K.push(pk);D.push(pd);J.push(3*pk-2*pd)}return{k:K,d:D,j:J}}
function obv(c){c=rows(c);const o=[0];for(let i=1;i<c.length;i++)o.push(o[i-1]+(c[i].close>c[i-1].close?c[i].volume:c[i].close<c[i-1].close?-c[i].volume:0));return o}
function volumeRatio(c,p=20){c=rows(c);if(c.length<2)return null;const prev=c.slice(Math.max(0,c.length-p-1),-1),base=prev.length?prev.reduce((s,x)=>s+x.volume,0)/prev.length:0;return base>0?c.at(-1).volume/base:null}
function volumeProfile(c,bins=24,meta={}){c=rows(c);if(!c.length)return{bins:[],poc:null,valueArea:null,lookbackBars:0};const lo=Math.min(...c.map(x=>x.low)),hi=Math.max(...c.map(x=>x.high)),step=(hi-lo)/Math.max(1,bins)||1,arr=Array.from({length:bins},(_,i)=>({from:lo+i*step,to:lo+(i+1)*step,mid:lo+(i+.5)*step,volume:0}));for(const x of c){const px=(x.high+x.low+x.close)/3,idx=clamp(Math.floor((px-lo)/step),0,bins-1);arr[idx].volume+=x.volume}const total=arr.reduce((s,x)=>s+x.volume,0),poc=arr.slice().sort((a,b)=>b.volume-a.volume)[0]||null;let used=0,selected=[];for(const x of arr.slice().sort((a,b)=>b.volume-a.volume)){selected.push(x);used+=x.volume;if(total&&used/total>=.7)break}const valueArea=selected.length?{low:Math.min(...selected.map(x=>x.from)),high:Math.max(...selected.map(x=>x.to))}:null;const current=c.at(-1)?.close,pocPrice=poc?.mid,distancePct=finite(current)&&finite(pocPrice)?Math.abs(pocPrice-current)/Math.max(Math.abs(current),1e-9)*100:null;return{bins:arr,poc:poc?{price:poc.mid,volume:poc.volume}:null,valueArea,total,lookbackBars:c.length,timeframe:meta.timeframe||null,distancePct,profileRole:meta.profileRole||'ACTIONABLE',approximation:'typical-price candle volume binning'}}
function profileLookback(tf){return({"5m":240,"15m":192,"1h":120,"4h":90,"12h":60,"1d":60,"3d":52,"1w":52})[String(tf||'1h').toLowerCase()]||120}
function maMap(c){c=rows(c);const close=c.map(x=>x.close),periods=[5,10,20,60,112,120,224,448],out={};for(const p of periods){const e=ema(close,p);out[p]=e.at(-1)??null;out['series'+p]=e}return out}
function recentCross(close,series,lookback=4){for(let i=Math.max(1,close.length-lookback);i<close.length;i++)if(finite(series[i])&&finite(series[i-1])&&close[i]>=series[i]&&close[i-1]<series[i-1])return i;return-1}
function pct(a,b){return a?((b-a)/Math.abs(a))*100:null}
function danteSignals(c){c=rows(c);const close=c.map(x=>x.close),ma=maMap(c),a=atr(c),last=c.at(-1)||{},prev=c.at(-2)||{},rv=volumeRatio(c),out=[];const score=(id,label,s,reasons,invalidations=[],auto='자동 판별')=>out.push({id,label,score:Math.round(clamp(s)),matched:s>=65,reasons,invalidations,automation:auto});
const s112=ma.series112||[],s224=ma.series224||[],s448=ma.series448||[],cross112=recentCross(close,s112,5),cross224=recentCross(close,s224,5);
const below224=c.slice(-90,-5).filter((x,i)=>finite(s224[s224.length-Math.min(90,c.length)+i])&&x.close<s224[s224.length-Math.min(90,c.length)+i]).length;const sample224=Math.max(1,c.slice(-90,-5).length),longBelow=below224/sample224>=.7;
let sc=0,rs=[];if(longBelow){sc+=35;rs.push('장기간 224선 아래 체류')}if(cross224>=0){sc+=40;rs.push('최근 224선 상향 돌파')}if(finite(ma[224])&&last.close>=ma[224]){sc+=15;rs.push('현재 224선 위')}if(rv>=1.5){sc+=10;rs.push('거래량 동반')}score('bowl224','밥그릇·224 돌파',sc,rs,['224선 재이탈','돌파 거래량 소멸']);
sc=0;rs=[];const reverse=finite(ma[112])&&finite(ma[224])&&finite(ma[448])&&ma[112]<ma[224]&&ma[224]<ma[448];if(reverse){sc+=30;rs.push('장기 이평 역배열')}if(cross112>=0){sc+=35;rs.push('112선 돌파')}if(finite(ma[112])&&last.close>=ma[112]){sc+=15;rs.push('112선 위 안착 시도')}if(finite(ma[224])&&last.close<ma[224]){sc+=10;rs.push('224선까지 이격 존재')}if(rv>=1.3){sc+=10;rs.push('거래량 증가')}score('ma-hit','이평때리기',sc,rs,['112선 종가 재이탈','224선 도전 실패 후 거래량 매도 전환']);
sc=0;rs=[];if(c.length>=30){const w=c.slice(-30),min=Math.min(...w.map(x=>x.low)),mi=w.findIndex(x=>x.low===min),left=Math.max(...w.slice(0,Math.max(1,mi)).map(x=>x.high)),right=Math.max(...w.slice(mi+1).map(x=>x.high));const drop=pct(left,min),recovery=pct(min,last.close);if(drop!=null&&drop<=-10){sc+=30;rs.push('급락 후 V자 저점 형성')}if(recovery!=null&&recovery>=10){sc+=25;rs.push('저점 대비 강한 회복')}if(mi>=4&&mi<=24){sc+=15;rs.push('저점 이후 회복 구간 확보')}if(last.close>=right*.99){sc+=20;rs.push('직전 고점 재도전/돌파')}if(rv>=1.2){sc+=10;rs.push('거래량 확인')}}score('highheel','하이힐',sc,rs,['V저점 재이탈','전고점 돌파 실패 후 거래량 확대 하락']);
sc=0;rs=[];const av=a.at(-1)||0,ma224=ma[224];if(finite(ma224)&&av>0){const dist=Math.abs(last.close-ma224)/av;if(dist<=1.5){sc+=30;rs.push('224선 근접')}const s=ma.series224;if(s.length>15&&finite(s.at(-15))){const slope=Math.abs((s.at(-1)-s.at(-15))/(av||1));if(slope<=1.2){sc+=25;rs.push('장기 이평 기울기 완화')}}const atrp=last.close?av/last.close*100:null;if(atrp!=null&&atrp<5){sc+=20;rs.push('변동성 압축')}if(rv!=null&&rv<=1.3){sc+=15;rs.push('거래량 과열 없음')}}score('concrete','공구리',sc,rs,['장기 이평 급격한 재하락','압축 구간 저점 이탈'],['자동 근사 판별']);
sc=0;rs=[];const kijun=c.length>=26?(Math.max(...c.slice(-26).map(x=>x.high))+Math.min(...c.slice(-26).map(x=>x.low)))/2:null;if(finite(kijun)&&last.close>=kijun){sc+=35;rs.push('일목 기준선 위')}if(finite(ma[5])&&last.close>=ma[5]){sc+=25;rs.push('5이평 위')}if(prev&&finite(kijun)&&prev.low<=Math.max(kijun,ma[5]||kijun)*1.01&&last.close>prev.close){sc+=25;rs.push('기준선/5이평 반등 형태')}if(rv>=1.3){sc+=15;rs.push('거래량 증가')}score('kijun-scalp','기준선 단타',sc,rs,['기준선 종가 이탈','시가/세션 기준 손절 규칙 별도 확인'],['코인 24/7 시장은 세션 기준 변형 필요']);
sc=0;rs=[];if(c.length>=50){const w=c.slice(-50),mid=Math.floor(w.length/2),leftMove=Math.abs(pct(w[0].close,w[mid].close)||0),rightMove=Math.abs(pct(w[mid].close,w.at(-1).close)||0),ratio=leftMove?rightMove/leftMove:null;if(ratio!=null&&ratio>=.65&&ratio<=1.45){sc+=45;rs.push('가격 파동 대칭 근접')}const lBars=mid,rBars=w.length-1-mid,br=rBars/lBars;if(br>=.7&&br<=1.3){sc+=35;rs.push('기간 대칭 근접')}if(rv&&rv>=1){sc+=10;rs.push('현재 거래량 유지')}}score('symmetry','대칭이론',sc,rs,['대칭 기준 파동 무효화'],['자동 근사 판별']);
sc=0;rs=[];for(const p of[60,112,224]){const ser=ma['series'+p];if(!ser?.length||!finite(ser.at(-1)))continue;const m=ser.at(-1),dist=(last.close-m)/(Math.abs(m)||1);const w=c.slice(-40),below=Math.max(0,...w.map((x,i)=>{const idx=ser.length-w.length+i;return finite(ser[idx])?(ser[idx]-x.low)/(Math.abs(ser[idx])||1):0}));if(dist>0&&below>0){const rr=dist/below;if(rr>=.8&&rr<=1.4){sc=Math.max(sc,70);rs=[p+'일선 기준 매수·매도 힘 1:1 근접'];break}}}score('share','지분기법',sc,rs,['기준 이평 재이탈'],['자동 근사 판별']);
for(const [id,label] of[['256','256기법'],['dead-dive','데드다이빙'],['open-price','시초가 매매'],['close-bet','종가 베팅'],['force-balance','힘의 균형'],['reverse-wave','역매공파'],['elliott','엘리엇 파동']])score(id,label,0,['공개 자료상 세부 규칙의 수동 확인이 필요'],[],['설명·체크리스트 중심']);
return out.sort((a,b)=>b.score-a.score)}
function summarize({candles,analysis,smc,liquidity,timeframe='1h'}={}){const c=rows(candles),last=c.at(-1);if(!last)return{state:'데이터 없음',text:'확정봉 데이터가 없습니다.'};const close=c.map(x=>x.close),ma=maMap(c),rv=volumeRatio(c),rs=rsi(close),mc=macd(close),st=stochRsi(close),kd=kdj(c),ov=obv(c),vpBars=profileLookback(timeframe),vp=volumeProfile(c.slice(-vpBars),24,{timeframe,profileRole:'ACTIONABLE'}),vpContext=volumeProfile(c.slice(-Math.min(160,c.length)),24,{timeframe,profileRole:'CONTEXT'});let bull=0,bear=0,reasons=[];if(finite(ma[20])&&last.close>ma[20]){bull++;reasons.push('20이평 위')}else bear++;if(finite(ma[60])&&last.close>ma[60]){bull++;reasons.push('60이평 위')}else bear++;if(finite(rs.at(-1))&&rs.at(-1)>=50){bull++;reasons.push('RSI 50 이상')}else bear++;if(finite(mc.histogram.at(-1))&&mc.histogram.at(-1)>0){bull++;reasons.push('MACD 히스토그램 양수')}else bear++;const latestMss=smc?.mss?.at(-1);if(latestMss?.dir==='up'){bull++;reasons.push('최근 MSS 상승')}if(latestMss?.dir==='down'){bear++;reasons.push('최근 MSS 하락')}const state=bull>=bear+2?'상승 우위':bear>=bull+2?'하락 우위':'중립/혼조';const dante=danteSignals(c);return{state,text:`${state} · ${reasons.slice(0,4).join(' · ')||'방향 확정 근거 부족'}`,price:last.close,rvol:rv,rsi:rs.at(-1),macdHist:mc.histogram.at(-1),stochK:st.k.at(-1),stochD:st.d.at(-1),kdj:{k:kd.k.at(-1),d:kd.d.at(-1),j:kd.j.at(-1)},obv:ov.at(-1),obvDelta:ov.length>6?ov.at(-1)-ov.at(-6):null,ma,volumeProfile:vp,volumeProfileContext:vpContext,profileLookbackBars:vpBars,dante,trendlines:analysis?.trendlines||{},smc:{mss:latestMss||null,sweep:smc?.sweeps?.at(-1)||null,pd:smc?.pdOte||null,fvgCount:(smc?.fvgs||[]).filter(x=>!['violated','expired'].includes(x.state)).length,obCount:(smc?.orderBlocks||[]).filter(x=>!['violated','expired'].includes(x.state)).length},liquidity:{levels:(liquidity?.levels||[]).slice(0,8),sweeps:(liquidity?.sweeps||[]).slice(-4)}}}
return{rows,ema,sma,atr,rsi,macd,stochRsi,kdj,obv,volumeRatio,volumeProfile,profileLookback,maMap,danteSignals,summarize};
});