(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseSnapshotRecord=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const VERSION='SNAPSHOT_BOARD_v1',DB_NAME='pulse-snapshot-archive-v1',STORE='eventSnapshots';
const finite=v=>Number.isFinite(Number(v));
const ms=t=>{const n=Number(t);return finite(n)?(n>1e12?Math.trunc(n):Math.trunc(n*1000)):null};
const compactIso=t=>{const m=ms(t);if(!m)return'NA';return new Date(m).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')};
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==='object'){const o={};Object.keys(v).sort().forEach(k=>o[k]=stable(v[k]));return o}return v}
function hash(v){const s=JSON.stringify(stable(v??{}));let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return('00000000'+(h>>>0).toString(16)).slice(-8)}
function cleanSymbol(v){return String(v||'BTCUSDT').trim().toUpperCase().replace(/[^A-Z0-9]/g,'')||'BTCUSDT'}
function tfLabel(v){return String(v||'1h').replace(/[^0-9a-z]/gi,'').toUpperCase()}
function corePd(ict,limit=5){const price=Number(ict?.price);return(ict?.pdArrays||[]).map(x=>({...x,_distance:finite(price)&&finite(x.mid)?Math.abs(Number(x.mid)-price):Infinity})).filter(x=>finite(x.mid)||finite(x.low)||finite(x.high)).sort((a,b)=>a._distance-b._distance||Number(b.quality||0)-Number(a.quality||0)).slice(0,limit).map(x=>({type:x.type||'PD_ARRAY',subtype:x.subtype||null,dir:x.dir||null,index:finite(x.index)?Number(x.index):null,time:finite(x.time)?Number(x.time):null,low:finite(x.low)?Number(x.low):null,high:finite(x.high)?Number(x.high):null,mid:finite(x.mid)?Number(x.mid):null,quality:finite(x.quality)?Number(x.quality):null}))}
function nearestLiquidity(ict,limit=6){const price=Number(ict?.price),rows=[...(ict?.liquidity?.bsl||[]),...(ict?.liquidity?.ssl||[])];return rows.map(x=>({...x,_distance:finite(price)&&finite(x.price)?Math.abs(Number(x.price)-price):Infinity})).filter(x=>finite(x.price)).sort((a,b)=>a._distance-b._distance).slice(0,limit).map(x=>({side:x.side||null,kind:x.kind||null,price:Number(x.price),index:finite(x.index)?Number(x.index):null,time:finite(x.time)?Number(x.time):null,count:finite(x.count)?Number(x.count):null}))}
function overlayRecord({analysis,smc,ict}={}){const trend=analysis?.trendlines||{};const lastMss=(smc?.mss||[]).at(-1)||ict?.structure?.lastMss||null,lastSweep=ict?.liquidity?.lastSweep||null,cisd=ict?.delivery?.cisd||null,dol=ict?.liquidity?.drawOnLiquidity||null,pd=corePd(ict,5),liq=nearestLiquidity(ict,6);return{
 trendlines:['support','resistance'].flatMap(k=>trend[k]?[{kind:k,anchorA:trend[k].anchorA||null,anchorB:trend[k].anchorB||null}]:[]),
 structure:{mss:lastMss,cisd,lastSweep},
 pdArrays:pd,
 liquidity:liq,
 drawOnLiquidity:dol?{side:dol.side||null,kind:dol.kind||null,price:finite(dol.price)?Number(dol.price):null,index:finite(dol.index)?Number(dol.index):null}:null,
 labels:{bias:ict?.bias||'N/A',ipdaStage:ict?.delivery?.phase||'N/A',recentSweep:lastSweep?.kind||'N/A',drawOnLiquidity:dol?.kind||dol?.side||'N/A',nearestPdArray:ict?.nearestPd?.type||'N/A',readiness:finite(ict?.readiness)?Number(ict.readiness):null,mmxm:ict?.mmxm?.model||'none'}
}}
function buildRecord({symbol,tf,candles=[],analysis=null,smc=null,liquidity=null,ict=null,params={}}={}){const rows=(Array.isArray(candles)?candles:[]).filter(x=>x&&finite(x.time)&&finite(x.open)&&finite(x.high)&&finite(x.low)&&finite(x.close)).map(x=>({time:Number(x.time),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close),volume:finite(x.volume)?Number(x.volume):null}));const last=rows.at(-1);if(!last)throw new Error('snapshot candles unavailable');const engineVersion=String(ict?.version||'ICT_TRAINER_v1'),paramsHash=hash(params),confirmedBarTime=ms(last.time),snapshotId=`${cleanSymbol(symbol)}_${tfLabel(tf)}_${compactIso(last.time)}_${engineVersion}_${paramsHash}`;return{schemaVersion:VERSION,snapshotId,symbol:cleanSymbol(symbol),timeframe:String(tf||''),confirmedBarTime,confirmedBarIso:new Date(confirmedBarTime).toISOString(),engineVersion,paramsHash,params:stable(params),candles:rows,analysis:{ict:ict||null,overlays:overlayRecord({analysis,smc,liquidity,ict})}}}
function openDb(){return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined')return reject(new Error('IndexedDB unavailable'));const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'archiveKey'});s.createIndex('eventId','eventId',{unique:false});s.createIndex('symbol','symbol',{unique:false})}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('IndexedDB open failed'))})}
async function cacheEventBundle(payload={}){const id=String(payload?.eventId||'').trim(),records=Array.isArray(payload?.records)?payload.records.filter(Boolean):[];if(!id)throw new Error('eventId required');if(!records.length)throw new Error('snapshot records required');const safe={...payload,eventId:id,symbol:payload.symbol||records[0]?.symbol||null,snapshotIds:Array.isArray(payload.snapshotIds)?payload.snapshotIds:records.map(x=>x.snapshotId),records};const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({archiveKey:id,...safe,payloadJson:JSON.stringify(safe)});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error('snapshot archive write failed'));tx.onabort=()=>reject(tx.error||new Error('snapshot archive aborted'))});db.close();return safe}
async function getEventBundle(eventId){const id=String(eventId||'').trim();if(!id)return null;const db=await openDb();const out=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error||new Error('snapshot archive read failed'))});db.close();return out?.payloadJson?JSON.parse(out.payloadJson):out}
async function saveEventBundle({eventId,eventMeta={},records=[]}={}){const id=String(eventId||'').trim();if(!id)throw new Error('eventId required');const safe=records.filter(Boolean);if(!safe.length)throw new Error('snapshot records required');return cacheEventBundle({schemaVersion:VERSION,eventId:id,eventMeta:stable(eventMeta),symbol:safe[0].symbol||null,savedAt:new Date().toISOString(),snapshotIds:safe.map(x=>x.snapshotId),records:safe})}
return{VERSION,buildRecord,overlayRecord,saveEventBundle,cacheEventBundle,getEventBundle,_internals:{hash,compactIso,corePd,nearestLiquidity,stable}};
});