const BASES=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];
async function getJson(path,params={}){let last;const qs=new URLSearchParams(params).toString();for(const base of BASES){try{const r=await fetch(base+path+(qs?'?'+qs:''),{headers:{'User-Agent':'PulseRadar-Pro/3.6'}});const t=await r.text();if(!r.ok)throw new Error(`Binance ${r.status}: ${t.slice(0,180)}`);return JSON.parse(t)}catch(e){last=e}}throw last||new Error('Binance request failed')}
async function getKlinesPaged(symbol,interval,targetBars){let out=[],endTime;while(out.length<targetBars){const limit=Math.min(1000,targetBars-out.length);const params={symbol,interval,limit:String(limit)};if(endTime)params.endTime=String(endTime);const page=await getJson('/api/v3/klines',params);if(!Array.isArray(page)||!page.length)break;out=page.concat(out);const first=Number(page[0][0]);if(!Number.isFinite(first)||page.length<limit)break;endTime=first-1}const seen=new Set();return out.filter(k=>{const t=Number(k[0]);if(seen.has(t))return false;seen.add(t);return true}).sort((a,b)=>Number(a[0])-Number(b[0])).slice(-targetBars)}
const n=v=>Number(v)||0,clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
function ema(a,p){const k=2/(p+1),o=[];let x=a[0]||0;for(let i=0;i<a.length;i++){x=i?a[i]*k+x*(1-k):a[i];o.push(x)}return o}
function sma(a,p){const o=Array(a.length).fill(null);let s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)o[i]=s/p}return o}
function rsi(a,p=14){const out=Array(a.length).fill(null);if(a.length<=p)return out;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;out[p]=l?100-100/(1+g/l):100;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;out[i]=l?100-100/(1+g/l):100}return out}
function sd(a){if(!a.length)return 0;const m=a.reduce((s,x)=>s+x,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}
function atr(h,l,c,p=14){const tr=h.map((x,i)=>i?Math.max(x-l[i],Math.abs(x-c[i-1]),Math.abs(l[i]-c[i-1])):x-l[i]);return ema(tr,p)}
function macdHist(a){const a12=ema(a,12),a26=ema(a,26),line=a.map((_,i)=>a12[i]-a26[i]),sig=ema(line,9);return line.map((x,i)=>x-sig[i])}
function avg(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:null}
function med(a){if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function quantile(a,q){if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),p=(x.length-1)*q,b=Math.floor(p),r=p-b;return x[b+1]!==undefined?x[b]+r*(x[b+1]-x[b]):x[b]}
function pct(a,b){return b?((a/b)-1)*100:0}
function build(raw){const o=raw.map(k=>n(k[1])),h=raw.map(k=>n(k[2])),l=raw.map(k=>n(k[3])),c=raw.map(k=>n(k[4])),v=raw.map(k=>n(k[5])),q=raw.map(k=>n(k[7])),taker=raw.map(k=>n(k[10]));return{o,h,l,c,v,q,taker,e5:ema(c,5),e20:ema(c,20),e60:ema(c,60),rr:rsi(c),aa:atr(h,l,c),vs:sma(v,20),mh:macdHist(c)}}
function snapshot(d,i){const{o,h,l,c,v,q,taker,e5,e20,e60,rr,aa,vs,mh}=d;if(i<80||!rr[i])return null;const price=c[i],atrPct=price?aa[i]/price*100:0,volRatio=vs[i]?v[i]/vs[i]:0;const maxE=Math.max(e5[i],e20[i],e60[i]),minE=Math.min(e5[i],e20[i],e60[i]),gap=maxE?(maxE-minE)/maxE*100:0;const w=c.slice(i-19,i+1),mid=avg(w),sigma=sd(w),upper=mid+2*sigma,bw=mid?4*sigma/mid:0;const prev=[];for(let z=i-40;z<=i-20;z++){const s=c.slice(z-19,z+1);if(s.length===20){const m=avg(s);if(m)prev.push(4*sd(s)/m)}}const prevAvg=avg(prev)||bw;let bq=0,tq=0;for(let z=i-4;z<=i;z++){bq+=taker[z]||0;tq+=q[z]||0}const buyRatio=tq?bq/tq:.5,lastRange=o[i]?(h[i]-l[i])/o[i]*100:0;const squeeze=bw<prevAvg*.82,converging=gap<1.3,breakout=price>upper,macdPos=mh[i]>0;let score=0;const reasons=[];if(squeeze){score+=22;reasons.push('BB 압축')}if(converging){score+=20;reasons.push('EMA 수렴')}if(volRatio>=1.1&&volRatio<=2.5){score+=18;reasons.push('거래량 활성')}if(rr[i]>=47&&rr[i]<=62){score+=15;reasons.push('RSI 회복 구간')}if(macdPos){score+=15;reasons.push('MACD 양수')}if(buyRatio>=.52){score+=10;reasons.push('매수 체결 우위')}let penalty=0;if(rr[i]>72||volRatio>4||atrPct>8)penalty+=12;score=clamp(score-penalty);const hard=rr[i]>=82||gap>=8||atrPct>=9||volRatio>=6||lastRange>=10;const warn=rr[i]>=75||gap>=5||atrPct>=6||volRatio>=4||lastRange>=6;const triggerConfirm=(breakout||(volRatio>=1.15&&macdPos&&buyRatio>=.52))&&rr[i]>=48&&rr[i]<75;return{score,hard,warn,rsi:rr[i],volRatio,atrPct,gap,buyRatio,squeeze,converging,breakout,macdPos,lastRange,reasons,triggerConfirm}}
function observedState(s){if(!s)return'RESET';if(s.hard||s.warn)return'EXTENDED';if(s.score>=55&&s.triggerConfirm)return'TRIGGERED';if(s.score>=55)return'READY';if(s.score>=35)return'FORMING';return'RESET'}
function confidenceLabel(n){if(n<20)return'참고용';if(n<50)return'낮음';if(n<100)return'중간';return'상대적으로 안정'}
function summarize(events,key){const a=events.map(e=>e[key]).filter(Number.isFinite);return{n:a.length,mean:avg(a),median:med(a),positiveRate:a.length?a.filter(x=>x>0).length/a.length*100:null,p10:quantile(a,.10),p25:quantile(a,.25),p75:quantile(a,.75),p90:quantile(a,.90),min:a.length?Math.min(...a):null,max:a.length?Math.max(...a):null}}
function bucketFor(score){if(score>=95)return'95-100';if(score>=85)return'85-94';if(score>=75)return'75-84';if(score>=65)return'65-74';return'55-64'}
function bucketSummary(events,label){const x=events.filter(e=>bucketFor(e.score)===label);return{range:label,n:x.length,confidence:confidenceLabel(x.length),r10:summarize(x,'r10'),r20:summarize(x,'r20'),r40:summarize(x,'r40'),mfe40:{mean:avg(x.map(e=>e.mfe40)),median:med(x.map(e=>e.mfe40))},mae40:{mean:avg(x.map(e=>e.mae40)),median:med(x.map(e=>e.mae40))},worst40:x.length?Math.min(...x.map(e=>e.r40)):null}}
function monotonicity(buckets){const usable=buckets.filter(b=>b.n>=5&&Number.isFinite(b.r40.median));if(usable.length<3)return{status:'표본 부족',score:null,usable:usable.length};let good=0,total=0;for(let i=1;i<usable.length;i++){total++;if(usable[i].r40.median>=usable[i-1].r40.median)good++}return{status:good===total?'개선 경향':good/Math.max(1,total)>=.5?'혼합':'역행 가능',score:total?good/total*100:null,usable:usable.length}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=120');try{const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase();const interval=String(req.query.interval||'1h');const friction=Math.max(0,Math.min(2,Number(req.query.friction??0.2)));const cooldown=Math.max(1,Math.min(100,Number(req.query.cooldown??12)));const bars=Math.max(1000,Math.min(10000,Number(req.query.bars??5000)));const raw=await getKlinesPaged(symbol,interval,bars);if(!Array.isArray(raw)||raw.length<150)throw new Error('Not enough candle history');const d=build(raw),events=[],transitions=[];let machine='RESET',lastTrigger=-Infinity,armed=true,resetAfterTrigger=true;const maxHorizon=40;
for(let i=80;i<raw.length-maxHorizon-1;i++){const s=snapshot(d,i);if(!s)continue;const obs=observedState(s),prevMachine=machine;if(obs==='RESET'){machine='RESET';resetAfterTrigger=true;armed=true}else if(i-lastTrigger<cooldown){machine='COOLDOWN'}else if(obs==='EXTENDED'){machine='EXTENDED'}else if(obs==='FORMING'){machine='FORMING'}else if(obs==='READY'){machine='READY'}else if(obs==='TRIGGERED'){const validTransition=armed&&resetAfterTrigger&&(prevMachine==='FORMING'||prevMachine==='READY'||prevMachine==='RESET');if(validTransition&&!s.hard){const entry=d.o[i+1];if(entry){const r5=pct(d.c[i+5],entry)-friction,r10=pct(d.c[i+10],entry)-friction,r20=pct(d.c[i+20],entry)-friction,r30=pct(d.c[i+30],entry)-friction,r40=pct(d.c[i+40],entry)-friction;let maxH=-Infinity,minL=Infinity;for(let z=i+1;z<=i+40;z++){maxH=Math.max(maxH,d.h[z]);minL=Math.min(minL,d.l[z])}events.push({time:raw[i][0],score:Math.round(s.score),from:prevMachine,to:'TRIGGERED',entry,r5,r10,r20,r30,r40,mfe40:pct(maxH,entry),mae40:pct(minL,entry),rsi:s.rsi,volRatio:s.volRatio,atrPct:s.atrPct,buyRatio:s.buyRatio,reasons:s.reasons});lastTrigger=i;armed=false;resetAfterTrigger=false;machine='COOLDOWN';transitions.push({time:raw[i][0],from:prevMachine,to:'TRIGGERED',score:Math.round(s.score),reasons:s.reasons})}}else machine='TRIGGERED'}if(machine!==prevMachine&&transitions.length<1000&&obs!=='TRIGGERED')transitions.push({time:raw[i][0],from:prevMachine,to:machine,score:Math.round(s.score),reasons:s.reasons})}
const overall={r5:summarize(events,'r5'),r10:summarize(events,'r10'),r20:summarize(events,'r20'),r30:summarize(events,'r30'),r40:summarize(events,'r40'),mfe40:{mean:avg(events.map(e=>e.mfe40)),median:med(events.map(e=>e.mfe40))},mae40:{mean:avg(events.map(e=>e.mae40)),median:med(events.map(e=>e.mae40))}};const buckets=['55-64','65-74','75-84','85-94','95-100'].map(x=>bucketSummary(events,x));const mono=monotonicity(buckets);res.status(200).json({ok:true,version:'3.6',symbol,interval,requestedBars:bars,historyBars:raw.length,historyStart:raw[0][0],historyEnd:raw.at(-1)[0],assumptions:{mode:'Signal Study',signal:'FORMING/READY/RESET → TRIGGERED state transition only; hard risk excluded',referenceEntry:'next candle open',frictionPct:friction,cooldownBars:cooldown,rearm:'RESET observed after a trigger before a new event is allowed',holding:'5/10/20/30/40 candles, no TP/SL'},sampleSize:events.length,sampleConfidence:confidenceLabel(events.length),summary:overall,buckets,monotonicity:mono,horizon:[5,10,20,30,40].map(h=>({bars:h,...overall['r'+h]})),events:events.slice(-120).reverse(),transitions:transitions.slice(-160).reverse()})}catch(e){res.status(502).json({ok:false,error:e?.message||'Backtest failed'})}}