const spot=require('../lib/spot-detail.js');
const futures=require('../lib/futures-data.js');
const multi=require('../lib/multi-futures-data.js');
function capture(){let code=200,body=null;return{res:{setHeader(){},status(c){code=c;return this},json(v){body=v;return this}},get:()=>({code,body})}}
async function runSpot(req){const c=capture();try{await spot(req,c.res)}catch(e){return{code:500,body:{ok:false,error:e?.message||String(e)}}}return c.get()}
function stripHtml(s=''){return String(s).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function decode(s=''){return String(s).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<!\[CDATA\[|\]\]>/g,'').trim()}
function hasKo(s=''){return /[가-힣]/.test(String(s))}
function category(title=''){const t=title.toLowerCase();if(/burn|burning|소각|deflation/.test(t))return'소각/공급';if(/unlock|vesting|token release|언락|베스팅/.test(t))return'언락/공급';if(/mainnet|upgrade|hard fork|migration|migrate|bridge|shutdown|sunset|전환|마이그레이션|브리지|종료/.test(t))return'네트워크/전환';if(/list|listing|delist|perpetual|futures|spot market|상장|선물/.test(t))return'거래소/파생';if(/airdrop|snapshot|claim|에어드롭/.test(t))return'에어드롭';if(/governance|proposal|vote|dao|거버넌스|투표/.test(t))return'거버넌스';if(/partnership|partner|integration|launch|adoption|제휴|통합|출시/.test(t))return'사업/파트너십';return'관련 뉴스'}
function eventLike(title=''){return /will|plans?|scheduled|deadline|upcoming|launch|starts?|ends?|shutdown|migration|bridge|vote|proposal|airdrop|unlock|burn|list|\b20\d{2}\b|예정|일정|마감|종료|소각|언락|상장|출시|투표/i.test(title)}
function parseRss(xml=''){const out=[];for(const block of String(xml).match(/<item>[\s\S]*?<\/item>/g)||[]){const pick=tag=>{const m=block.match(new RegExp(`<${tag}(?: [^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decode(stripHtml(m[1])):''};const sm=block.match(/<source(?: [^>]*)?>([\s\S]*?)<\/source>/i),title=pick('title');if(title)out.push({title,link:pick('link'),pubDate:pick('pubDate'),source:sm?decode(stripHtml(sm[1])):'',category:category(title),isEvent:eventLike(title)})}return out}
async function getJson(url){const ac=new AbortController(),to=setTimeout(()=>ac.abort(),5500);try{const r=await fetch(url,{signal:ac.signal,headers:{'User-Agent':'PulseRadar/1.0','Accept':'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}finally{clearTimeout(to)}}
async function getText(url){const ac=new AbortController(),to=setTimeout(()=>ac.abort(),5500);try{const r=await fetch(url,{signal:ac.signal,headers:{'User-Agent':'Mozilla/5.0 PulseRadar/1.0','Accept':'application/rss+xml,text/xml,*/*'}});if(!r.ok)throw Error('HTTP '+r.status);return r.text()}finally{clearTimeout(to)}}
function dedupe(a){const seen=new Set();return a.filter(x=>{const k=x.title.toLowerCase().replace(/[^a-z0-9가-힣]/g,'');if(seen.has(k))return false;seen.add(k);return true})}
async function translateKo(text){if(!text||hasKo(text))return text;try{const url='https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=ko&dt=t&q='+encodeURIComponent(text);const j=await getJson(url);const out=(j?.[0]||[]).map(x=>x?.[0]||'').join('').trim();return out||text}catch{return text}}
function parseAmount(title,base){const t=String(title),re=new RegExp('([0-9]+(?:\\.[0-9]+)?)\\s*(K|M|B|million|billion|thousand)?\\s*'+base+'\\b','i'),m=t.match(re);if(!m)return null;let n=Number(m[1]),u=(m[2]||'').toLowerCase();if(u==='k'||u==='thousand')n*=1e3;if(u==='m'||u==='million')n*=1e6;if(u==='b'||u==='billion')n*=1e9;return Number.isFinite(n)?n:null}
function extractEventDate(title){const t=String(title);let m=t.match(/\b(20\d{2})[-\/.](\d{1,2})[-\/.](\d{1,2})\b/);if(m){const d=new Date(`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}T00:00:00Z`);if(!isNaN(d))return d.toISOString()}m=t.match(/\b(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)\s+(\d{1,2})(?:st|nd|rd|th)?,?\s+(20\d{2})\b/i);if(m){const d=new Date(`${m[1]} ${m[2]}, ${m[3]} 00:00:00 UTC`);if(!isNaN(d))return d.toISOString()}m=t.match(/\b(20\d{2})년\s*(\d{1,2})월\s*(\d{1,2})일/);if(m){const d=new Date(`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}T00:00:00Z`);if(!isNaN(d))return d.toISOString()}return null}
function importance(x){let s=20;if(x.category==='소각/공급'||x.category==='언락/공급')s+=35;if(x.category==='네트워크/전환')s+=30;if(x.category==='거래소/파생')s+=20;if(x.category==='거버넌스')s+=15;if(x.isEvent)s+=10;if(/official|foundation|labs|dao/i.test(x.source||''))s+=10;return Math.min(100,s)}
const num=v=>{v=Number(v);return Number.isFinite(v)?v:null};
function pctChange(a,b){a=num(a);b=num(b);return a!=null&&b!=null&&a!==0?(b-a)/Math.abs(a)*100:null}
function sum(a){return a.reduce((s,x)=>s+(num(x)||0),0)}
async function derivativesIntel(symbol){const base='https://fapi.binance.com';try{const [premiumR,oiR,oiHistR,tickerR,klinesR,takerR]=await Promise.allSettled([
getJson(`${base}/fapi/v1/premiumIndex?symbol=${encodeURIComponent(symbol)}`),
getJson(`${base}/fapi/v1/openInterest?symbol=${encodeURIComponent(symbol)}`),
getJson(`${base}/futures/data/openInterestHist?symbol=${encodeURIComponent(symbol)}&period=1h&limit=25`),
getJson(`${base}/fapi/v1/ticker/24hr?symbol=${encodeURIComponent(symbol)}`),
getJson(`${base}/fapi/v1/klines?symbol=${encodeURIComponent(symbol)}&interval=1h&limit=49`),
getJson(`${base}/futures/data/takerlongshortRatio?symbol=${encodeURIComponent(symbol)}&period=1h&limit=12`)
]);
if(premiumR.status!=='fulfilled'||tickerR.status!=='fulfilled')return{available:false,reason:'Binance USD-M 무기한 선물 미지원 또는 데이터 없음'};
const premium=premiumR.value||{},ticker=tickerR.value||{},oi=oiR.status==='fulfilled'?oiR.value:null,oh=oiHistR.status==='fulfilled'&&Array.isArray(oiHistR.value)?oiHistR.value:[],ks=klinesR.status==='fulfilled'&&Array.isArray(klinesR.value)?klinesR.value:[],tk=takerR.status==='fulfilled'&&Array.isArray(takerR.value)?takerR.value:[];
const mark=num(premium.markPrice),oiContracts=num(oi?.openInterest),oiUsd=oiContracts!=null&&mark!=null?oiContracts*mark:null,oi24=pctChange(oh[0]?.sumOpenInterestValue,oh.at(-1)?.sumOpenInterestValue),funding=num(premium.lastFundingRate),fundingPct=funding!=null?funding*100:null;
const closed=ks.filter(k=>num(k?.[6])<Date.now()),recent=closed.slice(-24),prev=closed.slice(-48,-24),recentQ=sum(recent.map(k=>k?.[7])),prevQ=sum(prev.map(k=>k?.[7])),volumeRatio=prevQ>0?recentQ/prevQ:null,change24=num(ticker.priceChangePercent),quoteVol24=num(ticker.quoteVolume);
const takerBuy=avgSafe(tk.map(x=>num(x.buyVol)).filter(Number.isFinite)),takerSell=avgSafe(tk.map(x=>num(x.sellVol)).filter(Number.isFinite)),takerRatio=takerSell>0?takerBuy/takerSell:null;
let pressure='중립';const flags=[];if(oi24!=null&&oi24>=20)flags.push('미결제약정 급증');if(volumeRatio!=null&&volumeRatio>=2)flags.push('거래량 급증');if(fundingPct!=null&&Math.abs(fundingPct)>=.05)flags.push(fundingPct>0?'양(+) 펀딩 쏠림':'음(-) 펀딩 쏠림');if(takerRatio!=null&&takerRatio>=1.2)flags.push('공격적 매수 우위');if(takerRatio!=null&&takerRatio<=.8)flags.push('공격적 매도 우위');if(flags.length>=3)pressure='레버리지 과열';else if(flags.length>=1)pressure='레버리지 확대';
return{available:true,symbol,markPrice:mark,change24,quoteVolume24:quoteVol24,openInterestContracts:oiContracts,openInterestUsdApprox:oiUsd,openInterestChange24hPct:oi24,fundingRate:funding,fundingRatePct:fundingPct,nextFundingTime:num(premium.nextFundingTime),volume24hVsPrev24hRatio:volumeRatio,takerBuySellRatio:takerRatio,pressure,flags,liquidation:{available:false,exact24hUsd:null,note:'Binance 공개 REST만으로는 시장 전체 24시간 청산 총액을 제공하지 않아 정확한 청산액은 표시하지 않습니다.'},source:'Binance USD-M public REST'}
}catch(e){return{available:false,reason:'선물 시장 지표를 불러오지 못했습니다.',detail:e?.message||String(e)}}}
function avgSafe(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}
function catalystSummary(news,change24,deriv){const cats=new Set(news.slice(0,12).map(x=>x.category)),factors=[];if(cats.has('소각/공급'))factors.push('소각·공급 감소 기대');if(cats.has('언락/공급'))factors.push('언락·베스팅 공급 변화');if(cats.has('네트워크/전환'))factors.push('메인넷·마이그레이션·네트워크 전환');if(cats.has('거래소/파생'))factors.push('거래소 상장·파생상품 이슈');if(cats.has('거버넌스'))factors.push('DAO·거버넌스 결정');if(cats.has('사업/파트너십'))factors.push('출시·제휴·사업 확장');if(deriv?.available){if(deriv.openInterestChange24hPct>=20)factors.push('선물 미결제약정 급증');if(deriv.volume24hVsPrev24hRatio>=2)factors.push('선물 거래량 급증');if(Math.abs(deriv.fundingRatePct||0)>=.05)factors.push('펀딩비 쏠림');if(deriv.takerBuySellRatio>=1.2)factors.push('선물 공격적 매수 우위');if(deriv.takerBuySellRatio<=.8)factors.push('선물 공격적 매도 우위')}
let direction='가격 변동';if(Number.isFinite(change24))direction=change24>=8?'급등':change24<=-8?'급락':change24>=2?'상승':change24<=-2?'하락':'보합권';const intro=Number.isFinite(change24)?`최근 24시간 가격은 ${change24>=0?'+':''}${change24.toFixed(2)}%로 ${direction} 흐름입니다.`:'최근 가격 변동률을 확인하지 못했습니다.';const reason=factors.length?` 공개 뉴스·선물 데이터에서 ${factors.slice(0,6).join(', ')}가 함께 관측됩니다.`:' 공개 정보만으로 뚜렷한 단일 촉매는 확인되지 않습니다.';const squeeze=deriv?.available&&deriv.openInterestChange24hPct>=20&&deriv.volume24hVsPrev24hRatio>=2?` 레버리지 참여가 빠르게 늘어난 구간이라 강제청산이 변동성을 확대했을 가능성은 있으나, 공개 REST만으로 정확한 시장 전체 청산액은 확인할 수 없습니다.`:'';return{direction,summary:intro+reason+squeeze+' 이는 원인 확정이 아니라 공개 정보 기반의 가능 요인 정리입니다.',factors}}
async function intel(symbol){const base=String(symbol||'BTCUSDT').toUpperCase().replace(/USDT$/,''),pair=base+'USDT',warnings=[];let coin=null,news=[];try{const s=await getJson('https://api.coingecko.com/api/v3/search?query='+encodeURIComponent(base));const exact=(s.coins||[]).find(x=>String(x.symbol).toUpperCase()===base)||(s.coins||[])[0];if(exact)coin=await getJson(`https://api.coingecko.com/api/v3/coins/${encodeURIComponent(exact.id)}?localization=true&tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false`)}catch(e){warnings.push('프로젝트 메타데이터를 불러오지 못했습니다.')}
const name=coin?.name||base;try{const [en,ko]=await Promise.allSettled([getText('https://news.google.com/rss/search?q='+encodeURIComponent(`${name} ${base} crypto token`)+'&hl=en-US&gl=US&ceid=US:en'),getText('https://news.google.com/rss/search?q='+encodeURIComponent(`${name} ${base} 코인`)+'&hl=ko&gl=KR&ceid=KR:ko')]);let all=[];if(en.status==='fulfilled')all.push(...parseRss(en.value));if(ko.status==='fulfilled')all.push(...parseRss(ko.value));news=dedupe(all).slice(0,20)}catch(e){warnings.push('최신 뉴스 피드를 불러오지 못했습니다.')}
const toTranslate=news.filter(x=>!hasKo(x.title)).slice(0,12);await Promise.all(toTranslate.map(async x=>{x.titleKo=await translateKo(x.title)}));news.forEach(x=>{x.titleKo=x.titleKo||x.title;x.eventDate=extractEventDate(x.title);x.importance=importance(x);x.amount=parseAmount(x.title,base)});
const md=coin?.market_data||{},supply=md.total_supply??md.circulating_supply??null;news.forEach(x=>{x.supplyRatio=x.amount&&supply?x.amount/supply*100:null});
const deriv=await derivativesIntel(pair),events=news.filter(x=>x.isEvent||x.category!=='관련 뉴스').sort((a,b)=>{const ad=a.eventDate?new Date(a.eventDate).getTime():0,bd=b.eventDate?new Date(b.eventDate).getTime():0;return(bd-ad)||(b.importance-a.importance)}).slice(0,10),burns=news.filter(x=>x.category==='소각/공급'||x.category==='언락/공급').sort((a,b)=>b.importance-a.importance).slice(0,7),exchange=news.filter(x=>x.category==='거래소/파생').sort((a,b)=>b.importance-a.importance).slice(0,7),liquidationNews=news.filter(x=>/liquidat|short squeeze|long squeeze|청산|숏\s*스퀴즈|롱\s*스퀴즈/i.test(x.title+' '+x.titleKo)).slice(0,5),links=coin?.links||{},official=[];(links.homepage||[]).filter(Boolean).slice(0,1).forEach(url=>official.push({label:'공식 홈페이지',url}));(links.announcement_url||[]).filter(Boolean).slice(0,2).forEach((url,i)=>official.push({label:i?'공식 공지 2':'공식 공지',url}));if(links.twitter_screen_name)official.push({label:'공식 X',url:'https://x.com/'+links.twitter_screen_name});const change24=Number(md.price_change_percentage_24h),catalyst=catalystSummary(news,Number.isFinite(change24)?change24:deriv.change24,deriv),descKo=stripHtml(coin?.description?.ko||''),descEn=stripHtml(coin?.description?.en||'');let description=descKo||descEn.slice(0,700);if(!descKo&&descEn)description=await translateKo(descEn.slice(0,700));const timeline=events.map(x=>({title:x.title,titleKo:x.titleKo,category:x.category,source:x.source,link:x.link,pubDate:x.pubDate,eventDate:x.eventDate,importance:x.importance,amount:x.amount,supplyRatio:x.supplyRatio}));return{ok:true,intel:true,version:'coin-intel-v3-derivatives',symbol:pair,base,name,updatedAt:new Date().toISOString(),project:{name,symbol:base,description,marketCapUsd:md.market_cap?.usd??null,circulating:md.circulating_supply??null,totalSupply:md.total_supply??null,maxSupply:md.max_supply??null,priceUsd:md.current_price?.usd??deriv.markPrice??null,change24:Number.isFinite(change24)?change24:deriv.change24??null},summary:{headline:events[0]?.titleKo||news[0]?.titleKo||'최근 주요 이벤트 없음',eventCount:events.length,burnCount:burns.length,exchangeCount:exchange.length,newsCount:news.length},catalyst,derivatives:deriv,liquidationNews,timeline,events,burns,exchange,news:news.slice(0,14),official,warnings,note:'공개 뉴스·프로젝트 메타데이터·Binance USD-M 공개 선물 데이터를 자동 수집·번역·분류한 결과입니다. 선물 지표는 연구용 시장 상태 정보이며 매매 지시가 아닙니다. Binance 공개 REST만으로 정확한 시장 전체 청산액은 제공되지 않아 청산 총액은 추정하지 않습니다. 일정·소각·언락·상장 여부는 반드시 공식 원문에서 재확인하세요.'}}
function externalFuturesDetail(row,requested){
  const exchanges=Array.isArray(row?.exchanges)?row.exchanges:[],name=String(requested||row?.symbol||'').toUpperCase();
  return{ok:true,market:'futures',symbol:row?.symbol||name,externalFuturesOnly:true,sourceExchanges:exchanges,primaryExchange:row?.primaryExchange||null,
    timeframes:[],preSurge:{score:row?.preScore??0,stage:'외부 선물 관찰',reasons:[`${exchanges.length||1}개 선물 거래소 중복 제거 집계`,'Binance 정밀 캔들 미지원 종목은 외부 시세 기준으로만 표시']},
    surge:{score:row?.surgeScore??0,aligned:0},
    riskGate:{hard:[],warn:['외부 거래소 전용 종목 · 정밀 MTF 지표는 아직 Binance 지원 종목에 우선 제공'],excluded:false},
    confidence:{grade:'OBSERVE',label:'멀티거래소 선물 시세 관찰'},
    externalMarket:{price:row?.price??null,change24:row?.change24??null,quoteVolume24h:row?.quoteVol24??null,exchangeCount:row?.exchangeCount??exchanges.length,openInterestUsd:row?.openInterestUsd??null,fundingRate:row?.fundingRate??null,contracts:row?.contracts||[]}};
}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=300');try{
  if(String(req.query.intel||'')==='1')return res.status(200).json(await intel(req.query.symbol));
  const requested=String(req.query.symbol||'BTCUSDT').toUpperCase();
  const s=await runSpot(req);if(s.code<400&&s.body?.ok)return res.status(200).json({...s.body,market:'spot'});
  try{return res.status(200).json(await futures.detail(requested))}
  catch(_binanceError){
    const row=await multi.find(requested);
    if(row?.detailSymbol){try{return res.status(200).json(await futures.detail(row.detailSymbol))}catch(_e){}}
    if(row)return res.status(200).json(externalFuturesDetail(row,requested));
    throw _binanceError;
  }
}catch(e){return res.status(502).json({ok:false,error:e?.message||'Detail fetch failed'})}}
