const BASES=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];
const n=v=>Number(v)||0,avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null,med=a=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2},pct=(a,b)=>b?((a/b)-1)*100:null;
async function getJson(path,params={}){let last;const qs=new URLSearchParams(params).toString();for(const base of BASES){try{const r=await fetch(base+path+(qs?'?'+qs:''),{headers:{'User-Agent':'PulseRadar-Pro/3.12.2'}});const t=await r.text();if(!r.ok)throw Error(`Binance ${r.status}`);return JSON.parse(t)}catch(e){last=e}}throw last||Error('Binance failed')}
async function paged(symbol,interval,bars){let out=[],end;while(out.length<bars){const lim=Math.min(1000,bars-out.length),p={symbol,interval,limit:String(lim)};if(end)p.endTime=String(end);const a=await getJson('/api/v3/klines',p);if(!a.length)break;out=a.concat(out);end=Number(a[0][0])-1;if(a.length<lim)break}const seen=new Set();return out.filter(k=>{const t=n(k[0]);if(seen.has(t))return false;seen.add(t);return true}).sort((a,b)=>n(a[0])-n(b[0])).slice(-bars)}
function sma(a,p){let o=Array(a.length).fill(null),s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)o[i]=s/p}return o}
function pivots(h,l,left=3,right=3){const out=[];for(let i=left;i<h.length-right;i++){let ph=true,pl=true;for(let j=i-left;j<=i+right;j++){if(j===i)continue;if(h[j]>=h[i])ph=false;if(l[j]<=l[i])pl=false}if(ph)out.push({i,type:'H',price:h[i],confirmedAt:i+right});if(pl)out.push({i,type:'L',price:l[i],confirmedAt:i+right})}return out.sort((a,b)=>a.confirmedAt-b.confirmedAt)}
function labels(ps){let lh=null,ll=null;return ps.map(p=>{let label;if(p.type==='H'){label=lh==null?'H':p.price>lh?'HH':'LH';lh=p.price}else{label=ll==null?'L':p.price>ll?'HL':'LL';ll=p.price}return{...p,label}})}
function summarize(a){return{n:a.length,mean:avg(a),median:med(a),positiveRate:a.length?a.filter(x=>x>0).length/a.length*100:null,min:a.length?Math.min(...a):null,max:a.length?Math.max(...a):null}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=120');try{const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase(),interval=String(req.query.interval||'1h'),bars=Math.max(1000,Math.min(10000,n(req.query.bars)||5000)),raw=await paged(symbol,interval,bars);if(raw.length<200)throw Error('Not enough history');const t=raw.map(k=>n(k[0])),o=raw.map(k=>n(k[1])),h=raw.map(k=>n(k[2])),l=raw.map(k=>n(k[3])),c=raw.map(k=>n(k[4])),v=raw.map(k=>n(k[5])),vs=sma(v,20),ps=labels(pivots(h,l,3,3)),events=[];let activeH=null,activeL=null,trend='neutral',pidx=0;for(let i=10;i<raw.length-41;i++){while(pidx<ps.length&&ps[pidx].confirmedAt<=i){const p=ps[pidx++];if(p.type==='H')activeH=p;else activeL=p;if((p.label==='HL'||p.label==='LL'||p.label==='HH'||p.label==='LH')&&p.confirmedAt===i){events.push({kind:p.label,i,time:t[i],level:p.price,volumeRatio:vs[i]?v[i]/vs[i]:null})}}if(activeH&&c[i]>activeH.price){const kind=trend==='down'?'CHOCH_UP':'BOS_UP';events.push({kind,i,time:t[i],level:activeH.price,volumeRatio:vs[i]?v[i]/vs[i]:null});trend='up';activeH=null}if(activeL&&c[i]<activeL.price){const kind=trend==='up'?'CHOCH_DOWN':'BOS_DOWN';events.push({kind,i,time:t[i],level:activeL.price,volumeRatio:vs[i]?v[i]/vs[i]:null});trend='down';activeL=null}}
const enriched=[];for(const e of events){const i=e.i,entry=o[i+1];if(!entry||i+40>=raw.length)continue;const dir=e.kind.endsWith('_DOWN')?-1:1;let maxH=-Infinity,minL=Infinity;for(let z=i+1;z<=i+40;z++){maxH=Math.max(maxH,h[z]);minL=Math.min(minL,l[z])}const ret=x=>dir*pct(c[i+x],entry);enriched.push({...e,entry,r10:ret(10),r20:ret(20),r40:ret(40),mfe40:dir===1?pct(maxH,entry):-pct(minL,entry),mae40:dir===1?pct(minL,entry):-pct(maxH,entry)})}
const kinds=['BOS_UP','CHOCH_UP','HL','HH','BOS_DOWN','CHOCH_DOWN','LH','LL'],stats=kinds.map(kind=>{const a=enriched.filter(e=>e.kind===kind);return{kind,n:a.length,r10:summarize(a.map(x=>x.r10).filter(Number.isFinite)),r20:summarize(a.map(x=>x.r20).filter(Number.isFinite)),r40:summarize(a.map(x=>x.r40).filter(Number.isFinite)),mfe40:summarize(a.map(x=>x.mfe40).filter(Number.isFinite)),mae40:summarize(a.map(x=>x.mae40).filter(Number.isFinite)),avgVolumeRatio:avg(a.map(x=>x.volumeRatio).filter(Number.isFinite))}});res.status(200).json({ok:true,version:'3.12.2',symbol,interval,historyBars:raw.length,pivotRule:'left3/right3; event usable only at confirmedAt',entryReference:'next candle open',note:'Directional event study only. No TP/SL or execution simulation.',stats,events:enriched.slice(-120).reverse()})}catch(e){res.status(502).json({ok:false,error:e.message})}}
