(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseMultiChartCard=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){
  const htfFor=tf=>tf==='15m'||tf==='1h'?'4h':tf==='4h'?'1d':null;
  function browserDeps(){return{chartCore:root.PulseChartCore,plugins:root.PulseChartPlugins,chartData:root.PulseChartData,smcEngine:root.PulseSmcEngine,liquidityEngine:root.PulseLiquidityEngine,ictContextEngine:root.PulseIctContextEngine,factories:{structure:()=>root.PulseStructurePlugin.createStructurePlugin(),smc:()=>root.PulseSmcPlugin.createSmcPlugin(),liquidity:()=>root.PulseLiquidityPlugin.createLiquidityPlugin(),ict:()=>root.PulseIctPlugin.createIctPlugin(),dante:()=>root.PulseDantePlugin.createDantePlugin()}}}
  function createChartCard({root:host,config,library,coordinator,modeRegistry,onConfigChange=()=>{},deps,headless=false}={}){
    const D=deps||browserDeps();let cfg={...config},core=null,registry=null,status={state:'idle',message:'대기'},disposed=false;
    const getDef=()=>typeof modeRegistry?.getModeDefinition==='function'?modeRegistry.getModeDefinition(cfg.mode,(typeof innerWidth==='number'&&innerWidth<=760)?'mobile':'desktop'):modeRegistry?.(cfg.mode)||{presetId:cfg.mode,plugins:[],panes:[]};
    const setStatus=(state,message)=>{status={state,message};if(!headless&&host){const el=host.querySelector?.('[data-role="status"]');if(el){el.dataset.state=state;el.textContent=message}}};
    function renderShell(){if(headless||!host)return;host.className='mcCard';host.dataset.chartId=cfg.id;host.innerHTML=`<div class="mcCardHead"><div class="mcCardTitle"><b data-role="title">${cfg.symbol}</b><small>${cfg.id}</small></div><div class="mcCardControls"><select data-role="tf"><option>15m</option><option>1h</option><option>4h</option><option>1d</option></select><select data-role="mode"><option value="clean">Clean</option><option value="structure">Structure</option><option value="smc">SMC</option><option value="liquidity">Liquidity</option><option value="ict">ICT</option><option value="dante">Dante</option><option value="full">Full</option></select><button data-role="duplicate" title="차트 복제">⧉</button><button data-role="maximize" title="확대">⛶</button></div></div><div data-role="visual" class="mcVisualProfile"></div><div data-role="chart" class="mcChartHost"></div><div data-role="status" class="mcCardStatus">대기</div><div data-role="narrative" class="mcNarrative"></div>`;const tf=host.querySelector('[data-role="tf"]'),mode=host.querySelector('[data-role="mode"]');tf.value=cfg.timeframe;mode.value=cfg.mode;tf.onchange=()=>{setConfig({timeframe:tf.value});onConfigChange(cfg.id,{timeframe:tf.value})};mode.onchange=()=>{setConfig({mode:mode.value});onConfigChange(cfg.id,{mode:mode.value})};host.querySelector('[data-role="duplicate"]').onclick=()=>onConfigChange(cfg.id,{action:'duplicate'});host.querySelector('[data-role="maximize"]').onclick=()=>onConfigChange(cfg.id,{action:'maximize'});}
    function makePreset(def){const profile=def.visualProfile;const budget=profile==='full'?8:profile==='smc'?5:profile==='ict'||profile==='liquidity'?4:profile==='structure'||profile==='dante'?5:1;return{id:def.presetId||cfg.mode,label:cfg.mode,maxZones:budget,panes:def.panes||[]}}
    function narrativeFor(def,ictContext){if(def.visualProfile!=='ict')return'';return ictContext?.narrative?.text||'확인된 ICT 시퀀스가 아직 없습니다.'}
    async function load(){if(disposed)throw new Error('chart disposed');setStatus('loading','불러오는 중…');const def=getDef();try{const analysis=await coordinator.load(cfg.symbol,cfg.timeframe),raw=Array.isArray(analysis?.candles)?analysis.candles:[];if(!raw.length)throw new Error('확정봉 데이터가 없습니다');let htf=null,htfTf=htfFor(cfg.timeframe);if(htfTf){try{htf=await coordinator.load(cfg.symbol,htfTf)}catch{htf=null}}const normalized=D.chartData.normalizeCandles(raw),smc=D.smcEngine.analyzeSmcV2({candles:raw,canonicalSwings:analysis.canonicalSwings||[],canonicalEvents:analysis.events||[],htf:{bias:htf?.bias||null}});const layerErrors=[];let liquidity=null,ictContext=null;try{if(typeof D.liquidityEngine?.analyzeLiquidity!=='function')throw new Error('Liquidity Engine unavailable');liquidity=D.liquidityEngine.analyzeLiquidity({candles:raw,timeframe:cfg.timeframe,pivots:smc.canonicalSwings||analysis.canonicalSwings||[],equalLevels:smc.equalLevels||[],sweeps:smc.sweeps||[],displacement:smc.displacements||[],mss:smc.mss||[],fvgs:smc.fvgs||[],orderBlocks:smc.orderBlocks||[]})}catch(e){layerErrors.push(`liquidity: ${e?.message||'error'}`)}try{if(typeof D.ictContextEngine?.buildIctContext!=='function')throw new Error('ICT Context Engine unavailable');ictContext=D.ictContextEngine.buildIctContext({htf:{tf:htfTf||cfg.timeframe,swings:htf?.canonicalSwings||htf?.swings||smc.canonicalSwings||[],bias:htf?.bias||'neutral'},ltf:{tf:cfg.timeframe,mss:smc.mss||[],displacements:smc.displacements||[],mitigations:smc.mitigations||[]},smc,liquidity,currentIndex:raw.length-1})}catch(e){layerErrors.push(`ict: ${e?.message||'error'}`)}registry?.disposeAll?.();core?.dispose?.();const container=headless?{}:host.querySelector('[data-role="chart"]');const preset=makePreset(def);core=D.chartCore.createUnifiedChart({container,library:library||(root&&root.LightweightCharts),preset});core.setData({...normalized,indicators:{}});registry=D.plugins.createPluginRegistry();for(const id of def.plugins||[]){const f=D.factories?.[id];if(typeof f==='function')registry.register(f())}registry.mountAll(core);registry.updateAll({analysis,smc,liquidity,ictContext,rawCandles:raw,candles:normalized.candles,preset,dataApi:D.chartData});if(!headless&&host){host.dataset.mode=cfg.mode;host.dataset.profile=def.visualProfile;host.querySelector('[data-role="title"]').textContent=`${cfg.symbol} · ${cfg.timeframe}`;host.querySelector('[data-role="visual"]').textContent=def.visualProfile.toUpperCase();host.querySelector('[data-role="narrative"]').textContent=narrativeFor(def,ictContext)}if(layerErrors.length)setStatus('degraded',layerErrors.join(' · '));else setStatus('ready',`${raw.length}개 확정봉`);return{analysis,smc,liquidity,ictContext,preset}}catch(e){setStatus('error',e?.message||'차트 오류');throw e}}
    async function setConfig(patch={}){const prevTf=cfg.timeframe,prevMode=cfg.mode,prevSymbol=cfg.symbol;cfg={...cfg,...patch};if(!headless&&host){const tf=host.querySelector('[data-role="tf"]'),mode=host.querySelector('[data-role="mode"]');if(tf)tf.value=cfg.timeframe;if(mode)mode.value=cfg.mode}if(prevTf!==cfg.timeframe||prevMode!==cfg.mode||prevSymbol!==cfg.symbol)return load();return null}
    function resize(){core?.resize?.()}
    function dispose(){disposed=true;registry?.disposeAll?.();core?.dispose?.();registry=null;core=null;if(!headless&&host)host.innerHTML=''}
    function getStatus(){return{...status}}
    renderShell();return{load,setConfig,resize,dispose,getStatus,getConfig:()=>({...cfg})};
  }
  return{createChartCard,htfFor};
});