'use strict';
const TF_ORDER=['1w','1d','4h','1h','15m'];
const TF_ROLE={
 '1w':'장기 사이클','1d':'중기 구조','4h':'핵심 구조','1h':'단기 모멘텀','15m':'단기 타이밍'
};
function finite(v){const n=Number(v);return Number.isFinite(n)?n:null}
function row(k){if(!Array.isArray(k)||k.length<6)return null;return{t:finite(k[0]),o:finite(k[1]),h:finite(k[2]),l:finite(k[3]),c:finite(k[4]),v:finite(k[5]),q:finite(k[7]),buyQ:finite(k[10])}}
function rows(klines){return (Array.isArray(klines)?klines:[]).map(row).filter(x=>x&&[x.o,x.h,x.l,x.c].every(Number.isFinite))}
function avg(a){const x=a.filter(Number.isFinite);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null}
function pct(a,b){return a&&Number.isFinite(a)&&Number.isFinite(b)?((b/a)-1)*100:null}
function atr(candles,n=14){if(candles.length<2)return null;const tr=[];for(let i=1;i<candles.length;i++){const x=candles[i],p=candles[i-1];tr.push(Math.max(x.h-x.l,Math.abs(x.h-p.c),Math.abs(x.l-p.c)))}return avg(tr.slice(-n))}
function swings(candles,span=2){const out=[];for(let i=span;i<candles.length-span;i++){let hi=true,lo=true;for(let j=i-span;j<=i+span;j++){if(j===i)continue;if(candles[j].h>=candles[i].h)hi=false;if(candles[j].l<=candles[i].l)lo=false}if(hi)out.push({index:i,price:candles[i].h,type:'H'});if(lo)out.push({index:i,price:candles[i].l,type:'L'})}return out}
function metric(klines){const c=rows(klines);if(c.length<5)return{available:false,trend:'unknown',returnPct:null,volumeAcceleration:null,takerRatio:null,atr:null,last:null,swings:[]};const closes=c.map(x=>x.c),last=c.at(-1),ma20=avg(closes.slice(-20)),ret=pct(closes[Math.max(0,closes.length-21)],last.c),volRecent=avg(c.slice(-5).map(x=>x.v)),volBase=avg(c.slice(-25,-5).map(x=>x.v)),volumeAcceleration=volBase>0?volRecent/volBase:null;let buy=0,sell=0;for(const x of c.slice(-12)){if(x.q>0&&x.buyQ!=null&&x.q>=x.buyQ){buy+=x.buyQ;sell+=x.q-x.buyQ}}const takerRatio=sell>0?buy/sell:buy>0?99:null;const trend=last.c>ma20*1.01&&ret>0?'bullish':last.c<ma20*.99&&ret<0?'bearish':'neutral';return{available:true,trend,returnPct:ret,volumeAcceleration,takerRatio,atr:atr(c),last:last.c,ma20,swings:swings(c),candles:c}}
function nearestLevels(m){if(!m.available)return{support:null,resistance:null,supportZone:null,resistanceZone:null};const price=m.last,A=m.atr||price*.01,lows=m.swings.filter(x=>x.type==='L'&&x.price<price).sort((a,b)=>b.price-a.price),highs=m.swings.filter(x=>x.type==='H'&&x.price>price).sort((a,b)=>a.price-b.price);const support=lows[0]?.price??Math.min(...m.candles.slice(-20).map(x=>x.l)),resistance=highs[0]?.price??Math.max(...m.candles.slice(-20).map(x=>x.h));return{support,resistance,supportZone:[support-A*.35,support+A*.35],resistanceZone:[resistance-A*.35,resistance+A*.35]}}
function fvgs(m){if(!m.available)return[];const c=m.candles,out=[];for(let i=Math.max(2,c.length-45);i<c.length;i++){if(c[i].l>c[i-2].h)out.push({type:'bullish',from:c[i-2].h,to:c[i].l,index:i});else if(c[i].h<c[i-2].l)out.push({type:'bearish',from:c[i].h,to:c[i-2].l,index:i})}return out.slice(-3)}
function liquidity(m){if(!m.available)return[];const A=m.atr||m.last*.01,tol=A*.35,pts=m.swings.slice(-14),out=[];for(const type of ['H','L']){const a=pts.filter(x=>x.type===type);for(let i=0;i<a.length;i++){const cluster=a.filter((x,j)=>j!==i&&Math.abs(x.price-a[i].price)<=tol);if(cluster.length){out.push({type:type==='H'?'buy_side':'sell_side',price:avg([a[i].price,...cluster.map(x=>x.price)]),touches:cluster.length+1});break}}}return out}
function structureBreak(m){if(!m.available)return{type:'none',price:null};const prev=m.swings.filter(x=>x.index<m.candles.length-2),last=m.candles.at(-1).c,hi=prev.filter(x=>x.type==='H').at(-1),lo=prev.filter(x=>x.type==='L').at(-1);if(hi&&last>hi.price)return{type:'BOS_BULLISH',price:hi.price};if(lo&&last<lo.price)return{type:'BOS_BEARISH',price:lo.price};return{type:'none',price:null}}
function patternLine(a,b,base,span=29){if(!a||!b||b.index===a.index)return null;const slope=(b.price-a.price)/(b.index-a.index),endIndex=base+span;return{x1:Math.max(0,Math.min(1,(a.index-base)/span)),y1:a.price,x2:1,y2:b.price+slope*(endIndex-b.index)}}
function simplePattern(m){if(!m.available||m.candles.length<30)return{name:'none',label:'뚜렷한 패턴 없음',state:'관찰',geometry:null};const c=m.candles.slice(-30),base=m.candles.length-30,half=Math.floor(c.length/2),r1=Math.max(...c.slice(0,half).map(x=>x.h))-Math.min(...c.slice(0,half).map(x=>x.l)),r2=Math.max(...c.slice(half).map(x=>x.h))-Math.min(...c.slice(half).map(x=>x.l)),s=m.swings.filter(x=>x.index>=base).slice(-10),H=s.filter(x=>x.type==='H'),L=s.filter(x=>x.type==='L'),flatH=H.length>=2&&Math.abs(H.at(-1).price-H.at(-2).price)<=Math.max(m.atr||0,m.last*.004),riseL=L.length>=2&&L.at(-1).price>L.at(-2).price,fallH=H.length>=2&&H.at(-1).price<H.at(-2).price,upper=patternLine(H.at(-2),H.at(-1),base),lower=patternLine(L.at(-2),L.at(-1),base);if(flatH&&riseL)return{name:'ascending_triangle',label:'상승 삼각수렴',state:'상단 돌파 여부 관찰',geometry:{upper,lower}};if(fallH&&riseL)return{name:'symmetrical_triangle',label:'대칭 삼각수렴',state:'수렴 이탈 방향 관찰',geometry:{upper,lower}};if(r2<r1*.65){const first=c.slice(0,half),second=c.slice(half);return{name:'compression',label:'변동성 수렴',state:'변동성 확대 가능 구간',geometry:{upper:{x1:0,y1:Math.max(...first.map(x=>x.h)),x2:1,y2:Math.max(...second.map(x=>x.h))},lower:{x1:0,y1:Math.min(...first.map(x=>x.l)),x2:1,y2:Math.min(...second.map(x=>x.l))}}}}const top=Math.max(...c.map(x=>x.h)),bottom=Math.min(...c.map(x=>x.l));return{name:'range',label:'박스/범위 움직임',state:'범위 상·하단 반응 관찰',geometry:{upper:{x1:0,y1:top,x2:1,y2:top},lower:{x1:0,y1:bottom,x2:1,y2:bottom}}}}
function tfSummary(tf,m){if(!m.available)return{tf,role:TF_ROLE[tf],trend:'unknown',summary:'데이터 부족',returnPct:null,volumeAcceleration:null,takerRatio:null};const trendKo=m.trend==='bullish'?'상승 구조':m.trend==='bearish'?'하락 구조':'중립/횡보';const extras=[];if(m.volumeAcceleration>=1.5)extras.push(`거래량 ${m.volumeAcceleration.toFixed(1)}배 확대`);if(m.takerRatio>=1.2)extras.push('매수 체결 우위');if(m.takerRatio!=null&&m.takerRatio<=.83)extras.push('매도 체결 우위');return{tf,role:TF_ROLE[tf],trend:m.trend,summary:`${trendKo}${extras.length?' · '+extras.join(' · '):''}`,returnPct:m.returnPct,volumeAcceleration:m.volumeAcceleration,takerRatio:m.takerRatio}}
function beginnerSummary(tf,conflict,dataWarnings){if(dataWarnings.length)return{headline:'판단 보류',text:'일부 핵심 데이터가 부족하거나 지연되어 방향을 단정하지 않습니다.',decisionState:'DATA_WARNING'};if(conflict)return{headline:'시간봉 신호 충돌',text:'큰 시간봉과 작은 시간봉의 방향이 엇갈립니다. 지금은 한 방향으로 단정하기보다 주요 지지·저항 반응을 확인하는 구간입니다.',decisionState:'NO_SIGNAL'};const dirs=TF_ORDER.map(k=>tf[k]?.trend),bull=dirs.filter(x=>x==='bullish').length,bear=dirs.filter(x=>x==='bearish').length;if(bull>=4)return{headline:'여러 시간봉 상승 구조 정렬',text:'1주봉부터 단기 시간봉까지 상승 구조가 비교적 정렬되어 있습니다. 다만 바로 위 저항과 과도한 거래량 확대 여부를 함께 확인해야 합니다.',decisionState:'OBSERVE'};if(bear>=4)return{headline:'여러 시간봉 하락 구조 정렬',text:'여러 시간봉에서 하락 구조가 겹칩니다. 반전으로 단정하기보다 지지 회복과 구조 전환이 실제로 나타나는지 확인하는 단계입니다.',decisionState:'OBSERVE'};return{headline:'방향성 혼조',text:'시간봉별 방향이 완전히 정렬되지 않았습니다. 핵심 지지·저항과 수급 구간 반응을 우선 확인하세요.',decisionState:'NO_SIGNAL'}}
function analyzeCoinReport({symbol,frames={},derivatives={},errors=[]}={}){const metrics={},tf={};for(const k of TF_ORDER){metrics[k]=metric(frames[k]);tf[k]=tfSummary(k,metrics[k])}const usable=TF_ORDER.filter(k=>metrics[k].available),dataWarnings=[];for(const k of TF_ORDER)if(!metrics[k].available)dataWarnings.push(`${k} 데이터 부족`);for(const e of errors||[])if(e?.interval&&TF_ORDER.includes(e.interval))dataWarnings.push(`${e.interval} 수집 오류`);const bull=usable.filter(k=>metrics[k].trend==='bullish').length,bear=usable.filter(k=>metrics[k].trend==='bearish').length,conflict=bull>=2&&bear>=2;const base=metrics['4h'].available?metrics['4h']:metrics['1h'];const levels=nearestLevels(base),fvg=fvgs(base),liq=liquidity(base),structure=structureBreak(base),pattern=simplePattern(base);const anomalies=[];for(const k of ['4h','1h','15m']){const m=metrics[k];if(m.volumeAcceleration>=1.5)anomalies.push({type:'VOLUME_SPIKE',tf:k,label:`${k} 거래량`,value:`기준 대비 ${m.volumeAcceleration.toFixed(2)}배`});if(m.takerRatio>=1.2)anomalies.push({type:'BUY_FLOW',tf:k,label:`${k} 체결 흐름`,value:`매수/매도 ${m.takerRatio.toFixed(2)}배`});if(m.takerRatio!=null&&m.takerRatio<=.83)anomalies.push({type:'SELL_FLOW',tf:k,label:`${k} 체결 흐름`,value:`매수/매도 ${m.takerRatio.toFixed(2)}배`})}const beginner=beginnerSummary(tf,conflict,dataWarnings);const labels=[];if(levels.support)labels.push({kind:'support',label:'주요 지지',price:levels.support});if(levels.resistance)labels.push({kind:'resistance',label:'주요 저항',price:levels.resistance});if(levels.supportZone)labels.push({kind:'demand',label:'수요 구간',from:levels.supportZone[0],to:levels.supportZone[1]});if(levels.resistanceZone)labels.push({kind:'supply',label:'공급 구간',from:levels.resistanceZone[0],to:levels.resistanceZone[1]});if(pattern.geometry)labels.push({kind:'pattern',label:pattern.label,geometry:pattern.geometry});if(structure.price)labels.push({kind:'structure',label:structure.type,price:structure.price});for(const x of fvg.slice(-2))labels.push({kind:'fvg',label:`${x.type==='bullish'?'상승':'하락'} FVG`,from:x.from,to:x.to});for(const x of liq.slice(0,2))labels.push({kind:'liquidity',label:x.type==='buy_side'?'상단 유동성':'하단 유동성',price:x.price});const snapshotCandles=(base?.candles||[]).slice(-80).map(x=>({t:x.t,o:x.o,h:x.h,l:x.l,c:x.c,v:x.v}));return{status:'ok',symbol:String(symbol||'').toUpperCase(),updatedAt:Date.now(),decisionState:beginner.decisionState,beginnerSummary:beginner,multiTimeframe:tf,conflict:{active:conflict,bullishCount:bull,bearishCount:bear},smartMoney:{structure,orderBlockLike:{demand:levels.supportZone,supply:levels.resistanceZone},fvg,liquidity:liq},pattern,anomalies:anomalies.slice(0,8),levels,derivatives:{oiChangePct:finite(derivatives.oiChangePct),fundingPct:finite(derivatives.fundingPct)},dataWarnings:[...new Set(dataWarnings)].slice(0,8),snapshot:{timeframe:base===metrics['4h']?'4h':'1h',candles:snapshotCandles,overlays:labels.slice(0,8)},calibration:{status:'client-derived',source:'pulse_signal_outcomes_v2'}}}
module.exports={TF_ORDER,TF_ROLE,rows,metric,swings,nearestLevels,fvgs,liquidity,structureBreak,patternLine,simplePattern,analyzeCoinReport};