'use strict';
const BASE='https://api.coingecko.com/api/v3';
const cleanBaseSymbol=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').replace(/(USDT|USDC|FDUSD|BUSD|USD)$/,'');
const num=v=>Number.isFinite(Number(v))?Number(v):null;
function createCoinGeckoProvider({fetchImpl=global.fetch,apiKey=process.env.COINGECKO_API_KEY||''}={}){
  const available=Boolean(apiKey&&fetchImpl);
  async function get(path){if(!available){const e=new Error('CoinGecko unavailable');e.code='CG_UNAVAILABLE';throw e}const r=await fetchImpl(BASE+path,{headers:{accept:'application/json','x-cg-demo-api-key':apiKey}});if(!r.ok){const e=new Error(`CoinGecko HTTP ${r.status}`);e.statusCode=r.status;throw e}return r.json()}
  async function getOverview(){const [g,t,c]=await Promise.all([get('/global'),get('/search/trending'),get('/coins/categories?order=market_cap_desc')]);const d=g?.data||{};return{global:{activeCryptocurrencies:num(d.active_cryptocurrencies),totalMarketCapUsd:num(d.total_market_cap?.usd),totalVolume24hUsd:num(d.total_volume?.usd),btcDominancePct:num(d.market_cap_percentage?.btc)},trending:(t?.coins||[]).slice(0,12).map(x=>({id:x.item?.id||null,symbol:String(x.item?.symbol||'').toUpperCase(),name:x.item?.name||null,rank:num(x.item?.market_cap_rank)})),categories:(c||[]).slice(0,20).map(x=>({id:x.id||null,name:x.name||null,marketCapUsd:num(x.market_cap),marketCapChange24hPct:num(x.market_cap_change_24h),volume24hUsd:num(x.volume_24h)}))}}
  async function resolveId(symbol){const base=cleanBaseSymbol(symbol);if(!base){const e=new Error('invalid symbol');e.statusCode=400;throw e}const q=await get('/search?query='+encodeURIComponent(base));const matches=(q?.coins||[]).filter(x=>String(x.symbol||'').toUpperCase()===base);const list=(matches.length?matches:q?.coins||[]).sort((a,b)=>(num(a.market_cap_rank)??1e9)-(num(b.market_cap_rank)??1e9));if(!list[0]?.id){const e=new Error('CoinGecko asset not found');e.statusCode=404;throw e}return{base,id:list[0].id}}
  async function getAssetBySymbol(symbol){const {base,id}=await resolveId(symbol);const rows=await get('/coins/markets?vs_currency=usd&ids='+encodeURIComponent(id)+'&order=market_cap_desc&per_page=1&page=1&sparkline=false');const x=rows?.[0];if(!x){const e=new Error('CoinGecko market data unavailable');e.statusCode=404;throw e}return{source:'coingecko',id,symbol:base,name:x.name||null,rank:num(x.market_cap_rank),priceUsd:num(x.current_price),marketCapUsd:num(x.market_cap),volume24hUsd:num(x.total_volume),circulatingSupply:num(x.circulating_supply),totalSupply:num(x.total_supply),lastUpdated:x.last_updated||null}}
  const pool=x=>({id:x?.id||null,network:x?.relationships?.network?.data?.id||String(x?.id||'').split('_')[0]||null,dex:x?.relationships?.dex?.data?.id||null,name:x?.attributes?.name||null,address:x?.attributes?.address||null,liquidityUsd:num(x?.attributes?.reserve_in_usd),volume24hUsd:num(x?.attributes?.volume_usd?.h24),createdAt:x?.attributes?.pool_created_at||null});
  async function getDexDiscovery(){const [a,b]=await Promise.allSettled([get('/onchain/networks/trending_pools?include=base_token%2Cquote_token&page=1'),get('/onchain/networks/new_pools?include=base_token%2Cquote_token&page=1')]);const trending=a.status==='fulfilled'?(a.value?.data||[]).map(pool):[],newPools=b.status==='fulfilled'?(b.value?.data||[]).map(pool):[];const warnings=[];if(a.status==='rejected')warnings.push(String(a.reason?.message||a.reason));if(b.status==='rejected')warnings.push(String(b.reason?.message||b.reason));return{source:'geckoterminal',pools:[...trending.map(x=>({...x,kind:'trending'})),...newPools.map(x=>({...x,kind:'new'}))].slice(0,60),warnings}}
  return{available,getOverview,getAssetBySymbol,getDexDiscovery,resolveId};
}
module.exports={BASE,cleanBaseSymbol,createCoinGeckoProvider};
