'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,ChevronRight,Play,RotateCcw,Pause,Layers3,ScanLine,SlidersHorizontal,Braces,Check,AlertTriangle,Loader2,Zap,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Progress} from '@/components/ui/progress';

// Heterogeneous indicator payloads are rendered with explicit null/availability checks.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Any = any;
const TFS=['1w','3d','1d','12h','4h','3h','2h','1h','15m','5m'];
const STATES=['전체','점화전','점화대기','점화초기','리테스트','재축적','이미 진행','과열','제외'];
const STAGE:Record<string,string>={universe:'시장 조회',oi:'OI 선별',prescan:'프리스캔',deep:'정밀검사',done:'완료',sample:'샘플 역추적'};
const num=(v:Any,d=2)=>v==null||!Number.isFinite(v)?'N/A':Number(v).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const signed=(v:Any,d=2)=>v==null?'N/A':`${v>0?'+':''}${num(v,d)}%`;
const time=(v:Any)=>v?new Date(v).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Asia/Seoul'}):'—';
const tone=(status:string)=>status==='점화초기'?'lime':status==='과열'||status==='제외'?'red':status==='리테스트'||status==='재축적'?'blue':'neutral';
function Spark({values=[]}:{values:number[]}){if(values.length<2)return <span className="muted">—</span>;const min=Math.min(...values),max=Math.max(...values);return <svg className="spark" viewBox="0 0 100 30" aria-label="최근 40개 1시간봉 종가"><polyline fill="none" stroke="currentColor" strokeWidth="1.7" points={values.map((v,i)=>`${i/(values.length-1)*100},${27-(v-min)/(max-min||1)*24}`).join(' ')}/></svg>}
async function api(path:string,body?:Any):Promise<Any>{const r=await fetch('/api/v1/'+path,body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d:Any=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
function Metric({label,value,sub}:{label:string,value:Any,sub?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
export default function Home(){const [job,setJob]=useState<Any>(null),[sampleJob,setSampleJob]=useState<Any>(null),[samples,setSamples]=useState<Any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[running,setRunning]=useState(false),[sampleRunning,setSampleRunning]=useState(false),[filter,setFilter]=useState('전체'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Any>(null),[tf,setTf]=useState('1h'),[settings,setSettings]=useState(false),[apiOpen,setApiOpen]=useState(false),[config,setConfig]=useState({maxChange:10,minVolume:10000000,minOi:1,top:30}),[copied,setCopied]=useState(false);const alive=useRef(true),stop=useRef(false),sampleStop=useRef(false);
 useEffect(()=>{alive.current=true;Promise.allSettled([api('results'),api('samples')]).then(([r,s])=>{if(!alive.current)return;if(r.status==='fulfilled'&&r.value.id){setJob(r.value);setConfig(r.value.config);}if(s.status==='fulfilled')setSamples(s.value.samples);if(r.status==='rejected')setError(r.reason.message);});return()=>{alive.current=false;stop.current=true;sampleStop.current=true;};},[]);
 async function drive(j:Any,isSample=false){const stopper=isSample?sampleStop:stop;stopper.current=false;if(isSample)setSampleRunning(true);else setRunning(true);try{while(alive.current&&!stopper.current&&['running','paused'].includes(j.status)){if(j.retryAt>Date.now()){await new Promise(r=>setTimeout(r,1500));continue;}const next=await api(`jobs/${j.id}/step`,{});if(next.busy){await new Promise(r=>setTimeout(r,1000));continue;}j=next;if(isSample)setSampleJob(j);else setJob(j);if(j.status==='failed')setError(j.errors.at(-1)?.message||'검색 실패');}if(isSample)setSamples((await api('samples')).samples);}catch(e){setError(e instanceof Error?e.message:'연결 오류');}finally{if(isSample)setSampleRunning(false);else setRunning(false);}}
 async function start(isSample=false){setError('');setLoading(true);try{const j=await api(isSample?'samples/collect':'scans',config);if(isSample)setSampleJob(j);else setJob(j);void drive(j,isSample);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 const candidates:Any[]=job?.candidates||[],visible=candidates.filter(r=>(filter==='전체'||r.status===filter)&&r.symbol.toLowerCase().includes(query.toLowerCase()));const active=job&&['running','paused'].includes(job.status);const counts=job?.counts||{};const progress=!job?0:job.status==='complete'?100:job.stage==='universe'?3:job.stage==='oi'?10+(job.cursor/Math.max(1,counts.filtered))*20:job.stage==='prescan'?30+(job.cursor/Math.max(1,counts.oi))*20:50+(counts.deep/Math.max(1,counts.candidates))*50;
 const applied=job?.config||config;
 const frame=(candidates.find(r=>r.symbol===selected?.symbol)||selected)?.frames?.[tf];
 return <main>
 <header className="topbar"><div className="brand"><span className="brand-icon"><Zap size={20} fill="currentColor"/></span><span>IGNITION<span className="brand-suffix"> / SCANNER</span></span></div><div className="header-right"><span className="exchange"><span className="diamond"/> BINANCE <span className="muted">USDT PERP</span></span><Button variant="ghost" size="icon" aria-label="결과 API 안내" onClick={()=>setApiOpen(true)}><Braces size={19}/></Button></div></header>
 <div className="workspace">
 <section className="heading"><div><div className="eyebrow">FIND THE MOVE. BEFORE THE MOVE.</div><h1>시장이 움직이기 전에<span>.</span></h1><p>전체 선물 시장에서 점화 전 후보를 빠르게 압축합니다.</p></div><div className="heading-controls"><Button variant="outline" className="settings-btn" onClick={()=>setSettings(true)}><SlidersHorizontal size={16}/> 검색 조건</Button><Button className="scan-btn" disabled={loading||sampleRunning} onClick={()=>running?(stop.current=true):active?void drive(job):void start()}>{running?<Pause size={17}/>:active?<Play size={17}/>:<ScanLine size={17}/>} {running?'일시정지':active?'검색 이어서':'전체 시장 검색'}{!running&&<ArrowRight size={17}/>}</Button></div></section>
 {job?.freshnessMs>300000&&<div className="stale-note">검색 기준 시각에서 {Math.floor(job.freshnessMs/60000)}분 지난 결과입니다. 모든 TF는 동일 검색 시점을 기준으로 계산합니다.</div>}
 {error&&<div role="alert" className="error-box"><AlertTriangle size={18}/><span>{error}</span><button aria-label="알림 닫기" onClick={()=>setError('')}><X size={16}/></button></div>}
 <section className="pipeline" aria-label="검색 진행 상황"><div className="pipeline-top"><span className="section-kicker">SCAN PIPELINE</span><span className="pipeline-status">{running?<Loader2 size={13} className="spin"/>:job?.status==='complete'?<Check size={13}/>:<span className="status-dot"/>}{job?job.status==='complete'?(job.partialData?'부분 완료 · 누락 확인':'검색 완료'):job.status==='failed'?'연결 확인 필요':job.status==='paused'?'요청 제한 · 대기 중':running?STAGE[job.stage]:'중지됨 · 이어서 가능':'검색 준비'}<span className="divider">/</span>기준 {time(job?.asOf)} KST</span></div><div className="stages">{[['01','전체 시장',counts.universe,'universe'],['02','가격 · 거래대금',counts.filtered,'oi'],['03','OI 선행 증가',counts.oi,'prescan'],['04','후보 압축',counts.candidates,'deep'],['05','10TF 정밀검사',counts.deep,'done']].map(([n,label,count,stage],i)=><div key={String(n)} className={`stage ${job?.stage===stage?'current':''}`}><span className="stage-no">{n}</span><div><p>{label}</p><strong>{count==null?'—':Number(count).toLocaleString()}<small>종목</small></strong></div>{i<4&&<ChevronRight className="stage-arrow" size={16}/>}</div>)}</div><Progress value={progress} className="pipeline-progress"/></section>
 <div className="filter-summary"><span><span className="tiny-square"/>확정봉 기준</span><span>24H ±{applied.maxChange}%</span><span>거래대금 ≥ ${num(applied.minVolume/1000000,0)}M</span><span>4H OI &gt; +{applied.minOi}%</span><span>최대 {applied.top}개 정밀검사</span><span className="filter-note">{job?.metrics?`API ${job.metrics.requests}회 · 캐시 ${job.metrics.hits}회`:'후보부터 표시 · 결과 순차 반영'}</span></div>
 <Tabs defaultValue="scan" className="main-tabs"><div className="tabbar"><TabsList><TabsTrigger value="scan"><ScanLine size={16}/> 검색 결과 <span className="count-chip">{candidates.length}</span></TabsTrigger><TabsTrigger value="samples"><Layers3 size={16}/> Sample Engine <span className="count-chip">{samples.length}</span></TabsTrigger></TabsList><span className="tab-note">{job?.finishedAt?`완료 ${time(job.finishedAt)}`:'BINANCE ORIGINAL DATA'}</span></div>
 <TabsContent value="scan"><div className="results-toolbar"><div className="state-filters">{STATES.map(s=><button key={s} className={filter===s?'active':''} onClick={()=>setFilter(s)}>{s}{s==='점화초기'&&<span className="filter-dot"/>}</button>)}</div><Input className="symbol-search" placeholder="종목 검색" aria-label="종목 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <div className="results-table"><Table><TableHeader><TableRow><TableHead className="rank-head">#</TableHead><TableHead>종목 / 1H 흐름</TableHead><TableHead>상태</TableHead><TableHead className="numeric">24H 변화</TableHead><TableHead className="numeric">OI 4H</TableHead><TableHead className="numeric">RVOL 1H</TableHead><TableHead className="numeric">RSI 1H</TableHead><TableHead className="numeric">합치도</TableHead><TableHead className="numeric">샘플 유사도</TableHead><TableHead/></TableRow></TableHeader><TableBody>{visible.map((r,i)=><TableRow key={r.symbol} onClick={()=>{setSelected(r);setTf('1h');}} className="candidate-row"><TableCell className="row-rank">{String(i+1).padStart(2,'0')}</TableCell><TableCell><div className="symbol-cell"><div><button className="symbol-button" onClick={()=>setSelected(r)}>{r.symbol.replace(/USDT$/,'')}<ArrowUpRight size={12}/></button><small>{num(r.price,r.price<1?6:3)} USDT</small></div><Spark values={r.frames?.['1h']?.sparkline}/></div></TableCell><TableCell><span className={`badge ${tone(r.status)}`}>{r.status}</span><small className="detail-state">{r.detailComplete?`${r.coverage}/10 TF 확인`:'정밀검사 대기'}</small></TableCell><TableCell className={`numeric ${r.change>=0?'positive':'negative'}`}>{signed(r.change)}</TableCell><TableCell className="numeric positive">{signed(r.oi?.change4h)}</TableCell><TableCell className="numeric">{num(r.frames?.['1h']?.rvol)}<span className="muted">×</span></TableCell><TableCell className="numeric">{num(r.frames?.['1h']?.rsi,1)}</TableCell><TableCell className="numeric"><span className="score">{r.score}</span><span className="muted"> /100</span></TableCell><TableCell className="numeric">{r.matches?.length?`${r.matches[0].score}%`:'—'}</TableCell><TableCell><ChevronRight size={16} className="muted"/></TableCell></TableRow>)}</TableBody></Table>
 {visible.length===0&&<div className="empty-state"><div className="empty-icon"><ScanLine size={28}/></div><h2>{running?'시장 전체를 좁혀가는 중입니다':candidates.length?'조건에 맞는 결과가 없습니다':job?.status==='complete'?'이번 조건을 통과한 후보가 없습니다':'다음 움직임을 찾아보세요'}</h2><p>{running?'OI 선별과 1H·4H 프리스캔 후 후보가 표시됩니다.':candidates.length?'상태 필터 또는 검색어를 바꿔보세요.':'전체 시장을 검색하면 아직 덜 오른 후보부터 확인할 수 있습니다.'}</p>{!running&&!candidates.length&&<Button variant="outline" disabled={sampleRunning||loading} onClick={()=>active?void drive(job):void start()}><Play size={14}/>{active?'검색 이어서':'첫 검색 시작'}</Button>}<div className="empty-tfs"><span>정밀 분석</span><b>1W</b><i>→</i><b>1D</b><i>→</i><b>4H</b><i>→</i><b>1H</b><i>→</i><b>5m</b><span>총 10 TF</span></div></div>}
 </div><div className="table-footer"><span>{visible.length}개 표시 · 합치도 높은 순</span><span>합치도·샘플 유사도는 상승 확률이 아닙니다.</span></div>
 {job?.errors?.length>0&&<details className="error-details"><summary>데이터 누락 및 연결 오류 {job.errors.length}건</summary>{job.errors.map((e:Any,i:number)=><p key={i}>{e.symbol} {e.stage} — {e.message}</p>)}</details>}
 </TabsContent>
 <TabsContent value="samples"><section className="sample-intro"><div><span className="section-kicker">BEFORE THE BREAKOUT</span><h2>급등 이후, 직전의 흔적을 찾습니다.</h2><p>최근 +10% 이상 상승한 종목의 돌파 직전 1H 데이터를 저장하고, 새 후보와 자동 대조합니다.</p><small>특징은 돌파 전 확정봉만 사용 · 이후 6시간 수익률은 결과 라벨로 분리</small></div><Button className="scan-btn" disabled={running||loading||sampleRunning} onClick={()=>void start(true)}>{sampleRunning?<Loader2 size={16} className="spin"/>:<RotateCcw size={16}/>} {sampleRunning?`역추적 ${sampleJob?.cursor||0}/${sampleJob?.counts?.filtered||0}`:'급등 샘플 수집'}</Button></section>
 {sampleJob&&<p className="muted sample-status">{STAGE[sampleJob.stage]} · 이번 작업 {sampleJob.samplesAdded}개 추출 {sampleJob.status==='failed'?'· 수집 실패':''}</p>}
 <div className="sample-grid">{samples.map(s=><article key={s.id} className="sample-card"><div><strong>{s.symbol.replace('USDT','')}</strong><span className="badge blue">직전 샘플</span></div><small>{new Date(s.cutoff).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} KST</small><Spark values={s.frame?.sparkline}/><div className="sample-metrics"><span>직전 RSI <b>{num(s.frame?.rsi,1)}</b></span><span>직전 RVOL <b>{num(s.frame?.rvol)}×</b></span><span>6H 최대상승 <b className="positive">{signed(s.outcome?.maxGain)}</b></span><span>6H 최대하락 <b>{signed(s.outcome?.maxDrawdown)}</b></span></div></article>)}</div>{!samples.length&&<div className="empty-state"><Layers3 size={30}/><h2>저장된 급등 전 샘플이 없습니다</h2><p>샘플 수집을 실행하면 조건을 충족한 실제 시장 데이터만 저장합니다.</p></div>}
 </TabsContent></Tabs>
 <footer><span><Zap size={12}/> IGNITION <span className="muted">독립 선물 검색기</span></span><span>RSI · OI · STRUCTURE · SAMPLE MATCHING</span><button onClick={()=>setApiOpen(true)}>결과 API <ArrowUpRight size={13}/></button></footer>
 </div>
 <Sheet open={settings} onOpenChange={setSettings}><SheetContent className="drawer"><SheetHeader><SheetTitle>검색 조건</SheetTitle><SheetDescription>조건은 다음 새 검색에 적용됩니다.</SheetDescription></SheetHeader><div className="drawer-body">{[['maxChange','24H 변동 절댓값 상한 (%)',1,20],['minVolume','24H 최소 거래대금 (USDT)',1000000,1000000000],['minOi','4H OI 증가 하한 (%)',0,10],['top','정밀검사 후보 수',20,40]].map(([key,label,min,max])=><label className="field" key={key}>{label}<Input type="number" min={min} max={max} value={config[key as keyof typeof config]} onChange={e=>setConfig({...config,[key]:Number(e.target.value)})}/></label>)}<p className="muted">기본값: ±10% / $10M / OI +1% / 30개. 현재 작업은 생성 시점 조건을 유지합니다.</p><Button className="scan-btn" onClick={()=>setSettings(false)}>적용</Button></div></SheetContent></Sheet>
 <Sheet open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><SheetContent className="drawer detail-drawer"><SheetHeader><SheetTitle>{selected?.symbol} <span className={`badge ${tone(selected?.status)}`}>{selected?.status}</span></SheetTitle><SheetDescription>{selected?.reasons?.join(' · ')} · 검색 시점 {time(selected?.asOf)}</SheetDescription></SheetHeader><div className="drawer-body"><div className="tf-selector">{TFS.map(t=><button className={tf===t?'active':''} key={t} onClick={()=>setTf(t)}>{t.toUpperCase()}</button>)}</div>{!frame?.available?<p className="empty-frame">{frame?.reason||'이 타임프레임은 정밀검사 대기 중입니다.'}</p>:<><Spark values={frame.sparkline}/><div className="metrics-grid"><Metric label="RSI 14" value={num(frame.rsi,1)}/><Metric label="RVOL" value={num(frame.rvol)+'×'}/><Metric label="MACD / Signal" value={num(frame.macd?.value,5)} sub={num(frame.macd?.signal,5)}/><Metric label="Stoch RSI K / D" value={num(frame.stochRsi?.k,1)+' / '+num(frame.stochRsi?.d,1)}/><Metric label="KDJ K / D / J" value={[frame.kdj?.k,frame.kdj?.d,frame.kdj?.j].map(x=>num(x,1)).join(' / ')}/><Metric label="OBV" value={num(frame.obv,0)} sub={frame.obvRising?'최근 5봉 상승':'최근 5봉 비상승'}/><Metric label="압축 / 이격 (ATR)" value={num(frame.compression)+' / '+num(frame.extensionAtr)}/><Metric label="봉 수 / EMA448" value={frame.bars} sub={frame.ema448Warmup}/></div><h3>이동평균</h3><div className="ma-grid">{Object.entries(frame.sma||{}).map(([p,v])=><span key={'s'+p}>SMA {p}<b>{num(v,5)}</b></span>)}{Object.entries(frame.ema||{}).map(([p,v])=><span key={'e'+p}>EMA {p}<b>{num(v,5)}</b></span>)}</div><h3>시장 구조</h3><div className="structure-grid">{[['압축→점화',frame.ignitionStructure?.trigger?'점화 확인':frame.ignitionStructure?.wasCompressed?'직전 압축':'미확인'],['BOS',frame.structure?.bos],['CHoCH',frame.structure?.choch],['MSS',frame.structure?.mss],['BSL',frame.structure?.bsl],['SSL',frame.structure?.ssl],['유동성 스윕',frame.structure?.sweep],['밥그릇',frame.structure?.bowl?.stage],['추세선',frame.structure?.trendline?.retest?'리테스트':frame.structure?.trendline?.breakout?'돌파':frame.structure?.trendline?.above?'상단 유지':null]].map(([l,v])=><div key={l}><span>{l}</span><b>{v??'미확인'}</b></div>)}</div><p className="small-note">구조·밥그릇은 명시적 규칙 기반 탐지입니다. 확정 피벗 이후에만 판정합니다.</p><h3>FVG / OB</h3>{frame.structure?.fvg?.length?frame.structure.fvg.map((f:Any,i:number)=><p className="data-line" key={i}>{f.side==='bull'?'상승':'하락'} FVG <b>{num(f.low,6)} — {num(f.high,6)}</b></p>):<p className="muted">활성 FVG 없음</p>}<p className="data-line">OB <b>{frame.structure?.ob?`${frame.structure.ob.side} ${num(frame.structure.ob.low,6)} — ${num(frame.structure.ob.high,6)}`:'현재 돌파봉에서 미확인'}</b></p><h3>다이버전스</h3><div className="divergences">{Object.entries(frame.divergence||{}).map(([k,v])=><span key={k} className={v?'positive':'muted'}>{k.replace('Bull',' 상승').replace('Bear',' 하락').toUpperCase()}: {v==null?'N/A':v?'탐지':'없음'}</span>)}</div></>}
 <h3>파생 · 현물 교차검증</h3><div className="metrics-grid"><Metric label="OI 4H / 8H" value={signed(selected?.oi?.change4h)+' / '+signed(selected?.oi?.change8h)}/><Metric label="Taker 1H / 캔들" value={num(selected?.taker?.ratio)+' / '+num(selected?.taker?.klineRatio)} sub={selected?.taker?.aligned?'동일 구간 교차검증':'구간 일치 미확인'}/><Metric label="최근 확정 Funding" value={selected?.funding?num(selected.funding.rate*100,4)+'%':'N/A'}/><Metric label="현물 대비 선물 가격차" value={signed(selected?.spot?.basisPct)}/><Metric label="1H 선물 / 현물 거래대금" value={selected?.spot?.available?`${num(selected.spot.futuresQuoteVolume1h/1000000)}M / ${num(selected.spot.quoteVolume1h/1000000)}M`:'N/A'}/><Metric label="현물 RSI / RVOL" value={`${num(selected?.spot?.rsi,1)} / ${num(selected?.spot?.rvol)}×`}/></div>{selected?.spot?.reason&&<p className="muted">{selected.spot.reason}</p>}
 <h3>급등 전 샘플 매칭</h3>{selected?.matches?.length?selected.matches.map((m:Any)=><div className="match" key={m.id}><strong>{m.symbol}</strong><span>{m.score}% 유사 · {m.dimensions}개 특성 비교</span></div>):<p className="muted">비교 가능한 과거 샘플 없음</p>}{selected?.errors?.map((e:string)=><p key={e} className="negative">{e}</p>)}</div></SheetContent></Sheet>
 <Sheet open={apiOpen} onOpenChange={setApiOpen}><SheetContent className="drawer"><SheetHeader><SheetTitle>Pulse Radar 결과 API</SheetTitle><SheetDescription>검색기와 별개로 결과를 읽을 수 있는 버전 API입니다.</SheetDescription></SheetHeader><div className="drawer-body"><code className="api-code">GET /api/v1/results</code><p>최신 검색의 후보, 10TF 지표, 상태 근거, 샘플 매칭, 누락 정보 및 기준 시각을 반환합니다.</p><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/api/v1/results');setCopied(true);}catch{setError('주소 복사 권한을 확인하세요.');}}}>{copied?<Check size={16}/>:<Braces size={16}/>} {copied?'주소 복사됨':'전체 API 주소 복사'}</Button><h3>작업 API</h3><pre className="api-code">{'POST /api/v1/scans\nPOST /api/v1/jobs/:id/step\nGET  /api/v1/jobs/:id\nGET  /api/v1/samples\nPOST /api/v1/samples/collect'}</pre><p className="muted">검색 중에는 페이지가 작업 배치를 이어서 실행합니다. 창을 닫으면 현재 배치 후 멈추며, 다시 열어 이어갈 수 있습니다. 외부 연동 시에는 사이트 접근 인증이 필요합니다.</p></div></SheetContent></Sheet>
 </main>;
}
