'use strict';
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v))}
function createMemoryStore(){
  const snapshots=new Map(),outcomes=new Map(),checkpoints=new Map(),alerts=new Map(),evidence=new Map(),health=new Map(),states=new Map(),transitionSnapshots=new Map(),marketValidationSnapshots=new Map(),marketValidationRaw=new Map(),marketValidationNormalized=new Map(),marketValidationOutcomes=new Map(),marketValidationStats=new Map(),recommendations=new Map(),recommendationOutcomes=new Map(),recommendationStats=new Map(),preIgnitionSnapshots=new Map(),preIgnitionOutcomes=new Map(),selectorSnapshots=new Map(),selectorRaw=new Map(),selectorTransitions=new Map(),selectorOutcomes=new Map(),selectorStats=new Map(),selectorEvidence=new Map();
  return{
    async putSnapshot(snapshot){if(!snapshot?.id)throw new Error('snapshot id required');if(snapshots.has(snapshot.id))return false;snapshots.set(snapshot.id,clone(snapshot));return true},
    async getSnapshot(id){return clone(snapshots.get(String(id))??null)},
    async putOutcome(id,outcome){if(!id)throw new Error('outcome id required');outcomes.set(String(id),clone(outcome));return true},
    async getOutcome(id){return clone(outcomes.get(String(id))??null)},
    async listSnapshots(){return [...snapshots.values()].map(clone)},
    async listOutcomes(){return [...outcomes.values()].map(clone)},
    async putCheckpoint(id,value){if(!id)throw new Error('checkpoint id required');checkpoints.set(String(id),clone(value));return true},
    async getCheckpoint(id){return clone(checkpoints.get(String(id))??null)},
    async putAlert(id,value){if(!id)throw new Error('alert id required');if(alerts.has(String(id)))return false;alerts.set(String(id),clone(value));return true},
    async listAlerts(){return [...alerts.values()].map(clone)},
    async putEvidence(id,value){if(!id)throw new Error('evidence id required');evidence.set(String(id),clone(value));return true},
    async listEvidence(){return [...evidence.values()].map(clone)},
    async putHealth(id,value){if(!id)throw new Error('health id required');health.set(String(id),clone(value));return true},
    async getHealth(id){return clone(health.get(String(id))??null)},
    async putState(id,value){if(!id)throw new Error('state id required');states.set(String(id),clone(value));return true},
    async getState(id){return clone(states.get(String(id))??null)},
    async putTransitionSnapshot(id,value){if(!id)throw new Error('transition snapshot id required');if(transitionSnapshots.has(String(id)))return false;transitionSnapshots.set(String(id),clone(value));return true},
    async getTransitionSnapshot(id){return clone(transitionSnapshots.get(String(id))??null)},
    async listTransitionSnapshots(){return [...transitionSnapshots.values()].map(clone)},
    async putMarketValidationSnapshot(id,value){if(!id)throw new Error('market validation snapshot id required');if(marketValidationSnapshots.has(String(id)))return false;marketValidationSnapshots.set(String(id),clone(value));return true},
    async getMarketValidationSnapshot(id){return clone(marketValidationSnapshots.get(String(id))??null)},
    async listMarketValidationSnapshots(){return [...marketValidationSnapshots.values()].map(clone)},
    async putMarketValidationRaw(id,value){if(!id)throw new Error('market validation raw id required');if(marketValidationRaw.has(String(id)))return false;marketValidationRaw.set(String(id),clone(value));return true},
    async getMarketValidationRaw(id){return clone(marketValidationRaw.get(String(id))??null)},
    async putMarketValidationNormalized(id,value){if(!id)throw new Error('market validation normalized id required');if(marketValidationNormalized.has(String(id)))return false;marketValidationNormalized.set(String(id),clone(value));return true},
    async getMarketValidationNormalized(id){return clone(marketValidationNormalized.get(String(id))??null)},
    async putMarketValidationOutcome(id,value){if(!id)throw new Error('market validation outcome id required');marketValidationOutcomes.set(String(id),clone(value));return true},
    async getMarketValidationOutcome(id){return clone(marketValidationOutcomes.get(String(id))??null)},
    async listMarketValidationOutcomes(){return [...marketValidationOutcomes.values()].map(clone)},
    async putMarketValidationStats(id,value){if(!id)throw new Error('market validation stats id required');marketValidationStats.set(String(id),clone(value));return true},
    async getMarketValidationStats(id){return clone(marketValidationStats.get(String(id))??null)},
    async putRecommendation(id,value){if(!id)throw new Error('recommendation id required');if(recommendations.has(String(id)))return false;recommendations.set(String(id),clone(value));return true},
    async listRecommendations(){return [...recommendations.values()].map(clone)},
    async putRecommendationOutcome(id,value){if(!id)throw new Error('recommendation outcome id required');recommendationOutcomes.set(String(id),clone(value));return true},
    async getRecommendationOutcome(id){return clone(recommendationOutcomes.get(String(id))??null)},
    async listRecommendationOutcomes(){return [...recommendationOutcomes.values()].map(clone)},
    async putRecommendationStats(id,value){if(!id)throw new Error('recommendation stats id required');recommendationStats.set(String(id),clone(value));return true},
    async getRecommendationStats(id){return clone(recommendationStats.get(String(id))??null)},
    async putPreIgnitionSnapshot(id,value){if(!id)throw new Error('pre-ignition snapshot id required');if(preIgnitionSnapshots.has(String(id)))return false;preIgnitionSnapshots.set(String(id),clone(value));return true},
    async getPreIgnitionSnapshot(id){return clone(preIgnitionSnapshots.get(String(id))??null)},
    async listPreIgnitionSnapshots(){return [...preIgnitionSnapshots.values()].map(clone)},
    async putPreIgnitionOutcome(id,value){if(!id)throw new Error('pre-ignition outcome id required');preIgnitionOutcomes.set(String(id),clone(value));return true},
    async getPreIgnitionOutcome(id){return clone(preIgnitionOutcomes.get(String(id))??null)},
    async listPreIgnitionOutcomes(){return [...preIgnitionOutcomes.values()].map(clone)},
    async putSelectorSnapshot(id,value){if(!id)throw new Error('selector snapshot id required');if(selectorSnapshots.has(String(id)))return false;selectorSnapshots.set(String(id),clone(value));return true},
    async getSelectorSnapshot(id){return clone(selectorSnapshots.get(String(id))??null)},
    async listSelectorSnapshots(){return [...selectorSnapshots.values()].map(clone)},
    async putSelectorRaw(id,value){if(!id)throw new Error('selector raw id required');if(selectorRaw.has(String(id)))return false;selectorRaw.set(String(id),clone(value));return true},
    async getSelectorRaw(id){return clone(selectorRaw.get(String(id))??null)},
    async putSelectorTransition(id,value){if(!id)throw new Error('selector transition id required');if(selectorTransitions.has(String(id)))return false;selectorTransitions.set(String(id),clone(value));return true},
    async listSelectorTransitions(){return [...selectorTransitions.values()].map(clone)},
    async putSelectorOutcome(id,value){if(!id)throw new Error('selector outcome id required');selectorOutcomes.set(String(id),clone(value));return true},
    async getSelectorOutcome(id){return clone(selectorOutcomes.get(String(id))??null)},
    async listSelectorOutcomes(){return [...selectorOutcomes.values()].map(clone)},
    async putSelectorStats(id,value){if(!id)throw new Error('selector stats id required');selectorStats.set(String(id),clone(value));return true},
    async getSelectorStats(id){return clone(selectorStats.get(String(id))??null)},
    async putSelectorEvidence(id,value){if(!id)throw new Error('selector evidence id required');if(selectorEvidence.has(String(id)))return false;selectorEvidence.set(String(id),clone(value));return true},
    async getSelectorEvidence(id){return clone(selectorEvidence.get(String(id))??null)},
    async listSelectorEvidence(){return [...selectorEvidence.values()].map(clone)}
  };
}
function createBlobStore({getStore}={}){
  if(typeof getStore!=='function')throw new Error('Netlify Blobs getStore adapter required');
  const store=()=>getStore('pulse-signal-performance');
  const key=(prefix,id)=>`${prefix}/${String(id)}.json`;
  const snapKey=id=>key('signal-snapshots',id),outKey=id=>key('signal-outcomes',id);
  async function read(k){const v=await store().get(k,{type:'json'});if(v==null)return null;if(typeof v==='string'){try{return JSON.parse(v)}catch{return null}}return clone(v)}
  async function write(k,value){const s=store();if(typeof s.setJSON==='function')return s.setJSON(k,clone(value));return s.set(k,JSON.stringify(value),{contentType:'application/json'})}
  async function listPrefix(prefix){const s=store();const out=[];let cursor;do{const page=await s.list({prefix,cursor});for(const b of page?.blobs||[]){if(!String(b?.key||'').startsWith(prefix))continue;const v=await read(b.key);if(v!=null)out.push(v)}cursor=page?.next_cursor||page?.cursor||null}while(cursor);return out}
  return{
    async putSnapshot(snapshot){if(!snapshot?.id)throw new Error('snapshot id required');const k=snapKey(snapshot.id);if(await read(k))return false;await write(k,snapshot);return true},
    async getSnapshot(id){return read(snapKey(id))},
    async putOutcome(id,outcome){if(!id)throw new Error('outcome id required');await write(outKey(id),outcome);return true},
    async getOutcome(id){return read(outKey(id))},
    async listSnapshots(){return listPrefix('signal-snapshots/')},
    async listOutcomes(){return listPrefix('signal-outcomes/')},
    async putCheckpoint(id,value){if(!id)throw new Error('checkpoint id required');await write(key('signal-checkpoints',id),value);return true},
    async getCheckpoint(id){return read(key('signal-checkpoints',id))},
    async putAlert(id,value){if(!id)throw new Error('alert id required');const k=key('signal-alerts',id);if(await read(k))return false;await write(k,value);return true},
    async listAlerts(){return listPrefix('signal-alerts/')},
    async putEvidence(id,value){if(!id)throw new Error('evidence id required');await write(key('signal-evidence',id),value);return true},
    async listEvidence(){return listPrefix('signal-evidence/')},
    async putHealth(id,value){if(!id)throw new Error('health id required');await write(key('signal-health',id),value);return true},
    async getHealth(id){return read(key('signal-health',id))},
    async putState(id,value){if(!id)throw new Error('state id required');await write(key('signal-states',id),value);return true},
    async getState(id){return read(key('signal-states',id))},
    async putTransitionSnapshot(id,value){if(!id)throw new Error('transition snapshot id required');const k=key('transition-snapshots',id);if(await read(k))return false;await write(k,value);return true},
    async getTransitionSnapshot(id){return read(key('transition-snapshots',id))},
    async listTransitionSnapshots(){return listPrefix('transition-snapshots/')},
    async putMarketValidationSnapshot(id,value){if(!id)throw new Error('market validation snapshot id required');const k=key('market-validation-snapshots',id);if(await read(k))return false;await write(k,value);return true},
    async getMarketValidationSnapshot(id){return read(key('market-validation-snapshots',id))},
    async listMarketValidationSnapshots(){return listPrefix('market-validation-snapshots/')},
    async putMarketValidationRaw(id,value){if(!id)throw new Error('market validation raw id required');const k=key('market-validation-raw',id);if(await read(k))return false;await write(k,value);return true},
    async getMarketValidationRaw(id){return read(key('market-validation-raw',id))},
    async putMarketValidationNormalized(id,value){if(!id)throw new Error('market validation normalized id required');const k=key('market-validation-normalized',id);if(await read(k))return false;await write(k,value);return true},
    async getMarketValidationNormalized(id){return read(key('market-validation-normalized',id))},
    async putMarketValidationOutcome(id,value){if(!id)throw new Error('market validation outcome id required');await write(key('market-validation-outcomes',id),value);return true},
    async getMarketValidationOutcome(id){return read(key('market-validation-outcomes',id))},
    async listMarketValidationOutcomes(){return listPrefix('market-validation-outcomes/')},
    async putMarketValidationStats(id,value){if(!id)throw new Error('market validation stats id required');await write(key('market-validation-stats',id),value);return true},
    async getMarketValidationStats(id){return read(key('market-validation-stats',id))},
    async putRecommendation(id,value){if(!id)throw new Error('recommendation id required');const k=key('auto-recommendations',id);if(await read(k))return false;await write(k,value);return true},
    async listRecommendations(){return listPrefix('auto-recommendations/')},
    async putRecommendationOutcome(id,value){if(!id)throw new Error('recommendation outcome id required');await write(key('auto-recommendation-outcomes',id),value);return true},
    async getRecommendationOutcome(id){return read(key('auto-recommendation-outcomes',id))},
    async listRecommendationOutcomes(){return listPrefix('auto-recommendation-outcomes/')},
    async putRecommendationStats(id,value){if(!id)throw new Error('recommendation stats id required');await write(key('auto-recommendation-stats',id),value);return true},
    async getRecommendationStats(id){return read(key('auto-recommendation-stats',id))},
    async putPreIgnitionSnapshot(id,value){if(!id)throw new Error('pre-ignition snapshot id required');return immutable('preignition-oos-snapshots',id,value)},
    async getPreIgnitionSnapshot(id){return read(key('preignition-oos-snapshots',id))},
    async listPreIgnitionSnapshots(){return listPrefix('preignition-oos-snapshots/')},
    async putPreIgnitionOutcome(id,value){if(!id)throw new Error('pre-ignition outcome id required');await write(key('preignition-oos-outcomes',id),value);return true},
    async getPreIgnitionOutcome(id){return read(key('preignition-oos-outcomes',id))},
    async listPreIgnitionOutcomes(){return listPrefix('preignition-oos-outcomes/')},
    async putSelectorSnapshot(id,value){if(!id)throw new Error('selector snapshot id required');return immutable('selector-snapshots',id,value)},
    async getSelectorSnapshot(id){return read(key('selector-snapshots',id))},
    async listSelectorSnapshots(){return listPrefix('selector-snapshots/')},
    async putSelectorRaw(id,value){if(!id)throw new Error('selector raw id required');return immutable('selector-raw',id,value)},
    async getSelectorRaw(id){return read(key('selector-raw',id))},
    async putSelectorTransition(id,value){if(!id)throw new Error('selector transition id required');return immutable('selector-transitions',id,value)},
    async listSelectorTransitions(){return listPrefix('selector-transitions/')},
    async putSelectorOutcome(id,value){if(!id)throw new Error('selector outcome id required');await write(key('selector-outcomes',id),value);return true},
    async getSelectorOutcome(id){return read(key('selector-outcomes',id))},
    async listSelectorOutcomes(){return listPrefix('selector-outcomes/')},
    async putSelectorStats(id,value){if(!id)throw new Error('selector stats id required');await write(key('selector-stats',id),value);return true},
    async getSelectorStats(id){return read(key('selector-stats',id))},
    async putSelectorEvidence(id,value){if(!id)throw new Error('selector evidence id required');return immutable('selector-evidence',id,value)},
    async getSelectorEvidence(id){return read(key('selector-evidence',id))},
    async listSelectorEvidence(){return listPrefix('selector-evidence/')}
  };
}
module.exports={createMemoryStore,createBlobStore};
