(function(root,factory){const deps=typeof module==='object'&&module.exports?{D:require('./data'),I:require('./indicators'),M:require('./models')}:{D:root.ChartBroData,I:root.ChartBroIndicators,M:root.ChartBroModels};const api=factory(deps);if(typeof module==='object'&&module.exports)module.exports=api;else root.ChartBroEngine=api;})(globalThis,function(deps){'use strict';const {D,I,M}=deps;
const VERSION='chartbro-research-1.0.0';
const DEFAULTS={k:3,tick:.01,body_atr:1.2,body_ratio:.65,close_location:.8,cluster_atr:.1,zone_expiry:180,setup_expiry:24,ob_lookback:8,tf:'4h',venue:'binance',market:'perpetual',symbol:'BTCUSDT'};
const round=n=>Math.round(n*1e10)/1e10;
function analyze(rows,options={}){
 const cfg={...DEFAULTS,...options};if(!Number.isInteger(cfg.k)||cfg.k<1||cfg.k>20||!(cfg.tick>0))throw new Error('invalid engine config');
 const {bars,quality}=D.normalize(rows,{tf:cfg.tf,at:cfg.at??Infinity,availability:cfg.availability||'bar_close'}),gaps=new Set(quality.gaps.map(g=>g.index));
 const features=[];let seg=0;for(let end=1;end<=bars.length;end++){if(end===bars.length||gaps.has(end)){features.push(...I.features(bars.slice(seg,end)));seg=end;}}
 const events=[],pivots=[],levels=[],zones=[],ranges=[],setups=[],snapshots=[],broken=new Set(),pairs=new Set(),reversals=new Set();let trend='INSUFFICIENT_STRUCTURE',lastRange=null,currentSegment=0,lastDisplacement={long:null,short:null},lastSweep={long:null,short:null};
 const identity={venue:cfg.venue,market:cfg.market,symbol:cfg.symbol,timeframe:cfg.tf};
 function id(type,time,ref=''){return [cfg.venue,cfg.market,cfg.symbol,cfg.tf,type,time,ref].join(':');}
 function emit(type,b,object={},extra={}){const e={id:id(type,b.close_time,object.id||extra.reference_id||events.length),type,event_at:b.close_time,known_at:b.close_time,object_id:object.id??null,...extra};events.push(D.copy(e));return e;}
 function addZone(kind,side,lower,upper,b,index,extra={}){if(!(upper>lower))return null;const z={id:id(kind,b.close_time,extra.reference_id||zones.length),kind,side,lower:round(lower),upper:round(upper),mid:round((lower+upper)/2),event_at:b.close_time,known_at:b.close_time,created_index:index,state:'FRESH',fill_state:'FRESH',validity:'VALID',touches:0,penetration:0,expires_index:index+cfg.zone_expiry,...extra};zones.push(z);emit('ZONE_CREATED',b,z,{kind,side,lower:z.lower,upper:z.upper,rule_origin:'independent_research'});return z;}
 function addLevel(kind,price,p,b,index,extra={}){const tol=Math.max(cfg.tick*2,(features[Math.max(0,index-1)]?.atr||0)*cfg.cluster_atr),l={id:id(kind,b.close_time,p.id),kind,side:p.kind==='high'?'BSL':'SSL',price,event_at:p.event_at,known_at:b.close_time,created_index:index,tolerance:tol,state:'ACTIVE',reference_ids:[p.id],...extra};levels.push(l);emit('LEVEL_CREATED',b,l,{side:l.side,price,reference_ids:l.reference_ids});}
 function pivotsNow(index,b){const o=index-cfg.k;if(o-cfg.k<currentSegment)return;const w=bars.slice(o-cfg.k,index+1),a=bars[o];for(const kind of ['high','low']){const xs=w.map(x=>x[kind]),ext=kind==='high'?Math.max(...xs):Math.min(...xs);if(a[kind]!==ext||xs.indexOf(ext)!==cfg.k)continue;const same=pivots.filter(p=>p.kind===kind&&p.segment===currentSegment),prev=same.at(-1),tol=cfg.tick*2,delta=prev?a[kind]-prev.price:0,classification=!prev?'FIRST':Math.abs(delta)<=tol?'EQ':kind==='high'?(delta>0?'HH':'LH'):(delta>0?'HL':'LL');const p={id:id('PIVOT_'+kind,a.close_time),kind,price:a[kind],index:o,event_at:a.close_time,known_at:b.close_time,classification,segment:currentSegment};pivots.push(p);emit('PIVOT_CONFIRMED',b,p,{event_at:p.event_at,kind,price:p.price,classification});addLevel(kind==='high'?'SWING_HIGH':'SWING_LOW',p.price,p,b,index);
   const recent=levels.filter(l=>l.kind===(kind==='high'?'EQH':'EQL')&&l.state==='ACTIVE');if(!recent.some(l=>l.reference_ids.includes(p.id))){const peers=same.filter(x=>o-x.index>=cfg.k&&Math.abs(x.price-p.price)<=Math.max(tol,(features[index-1]?.atr||0)*cfg.cluster_atr));if(peers.length){const q=peers.at(-1);addLevel(kind==='high'?'EQH':'EQL',(q.price+p.price)/2,p,b,index,{reference_ids:[q.id,p.id],lower:Math.min(q.price,p.price),upper:Math.max(q.price,p.price)});}}
  }
  const hs=pivots.filter(p=>p.kind==='high'&&p.segment===currentSegment),ls=pivots.filter(p=>p.kind==='low'&&p.segment===currentSegment);if(hs.length>=2&&ls.length>=2){const h=hs.at(-1),h0=hs.at(-2),l=ls.at(-1),l0=ls.at(-2);if(h.price>h0.price&&l.price>l0.price)trend='UP';else if(h.price<h0.price&&l.price<l0.price)trend='DOWN';else trend='RANGE';}if(!lastRange&&hs.length&&ls.length)makeRange(b,hs.at(-1),ls.at(-1),'initial_confirmed_swings');
 }
 function makeRange(b,h,l,reason){if(!h||!l||h.price<=l.price)return;const r={id:id('RANGE',b.close_time,ranges.length),lower:l.price,upper:h.price,eq:(h.price+l.price)/2,high_id:h.id,low_id:l.id,anchor_start:Math.min(h.event_at,l.event_at),anchor_end:Math.max(h.event_at,l.event_at),known_at:b.close_time,reason,active:true};if(lastRange)lastRange.active=false;ranges.push(r);lastRange=r;emit('RANGE_CREATED',b,r,{lower:r.lower,upper:r.upper,high_id:h.id,low_id:l.id});}
 function displaced(b,index){if(index<=currentSegment)return null;const atr=features[index-1]?.atr,body=Math.abs(b.close-b.open),span=b.high-b.low;if(!(atr>0)||!span)return null;const loc=(b.close-b.low)/span;if(body<cfg.body_atr*atr||body/span<cfg.body_ratio)return null;const side=b.close>b.open&&loc>=cfg.close_location?'long':b.close<b.open&&loc<=1-cfg.close_location?'short':null;return side?{side,body_atr:body/atr,body_ratio:body/span,close_location:loc}:null;}
 function advanceLevels(b,index,disp){for(const l of levels){if(l.created_index>=index||['EXPIRED','SUSTAINED_BREAK'].includes(l.state))continue;if(index-l.created_index>cfg.zone_expiry){l.state='EXPIRED';emit('LEVEL_EXPIRED',b,l);continue;}const high=l.side==='BSL',hit=high?b.high>=l.price:b.low<=l.price,pierce=high?b.high>=l.price+cfg.tick:b.low<=l.price-cfg.tick,reclaim=high?b.close<l.price:b.close>l.price;if(l.state==='RECLAIMED'){if(!pierce||b.close_time-l.last_sweep_at<(D.TF_MS[cfg.tf]||30*86400000)*2)continue;l.state='ACTIVE';l.pierced_at=null;l.pierced_index=null;}
   if(hit&&l.state==='ACTIVE'){l.state='TOUCHED';emit('LEVEL_TOUCHED',b,l);}
   if(pierce&&l.pierced_at==null){l.state='PIERCED';l.pierced_at=b.close_time;l.pierced_index=index;l.pierce_extreme=high?b.high:b.low;emit('LEVEL_PIERCED',b,l,{side:high?'short':'long'});}
   if(l.state==='PIERCED'){l.pierce_extreme=high?Math.max(l.pierce_extreme,b.high):Math.min(l.pierce_extreme,b.low);if(reclaim&&index-l.pierced_index<=2){l.state='RECLAIMED';l.sweep_count=(l.sweep_count||0)+1;l.first_sweep_at=l.first_sweep_at??b.close_time;l.last_sweep_at=b.close_time;const side=high?'short':'long',e=emit('SWEEP_CANDIDATE',b,l,{side,level:l.price,extreme:l.pierce_extreme,pierced_at:l.pierced_at,price_based_proxy:true});lastSweep[side]=e;}else if(!reclaim&&index-l.pierced_index>=2){l.state='SUSTAINED_BREAK';emit('BREAKOUT_CONFIRMED',b,l,{side:high?'long':'short',level:l.price});}}
  }
 }
 function advanceZones(b,index){const invalid=[];for(const z of zones){if(z.created_index>=index||z.validity==='INVALIDATED'||z.state==='EXPIRED')continue;if(index>z.expires_index){z.state='EXPIRED';emit('ZONE_EXPIRED',b,z);continue;}const intersects=b.low<=z.upper&&b.high>=z.lower;if(intersects){if(!z.in_contact){z.touches++;emit('ZONE_TOUCH',b,z,{side:z.side,visit:z.touches});}z.in_contact=true;const depth=z.side==='long'?(z.upper-b.low)/(z.upper-z.lower):(b.high-z.lower)/(z.upper-z.lower);z.penetration=Math.max(z.penetration,Math.max(0,Math.min(1,depth)));const next=z.penetration>=1?'FILLED':z.penetration>0?'PARTIAL':'TOUCHED';if(next!==z.fill_state){z.fill_state=next;z.state=next;emit('ZONE_'+next,b,z,{side:z.side,penetration:z.penetration});}const held=z.side==='long'?b.close>z.upper:b.close<z.lower;if(held)emit('ZONE_RETEST',b,z,{side:z.side});}else z.in_contact=false;
   const failed=z.side==='long'?b.close<z.lower:b.close>z.upper;if(failed){z.validity='INVALIDATED';z.state='INVALIDATED';z.invalidated_at=b.close_time;z.invalidated_index=index;emit('ZONE_INVALIDATED',b,z,{side:z.side==='long'?'short':'long',fill_state:z.fill_state});invalid.push(z);}
  }return invalid;
 }
 function structure(b,index,disp){const hs=pivots.filter(p=>p.kind==='high'&&p.segment===currentSegment),ls=pivots.filter(p=>p.kind==='low'&&p.segment===currentSegment);const h=hs.at(-1),l=ls.at(-1),prev=bars[index-1];if(!prev)return [];const result=[];for(const [p,side] of [[h,'long'],[l,'short']]){if(!p||broken.has(p.id))continue;const crossed=side==='long'?prev.close<=p.price&&b.close>p.price:prev.close>=p.price&&b.close<p.price;if(!crossed)continue;broken.add(p.id);const opposite=side==='long'?trend==='DOWN':trend==='UP',type=opposite?'CHoCH':'BOS',e=emit(type,b,p,{side,level:p.price,trend_before:trend,reference_id:p.id,structure_scope:'timeframe_local'});result.push(e);if(opposite&&disp?.side===side)result.push(emit('MSS',b,p,{side,level:p.price,parent_event_id:e.id,displacement:disp}));trend=side==='long'?'UP':'DOWN';if(h&&l)makeRange(b,h,l,type);const sw=lastSweep[side];if(sw&&index-bars.findIndex(x=>x.close_time===sw.known_at)<=cfg.setup_expiry&&disp?.side===side&&!reversals.has(sw.id)){reversals.add(sw.id);emit('REVERSAL_CONFIRMED',b,p,{side,sweep_event_id:sw.id,structure_event_id:e.id});}
   if(disp?.side===side||lastDisplacement[side]!=null&&index-lastDisplacement[side]<=3){let j=index-1;for(;j>=Math.max(currentSegment,index-cfg.ob_lookback);j--){const c=bars[j];if(side==='long'?c.close<c.open:c.close>c.open)break;}if(j>=Math.max(currentSegment,index-cfg.ob_lookback)){const c=bars[j];addZone('OB',side,c.low,c.high,b,index,{reference_id:p.id,source_candle_at:c.open_time,body_lower:Math.min(c.open,c.close),body_upper:Math.max(c.open,c.close),structure_event_id:e.id,sweep_event_id:sw?.id??null,boundary_policy:'full_range'});}}
   const same=side==='long'?ls:hs;if(same.length>=2){const a=same.at(-2),q=same.at(-1),failure=side==='long'?q.price>a.price:q.price<a.price;if(failure){const c=bars[q.index];addZone('MITIGATION_PROXY',side,c.low,c.high,b,index,{reference_id:q.id,failure_swing_ids:[a.id,q.id],structure_event_id:e.id});}}
  }return result;
 }
 function createZones(b,index,disp,breaks,invalid){if(index>=currentSegment+2){const a=bars[index-2];if(b.low>a.high)addZone('FVG','long',a.high,b.low,b,index,{displacement:displaced(bars[index-1],index-1)?.side==='long',source_candle_at:bars[index-1].open_time});if(b.high<a.low)addZone('FVG','short',b.high,a.low,b,index,{displacement:displaced(bars[index-1],index-1)?.side==='short',source_candle_at:bars[index-1].open_time});}
  // Invalidated parent remains immutable in historical snapshots; inverse is a new object.
  for(const z of invalid)if(z.kind==='FVG'||z.kind==='OB'){const kind=z.kind==='FVG'?'IFVG_CANDIDATE':'BREAKER_CANDIDATE';if(z.kind==='OB'&&!z.sweep_event_id)continue;addZone(kind,z.side==='long'?'short':'long',z.lower,z.upper,b,index,{parent_zone_id:z.id,failure_event_at:b.close_time,requires_retest:true,sweep_event_id:z.sweep_event_id??null});}
  const fresh=zones.filter(z=>z.created_index===index&&z.kind==='FVG');for(const a of fresh)for(const q of zones.filter(z=>z.kind==='FVG'&&z.id!==a.id&&M.alive(z))){const key=[a.id,q.id].sort().join('|');if(pairs.has(key))continue;const bp=M.bpr(a,q);if(bp){pairs.add(key);addZone('BPR',a.side,bp.lower,bp.upper,b,index,{parent_zone_ids:bp.parent_zone_ids});}}
  const body=Math.abs(b.close-b.open),den=Math.max(body,cfg.tick,(features[index-1]?.atr||0)*.01),span=b.high-b.low;if(span){const lower=Math.min(b.open,b.close)-b.low,upper=b.high-Math.max(b.open,b.close),location=(b.close-b.low)/span;for(const [side,wick,ok,lo,hi] of [['long',lower,location>=2/3,b.low,Math.min(b.open,b.close)],['short',upper,location<=1/3,Math.max(b.open,b.close),b.high]])if(wick/den>=2&&ok&&levels.some(l=>Math.abs(l.price-(side==='long'?b.low:b.high))<=l.tolerance))addZone('REJECTION_PROXY',side,lo,hi,b,index,{wick_body:wick/den});}
  if(disp&&index>currentSegment&&displaced(bars[index-1],index-1)?.side===disp.side){const a=bars[index-1],overlap=Math.max(0,Math.min(a.high,b.high)-Math.max(a.low,b.low)),minSpan=Math.min(a.high-a.low,b.high-b.low);if(minSpan>0&&overlap/minSpan<.3)addZone('VOID_PROXY',disp.side,Math.min(a.low,b.low),Math.max(a.high,b.high),b,index,{overlap_ratio:overlap/minSpan});}
  if(disp){const base=bars.slice(Math.max(currentSegment,index-4),index);if(base.length===4&&features[index-1]?.atr>0){const lo=Math.min(...base.map(x=>x.low)),hi=Math.max(...base.map(x=>x.high));if(hi-lo<=features[index-1].atr*1.2)addZone('DEMAND_SUPPLY_PROXY',disp.side,lo,hi,b,index,{base_start:base[0].open_time,base_bars:4});}}
 }
 function advanceSetups(b,index,breaks){for(const side of ['long','short']){const sw=lastSweep[side],br=breaks.find(e=>e.side===side);if(sw&&br&&b.close_time-sw.known_at<=(D.TF_MS[cfg.tf]||30*86400000)*cfg.setup_expiry&&events.some(e=>e.type==='REVERSAL_CONFIRMED'&&e.known_at===b.close_time&&e.sweep_event_id===sw.id)&&!setups.some(s=>s.sweep_event_id===sw.id)){const s={id:id('SETUP',b.close_time,sw.id),side,state:'SETUP',known_at:b.close_time,created_index:index,sweep_event_id:sw.id,structure_event_id:br.id,range_id:lastRange?.id??null,invalidation_level:sw.extreme,expires_at:b.close_time+(D.TF_MS[cfg.tf]||30*86400000)*cfg.setup_expiry,zone_id:null,reference_high_id:lastRange?.high_id??null,reference_low_id:lastRange?.low_id??null,episode_id:sw.id,rule_origin:'independent_research'};setups.push(s);emit('SETUP_CREATED',b,s,{side,state:s.state});}}
  for(const s of setups){if(['INVALIDATED','EXPIRED'].includes(s.state))continue;const invalid=s.side==='long'?b.close<s.invalidation_level:b.close>s.invalidation_level;if(invalid){s.state='INVALIDATED';emit('SETUP_INVALIDATED',b,s,{side:s.side});continue;}if(b.close_time>s.expires_at){s.state='EXPIRED';emit('SETUP_EXPIRED',b,s);continue;}if(s.state==='TRIGGER_CONFIRMED'&&b.close_time>s.trigger_at){s.state='ACTIVE_RESEARCH';emit('SETUP_ACTIVE_RESEARCH',b,s,{side:s.side});}if(s.state==='ACTIVE_RESEARCH')continue;if(!s.zone_id){const z=zones.find(z=>z.kind==='FVG'&&z.side===s.side&&z.known_at>=s.known_at&&M.alive(z));if(z){s.zone_id=z.id;s.state='WAIT_RETEST';emit('SETUP_WAIT_RETEST',b,s,{side:s.side,zone_id:z.id});}}
   const z=zones.find(z=>z.id===s.zone_id);if(!z)continue;if(z.validity==='INVALIDATED'){s.state='INVALIDATED';emit('SETUP_INVALIDATED',b,s,{reason:'zone_invalidated'});continue;}if(index>z.created_index&&z.in_contact&&(s.side==='long'?b.close>z.upper:b.close<z.lower)){s.state='TRIGGER_CONFIRMED';s.trigger_at=b.close_time;s.first_execution_after=b.close_time;s.trigger_price=b.close;emit('SETUP_TRIGGER',b,s,{side:s.side,zone_id:z.id,next_bar_execution:true});}
  }
 }
 for(let index=0;index<bars.length;index++){const b=bars[index];if(gaps.has(index)){currentSegment=index;trend='INSUFFICIENT_STRUCTURE';for(const z of zones)if(M.alive(z)){z.state='EXPIRED';emit('ZONE_EXPIRED',b,z,{reason:'data_gap'});}for(const l of levels)if(!['RECLAIMED','SUSTAINED_BREAK','EXPIRED'].includes(l.state)){l.state='EXPIRED';emit('LEVEL_EXPIRED',b,l,{reason:'data_gap'});}for(const s of setups)if(!['INVALIDATED','EXPIRED','TRIGGER_CONFIRMED'].includes(s.state)){s.state='EXPIRED';emit('SETUP_EXPIRED',b,s,{reason:'data_gap'});}if(lastRange)lastRange.active=false;lastRange=null;lastSweep={long:null,short:null};lastDisplacement={long:null,short:null};emit('DATA_GAP',b,{},quality.gaps.find(g=>g.index===index));}
  const disp=displaced(b,index);if(disp){lastDisplacement[disp.side]=index;emit('DISPLACEMENT',b,{},disp);}pivotsNow(index,b);advanceLevels(b,index,disp);const invalid=advanceZones(b,index),breaks=structure(b,index,disp);createZones(b,index,disp,breaks,invalid);const ci=M.cisd(bars.slice(currentSegment),index-currentSegment);if(ci)emit(ci.type,b,{},ci);advanceSetups(b,index,breaks);
  // Breaker/IFVG remain candidates until a later retest holds.
  for(const z of zones)if(z.requires_retest&&z.created_index<index&&z.in_contact&&M.alive(z)&&(z.side==='long'?b.close>z.upper:b.close<z.lower)){z.requires_retest=false;z.kind=z.kind.replace('_CANDIDATE','_PROXY');emit('ROLE_REVERSAL_CONFIRMED',b,z,{side:z.side,parent_zone_id:z.parent_zone_id});}
  const f=features[index],range=lastRange?{...lastRange,location:(b.close-lastRange.lower)/(lastRange.upper-lastRange.lower)}:null,echo=M.volumeEcho(bars.slice(currentSegment,index+1),features.slice(currentSegment,index+1),index-currentSegment);
  const snapshot=D.copy({decision_at:b.close_time,last_closed_bar_at:b.close_time,identity,engine_version:VERSION,range_id:range?.id??null,range,structure:trend,features:f,objects:[...levels,...zones].filter(x=>x.known_at<=b.close_time).map(D.copy),setups,iof:M.delivery(events,b.close_time),volume_echo:echo,targets:M.targets(levels,zones,b.close,f.atr),data_quality:{price:index-currentSegment>=2?'available':'warming_up',oi:'missing'},event_count:events.length});if(cfg.capture_snapshots===false)snapshots[0]=snapshot;else snapshots.push(snapshot);
 }
 const last=snapshots.at(-1)??null;return {engine_version:VERSION,config:cfg,config_hash:D.digest(Object.fromEntries(Object.entries(cfg).filter(([k])=>!['at','flow','higher'].includes(k)))),identity,bars,events,pivots,zones,levels,ranges,setups,snapshots,last,features,data_quality:quality,divergences:M.divergence(pivots,features.map(f=>f.macd.line),{min_indicator:.01}),three_drive:M.threeDrive(pivots),institutional_swings:M.institutionalSwings(pivots,events),swing_metrics:M.swingMetrics(pivots,bars,features),volume_profile:I.volumeProfile(bars.slice(-Math.min(bars.length,200))),rule_origin:'independent_research'};
}
return {VERSION,DEFAULTS,analyze};
});
