(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ChartBroIndicators=api;})(globalThis,function(){'use strict';
const valid=v=>v!=null&&Number.isFinite(v);
function sma(xs,n){return xs.map((_,i)=>{const w=xs.slice(Math.max(0,i-n+1),i+1);return w.length===n&&w.every(valid)?w.reduce((a,b)=>a+b,0)/n:null;});}
function ema(xs,n){let current=null,seed=[];return xs.map(v=>{if(!valid(v)){current=null;seed=[];return null;}if(current==null){seed.push(v);if(seed.length<n)return null;current=seed.reduce((a,b)=>a+b,0)/n;}else current+=2/(n+1)*(v-current);return current;});}
function cross(pk,pd,k,d){return [pk,pd,k,d].every(valid)?pk<=pd&&k>d?'UP':pk>=pd&&k<d?'DOWN':null:null;}
function stochastic(bars,[n,ks,ds]){const raw=bars.map((b,i)=>{if(i+1<n)return null;const w=bars.slice(i-n+1,i+1),lo=Math.min(...w.map(x=>x.low)),hi=Math.max(...w.map(x=>x.high));return hi>lo?100*(b.close-lo)/(hi-lo):null;}),k=sma(raw,ks),d=sma(k,ds);return bars.map((_,i)=>({k:k[i],d:d[i],cross:i?cross(k[i-1],d[i-1],k[i],d[i]):null,slope:i&&valid(k[i])&&valid(k[i-1])?k[i]-k[i-1]:null}));}
function atr(bars,n=14){return sma(bars.map((b,i)=>Math.max(b.high-b.low,i?Math.abs(b.high-bars[i-1].close):0,i?Math.abs(b.low-bars[i-1].close):0)),n);}
function rvol(xs,n=20){return xs.map((v,i)=>{const w=xs.slice(i-n,i);return i>=n&&valid(v)&&w.every(valid)&&w.reduce((a,b)=>a+b,0)>0?v/(w.reduce((a,b)=>a+b,0)/n):null;});}
function macd(closes){const a=ema(closes,12),b=ema(closes,26),line=a.map((v,i)=>valid(v)&&valid(b[i])?v-b[i]:null),signal=ema(line,9);return line.map((v,i)=>({line:v,signal:signal[i],hist:valid(v)&&valid(signal[i])?v-signal[i]:null,cross:i?cross(line[i-1],signal[i-1],v,signal[i]):null}));}
function features(bars,{ema_periods=[14,28,57,92,142,224,268,378,448],stoch=[[20,12,12],[10,6,6],[5,3,3]]}={}){const closes=bars.map(b=>b.close),e=Object.fromEntries(ema_periods.map(n=>[n,ema(closes,n)])),a=atr(bars),m=macd(closes),s=stoch.map(p=>stochastic(bars,p)),r=rvol(bars.map(b=>b.quote_volume)),lastCross={macd:null,ema:null,stoch:[null,null,null]};return bars.map((b,i)=>{const out={atr:a[i],rvol:r[i],macd:m[i],stochastic:s.map((xs,j)=>({...xs[i],setting:stoch[j]})),taker_buy_share:valid(b.taker_buy_quote)&&b.quote_volume>0?b.taker_buy_quote/b.quote_volume:null};for(const n of ema_periods){out['ema'+n]=e[n][i];out['ema'+n+'_stable']=i+1>=n*3;}const band=[14,28,57,92].map(n=>e[n]?.[i]);out.compression_pct=band.every(valid)?(Math.max(...band)-Math.min(...band))/b.close*100:null;out.ema_cross=i?cross(e[14]?.[i-1],e[28]?.[i-1],e[14]?.[i],e[28]?.[i]):null;if(m[i].cross)lastCross.macd={direction:m[i].cross,at:b.close_time};if(out.ema_cross)lastCross.ema={direction:out.ema_cross,at:b.close_time};s.forEach((xs,j)=>{if(xs[i].cross)lastCross.stoch[j]={direction:xs[i].cross,at:b.close_time};});out.last_cross=JSON.parse(JSON.stringify(lastCross));return out;});}
function volumeProfile(bars,{bins=48,value_area=.7,trades=null}={}){if(!bars.length)return null;const lo=Math.min(...bars.map(b=>b.low)),hi=Math.max(...bars.map(b=>b.high));if(hi===lo)return null;bins=Math.max(2,Math.min(200,Math.floor(bins)));const width=(hi-lo)/bins,vs=Array(bins).fill(0);if(trades){for(const t of trades)if(t.price>=lo&&t.price<=hi&&t.quantity>=0)vs[Math.min(bins-1,Math.floor((t.price-lo)/width))]+=t.quantity;}else{if(bars.some(b=>b.base_volume==null))return null;for(const b of bars){const first=Math.min(bins-1,Math.floor((b.low-lo)/width)),last=Math.min(bins-1,Math.floor((b.high-lo)/width));for(let j=first;j<=last;j++)vs[j]+=b.base_volume/(last-first+1);}}
 const total=vs.reduce((a,b)=>a+b,0);if(!total)return null;const poc=vs.indexOf(Math.max(...vs));let left=poc,right=poc,sum=vs[poc];while(sum<total*value_area&&(left>0||right<bins-1)){if(left>0&&(right===bins-1||vs[left-1]>=vs[right+1]))sum+=vs[--left];else sum+=vs[++right];}return {lower:lo,upper:hi,bin_width:width,bins:vs,poc:lo+(poc+.5)*width,val:lo+left*width,vah:lo+(right+1)*width,value_area,approximation:!trades,range_start:bars[0].open_time,known_at:bars.at(-1).close_time};}
return {sma,ema,cross,stochastic,atr,rvol,macd,features,volumeProfile};
});
