(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ChartBroModels=api;})(globalThis,function(){'use strict';
const finite=v=>v!=null&&Number.isFinite(v),alive=z=>!['INVALIDATED','EXPIRED'].includes(z.state);
function bpr(a,b){if(a.kind!=='FVG'||b.kind!=='FVG'||a.side===b.side||!alive(a)||!alive(b))return null;const lower=Math.max(a.lower,b.lower),upper=Math.min(a.upper,b.upper);return upper>lower?{kind:'BPR',lower,upper,known_at:Math.max(a.known_at,b.known_at),parent_zone_ids:[a.id,b.id]}:null;}
function astra({quiet=false,volume_echo=false,taker_ratio=null,oi=null,price_stable=false,at=Infinity}={}){const oiOk=oi?.quality==='fresh'&&finite(oi.contracts_change_pct)&&oi.window_end<=at,lead=quiet&&oiOk&&oi.contracts_change_pct>1,b=quiet&&volume_echo&&finite(taker_ratio)&&taker_ratio>=1.15,c=price_stable&&oiOk&&finite(oi.previous_change_pct)&&oi.previous_change_pct<=-2&&oi.contracts_change_pct>=.3;return {type:lead&&b?'A+B':lead?'A':b?'B':c?'C':'OBSERVE',oi_quality:oi?.quality||'missing',oi_contracts_pct:oiOk?oi.contracts_change_pct:null,oi_notional_pct:oiOk?oi.notional_change_pct??null:null,taker_ratio,volume_echo};}
function smt({a=[],b=[],kind='low',at=Infinity,max_lag=3600000,min_correlation=.5,correlation=null,tick_a=0,tick_b=0}={}){if(!finite(correlation)||correlation<min_correlation||a.length<2||b.length<2)return {status:'INSUFFICIENT_DATA'};const aa=a.filter(p=>p.known_at<=at&&p.kind===kind),bb=b.filter(p=>p.known_at<=at&&p.kind===kind);if(aa.length<2||bb.length<2)return {status:'INSUFFICIENT_DATA'};const [a0,a1]=aa.slice(-2),[b0,b1]=bb.slice(-2);if(a0.kind!==b0.kind||a1.kind!==b1.kind||Math.abs(a0.event_at-b0.event_at)>max_lag||Math.abs(a1.event_at-b1.event_at)>max_lag)return {status:'INSUFFICIENT_DATA'};const high=a1.kind==='high',da=high?a1.price-a0.price:a0.price-a1.price,db=high?b1.price-b0.price:b0.price-b1.price;return {status:(da>tick_a&&db<=tick_b)||(db>tick_b&&da<=tick_a)?'NON_CONFIRMATION':'CONFIRMED',side:high?'short':'long',known_at:Math.max(a1.known_at,b1.known_at),references:[a0.id,a1.id,b0.id,b1.id],correlation};}
function divergence(pivots,indicator,{min_bars=3,min_price_pct=.1,min_indicator=1}={}){const out=[];for(const kind of ['high','low']){const ps=pivots.filter(p=>p.kind===kind);for(let i=1;i<ps.length;i++){const a=ps[i-1],b=ps[i],av=indicator[a.index],bv=indicator[b.index];if(a.segment!==b.segment||!finite(av)||!finite(bv)||b.index-a.index<min_bars||Math.abs(b.price/a.price-1)*100<min_price_pct||Math.abs(bv-av)<min_indicator)continue;const dp=b.price-a.price,di=bv-av;if(dp*di>=0)continue;out.push({type:kind==='low'?(dp<0?'BULLISH_REGULAR':'BULLISH_HIDDEN'):(dp>0?'BEARISH_REGULAR':'BEARISH_HIDDEN'),reference_ids:[a.id,b.id],known_at:b.known_at,indicator_from:av,indicator_to:bv});}}return out;}
function crossMatrix(frames,{indicator='macd',mode='window',window_ms=86400000,at=Date.now(),required=['12h','4h','1h','15m']}={}){const rows=required.map(tf=>{const s=frames[tf],f=s?.features,ev=indicator==='stochastic'?f?.last_cross?.stoch?.[2]:f?.last_cross?.[indicator];return {tf,at:ev?.at??null,direction:ev?.direction??null,below_zero:indicator==='macd'&&f?.macd?.line!=null?f.macd.line<0:null};}),ok=rows.every(r=>r.direction==='UP'&&r.at!=null&&r.at<=at);return {indicator,mode,window_ms,rows,confirmed:ok&&(mode==='maintained'||(mode==='exact'?rows.every(r=>r.at===rows[0].at):Math.max(...rows.map(r=>r.at))-Math.min(...rows.map(r=>r.at))<=window_ms&&rows.every(r=>at-r.at<=window_ms)))};}
function cisd(bars,i,{max_length=8}={}){const b=bars[i];if(!b||!i)return null;const side=b.close>b.open?'long':b.close<b.open?'short':null;if(!side)return null;let start=i-1,count=0;while(start>=0&&count<max_length&&(side==='long'?bars[start].close<bars[start].open:bars[start].close>bars[start].open)){count++;start--;}if(!count)return null;const ref=bars[start+1];if(side==='long'?b.close>ref.open:b.close<ref.open)return {type:'CISD_PROXY',side,level:ref.open,reference_time:ref.open_time,known_at:b.close_time,count};return null;}
function threeDrive(pivots){const p=[];const segment=pivots.at(-1)?.segment;for(const x of pivots.filter(p=>p.segment===segment)){if(p.at(-1)?.kind===x.kind){const last=p.at(-1);if(x.kind==='high'?x.price>last.price:x.price<last.price)p[p.length-1]=x;}else p.push(x);}if(p.length<6)return null;const q=p.slice(-6),side=q[0].kind==='low'?'long':'short',moves=[0,2,4].map(i=>({size:Math.abs(q[i+1].price-q[i].price),bars:q[i+1].index-q[i].index}));return {type:'THREE_DRIVE_PROXY',side,known_at:q[5].known_at,reference_ids:q.map(x=>x.id),moves,weakening:moves[2].size<moves[1].size||moves[2].size/moves[2].bars<moves[1].size/moves[1].bars,confirmed_reversal:false};}
function delivery(events,at,window=12*3600000){const xs=events.filter(e=>at-e.known_at<=window&&['BOS','CHoCH','MSS','ZONE_INVALIDATED','ZONE_RETEST'].includes(e.type)),up=xs.filter(x=>x.side==='long').length,down=xs.filter(x=>x.side==='short').length;return {state:!xs.length?'INSUFFICIENT_DATA':up&&down?'MIXED':up?'BULLISH_DELIVERY':'BEARISH_DELIVERY',evidence_ids:xs.map(x=>x.id),price_based_proxy:true};}
function targets(levels,zones,price,atr){return levels.filter(x=>!['EXPIRED','SUSTAINED_BREAK','RECLAIMED'].includes(x.state)).map(x=>({object_id:x.id,price:x.price,side:x.price>price?'above':'below',distance_atr:atr>0?Math.abs(x.price-price)/atr:null,obstacles:zones.filter(z=>alive(z)&&z.lower<Math.max(price,x.price)&&z.upper>Math.min(price,x.price)&&((x.price>price&&z.side==='short')||(x.price<price&&z.side==='long'))).map(z=>z.id),label:'target_candidate'})).sort((a,b)=>Math.abs(a.price-price)-Math.abs(b.price-price)).slice(0,8);}
function volumeEcho(bars,features,i){const now=features[i],b=bars[i];if(!now||now.rvol==null||now.rvol>1.2||now.ema14==null||b.close<now.ema14)return null;for(let j=i-1;j>=0;j--){const hours=(b.close_time-bars[j].close_time)/3600000;if(hours>72)break;if(hours>=3&&features[j].rvol>=2&&b.close>=bars[j].close*.97&&Math.min(...bars.slice(j+1,i+1).map(x=>x.low))>=bars[j].low*.97)return {anchor_time:bars[j].close_time,anchor_close:bars[j].close,anchor_low:bars[j].low,rvol:features[j].rvol};}return null;}
function compose(frames,at){
 const usable=tf=>frames[tf]&&frames[tf].last_closed_bar_at<=at&&frames[tf].data_quality?.price==='fresh';
 const evidence=[],reasons=[];const daily=frames['1d'],setup=frames['4h'],ready=frames['1h'];
 if(!usable('1d')||!usable('4h')||!usable('1h'))reasons.push('missing_or_stale_environment');
 const longEnvironment=daily&&daily.structure!=='DOWN',shortEnvironment=daily&&daily.structure!=='UP';
 const hits=['15m','5m'].flatMap(tf=>{const a=frames[tf];return usable(tf)?(a.setups||[]).filter(s=>s.state==='TRIGGER_CONFIRMED'&&s.trigger_at===a.last_closed_bar_at).map(s=>({...s,tf})):[];});
 const confirmed=hits.filter(s=>{
  const side=s.side,environment=side==='long'?longEnvironment:shortEnvironment;
  const htf=(setup?.setups||[]).some(x=>x.side===side&&!['INVALIDATED','EXPIRED'].includes(x.state))||(setup?.objects||[]).some(z=>z.side===side&&z.lower!=null&&alive(z)&&setup.bars?.at(-1)?.close>=z.lower&&setup.bars?.at(-1)?.close<=z.upper+(setup.features?.atr||0)*2);
  const preparation=ready&&(side==='long'?ready.structure==='UP':ready.structure==='DOWN')||(ready?.setups||[]).some(x=>x.side===side&&!['INVALIDATED','EXPIRED'].includes(x.state));
  if(environment&&htf&&preparation&&!reasons.length){evidence.push(s.id);return true;}return false;
 });
 return {confirmed:confirmed.length>0,side:confirmed[0]?.side??null,evidence_ids:evidence,reasons:confirmed.length?[]:[...reasons,'role_sequence_not_confirmed'],role_model:'1D_environment_4H_setup_1H_ready_15m_5m_execution',all_timeframes_same_direction_required:false};
}
function institutionalSwings(pivots,events){return events.filter(e=>e.type==='REVERSAL_CONFIRMED').flatMap(e=>{const sw=events.find(x=>x.id===e.sweep_event_id),p=sw&&pivots.find(p=>p.kind===(e.side==='long'?'low':'high')&&p.price===sw.extreme&&p.event_at<=e.known_at&&(sw.pierced_at==null||p.event_at>=sw.pierced_at));return p?[{id:'INSTITUTIONAL_PROXY:'+e.id,kind:'INSTITUTIONAL_SWING_PROXY',side:e.side,price:p.price,event_at:p.event_at,known_at:Math.max(e.known_at,p.known_at),pivot_id:p.id,sweep_event_id:sw.id,reversal_event_id:e.id,rule_origin:'independent_research'}]:[];});}
function swingMetrics(pivots,bars,features){const ps=[];for(const p of pivots){if(ps.at(-1)?.kind===p.kind)ps[ps.length-1]=p;else ps.push(p);}return ps.slice(1).flatMap((b,i)=>{const a=ps[i];if(a.segment!==b.segment||b.index<=a.index)return [];const move=b.price-a.price,atr=features[a.index]?.atr,previous=i?ps[i].price-ps[i-1].price:null;return [{from_id:a.id,to_id:b.id,known_at:b.known_at,price_change_pct:move/a.price*100,bars:b.index-a.index,change_per_bar:move/(b.index-a.index),atr_move:atr>0?Math.abs(move)/atr:null,pullback_depth:previous&&previous*move<0?Math.abs(move/previous):null,volume_sum:bars.slice(a.index,b.index+1).every(x=>x.base_volume!=null)?bars.slice(a.index,b.index+1).reduce((s,x)=>s+x.base_volume,0):null}];});}
return {institutionalSwings,swingMetrics,compose,bpr,astra,smt,divergence,crossMatrix,cisd,threeDrive,delivery,targets,volumeEcho,alive};
});
