(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ChartBroResearch=api;})(globalThis,function(){'use strict';
function positionSize({equity,risk_fraction,entry,stop,fee_rate=0,slippage=0,lot,min_notional=0,max_notional=Infinity,leverage=null}={}){if(![equity,risk_fraction,entry,stop,fee_rate,slippage,lot].every(Number.isFinite)||equity<=0||risk_fraction<=0||risk_fraction>1||entry<=0||stop<=0||entry===stop||lot<=0||fee_rate<0||slippage<0)throw new Error('invalid risk inputs');const risk_budget=equity*risk_fraction,expected_loss_per_unit=Math.abs(entry-stop)+(entry+stop)*fee_rate+2*slippage,quantity=Math.floor(Math.min(risk_budget/expected_loss_per_unit,max_notional/entry)/lot+1e-10)*lot,notional=quantity*entry;return {risk_budget,expected_loss_per_unit,quantity:quantity>0&&notional>=min_notional?quantity:0,notional,margin:leverage>0?notional/leverage:null,status:quantity>0&&notional>=min_notional?'VALID':'BELOW_MINIMUM',realized_loss_can_exceed_budget:true};}
function outcome(setup,bars,{fee_rate=0,slippage=0,funding_return=0,horizon_ms=72*3600000}={}){const side=setup.side==='long'?1:-1,start=bars.findIndex(b=>b.open_time>setup.known_at);if(start<0)return {result:'UNFILLED',mfe:null,mae:null};const xs=bars.slice(start).filter(b=>b.open_time<=setup.known_at+horizon_ms),entry=xs[0].open+side*slippage;if(entry<=0||!Number.isFinite(entry))throw new Error('invalid entry');let mfe=0,mae=0,exit=xs.at(-1).close,result=xs.at(-1).close_time>=setup.known_at+horizon_ms?'TIME_EXIT':'UNRESOLVED',ambiguous=false;for(const b of xs){mfe=Math.max(mfe,side===1?b.high/entry-1:1-b.low/entry);mae=Math.min(mae,side===1?b.low/entry-1:1-b.high/entry);const hitStop=side===1?b.low<=setup.stop:b.high>=setup.stop,hitTarget=side===1?b.high>=setup.target:b.low<=setup.target;if(hitStop||hitTarget){ambiguous=hitStop&&hitTarget;result=ambiguous?'AMBIGUOUS':hitStop?'STOP':'TARGET';exit=hitStop?(side===1?Math.min(setup.stop,b.open):Math.max(setup.stop,b.open)):setup.target;break;}}exit-=side*slippage;const net=side*(exit-entry)/entry-fee_rate*(entry+exit)/entry-funding_return;return {setup_id:setup.id??null,episode_id:setup.episode_id??setup.id??null,horizon_ms,result,entry,exit,mfe,mae,conservative_net_return:net,ambiguous,availability_assumption:'next_bar_open',costs:{fee_rate,slippage,funding_return},label_30pct:mfe>=.3};}
function split(cohort,{train_end,validation_end,test_end,horizon_ms=72*3600000,embargo_ms=0}={}){const result={train:[],validation:[],oos:[],purged:[]};for(const x of cohort){const t=x.known_at,end=t+horizon_ms;if(end<=train_end)result.train.push(x);else if(t>=train_end+embargo_ms&&end<=validation_end)result.validation.push(x);else if(t>=validation_end+embargo_ms&&end<=test_end)result.oos.push(x);else result.purged.push(x);}return result;}
function stats(outcomes){const seen=new Set(),unique=outcomes.filter(x=>{if(!x.episode_id)return true;const key=x.episode_id+':'+(x.horizon_ms??'');if(seen.has(key))return false;seen.add(key);return true;});const rs=unique.filter(x=>Number.isFinite(x.conservative_net_return)&&!['UNRESOLVED','UNFILLED'].includes(x.result)).map(x=>x.conservative_net_return),n=rs.length;let equity=1,peak=1,dd=0;for(const r of rs){equity*=1+r;peak=Math.max(peak,equity);dd=Math.max(dd,1-equity/peak);}const mean=n?rs.reduce((a,b)=>a+b,0)/n:null,variance=n>1?rs.reduce((s,r)=>s+(r-mean)**2,0)/(n-1):null;return {count:n,unresolved:unique.length-n,duplicate_episodes:outcomes.length-unique.length,equity_curve_assumption:'unit_notional_compounded',net_expectancy:mean,mean_interval_95:variance==null?null:[mean-1.96*Math.sqrt(variance/n),mean+1.96*Math.sqrt(variance/n)],max_drawdown:dd,ambiguous:outcomes.filter(x=>x.ambiguous).length};}
function ablation(cohort,resolve,conditions){return ['baseline',...conditions].map(drop=>{const selected=cohort.filter(x=>Object.entries(x.conditions||{}).every(([key,pass])=>key===drop||pass===true));return {dropped:drop,coverage:cohort.length?selected.length/cohort.length:0,...stats(selected.map(resolve))};});}
const recoveryRate=loss=>loss>=0&&loss<1?loss/(1-loss):null;
function portfolio(positions=[]){return {planned_risk:positions.reduce((s,p)=>s+(p.risk_budget||0),0),long_notional:positions.filter(p=>p.side==='long').reduce((s,p)=>s+p.notional,0),short_notional:positions.filter(p=>p.side==='short').reduce((s,p)=>s+p.notional,0),open_setups:positions.length};}
return {positionSize,outcome,split,stats,ablation,recoveryRate,portfolio};
});
