'use strict';
// Inventory copied from the user's 2026-10-03 specification; no footage has been verified by this engine.
const rows=[
['dcsMpijHgF8','90% 가짜 오더블럭을 구별하는 3가지 방법','OB'],['V3ahczuG46I','5년 걸려 깨달은 ICT 핵심','unverified'],['vW2VzuDdhy0','트레이딩 설계','risk'],['QYfwaJJEH0E','7가지 PD Array 총정리','PD_ARRAY'],['dHZNSbF32eA','700개 차트강의 18분 요약','unverified'],['iwDPnAg-VsU','3가지 캔들 단타매매법','unverified'],['vtaPjIZp0jg','+19% 매매 승률 방법','research'],['9FDNnqmZRdI','손실 계좌 복구','risk'],['rmgfnF-oS24','EP6 ICT Gap','unverified'],['wnE-F-QPn-I','EP5 오더블럭','OB'],['NFSS8TLlyf8','EP4 프리미엄 디스카운트','range'],['g-mQn2Y5TZ4','EP3 공정가치','unverified'],['u_-sZdDIspY','EP2 IPDA','unverified'],['daCuAhzMbus','EP1 거래량과 유동성','volume'],['2jI7yDjpWv8','ICT 강의 다시 시작','intro'],['oSxWQrhvXgY','워런 버핏 투자 비법','philosophy'],['pV376afkJA8','높은 낮은 저항 유동성','targets'],['4bL9Gj5fz4c','BTC 급락 전망','case'],['vo4xpNlv6K0','기관의 시장 구조와 스윙 포인트','swing_proxy'],['SL4Pvxik_hs','BTC 급락 유의','case'],['cC92MwPlCgI','선물거래 기초','risk'],['d23S1-yjzKQ','BTC 상승 대비','case'],['_7QTiohmk4s','BTC 나스닥 차트 분석','case'],['WeArZQZQxDo','MMXM 기관 주문 흐름','mmxm_proxy'],['aNRmnCLhxCI','MMXM 기관 시장 구조','mmxm_proxy'],['Za9fIFRmXL4','마켓 메이커 모델','mmxm_proxy'],['qhuSSGTASPc','ICT 필수 보조지표','unverified'],['ShJK5i7ViAk','차트패턴 돈 안되는 이유','case'],['urwT3vPB7Kw','SMT','smt'],['kp6NFbwFLpA','세션과 킬존','sessions'],['Fg3vsezz714','기준시간','sessions'],['zITizJfGnbk','Three Drive','three_drive'],['DnGemQi1sOE','BPR','BPR'],['VrE4qlFATeA','PD Array 총정리','PD_ARRAY'],['meabenx4n6M','Liquidity Engineering','sweep'],['0h9lpMUBSlE','CISD','cisd_proxy'],['8D243mFHHa4','스토캐스틱 시간론','wave_duration'],['4oDljfcZNss','3스토캐스틱 파동 연결','stochastic'],['l0-ztKG-LTc','ERL IRL','range'],['26Rtu27IcIc','고승덕 3스토캐스틱','stochastic'],['z139BWjdn70','다이버전스 이평 연계','divergence'],['hmj71al9qSc','IOF3','iof_proxy'],['lHPMUKOKSE8','IOF2','iof_proxy'],['zVYe6KYvgnU','IOF1','iof_proxy'],['5F33AU4u8vA','ICT Rejection Block','RB'],['dNHFZTw2p6A','이평선','ema'],['wvfssgXhTcA','추세반전 규모와 시기','unverified'],['3geLicPKAhU','Breaker Mitigation Block','PD_ARRAY'],['xX84pU4wBk0','1만 구독 차트분석 팁','unverified'],['yLATX0Z9rxE','스토캐스틱 보조지표','stochastic'],['Snt6eDn67JM','스토캐스틱 강의','stochastic'],['kFZXHyLWVdM','승률 높은 타점 핵심','unverified'],['t7jIVY6RDGs','FVG','FVG'],['nRBt2S44-w0','급락 차트강의','unverified'],['xZsfjWWW96k','Liquidity Sweep','sweep'],['rFP0dDnX3es','Liquidity Pools','liquidity'],['zIT8DKcGWs0','볼륨프로파일','VP'],['DkF3CjvKpyM','ICT Order Block','OB'],['A9ZryUct6nE','유동성과 변동성','liquidity'],['jFLJUsKlu38','터진 거래량 추격','volume'],['j-3Iw9KRxbE','Thrust Pullback','swing'],['j-EDnCCBjYg','D&S Zone','DS'],['S7CK3OH5vTQ','Liquidity Void','VOID'],['uW-B-1b4I9M','PD Array 가격','PD_ARRAY'],['EdrfcG6S4zE','시장구조','structure'],['blu90h4uJvg','다우이론','structure'],['fUw1t1Ui6lo','유동성 기초','liquidity'],['9I-uUdlUAJ4','IPDA','unverified'],['6aHvauA7uvk','Low Hanging Fruit','targets'],['6q9s2HWhZnc','Power of 3','amd_proxy'],['iBfFGAE5EtA','ICT Bias','iof_proxy'],['2TG0L4P-JBo','DOL','targets'],['h6BuOCUL8Vk','IDR','unverified']
];
const members=new Set([17,19,24,25,26,69,70,71,72,73]);
const modulePaths={OB:'lib/chartbro/engine.js',PD_ARRAY:'lib/chartbro/engine.js',range:'lib/chartbro/engine.js',risk:'lib/chartbro/research.js',research:'lib/chartbro/research.js',volume:'lib/chartbro/indicators.js',targets:'lib/chartbro/models.js',swing_proxy:'lib/chartbro/models.js',mmxm_proxy:'lib/chartbro/temporal.js',smt:'lib/chartbro/models.js',sessions:'lib/chartbro/sessions.js',three_drive:'lib/chartbro/models.js',BPR:'lib/chartbro/models.js',sweep:'lib/chartbro/engine.js',cisd_proxy:'lib/chartbro/models.js',stochastic:'lib/chartbro/indicators.js',divergence:'lib/chartbro/models.js',iof_proxy:'lib/chartbro/models.js',RB:'lib/chartbro/engine.js',ema:'lib/chartbro/indicators.js',FVG:'lib/chartbro/engine.js',liquidity:'lib/chartbro/engine.js',VP:'lib/chartbro/indicators.js',swing:'lib/chartbro/models.js',DS:'lib/chartbro/engine.js',VOID:'lib/chartbro/engine.js',structure:'lib/chartbro/engine.js',amd_proxy:'lib/chartbro/temporal.js'};
const sources=rows.map(([video_id,title,module],i)=>({video_id,title,url:'https://www.youtube.com/watch?v='+video_id,access_status:members.has(i+1)?'membership_user_reported':'public_user_reported',metadata_found:true,metadata_provenance:'user_supplied_spec_20261003',captions_available:'unknown',audio_reviewed:false,visual_reviewed:false,definition_extracted:false,definition_verified:false,module_linked:!!modulePaths[module],module,module_path:modulePaths[module]||null,source_time_interval:null,fixture_path:modulePaths[module]?'tests/chartbro/core.test.js':null,fixture_linked:['OB','FVG','BPR','risk','sessions','liquidity','structure','stochastic','VP','smt','amd_proxy','research'].includes(module),engine_rule_origin:'independent_research'}));
function coverage(){return {inventory_count:sources.length,audio_verified:0,visual_verified:0,definitions_verified:0,inventory_complete:false,playlists:['CHARTBRO 2026','CHARTBRO ICT 2025','CHARTBRO MEMBERSHIP','CHARTBRO ICT','CHARTBRO STOCHASTIC','CHARTBRO CONTENTS'],sources};}
module.exports={sources,coverage};
