const BASES=['https://fapi.binance.com','https://fapi1.binance.com','https://fapi2.binance.com','https://www.binance.com'];
const n=(v,f=0)=>{v=Number(v);return Number.isFinite(v)?v:f};
const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
async function getJson(path,params={}){const qs=new URLSearchParams(params).toString();let last;for(const base of BASES){const ac=new AbortController(),to=setTimeout(()=>ac.abort(),4500);try{const r=await fetch(base+path+(qs?'?'+qs:''),{signal:ac.signal,headers:{'User-Agent':'PulseRadar-Pro/Futures-Public'}}),t=await r.text();if(!r.ok)throw Error(`Binance Futures ${r.status}: ${t.slice(0,160)}`);return JSON.parse(t)}catch(e){last=e}finally{clearTimeout(to)}}throw last||Error('Binance Futures request failed')}
function ema(a,p){let x=a[0]||0,k=2/(p+1),o=[];for(let i=0;i<a.length;i++){x=i?a[i]*k+x*(1-k):a[i];o.push(x)}return o}
function sma(a,p){let s=0,o=Array(a.length).fill(null);for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)o[i]=s/p}return o}
function atr(h,l,c,p=14){const tr=h.map((x,i)=>i?Math.max(x-l[i],Math.abs(x-c[i-1]),Math.abs(l[i]-c[i-1])):x-l[i]);return ema(tr,p)}
function rsi(a,p=14){let o=Array(a.length).fill(null);if(a.length<=p)return o;let g=0,l=0;for(let i=1;i<=p;i++){let d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;o[p]=l?100-100/(1+g/l):100;for(let i=p+1;i<a.length;i++){let d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;o[i]=l?100-100/(1+g/l):100}return o}
function sd(a){const m=avg(a)||0;return Math.sqrt(avg(a.map(x=>(x-m)**2))||0)}
function pct(rows,key){const v=rows.map(x=>({s:x.symbol,v:n(x[key],NaN)})).filter(x=>Number.isFinite(x.v)).sort((a,b)=>a.v-b.v),m=new Map(),d=Math.max(1,v.length-1);v.forEach((x,i)=>m.set(x.s,i/d*100));return m}
async function market(minVolume=500000){const [ex,t]=await Promise.all([getJson('/fapi/v1/exchangeInfo'),getJson('/fapi/v1/ticker/24hr')]);const ok=new Set((ex.symbols||[]).filter(s=>s.status==='TRADING'&&s.quoteAsset==='USDT'&&s.contractType==='PERPETUAL').map(s=>s.symbol));let rows=(Array.isArray(t)?t:[]).filter(x=>ok.has(x.symbol)).map(x=>({symbol:x.symbol,market:'futures',contractType:'PERPETUAL',price:n(x.lastPrice),change24:n(x.priceChangePercent),quoteVol24:n(x.quoteVolume),change1h:0,change4h:0,velocity:n(x.quoteVolume),pass:n(x.quoteVolume)>=minVolume}));const pv=pct(rows,'quoteVol24'),pc=pct(rows,'change24');rows=rows.map(r=>{const v=pv.get(r.symbol)||0,m=pc.get(r.symbol)||0,over=Math.max(0,Math.abs(r.change24)-20),pre=Math.round(clamp(.58*v+.42*(100-Math.abs(m-65)*1.4)-over,0,99)*10)/10,surge=Math.round(clamp(.55*v+.45*m-over,0,100));return{...r,p1:m,p4:m,pv:v,btcRel:0,preScore:pre,surgeScore:surge,axis:{volume:Math.round(v/5),momentum:Math.round(m/5),relativeStrength:0},preFeatures:{futures24hProxy:true}}});const ranked=rows.filter(r=>r.pass).sort((a,b)=>b.preScore-a.preScore||b.quoteVol24-a.quoteVol24);ranked.forEach((r,i)=>{r.preRank=i+1;r.preTopPct=(i+1)/Math.max(1,ranked.length)*100});rows.sort((a,b)=>Math.max(b.surgeScore,b.preScore)-Math.max(a.surgeScore,a.preScore));return{ok:true,version:'futures-public-v2-multi-base',market:'futures',updatedAt:new Date().toISOString(),total:rows.length,eligible:ranked.length,results:rows,liteDiagnostics:{note:'USD-M perpetual futures; ranking uses 24h public market proxy'}}}
function pivots(h,l,left=3,right=3){let out=[];for(let i=left;i<h.length-right;i++){let ph=true,pl=true;for(let j=i-left;j<=i+right;j++){if(j===i)continue;if(h[j]>=h[i])ph=false;if(l[j]<=l[i])pl=false}if(ph)out.push({id:`FH-${i}`,i,type:'H',price:h[i],confirmedAt:i+right});if(pl)out.push({id:`FL-${i}`,i,type:'L',price:l[i],confirmedAt:i+right})}return out.sort((a,b)=>a.confirmedAt-b.confirmedAt||a.i-b.i)}
function canonical(raw){let sw=[],revisions=[],seq=0;for(const p of raw){let q={swingId:`FS-${++seq}`,type:p.type,price:p.price,pivotIndex:p.i,pivotId:p.id,confirmedAt:p.confirmedAt,status:'active'};if(!sw.length||sw.at(-1).type!==q.type)sw.push(q);else{let old=sw.at(-1),more=q.type==='H'?q.price>old.price:q.price<old.price;if(more){revisions.push({...old,status:'replaced',replacedAt:q.confirmedAt});sw[sw.length-1]=q}else revisions.push({...q,status:'discarded'})}}let H=null,L=null;for(const s of sw){if(s.type==='H'){s.label=H==null?'H':s.price>H?'HH':'LH';H=s.price}else{s.label=L==null?'L':s.price>L?'HL':'LL';L=s.price}}return{swings:sw,revisions}}
function events(sw,c,times){let hi=null,lo=null,trend='neutral',si=0,e=[];const ord=[...sw].sort((a,b)=>a.confirmedAt-b.confirmedAt);for(let i=0;i<c.length;i++){while(si<ord.length&&ord[si].confirmedAt<=i){let s=ord[si++];if(s.type==='H')hi=s;else lo=s}if(hi&&c[i]>hi.price){e.push({i,eventTime:times[i],type:trend==='down'?'CHOCH':'BOS',dir:'up',level:hi.price,retestStatus:'pending',sourceSwingConfirmedAt:hi.confirmedAt});trend='up';hi=null}if(lo&&c[i]<lo.price){e.push({i,eventTime:times[i],type:trend==='up'?'CHOCH':'BOS',dir:'down',level:lo.price,retestStatus:'pending',sourceSwingConfirmedAt:lo.confirmedAt});trend='down';lo=null}}return e.slice(-24)}
function fit(ps){if(ps.length<2)return null;const mx=avg(ps.map(x=>x.i)),my=avg(ps.map(x=>x.price));let a=0,b=0;ps.forEach(p=>{a+=(p.i-mx)*(p.price-my);b+=(p.i-mx)**2});const slope=b?a/b:0;return{slope,intercept:my-slope*mx}}
function lineAt(L,i){return L.intercept+L.slope*i}
function tl(raw,c,aa,times,side){const pts=raw.filter(x=>x.type===(side==='support'?'L':'H')).slice(-12);let best=null;for(let a=0;a<pts.length-2;a++)for(let b=a+1;b<pts.length-1;b++){if(pts[b].i-pts[a].i<8)continue;let base=fit([pts[a],pts[b]]),touch=pts.filter(p=>p.i>=pts[a].i&&Math.abs(p.price-lineAt(base,p.i))<=Math.max((aa[p.i]||aa.at(-1)||0)*.3,p.price*.002));if(touch.length<3)continue;let L=fit(touch),last=Math.max(...touch.map(x=>x.i)),span=last-Math.min(...touch.map(x=>x.i));if(c.length-1-last>40)continue;let current=lineAt(L,c.length-1),dist=(aa.at(-1)||0)?(c.at(-1)-current)/aa.at(-1):null,score=Math.round(clamp(touch.length*10+Math.min(20,span*.25)+Math.max(0,20-(c.length-1-last)*.5)));let q={side,state:Math.abs(dist||99)<=.35?'retest':score<60?'candidate':'active',slope:L.slope,intercept:L.intercept,anchorA:{barIndex:touch[0].i,price:lineAt(L,touch[0].i),time:times[touch[0].i]},anchorB:{barIndex:last,price:lineAt(L,last),time:times[last]},touchCount:touch.length,touchBars:touch.map(x=>x.i),spanBars:span,lastTouchBarsAgo:c.length-1-last,totalScore:score,currentLinePrice:current,currentDistanceAtr:dist,source:'futures_raw_pivot'};if(!best||q.totalScore>best.totalScore)best=q}return best}
function aggregateWeeklyRaw(rows){
  const WEEK=7*86400000,MONDAY_SHIFT=3*86400000,groups=new Map();
  for(const k of rows||[]){
    const t=n(k?.[0],NaN);if(!Number.isFinite(t))continue;
    const start=Math.floor((t+MONDAY_SHIFT)/WEEK)*WEEK-MONDAY_SHIFT;
    let g=groups.get(start);
    if(!g){g={start,rows:[]};groups.set(start,g)}
    g.rows.push(k);
  }
  return [...groups.values()].sort((a,b)=>a.start-b.start).map(g=>{
    const xs=g.rows.sort((a,b)=>n(a[0])-n(b[0])),first=xs[0],last=xs.at(-1);
    return [
      g.start,
      String(n(first?.[1])),
      String(Math.max(...xs.map(x=>n(x?.[2])))),
      String(Math.min(...xs.map(x=>n(x?.[3])))),
      String(n(last?.[4])),
      String(xs.reduce((s,x)=>s+n(x?.[5]),0)),
      g.start+WEEK-1,
      String(xs.reduce((s,x)=>s+n(x?.[7]),0)),
      xs.reduce((s,x)=>s+n(x?.[8]),0),
      String(xs.reduce((s,x)=>s+n(x?.[9]),0)),
      String(xs.reduce((s,x)=>s+n(x?.[10]),0)),
      '0'
    ];
  });
}
async function structure(symbol='BTCUSDT',interval='1h',limit=500){let raw;try{raw=await getJson('/fapi/v1/klines',{symbol,interval,limit:String(Math.min(1000,Math.max(80,limit)))})}catch(e){if(interval!=='1w')throw e;const daily=await getJson('/fapi/v1/klines',{symbol,interval:'1d',limit:'1000'});raw=aggregateWeeklyRaw(daily)}const closed=raw.filter(k=>n(k[6])<Date.now());if(closed.length<60)throw Error('선물 확정봉 데이터 부족');const times=closed.map(k=>n(k[0])),o=closed.map(k=>n(k[1])),h=closed.map(k=>n(k[2])),l=closed.map(k=>n(k[3])),c=closed.map(k=>n(k[4])),v=closed.map(k=>n(k[5])),vs=sma(v,20),aa=atr(h,l,c),rp=pivots(h,l),can=canonical(rp),ev=events(can.swings,c,times);let lastH=null,lastL=null,score=0;for(const s of can.swings.slice(-6)){if(s.type==='H')lastH=s;else lastL=s;if(s.label==='HH'||s.label==='HL')score++;if(s.label==='LH'||s.label==='LL')score--}const bias={label:score>1?'bullish':score<-1?'bearish':'neutral',score,components:['USD-M Futures confirmed candles','Canonical swing structure']};const support=tl(rp,c,aa,times,'support'),resistance=tl(rp,c,aa,times,'resistance'),cur=c.at(-1),tol=Math.max(cur*.0025,(aa.at(-1)||0)*.35),groups=[];for(const p of rp.slice(-36)){let g=groups.find(x=>Math.abs(x.center-p.price)<=tol);if(!g){g={center:p.price,vals:[],ps:[]};groups.push(g)}g.vals.push(p.price);g.ps.push(p);g.center=avg(g.vals)}const zones=groups.filter(g=>g.vals.length>=2).map(g=>({low:Math.min(...g.vals)-tol*.4,high:Math.max(...g.vals)+tol*.4,center:g.center,type:g.center<cur?'support':'resistance',touchCount:g.vals.length,strengthScore:Math.round(clamp(g.vals.length*20)),source:'futures_raw_pivot_cluster'})).sort((a,b)=>Math.abs(a.center-cur)-Math.abs(b.center-cur)).slice(0,6);const candles=closed.map((k,i)=>({time:times[i],openTime:times[i],closeTime:n(k[6]),open:o[i],high:h[i],low:l[i],close:c[i],volume:v[i],quoteVolume:n(k[7]),takerBuyQuote:n(k[10]),atr:aa[i],volSma20:vs[i]}));return{ok:true,version:'futures-structure-v1',market:'futures',dataSource:'Binance USD-M Perpetual Futures public klines',symbol,interval,lastClosedCloseTime:n(closed.at(-1)[6]),snapshotTime:n(closed.at(-1)[6]),candles,rawPivots:rp,canonicalSwings:can.swings,swingRevisions:can.revisions,events:ev,zones,bias,current:{price:cur,supportDistanceAtr:support?.currentDistanceAtr??null,resistanceDistanceAtr:resistance?.currentDistanceAtr??null},trendlines:{support,resistance,secondary:{support:[],resistance:[]},dedup:{support:{raw:support?1:0,unique:support?1:0},resistance:{raw:resistance?1:0,unique:resistance?1:0}}},trendlineComparison:{raw:{support,resistance},canonical:{support,resistance}},audit:{coreStatus:'PASS',checks:[{name:'Closed candle only',status:'PASS'},{name:'Futures public data',status:'PASS'},{name:'Canonical swing timing',status:'PASS'}]}}}
function analyze(raw,tf){const bars=raw.filter(k=>n(k[6])<Date.now()),h=bars.map(k=>n(k[2])),l=bars.map(k=>n(k[3])),c=bars.map(k=>n(k[4])),v=bars.map(k=>n(k[5])),price=c.at(-1),e5=ema(c,5).at(-1),e20=ema(c,20).at(-1),e60=ema(c,60).at(-1),rr=rsi(c).at(-1),aa=atr(h,l,c).at(-1),vs=sma(v,20).at(-1)||1,volRatio=v.at(-1)/vs,w=c.slice(-20),mid=avg(w),s=sd(w),bbWidth=mid?4*s/mid:0,prev=c.slice(-40,-20),pm=avg(prev),ps=sd(prev),prevW=pm?4*ps/pm:bbWidth,buy=bars.slice(-5).reduce((x,k)=>x+n(k[10]),0),q=bars.slice(-5).reduce((x,k)=>x+n(k[7]),0),gap=(Math.max(e5,e20,e60)-Math.min(e5,e20,e60))/Math.max(price,1e-12)*100;return{tf,price,ema5:e5,ema20:e20,ema60:e60,rsi14:rr,macdHist:0,atrPct:price?aa/price*100:0,volRatio,buyRatio:q?buy/q:.5,emaGapPct:gap,bbWidth,squeeze:bbWidth<prevW*.82,breakout:false,trendAligned:price>e5&&e5>e20&&e20>e60,converging:gap<1.3,lastRangePct:price?(h.at(-1)-l.at(-1))/price*100:0}}
async function detail(symbol='BTCUSDT'){const tfs=['5m','15m','1h'],raws=await Promise.all(tfs.map(interval=>getJson('/fapi/v1/klines',{symbol,interval,limit:'220'}))),frames=raws.map((r,i)=>analyze(r,tfs[i]));const aligned=frames.filter(x=>x.trendAligned).length,pre=Math.round(clamp(frames.reduce((s,x)=>s+(x.squeeze?22:0)+(x.converging?20:0)+(x.volRatio>=1.1&&x.volRatio<=2.5?18:0)+(x.rsi14>=47&&x.rsi14<=62?15:0),0)/3)),surge=Math.round(clamp(frames.reduce((s,x)=>s+(x.trendAligned?35:0)+Math.min(30,Math.max(0,(x.volRatio-1)*18))+(x.rsi14>=55&&x.rsi14<=72?25:8),0)/3)),warn=[],hard=[];frames.forEach(f=>{if(f.rsi14>=82)hard.push(`${f.tf} RSI 극과열`);else if(f.rsi14>=75)warn.push(`${f.tf} RSI 과열`);if(f.atrPct>=9)hard.push(`${f.tf} ATR 급변동`)});const riskGate={hard,warn,excluded:hard.length>0},grade=riskGate.excluded?'EXCLUDE':pre>=70||surge>=70?'A':pre>=55||surge>=60?'B':'C';return{ok:true,market:'futures',symbol,timeframes:frames,preSurge:{score:pre,stage:pre>=75?'압축 해제 임박 후보':pre>=55?'준비 단계 후보':pre>=35?'관찰 단계':'초기 조건 부족',reasons:['USD-M Futures public candles','진단 전용']},surge:{score:surge,aligned},riskGate,confidence:{grade,label:grade==='A'?'다중요인 강한 합의':grade==='B'?'양호, 일부 약점':grade==='EXCLUDE'?'위험 게이트':'혼합/초기'}}}
module.exports={market,structure,detail};