(()=>{'use strict';
const D=window.PulseDataIntegrity,O=window.PulseOutcomeRecorder,C=window.PulseCalibration,R=window.PulseRegime,A=window.PulseAlertState;
if(!D||!O||!C||!R||!A)return;
const net={samples:[],lastOkMs:null,lastErrorMs:null,errors:0,structures:new Map(),active:0};
const rawFetch=window.fetch.bind(window);
window.fetch=async function(input,init){const url=String(typeof input==='string'?input:input?.url||''),start=performance.now();net.active++;try{const res=await rawFetch(input,init),latency=performance.now()-start,ok=res.ok;net.samples.push({url,latencyMs:latency,ok,at:Date.now()});net.samples=net.samples.slice(-80);if(ok)net.lastOkMs=Date.now();else{net.lastErrorMs=Date.now();net.errors++}if(ok&&/\/api\/structure\?/.test(url)){try{const clone=res.clone(),data=await clone.json(),u=new URL(url,location.origin),tf=u.searchParams.get('interval')||'4h',symbol=u.searchParams.get('symbol')||'BTCUSDT';net.structures.set(`${symbol}:${tf}`,{data,fetchedAtMs:Date.now(),latencyMs:latency,url});}catch{}}return res}catch(e){net.lastErrorMs=Date.now();net.errors++;net.samples.push({url,latencyMs:performance.now()-start,ok:false,at:Date.now()});throw e}finally{net.active--}};
function $(id){return document.getElementById(id)}
function activeTf(){return document.querySelector('[data-tf].active')?.dataset.tf||new URLSearchParams(location.search).get('tf')||'4h'}
function symbol(){return String($('symbol')?.value||'BTCUSDT').trim().toUpperCase()}
function candlesFor(s,tf){return net.structures.get(`${s}:${tf}`)?.data?.candles||[]}
function scoreFromDom(){const t=$('snapshotNarrative')?.textContent||'';const m=t.match(/(?:패턴\s*점수|신뢰도)\s*(\d+(?:\.\d+)?)/);return m?Math.max(0,Math.min(100,Number(m[1]))):null}
function biasFromDom(){const t=$('snapshotScenario')?.textContent||'';if(/약세/.test(t))return'bearish';if(/강세/.test(t))return'bullish';return'neutral'}
function patternFromDom(){const t=$('snapshotNarrative')?.textContent||'';const names=['Falling Wedge','falling wedge','하락 쐐기','상승 쐐기','상승 채널','하락 채널','수평 채널','Triangle','Double Top','Double Bottom'];return names.find(x=>t.includes(x))||'none'}
function resolvePrior(s,tf,candles){if(!candles.length)return;const rows=O.list({symbol:s,tf});for(const row of rows){const snap=row.snapshot;if(!snap||!Number.isFinite(Number(snap.asOfTime))||!Number.isFinite(Number(snap.entryPrice)))continue;let i=candles.findIndex(c=>Number(c.time??c.openTime??c.closeTime)>=Number(snap.asOfTime));if(i<0)continue;for(const h of [5,10,20]){if(row.outcomes?.[String(h)]||!candles[i+h])continue;const exit=Number(candles[i+h].close);if(!Number.isFinite(exit))continue;const raw=(exit-Number(snap.entryPrice))/Number(snap.entryPrice)*100,success=snap.bias==='bearish'?raw<0:snap.bias==='bullish'?raw>0:false;O.attachOutcome(snap.id,h,{success,returnPct:raw,exitPrice:exit,exitTime:Number(candles[i+h].time??candles[i+h].closeTime)||null});}}}
function ensureUi(){if($('signalQuality'))return;const style=document.createElement('style');style.textContent='.qualityGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:8px 0 10px}.qualityCard{background:#0b1622;border:1px solid #20334a;border-radius:10px;padding:9px;min-width:0}.qualityCard small{display:block;color:#8096af;font-size:9px;margin-bottom:4px}.qualityCard b{font-size:12px;overflow-wrap:anywhere}.qualityCard .subq{font-size:9px;color:#8ea4bb;margin-top:4px;line-height:1.45}.evidenceDetails{margin-top:6px;border-top:1px solid #1d3146;padding-top:5px;color:#8ea4bb;font-size:9px}.evidenceDetails summary{cursor:pointer;color:#9fb4c9}.evidenceDetails div{margin-top:4px;line-height:1.55}.qok{color:#2fd6a1}.qwarn{color:#ffc45f}.qbad{color:#ff6677}@media(max-width:650px){.qualityGrid{grid-template-columns:1fr 1fr}.qualityCard{padding:8px}}';document.head.appendChild(style);const root=document.createElement('section');root.id='signalQuality';root.className='qualityGrid';root.innerHTML='<div class="qualityCard"><small>DATA</small><b id="qData">대기</b><div class="subq" id="qDataSub">데이터 무결성 확인 전</div></div><div class="qualityCard"><small>CALIBRATION</small><b id="qCal">수집 중</b><div class="subq" id="qCalSub">검증 표본 없음</div></div><div class="qualityCard"><small>REGIME</small><b id="qRegime">미확정</b><div class="subq" id="qRegimeSub">단순 레짐</div></div><div class="qualityCard"><small>STATE</small><b id="qState">OBSERVE</b><div class="subq" id="qStateSub">조건 확인 전</div><details class="evidenceDetails"><summary>근거 보기</summary><div id="qEvidence">구조 방향 — · Flow 데이터 — · 패턴 점수 —</div></details></div>';const controls=document.querySelector('.controls');controls?.insertAdjacentElement('afterend',root)}
let alertState={state:'OBSERVE'};
function render(){ensureUi();const s=symbol(),tf=activeTf(),entry=net.structures.get(`${s}:${tf}`),stats=D.summarize(net.samples),now=Date.now(),ageMs=entry?.fetchedAtMs?Math.max(0,now-entry.fetchedAtMs):null,integrity=D.deriveFeedState({nowMs:now,lastReceiveMs:entry?.fetchedAtMs||net.lastOkMs,staleAfterMs:D.staleAfter({kind:'kline',tf}),error:!entry&&net.lastErrorMs&&now-net.lastErrorMs<10000});const cls=integrity==='live'?'qok':integrity==='delayed'?'qwarn':'qbad';$('qData').className=cls;$('qData').textContent=integrity.toUpperCase();$('qDataSub').textContent=`${entry?'Binance/structure':'source 대기'} · age ${ageMs==null?'—':(ageMs/1000).toFixed(1)+'s'} · avg ${stats.avgLatencyMs==null?'—':Math.round(stats.avgLatencyMs)+'ms'} · errors ${net.errors}`;
const candles=candlesFor(s,tf),reg=R.classifyRegime(candles);$('qRegime').textContent=reg.available?`${reg.trend.toUpperCase()} · VOL ${reg.volatility.toUpperCase()}`:'INSUFFICIENT';$('qRegimeSub').textContent=reg.available?`Liquidity ${reg.liquidity}`:'최소 30개 캔들 필요';
const samples=O.resolvedSamples({horizon:'20',symbol:s,tf}),cal=C.report(samples,{minSamples:30}),score=scoreFromDom();$('qCal').textContent=cal.available?`${Math.round(cal.probability*100)}% · N=${cal.n}`:`수집 중 · N=${cal.n}`;$('qCalSub').textContent=cal.available?`Brier ${cal.brier.toFixed(3)} · ECE ${cal.ece.toFixed(3)} · pattern ${score==null?'없음':score}`:'확률 표시 보류 · raw 숨김';
const flowOk=!/없음/.test($('snapshotFlow')?.textContent||'없음'),bias=biasFromDom(),structureOk=bias!=='neutral',patternOk=score!=null,met=(structureOk?1:0)+(flowOk?1:0)+(patternOk?1:0),gatedMet=cal.available?met:Math.min(met,1);alertState=A.transition(alertState,{integrityState:integrity,conditionsMet:gatedMet,conditionsTotal:3,calibrationReady:cal.available});$('qState').textContent=alertState.state;$('qState').className=alertState.state==='NO_SIGNAL'?'qbad':alertState.state==='ARMED'||alertState.state==='WATCH'?'qwarn':'qok';$('qStateSub').textContent=cal.available?`evidence ${met}/3 · ${alertState.state==='NO_SIGNAL'?'INSUFFICIENT EVIDENCE':'자동 주문 없음'}`:`calibration pending · evidence ${met}/3 · ARMED 차단 · 자동 주문 없음`;$('qEvidence').innerHTML=`구조 방향 ${structureOk?'✓':'—'} · ${bias}<br>Flow 데이터 ${flowOk?'✓':'—'}<br>패턴 점수 ${patternOk?'✓ '+score:'— 없음'}`;
}
function capture(){const s=symbol(),tf=activeTf(),entry=net.structures.get(`${s}:${tf}`),candles=entry?.data?.candles||[];if(!candles.length){render();return}resolvePrior(s,tf,candles);const last=candles.at(-1),price=Number(last?.close),asOfTime=Number(last?.time??last?.openTime??last?.closeTime),score=scoreFromDom();O.recordSnapshot({symbol:s,tf,asOfTime:Number.isFinite(asOfTime)?asOfTime:Date.now(),entryPrice:Number.isFinite(price)?price:null,modelScore:Number.isFinite(score)?score:null,bias:biasFromDom(),pattern:patternFromDom(),dataSource:'structure-api',provenance:D.provenance({source:'Binance/structure',market:'spot/fallback',fetchedAtMs:entry?.fetchedAtMs,latencyMs:entry?.latencyMs,state:'live'})});render()}
function install(){ensureUi();const status=$('snapshotStatus');if(status)new MutationObserver(()=>{const t=status.textContent||'';if(/^완료/.test(t))setTimeout(capture,0);else render()}).observe(status,{childList:true,subtree:true,characterData:true});setInterval(render,5000);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
