(()=>{'use strict';
const D=window.PulseDataIntegrity,K=window.PulseClockIntegrity,O=window.PulseOutcomeRecorder,C=window.PulseCalibration,R=window.PulseRegime,A=window.PulseAlertState,M=window.PulseMicrostructure,X=window.PulseDriftMonitor;
if(!D||!K||!O||!C||!R||!A||!M||!X)return;
const net={samples:[],lastOkMs:null,lastErrorMs:null,errors:0,structures:new Map(),clock:new Map(),health:new Map(),active:0};
const rawFetch=window.fetch.bind(window);
function keyOf(symbol,tf){return `${symbol}:${tf}`}
function candleEventTime(c){return Number(c?.closeTime??c?.time??c?.openTime)||null}
function observeStructure(symbol,tf,data,receiveTimeMs,latencyMs,url){const key=keyOf(symbol,tf),candles=Array.isArray(data?.candles)?data.candles:[],last=candles.at(-1),eventTimeMs=candleEventTime(last),step=D.tfMs(tf),sequence=eventTimeMs!=null?Math.floor(eventTimeMs/step):null,prevClock=net.clock.get(key)||K.createClockState(),nextClock=K.observeEvent(prevClock,{eventTimeMs,receiveTimeMs,sequence}),gapDelta=Math.max(0,nextClock.gapCount-(prevClock.gapCount||0));net.clock.set(key,nextClock);let health=net.health.get(key)||D.createFeedHealth();health=D.noteFeedEvent(health,{state:'live',atMs:receiveTimeMs,eventTimeMs,receiveTimeMs,gapCount:gapDelta});net.health.set(key,health);net.structures.set(key,{data,fetchedAtMs:receiveTimeMs,receiveTimeMs,eventTimeMs,latencyMs,url,sequence});}
window.fetch=async function(input,init){const url=String(typeof input==='string'?input:input?.url||''),start=performance.now();net.active++;try{const res=await rawFetch(input,init),latency=performance.now()-start,ok=res.ok,at=Date.now();net.samples.push({url,latencyMs:latency,ok,at});net.samples=net.samples.slice(-120);if(ok)net.lastOkMs=at;else{net.lastErrorMs=at;net.errors++}if(/\/api\/structure\?/.test(url)){try{const u=new URL(url,location.origin),tf=u.searchParams.get('interval')||'4h',symbol=(u.searchParams.get('symbol')||'BTCUSDT').toUpperCase(),key=keyOf(symbol,tf);if(ok){const data=await res.clone().json();observeStructure(symbol,tf,data,at,latency,url)}else{const h=net.health.get(key)||D.createFeedHealth();net.health.set(key,D.noteFeedEvent(h,{state:'failed',atMs:at}))}}catch{}}return res}catch(e){const at=Date.now();net.lastErrorMs=at;net.errors++;net.samples.push({url,latencyMs:performance.now()-start,ok:false,at});if(/\/api\/structure\?/.test(url)){try{const u=new URL(url,location.origin),tf=u.searchParams.get('interval')||'4h',symbol=(u.searchParams.get('symbol')||'BTCUSDT').toUpperCase(),key=keyOf(symbol,tf),h=net.health.get(key)||D.createFeedHealth();net.health.set(key,D.noteFeedEvent(h,{state:'failed',atMs:at}))}catch{}}throw e}finally{net.active--}};
function $(id){return document.getElementById(id)}
function activeTf(){return document.querySelector('[data-tf].active')?.dataset.tf||new URLSearchParams(location.search).get('tf')||'4h'}
function symbol(){return String($('symbol')?.value||'BTCUSDT').trim().toUpperCase()}
function candlesFor(s,tf){return net.structures.get(keyOf(s,tf))?.data?.candles||[]}
function scoreFromDom(){const t=$('snapshotNarrative')?.textContent||'',m=t.match(/(?:패턴\s*점수|신뢰도)\s*(\d+(?:\.\d+)?)/);return m?Math.max(0,Math.min(100,Number(m[1]))):null}
function biasFromDom(){const t=$('snapshotScenario')?.textContent||'';if(/약세/.test(t))return'bearish';if(/강세/.test(t))return'bullish';return'neutral'}
function patternFromDom(){const t=$('snapshotNarrative')?.textContent||'',names=['Falling Wedge','falling wedge','하락 쐐기','상승 쐐기','상승 채널','하락 채널','수평 채널','Triangle','Double Top','Double Bottom'];return names.find(x=>t.includes(x))||'none'}
function parseFlow(){const t=$('snapshotFlow')?.textContent||'',fund=t.match(/funding\s*([+-]?\d+(?:\.\d+)?)%/i),taker=t.match(/taker\s*(\d+(?:\.\d+)?)×/i),oi=t.match(/\(([+-]?\d+(?:\.\d+)?)%\s*24h\)/i);return{fundingPct:fund?Number(fund[1]):null,takerRatio:taker?Number(taker[1]):null,oiAccelerationPct:oi?Number(oi[1]):null}}
function cexFeaturesFromDom(){const f=parseFlow(),ratio=f.takerRatio,takerBuy=ratio!=null?ratio:0,takerSell=ratio!=null?1:0;return M.cexFeatures({takerBuy,takerSell,oiAccelerationPct:f.oiAccelerationPct,fundingPct:f.fundingPct})}
function regimeKey(reg){return reg?.available?`${reg.trend}:${reg.volatility}:${reg.liquidity}`:'unknown'}
function resolvePrior(s,tf,candles){if(!candles.length)return;const rows=O.list({symbol:s,tf}),horizons=O.HORIZONS||[5,10,20,50];for(const row of rows){const snap=row.snapshot;if(!snap||!Number.isFinite(Number(snap.asOfTime))||!Number.isFinite(Number(snap.entryPrice)))continue;let i=candles.findIndex(c=>Number(c.time??c.openTime??c.closeTime)>=Number(snap.asOfTime));if(i<0)continue;for(const h of horizons){if(row.outcomes?.[String(h)]||!candles[i+h])continue;const exit=Number(candles[i+h].close);if(!Number.isFinite(exit))continue;const raw=(exit-Number(snap.entryPrice))/Number(snap.entryPrice)*100,success=snap.bias==='bearish'?raw<0:snap.bias==='bullish'?raw>0:false;O.attachOutcome(snap.id,h,{success,returnPct:raw,exitPrice:exit,exitTime:Number(candles[i+h].time??candles[i+h].closeTime)||null});}}}
function ensureUi(){if($('signalQuality'))return;const style=document.createElement('style');style.textContent='.qualityGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:8px 0 10px}.qualityCard{background:#0b1622;border:1px solid #20334a;border-radius:10px;padding:9px;min-width:0}.qualityCard small{display:block;color:#8096af;font-size:9px;margin-bottom:4px}.qualityCard b{font-size:12px;overflow-wrap:anywhere}.qualityCard .subq{font-size:9px;color:#8ea4bb;margin-top:4px;line-height:1.45}.evidenceDetails{margin-top:6px;border-top:1px solid #1d3146;padding-top:5px;color:#8ea4bb;font-size:9px}.evidenceDetails summary{cursor:pointer;color:#9fb4c9}.evidenceDetails div{margin-top:4px;line-height:1.55;overflow-wrap:anywhere}.qok{color:#2fd6a1}.qwarn{color:#ffc45f}.qbad{color:#ff6677}@media(max-width:650px){.qualityGrid{grid-template-columns:1fr 1fr}.qualityCard{padding:8px}}';document.head.appendChild(style);const root=document.createElement('section');root.id='signalQuality';root.className='qualityGrid';root.innerHTML='<div class="qualityCard"><small>DATA</small><b id="qData">대기</b><div class="subq" id="qDataSub">데이터 무결성 확인 전</div><details class="evidenceDetails"><summary>출처 · Clock</summary><div id="qProvenance">source 대기</div><div id="qClock">clock 대기</div></details></div><div class="qualityCard"><small>CALIBRATION</small><b id="qCal">수집 중</b><div class="subq" id="qCalSub">검증 표본 없음</div><details class="evidenceDetails"><summary>검증 상세</summary><div id="qCalDetail">Brier/ECE 대기</div><div id="qDrift">Drift insufficient</div></details></div><div class="qualityCard"><small>REGIME</small><b id="qRegime">미확정</b><div class="subq" id="qRegimeSub">단순 레짐</div></div><div class="qualityCard"><small>STATE</small><b id="qState">OBSERVE</b><div class="subq" id="qStateSub">조건 확인 전</div><details class="evidenceDetails"><summary>근거 보기</summary><div id="qEvidence">구조 방향 — · Flow 데이터 — · 패턴 점수 —</div></details></div>';document.querySelector('.controls')?.insertAdjacentElement('afterend',root)}
let alertState={state:'OBSERVE'};
function render(){ensureUi();const s=symbol(),tf=activeTf(),key=keyOf(s,tf),entry=net.structures.get(key),stats=D.summarize(net.samples),clock=K.summarizeClock(net.clock.get(key)||{}),health=net.health.get(key)||D.createFeedHealth(),now=Date.now(),ageMs=entry?.receiveTimeMs?Math.max(0,now-entry.receiveTimeMs):null,integrity=D.deriveFeedState({nowMs:now,lastEventMs:entry?.eventTimeMs,lastReceiveMs:entry?.receiveTimeMs||net.lastOkMs,staleAfterMs:D.staleAfter({kind:'kline',tf}),error:!entry&&net.lastErrorMs&&now-net.lastErrorMs<10000,connectionState:health.state==='reconnecting'?'reconnecting':undefined,backfillPending:health.state==='backfill',verifying:health.state==='verifying'}),cls=integrity==='live'?'qok':integrity==='delayed'?'qwarn':'qbad';$('qData').className=cls;$('qData').textContent=integrity.toUpperCase();$('qDataSub').textContent=`${entry?'Binance/structure':'source 대기'} · ${ageMs==null?'—':(ageMs/1000).toFixed(1)+'s'} · gaps ${health.gapCount||0} · errors ${net.errors}`;const prov=D.provenance({source:entry?'Binance/structure':'unknown',market:'cex',fetchedAtMs:entry?.fetchedAtMs,eventTimeMs:entry?.eventTimeMs,receiveTimeMs:entry?.receiveTimeMs,latencyMs:entry?.latencyMs,state:integrity,fallback:'REST',sequence:entry?.sequence,url:entry?.url});$('qProvenance').textContent=`source ${prov.source} · market ${prov.market} · fallback ${prov.fallback||'none'} · latency ${prov.latencyMs==null?'—':Math.round(prov.latencyMs)+'ms'} · recv ${prov.receiveTimeMs||'—'}`;$('qClock').textContent=`clock delay ${clock.lastDelayMs==null?'—':Math.round(clock.lastDelayMs)+'ms'} · p95 ${clock.p95DelayMs==null?'—':Math.round(clock.p95DelayMs)+'ms'} · out-of-order ${clock.outOfOrderCount||0} · gaps ${clock.gapCount||0} · reconnect ${health.reconnectCount||0} · backfilled ${health.backfilledBars||0}`;
const candles=candlesFor(s,tf),reg=R.classifyRegime(candles),regime=regimeKey(reg);$('qRegime').textContent=reg.available?`${reg.trend.toUpperCase()} · VOL ${reg.volatility.toUpperCase()}`:'INSUFFICIENT';$('qRegimeSub').textContent=reg.available?`Liquidity ${reg.liquidity}`:'최소 30개 캔들 필요';
const pattern=patternFromDom(),samples=O.resolvedSamples({horizon:'20',symbol:s,tf}),segSamples=O.resolvedSamples({horizon:'20',symbol:s,tf,pattern,regime}),cal=C.report(samples,{minSamples:30,adequateSamples:100,confidence:.9}),score=scoreFromDom(),ci=cal.ci?`${Math.round(cal.ci.low*100)}–${Math.round(cal.ci.high*100)}%`:'—';$('qCal').textContent=cal.available?`${Math.round(cal.probability*100)}% · N=${cal.n}`:`수집 중 · N=${cal.n}`;$('qCalSub').textContent=cal.available?`${cal.status} · CI90 ${ci} · pattern ${score==null?'없음':score}`:'확률 표시 보류 · raw 숨김';$('qCalDetail').textContent=`status ${cal.status||'insufficient'} · CI90 ${ci} · Brier ${cal.brier==null?'—':cal.brier.toFixed(3)} · ECE ${cal.ece==null?'—':cal.ece.toFixed(3)} · P@20 ${cal.precisionTop20==null?'—':(cal.precisionTop20*100).toFixed(1)+'%'} · conditional N=${segSamples.length}`;
const driftRows=samples.map(x=>({atMs:x.atMs,featureValue:x.features?.oiAccelerationPct,outcome:x.outcome})).filter(x=>Number.isFinite(Number(x.featureValue))&&Number.isFinite(Number(x.atMs))),drift=X.compareContribution(driftRows,{nowMs:now,recentDays:30,historyDays:180,minRecent:20,minHistorical:50,warningDrop:.25});$('qDrift').textContent=drift.status==='insufficient'?`Drift insufficient · recent ${drift.recentN||0} / historical ${drift.historicalN||0}`:`Drift ${drift.status} · recent ${(drift.recentContribution||0).toFixed(2)} / historical ${(drift.historicalContribution||0).toFixed(2)}`;
const flowOk=!/없음/.test($('snapshotFlow')?.textContent||'없음'),bias=biasFromDom(),structureOk=bias!=='neutral',patternOk=score!=null,met=(structureOk?1:0)+(flowOk?1:0)+(patternOk?1:0),gatedMet=cal.available?met:Math.min(met,1),reason=[structureOk?'structure':null,flowOk?'flow':null,patternOk?'pattern':null].filter(Boolean).join('+')||'insufficient';alertState=A.transition(alertState,{integrityState:integrity,conditionsMet:gatedMet,conditionsTotal:3,calibrationReady:cal.available,reason});$('qState').textContent=alertState.state;$('qState').className=alertState.state==='NO_SIGNAL'?'qbad':alertState.state==='ARMED'||alertState.state==='WATCH'?'qwarn':'qok';$('qStateSub').textContent=cal.available?`evidence ${met}/3 · ${alertState.state==='NO_SIGNAL'?'INSUFFICIENT EVIDENCE':'자동 주문 없음'}`:`calibration pending · evidence ${met}/3 · ARMED 차단 · 자동 주문 없음`;const micro=cexFeaturesFromDom();$('qEvidence').innerHTML=`구조 방향 ${structureOk?'✓':'—'} · ${bias}<br>Flow 데이터 ${flowOk?'✓':'—'}<br>패턴 점수 ${patternOk?'✓ '+score:'— 없음'}<br>CEX micro · taker ${micro.takerImbalance==null?'—':micro.takerImbalance.toFixed(2)} · OIΔ ${micro.oiAccelerationPct==null?'—':micro.oiAccelerationPct+'%'} · funding ${micro.fundingPct==null?'—':micro.fundingPct+'%'}`;
}
function capture(){const s=symbol(),tf=activeTf(),key=keyOf(s,tf),entry=net.structures.get(key),candles=entry?.data?.candles||[];if(!candles.length){render();return}resolvePrior(s,tf,candles);const last=candles.at(-1),price=Number(last?.close),asOfTime=Number(last?.time??last?.openTime??last?.closeTime),score=scoreFromDom(),reg=R.classifyRegime(candles),features=cexFeaturesFromDom(),clock=K.summarizeClock(net.clock.get(key)||{}),health=net.health.get(key)||D.createFeedHealth();O.recordSnapshot({symbol:s,tf,asOfTime:Number.isFinite(asOfTime)?asOfTime:Date.now(),entryPrice:Number.isFinite(price)?price:null,modelScore:Number.isFinite(score)?score:null,bias:biasFromDom(),pattern:patternFromDom(),regime:regimeKey(reg),venue:'cex',flow:parseFlow(),features,dataSource:'structure-api',integrity:{clock,health},provenance:D.provenance({source:'Binance/structure',market:'cex',fetchedAtMs:entry?.fetchedAtMs,eventTimeMs:entry?.eventTimeMs,receiveTimeMs:entry?.receiveTimeMs,latencyMs:entry?.latencyMs,state:'live',fallback:'REST',sequence:entry?.sequence,url:entry?.url})});render()}
function install(){ensureUi();const status=$('snapshotStatus');if(status)new MutationObserver(()=>{const t=status.textContent||'';if(/^완료/.test(t))setTimeout(capture,0);else render()}).observe(status,{childList:true,subtree:true,characterData:true});setInterval(render,5000);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
