const finite=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):0));
function aggregateMarketFlow({dexFlows=[],cexFlows=[],onchainThemeFlows=[],themeForMarket=()=> 'Other / Unclassified',previous={}}={}){
  const tokens=new Map();
  const touch=(base)=>{const k=String(base||'').toUpperCase();if(!k)return null;if(!tokens.has(k))tokens.set(k,{baseAsset:k,dex5m:0,dex1h:0,dex24h:0,cex24h:0,dexNetBuyUsdEstimate:0,dexMarkets:0,cexMarkets:0,activityScores:[],themes:new Set(),venueVolume:{},has5m:false,has1h:false,has24h:false});return tokens.get(k)};
  for(const r of dexFlows){const t=touch(r.baseAsset);if(!t)continue;const v5=finite(r.volume5mUsd),v1=finite(r.volume1hUsd),v24=finite(r.volume24hUsd);if(v5!=null){t.dex5m+=v5;t.has5m=true}if(v1!=null){t.dex1h+=v1;t.has1h=true}if(v24!=null){t.dex24h+=v24;t.has24h=true}t.dexNetBuyUsdEstimate+=finite(r.netBuyUsdEstimate)??0;t.dexMarkets++;if(finite(r.activityScore)!=null)t.activityScores.push(Number(r.activityScore));t.themes.add(themeForMarket(r));}
  for(const r of cexFlows){const t=touch(r.baseAsset);if(!t)continue;const v=finite(r.quoteVolumeUsd);if(v!=null){t.cex24h+=v;t.has24h=true}t.cexMarkets++;t.venueVolume[r.venue]=(t.venueVolume[r.venue]||0)+(v||0);t.themes.add(themeForMarket(r));}
  const tokenFlows=[];for(const t of tokens.values()){const total1h=t.dex1h,total24=t.dex24h+t.cex24h,topVenue=Object.entries(t.venueVolume).sort((a,b)=>b[1]-a[1])[0];tokenFlows.push({baseAsset:t.baseAsset,theme:[...t.themes][0]||'Other / Unclassified',activity5mUsd:t.has5m?t.dex5m:null,activity1hUsd:t.has1h?t.dex1h:null,activity4hUsd:null,activity24hUsd:t.has24h?total24:null,dexVolumeUsd:t.has1h?t.dex1h:null,cexVolumeUsd:t.cex24h||null,dexNetBuyUsdEstimate:t.dexMarkets?t.dexNetBuyUsdEstimate:null,dexContributionShare:total24?t.dex24h/total24:null,cexContributionShare:total24?t.cex24h/total24:null,activeMarketCount:t.dexMarkets+t.cexMarkets,venueConcentration:topVenue&&t.cex24h?topVenue[1]/t.cex24h:null,avgActivityScore:t.activityScores.length?t.activityScores.reduce((a,b)=>a+b,0)/t.activityScores.length:null});}
  const byTheme=new Map();for(const t of tokenFlows){const k=t.theme||'Other / Unclassified';if(!byTheme.has(k))byTheme.set(k,[]);byTheme.get(k).push(t)}
  const onchainMap=new Map(onchainThemeFlows.map(x=>[x.theme,x]));const themeFlows=[];let grand=0;for(const [theme,rows] of byTheme){const dex=rows.reduce((s,r)=>s+(r.dexVolumeUsd||0),0),cex=rows.reduce((s,r)=>s+(r.cexVolumeUsd||0),0),a5=rows.some(r=>r.activity5mUsd!=null)?rows.reduce((s,r)=>s+(r.activity5mUsd||0),0):null,a1=rows.some(r=>r.activity1hUsd!=null)?rows.reduce((s,r)=>s+(r.activity1hUsd||0),0):null,a24=rows.some(r=>r.activity24hUsd!=null)?rows.reduce((s,r)=>s+(r.activity24hUsd||0),0):null;grand+=(a24??a1??0);themeFlows.push({theme,activity5mUsd:a5,activity1hUsd:a1,activity4hUsd:null,activity24hUsd:a24,dexVolumeUsd:dex||null,cexVolumeUsd:cex||null,dexActivityShare:null,cexActivityShare:null,activeMarketCount:rows.reduce((s,r)=>s+r.activeMarketCount,0),breadth:rows.length,concentrationShare:0,dexNetBuyUsdEstimate:rows.some(r=>r.dexNetBuyUsdEstimate!=null)?rows.reduce((s,r)=>s+(r.dexNetBuyUsdEstimate||0),0):null,onchainNetFlowUsd:finite(onchainMap.get(theme)?.netFlow1hUsd),rotationScore:0});}
  for(const t of themeFlows){const total=(t.activity24hUsd??t.activity1hUsd??0);const split=(t.dexVolumeUsd||0)+(t.cexVolumeUsd||0);t.dexActivityShare=split?(t.dexVolumeUsd||0)/split:null;t.cexActivityShare=split?(t.cexVolumeUsd||0)/split:null;t.concentrationShare=grand?total/grand:0;const prev=previous[t.theme]||{},prevTotal=finite(prev.totalActivityUsd),change=prevTotal&&prevTotal>0?(total-prevTotal)/prevTotal:0;const breadthFactor=Math.min(1,t.breadth/6),flowBoost=t.dexNetBuyUsdEstimate==null?0:Math.min(1,Math.abs(t.dexNetBuyUsdEstimate)/Math.max(1,total))*.2;t.rotationScore=clamp(t.concentrationShare*55+breadthFactor*20+Math.min(1,Math.abs(change))*15+flowBoost*10);}
  themeFlows.sort((a,b)=>b.rotationScore-a.rotationScore);return{tokenFlows,themeFlows};
}
module.exports={aggregateMarketFlow};
