const finite=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):0));
function aggregateMarketFlow({dexFlows=[],cexFlows=[],onchainThemeFlows=[],themeForMarket=()=> 'Other / Unclassified',previous={}}={}){
  const tokens=new Map();
  const touch=(base)=>{const k=String(base||'').toUpperCase();if(!k)return null;if(!tokens.has(k))tokens.set(k,{baseAsset:k,dexVolumeUsd:0,cexVolumeUsd:0,dexNetBuyUsdEstimate:0,dexMarkets:0,cexMarkets:0,activityScores:[],themes:new Set(),venueVolume:{}});return tokens.get(k)};
  for(const r of dexFlows){const t=touch(r.baseAsset);if(!t)continue;const v=finite(r.volume1hUsd)??finite(r.volume5mUsd)??0;t.dexVolumeUsd+=v;t.dexNetBuyUsdEstimate+=finite(r.netBuyUsdEstimate)??0;t.dexMarkets++;if(finite(r.activityScore)!=null)t.activityScores.push(Number(r.activityScore));t.themes.add(themeForMarket(r));}
  for(const r of cexFlows){const t=touch(r.baseAsset);if(!t)continue;const v=finite(r.quoteVolumeUsd)??0;t.cexVolumeUsd+=v;t.cexMarkets++;t.venueVolume[r.venue]=(t.venueVolume[r.venue]||0)+v;t.themes.add(themeForMarket(r));}
  const tokenFlows=[];for(const t of tokens.values()){const total=t.dexVolumeUsd+t.cexVolumeUsd,topVenue=Object.entries(t.venueVolume).sort((a,b)=>b[1]-a[1])[0];tokenFlows.push({baseAsset:t.baseAsset,theme:[...t.themes][0]||'Other / Unclassified',dexVolumeUsd:t.dexVolumeUsd||null,cexVolumeUsd:t.cexVolumeUsd||null,dexNetBuyUsdEstimate:t.dexMarkets?t.dexNetBuyUsdEstimate:null,dexContributionShare:total?t.dexVolumeUsd/total:null,cexContributionShare:total?t.cexVolumeUsd/total:null,activeMarketCount:t.dexMarkets+t.cexMarkets,venueConcentration:topVenue&&t.cexVolumeUsd?topVenue[1]/t.cexVolumeUsd:null,avgActivityScore:t.activityScores.length?t.activityScores.reduce((a,b)=>a+b,0)/t.activityScores.length:null});}
  const byTheme=new Map();for(const t of tokenFlows){const k=t.theme||'Other / Unclassified';if(!byTheme.has(k))byTheme.set(k,[]);byTheme.get(k).push(t)}
  const onchainMap=new Map(onchainThemeFlows.map(x=>[x.theme,x]));const themeFlows=[];let grand=0;for(const [theme,rows] of byTheme){const dex=rows.reduce((s,r)=>s+(r.dexVolumeUsd||0),0),cex=rows.reduce((s,r)=>s+(r.cexVolumeUsd||0),0);grand+=dex+cex;themeFlows.push({theme,dexVolumeUsd:dex||null,cexVolumeUsd:cex||null,dexActivityShare:null,cexActivityShare:null,activeMarketCount:rows.reduce((s,r)=>s+r.activeMarketCount,0),breadth:rows.length,concentrationShare:0,dexNetBuyUsdEstimate:rows.some(r=>r.dexNetBuyUsdEstimate!=null)?rows.reduce((s,r)=>s+(r.dexNetBuyUsdEstimate||0),0):null,onchainNetFlowUsd:finite(onchainMap.get(theme)?.netFlow1hUsd),rotationScore:0});}
  for(const t of themeFlows){const total=(t.dexVolumeUsd||0)+(t.cexVolumeUsd||0);t.dexActivityShare=total?(t.dexVolumeUsd||0)/total:null;t.cexActivityShare=total?(t.cexVolumeUsd||0)/total:null;t.concentrationShare=grand?total/grand:0;const prev=previous[t.theme]||{},prevTotal=finite(prev.totalActivityUsd),change=prevTotal&&prevTotal>0?(total-prevTotal)/prevTotal:0;const breadthFactor=Math.min(1,t.breadth/6),flowBoost=t.dexNetBuyUsdEstimate==null?0:Math.min(1,Math.abs(t.dexNetBuyUsdEstimate)/Math.max(1,total))*.2;t.rotationScore=clamp(t.concentrationShare*55+breadthFactor*20+Math.min(1,Math.abs(change))*15+flowBoost*10);}
  themeFlows.sort((a,b)=>b.rotationScore-a.rotationScore);return{tokenFlows,themeFlows};
}
module.exports={aggregateMarketFlow};
