(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.PulseRadarCoinAnomaly=api;})(typeof window!=='undefined'?window:null,function(){
const STABLE=new Set(['USDT','USDC','FDUSD','TUSD','DAI','USDE','USDS','BUSD','PYUSD','FRAX','LUSD','USD1','USDT0','USDC.E','USDP','GUSD','USDD','USDJ','USDY','RLUSD','EURC','EURS','SUSD','CRVUSD','GHO']);
const finite=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):0));const upper=v=>String(v||'').toUpperCase().trim();const sourceName=v=>String(v||'').trim().toLowerCase();
function isAltcoinAsset(asset){let a=upper(asset);if(/^W(BTC|ETH)$/.test(a))a=a.slice(1);return !!a&&a!=='BTC'&&a!=='ETH'&&!STABLE.has(a)&&!/^USD[CT]?$/.test(a)&&!/^USDC(?:\.|-)/.test(a)&&!/^USDT(?:\.|-)/.test(a)}
function median(values){const a=(values||[]).map(finite).filter(v=>v!=null&&v>=0).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function ratioToBaseline(current,samples){const c=finite(current),b=median(samples);return c!=null&&b!=null&&b>0?c/b:null}
function weightedScore(parts){let num=0,den=0;for(const p of parts){if(p.value==null||!Number.isFinite(Number(p.value)))continue;num+=clamp(p.value)*p.weight;den+=p.weight}return den?clamp(num/den):0}
function volumeScore(r){r=finite(r);if(r==null||r<=0)return r==null?null:0;return clamp(20+Math.log2(r)*25)}
function sumPresent(rows,key){let sum=0,seen=false;for(const r of rows){const v=finite(typeof key==='function'?key(r):r?.[key]);if(v!=null){sum+=v;seen=true}}return seen?sum:null}
function weightedMean(rows,key,maxFresh=Infinity){let num=0,den=0;for(const r of rows){const v=finite(r?.[key]),fresh=finite(r?.freshnessMs),conf=finite(r?.confidence??r?.sourceConfidence)??70;if(v==null||(fresh!=null&&fresh>maxFresh)||conf<35)continue;const w=Math.max(.1,conf/100);num+=v*w;den+=w}return den?num/den:null}
function weightedDexBuyShare(rows){let buys=0,sells=0,hasCounts=false;for(const r of rows){const b=finite(r.buys5m),s=finite(r.sells5m);if(b!=null||s!=null){buys+=b||0;sells+=s||0;hasCounts=true}}if(hasCounts&&buys+sells>0)return buys/(buys+sells);let num=0,den=0;for(const r of rows){const share=finite(r.buyShare);if(share==null)continue;const w=Math.max(1,finite(r.volume5mUsd)??finite(r.volume1hUsd)??1);num+=share*w;den+=w}return den?num/den:null}
function venueStats(rows){const perVenueType=new Map();for(const r of rows){const venue=String(r.venue||'').trim();if(!venue)continue;const type=String(r.marketType||'spot'),k=`${venue}|${type}`,v=finite(r.quoteVolumeUsd);if(v==null)continue;perVenueType.set(k,Math.max(v,perVenueType.get(k)||0))}const byVenue=new Map();for(const [k,v] of perVenueType){const venue=k.split('|')[0];byVenue.set(venue,(byVenue.get(venue)||0)+v)}const total=[...byVenue.values()].reduce((a,b)=>a+b,0),top=Math.max(0,...byVenue.values());return{venues:new Set(byVenue.keys()),volumeByVenue:byVenue,totalVolume:total,concentration:total?top/total:null}}
function buildCoinFlows(input={}){const dex=input.dexFlows||[],cex=input.cexFlows||[],live=input.liveRows||[],deriv=input.derivativesFlows||[],micro=input.microstructureFlows||[],history=input.historyByAsset||{},onchain=input.onchainByAsset||{},themeForAsset=input.themeForAsset||(()=> 'Other / Unclassified');const map=new Map(),touch=a=>{a=upper(a);if(!a)return null;if(!map.has(a))map.set(a,{baseAsset:a,dex:[],cex:[],live:[],deriv:[],micro:[]});return map.get(a)};for(const r of dex){const t=touch(r.baseAsset);if(t)t.dex.push(r)}for(const r of cex){const t=touch(r.baseAsset);if(t)t.cex.push(r)}for(const r of live){const t=touch(r.baseAsset||String(r.symbol||'').replace(/(USDT|USDC|FDUSD|BTC|ETH)$/,''));if(t)t.live.push(r)}for(const r of deriv){const t=touch(r.baseAsset);if(t)t.deriv.push(r)}for(const r of micro){const t=touch(r.baseAsset);if(t)t.micro.push(r)}const out=[];for(const t of map.values()){
 const h=history[t.baseAsset]||{},dex5=sumPresent(t.dex,'volume5mUsd')??0,dex1h=sumPresent(t.dex,'volume1hUsd')??0,current1=sumPresent(t.live,'volumeDelta1m'),live5=sumPresent(t.live,'volumeDelta5m'),current5=live5??(dex5>0?dex5:null),current15=finite(h.current15m);let a1=ratioToBaseline(current1,h.volume1m),a5=ratioToBaseline(current5,h.volume5m),a15=ratioToBaseline(current15,h.volume15m);if(a5==null&&dex5>0&&dex1h>0)a5=dex5/(dex1h/12);
 const dexBuyShare=weightedDexBuyShare(t.dex),netBuy=sumPresent(t.dex,'netBuyUsdEstimate'),venue=venueStats(t.cex),venues=venue.venues,types=new Set([...t.cex.map(r=>r.marketType),...t.live.map(r=>r.marketType)].filter(Boolean)),spotFuturesAligned=types.has('spot')&&types.has('futures');
 const shortChanges=t.live.map(r=>finite(r.change1m)??finite(r.change5m)).filter(v=>v!=null).map(Math.abs),hasPriceChange=shortChanges.length>0,muted=hasPriceChange?Math.max(...shortChanges)<1.2:false,volValues=[a1,a5,a15].filter(v=>v!=null),strongestVol=volValues.length?Math.max(...volValues):null,priceVolumeDivergence=strongestVol!=null&&strongestVol>=2&&hasPriceChange&&muted;
 const liqs=[...t.live.map(r=>finite(r.liquidityImpulse??r.liquidityDelta5m)),...t.dex.map(r=>finite(r.liquidityImpulse))].filter(v=>v!=null),liquidityImpulse=liqs.length?liqs.reduce((a,b)=>a+b,0)/liqs.length:null,oc=onchain[t.baseAsset]||{},onchainNetFlowUsd=finite(oc.netFlow1hUsd??oc.netFlowUsd),onchainConfidence=finite(oc.confidence??oc.dataConfidence);
 const freshDeriv=t.deriv.filter(r=>(finite(r.freshnessMs)??0)<=120000&&(finite(r.confidence)??70)>=45),freshMicro=t.micro.filter(r=>(finite(r.freshnessMs)??0)<=45000&&(finite(r.confidence)??70)>=45);
 const openInterestChange5m=weightedMean(freshDeriv,'openInterestChange5m',120000),openInterestChange15m=weightedMean(freshDeriv,'openInterestChange15m',120000),fundingRate=weightedMean(freshDeriv,'fundingRate',120000),fundingZScore=weightedMean(freshDeriv,'fundingZScore',120000),longShortRatio=weightedMean(freshDeriv,'longShortRatio',120000),takerBuySellRatio=weightedMean(freshDeriv,'takerBuySellRatio',120000),fundingCrowdingScore=clamp(Math.max(Math.abs(fundingRate??0)/.001*55,Math.abs(fundingZScore??0)*18));
 const bookImbalance=weightedMean(freshMicro,'bookImbalance',45000),tradeImbalance=weightedMean(freshMicro,'tradeImbalance',45000),topSpreadBps=weightedMean(freshMicro,'topSpreadBps',45000),bidDepthUsd=sumPresent(freshMicro,'bidDepthUsd'),askDepthUsd=sumPresent(freshMicro,'askDepthUsd'),derivativesVenueBreadth=new Set(freshDeriv.map(r=>r.venue).filter(Boolean)).size;
 const derivActivity=(openInterestChange5m!=null&&Math.abs(openInterestChange5m)>=.15)||(openInterestChange15m!=null&&Math.abs(openInterestChange15m)>=.25)||(takerBuySellRatio!=null&&(takerBuySellRatio>=1.2||takerBuySellRatio<=.83)),microActivity=(bookImbalance!=null&&Math.abs(bookImbalance)>=.2)||(tradeImbalance!=null&&Math.abs(tradeImbalance)>=.2),crowdingRisk=(fundingRate!=null&&Math.abs(fundingRate)>=.0015)||(fundingZScore!=null&&Math.abs(fundingZScore)>=3)||(longShortRatio!=null&&(longShortRatio>=3||longShortRatio<=.33)),bookRisk=(topSpreadBps!=null&&topSpreadBps>=80)||((bidDepthUsd??Infinity)<5000&&(askDepthUsd??Infinity)<5000&&freshMicro.length>0);
 const hasDex=t.dex.length>0,liveSourceNames=new Set(t.live.map(r=>sourceName(r.venue||r.source)).filter(Boolean)),marketSourceNames=new Set([...Array.from(venues,sourceName),...liveSourceNames]);let independentSources=marketSourceNames.size+(hasDex?1:0)+(onchainNetFlowUsd!=null&&(onchainConfidence==null||onchainConfidence>=60)?1:0);if(independentSources===0&&t.live.length)independentSources=1;
 const families=new Set();if(venues.size||t.live.length)families.add('spot/cex');if(hasDex)families.add('dex');if(freshDeriv.length)families.add('derivatives');if(freshMicro.length)families.add('microstructure');if(onchainNetFlowUsd!=null&&(onchainConfidence==null||onchainConfidence>=60))families.add('onchain');
 const breadthValue=(venues.size||hasDex||spotFuturesAligned)?clamp(Math.max(0,venues.size-1)*30+(spotFuturesAligned?20:0)+(hasDex&&venues.size?25:hasDex?10:0)):null,buyValue=dexBuyShare==null?null:clamp(Math.max(0,dexBuyShare-.5)*200),divergenceValue=strongestVol==null||!hasPriceChange?null:(priceVolumeDivergence?clamp(45+(strongestVol-2)*15):0),liquidityValue=liquidityImpulse==null?null:clamp(Math.max(0,liquidityImpulse)*250),onchainValue=onchainNetFlowUsd==null?null:(onchainNetFlowUsd>0&&(onchainConfidence==null||onchainConfidence>=60)?clamp(Math.log10(onchainNetFlowUsd+1)*12):0),derivValue=!freshDeriv.length?null:clamp((Math.abs(openInterestChange5m??0)*120)+(Math.abs(openInterestChange15m??0)*60)+(takerBuySellRatio!=null?Math.abs(Math.log(takerBuySellRatio))*55:0)),microValue=!freshMicro.length?null:clamp(Math.abs(bookImbalance??0)*100+Math.abs(tradeImbalance??0)*100);
 const components=[{value:volumeScore(strongestVol),weight:24},{value:breadthValue,weight:14},{value:buyValue,weight:10},{value:divergenceValue,weight:10},{value:liquidityValue,weight:8},{value:onchainValue,weight:8},{value:derivValue,weight:16},{value:microValue,weight:10}];let anomalyScore=Math.round(weightedScore(components));if(families.size<2)anomalyScore=Math.min(anomalyScore,55);
 const dimensions={volume:strongestVol!=null&&strongestVol>=1.8,breadth:venues.size>=2||(hasDex&&venues.size>=1)||spotFuturesAligned,buy:dexBuyShare!=null&&dexBuyShare>=.62,divergence:priceVolumeDivergence,liquidity:liquidityImpulse!=null&&liquidityImpulse>.08,onchain:onchainNetFlowUsd!=null&&onchainNetFlowUsd>0&&(onchainConfidence==null||onchainConfidence>=60),derivatives:derivActivity,microstructure:microActivity},evidenceCount=Object.values(dimensions).filter(Boolean).length;
 const totalDexLiquidity=t.dex.reduce((s,r)=>s+Math.max(0,finite(r.liquidityUsd)||0),0),knownQuality=t.dex.map(r=>finite(r.sourceConfidence)).filter(v=>v!=null),thinDex=hasDex&&totalDexLiquidity>0&&totalDexLiquidity<5000,lowQuality=knownQuality.length>0&&knownQuality.every(v=>v<45),liquidityDrop=liquidityImpulse!=null&&liquidityImpulse<=-.25,extremeThinSide=dexBuyShare!=null&&(dexBuyShare>=.97||dexBuyShare<=.03)&&totalDexLiquidity>0&&totalDexLiquidity<50000,risk=thinDex||lowQuality||liquidityDrop||extremeThinSide||crowdingRisk||bookRisk;
 const nonCrowdingActivity=dimensions.volume||dimensions.breadth||dimensions.buy||dimensions.liquidity||dimensions.onchain||dimensions.derivatives||dimensions.microstructure;let signal='WATCH';if(risk)signal='RISK';else if(evidenceCount>=4&&families.size>=3&&anomalyScore>=78&&hasPriceChange&&!muted&&dimensions.volume)signal='SURGE';else if(evidenceCount>=3&&families.size>=2&&anomalyScore>=60&&nonCrowdingActivity)signal='PRE-SURGE';
 const reasons=[];if(dimensions.volume)reasons.push('거래량 이상');if(venues.size>=2)reasons.push(`${venues.size}개 CEX 동시 활성`);if(spotFuturesAligned)reasons.push('Spot/Futures 동시 활성');if(dimensions.buy)reasons.push('DEX 매수 우위');if(priceVolumeDivergence)reasons.push('가격 대비 거래량 선행');if(dimensions.liquidity)reasons.push('유동성 증가');if(dimensions.onchain)reasons.push('온체인 유입');if(derivActivity)reasons.push('파생시장 활동 교차확인');if(microActivity)reasons.push('호가/체결 활동 교차확인');if(crowdingRisk)reasons.push('파생시장 쏠림 과열');if(bookRisk)reasons.push('호가 유동성 위험');if(thinDex)reasons.push('DEX 유동성 얕음');if(liquidityDrop)reasons.push('유동성 급감');if(lowQuality)reasons.push('데이터 품질 낮음');
 const available=components.filter(x=>x.value!=null).length,coverage=available/components.length,sourceFactor=Math.min(1,families.size/4),confidence=Math.round(clamp(coverage*70+sourceFactor*30)),freshnessValues=[...freshDeriv,...freshMicro].map(r=>finite(r.freshnessMs)).filter(v=>v!=null),freshnessMs=freshnessValues.length?Math.max(...freshnessValues):null;
 out.push({baseAsset:t.baseAsset,theme:themeForAsset(t.baseAsset,t),anomalyScore,signal,volumeAnomaly1m:a1,volumeAnomaly5m:a5,volumeAnomaly15m:a15,dexNetBuyUsdEstimate:netBuy,dexBuyShare,cexVenueBreadth:venues.size,spotFuturesAligned,priceVolumeDivergence,liquidityImpulse,onchainNetFlowUsd,onchainConfidence,flowConcentration:venue.concentration,confidence,evidenceSourceCount:independentSources,availableDimensions:available,reasons,altcoin:isAltcoinAsset(t.baseAsset),openInterestChange5m,openInterestChange15m,fundingRate,fundingZScore,fundingCrowdingScore,longShortRatio,takerBuySellRatio,bookImbalance,topSpreadBps,tradeImbalance,derivativesVenueBreadth,evidenceCount,sourceFamilyCount:families.size,derivativesConfirmed:derivActivity&&freshDeriv.length>0,microstructureConfirmed:microActivity&&freshMicro.length>0,crowdingRisk,freshnessMs});
}return out.sort((a,b)=>b.anomalyScore-a.anomalyScore||b.confidence-a.confidence)}
return{STABLE,isAltcoinAsset,median,ratioToBaseline,weightedScore,volumeScore,buildCoinFlows};
});
