const QUOTES=['USDT','USDC','FDUSD','USD','PERP'];
const finite=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):0));
function baseFromSymbol(symbol=''){let s=String(symbol||'').toUpperCase().replace(/[-_/]/g,'');for(const q of QUOTES)if(s.endsWith(q)&&s.length>q.length)return s.slice(0,-q.length);return s;}
function normalizeTs(v,fallback=Date.now(),unit='ms'){const n=finite(v);if(n==null)return fallback;return unit==='s'?n*1000:n;}
function mean(a){return a.length?a.reduce((s,v)=>s+v,0)/a.length:null}
function stdev(a,m){if(a.length<2)return 0;const v=a.reduce((s,x)=>s+(x-m)**2,0)/a.length;return Math.sqrt(v)}
function atOrBefore(history,target){for(let i=history.length-1;i>=0;i--){const x=history[i];if(finite(x?.ts)!=null&&Number(x.ts)<=target&&finite(x?.value)!=null)return Number(x.value)}return null}
function deriveOiChanges(history=[],current,now=Date.now()){const c=finite(current);if(c==null)return{openInterestChange5m:null,openInterestChange15m:null};const list=(history||[]).filter(x=>finite(x?.ts)!=null&&finite(x?.value)!=null).sort((a,b)=>a.ts-b.ts);const p5=atOrBefore(list,now-5*60*1000),p15=atOrBefore(list,now-15*60*1000);const ch=p=>p!=null&&p!==0?(c-p)/p:null;return{openInterestChange5m:ch(p5),openInterestChange15m:ch(p15)}}
function fundingCrowding(rate,baselineSamples=[]){const r=finite(rate),a=(baselineSamples||[]).map(finite).filter(v=>v!=null);if(r==null)return{fundingZScore:null,crowdingScore:0};const m=mean(a);let z=null;if(m!=null){const sd=stdev(a,m);if(sd>0)z=(r-m)/sd}const absRate=Math.abs(r),rateScore=clamp(absRate/0.001*55),zScore=z==null?0:clamp(Math.abs(z)*18);return{fundingZScore:z,crowdingScore:clamp(rateScore+zScore)}}
function isFresh(record,now=Date.now(),maxAgeMs=120000){const updated=normalizeTs(record?.updatedAt??record?.timestamp??record?.time,NaN,record?.timestampUnit||'ms');return Number.isFinite(updated)&&now-updated>=0&&now-updated<=maxAgeMs}
function normalizeDerivativesEvidence(raw={},venue='Unknown',context={}){const now=context.now??Date.now(),symbol=String(raw.symbol??raw.instId??raw.market??raw.product_id??'').toUpperCase(),baseAsset=String(raw.baseAsset||baseFromSymbol(symbol)).toUpperCase();if(!baseAsset)return null;const updatedAt=normalizeTs(raw.updatedAt??raw.timestamp??raw.time??raw.ts,now,context.timestampUnit||'ms'),openInterest=finite(raw.openInterest??raw.open_interest??raw.openInterestValue??raw.oi),markPrice=finite(raw.markPrice??raw.indexPrice??raw.lastPrice??raw.price??raw.markPx??raw.idxPx);let openInterestUsd=finite(raw.openInterestUsd??raw.open_interest_usd??raw.openInterestValueUsd);if(openInterestUsd==null&&openInterest!=null&&markPrice!=null&&context.contractUnit!=='nonlinear')openInterestUsd=openInterest*markPrice;const fundingRate=finite(raw.fundingRate??raw.funding_rate??raw.fundingRateValue??raw.funding),longShortRatio=finite(raw.longShortRatio??raw.long_short_ratio??raw.buyRatio??raw.accountRatio),takerBuySellRatio=finite(raw.takerBuySellRatio??raw.taker_buy_sell_ratio??raw.buySellRatio??raw.buySellRatioValue);const oiDelta5=finite(raw.openInterestChange5m),oiDelta15=finite(raw.openInterestChange15m),fundingZ=finite(raw.fundingZScore),confidence=clamp(finite(raw.confidence??raw.sourceConfidence)??88),freshnessMs=Math.max(0,now-updatedAt);return{venue,symbol,baseAsset,marketType:String(raw.marketType||context.marketType||'perpetual'),openInterest,openInterestUsd,openInterestChange5m:oiDelta5,openInterestChange15m:oiDelta15,fundingRate,fundingZScore:fundingZ,longShortRatio,takerBuySellRatio,updatedAt,freshnessMs,confidence}}
module.exports={finite,clamp,baseFromSymbol,deriveOiChanges,fundingCrowding,isFresh,normalizeDerivativesEvidence};