const finite=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):0));
function baseFromSymbol(symbol=''){let s=String(symbol||'').toUpperCase().replace(/[-_/]/g,'');for(const q of ['USDT','USDC','FDUSD','USD','KRW'])if(s.endsWith(q)&&s.length>q.length)return s.slice(0,-q.length);return s}
function normalizeTs(v,fallback=Date.now()){const n=finite(v);if(n==null)return fallback;return n<1e12?n*1000:n}
function depthUsd(levels=[],limit=10){let sum=0,seen=false;for(const x of (levels||[]).slice(0,limit)){const p=finite(Array.isArray(x)?x[0]:x?.price),q=finite(Array.isArray(x)?x[1]:x?.size??x?.qty??x?.quantity);if(p==null||q==null)continue;sum+=p*q;seen=true}return seen?sum:null}
function bookMetrics({bids=[],asks=[],midPrice=null,depthLevels=10}={}){const bidDepthUsd=depthUsd(bids,depthLevels),askDepthUsd=depthUsd(asks,depthLevels),den=(bidDepthUsd??0)+(askDepthUsd??0),bookImbalance=bidDepthUsd!=null&&askDepthUsd!=null&&den>0?(bidDepthUsd-askDepthUsd)/den:null;const bestBid=finite(Array.isArray(bids?.[0])?bids[0][0]:bids?.[0]?.price),bestAsk=finite(Array.isArray(asks?.[0])?asks[0][0]:asks?.[0]?.price),mid=finite(midPrice)??(bestBid!=null&&bestAsk!=null?(bestBid+bestAsk)/2:null),topSpreadBps=bestBid!=null&&bestAsk!=null&&mid>0&&bestAsk>=bestBid?((bestAsk-bestBid)/mid)*10000:null;return{bidDepthUsd,askDepthUsd,bookImbalance,topSpreadBps}}
function normalizeSide(v){const s=String(v||'').toLowerCase();if(['buy','bid','b','buyer','up'].includes(s))return'buy';if(['sell','ask','s','seller','down'].includes(s))return'sell';return null}
function tradeMetrics(trades=[]){let buy=0,sell=0,buySeen=false,sellSeen=false;for(const t of trades||[]){const side=normalizeSide(t?.side??t?.type??t?.ask_bid??t?.S),p=finite(t?.price??t?.p??t?.trade_price),q=finite(t?.size??t?.qty??t?.q??t?.trade_volume);const notional=finite(t?.notionalUsd)??(p!=null&&q!=null?p*q:null);if(side==='buy'&&notional!=null){buy+=notional;buySeen=true}else if(side==='sell'&&notional!=null){sell+=notional;sellSeen=true}}const tradeBuyUsd=buySeen?buy:null,tradeSellUsd=sellSeen?sell:null,den=(tradeBuyUsd??0)+(tradeSellUsd??0),tradeImbalance=tradeBuyUsd!=null&&tradeSellUsd!=null&&den>0?(tradeBuyUsd-tradeSellUsd)/den:null;return{tradeBuyUsd,tradeSellUsd,tradeImbalance}}
function isFresh(record,now=Date.now(),maxAgeMs=30000){const ts=normalizeTs(record?.updatedAt??record?.timestamp??record?.time,NaN);return Number.isFinite(ts)&&now-ts>=0&&now-ts<=maxAgeMs}
function normalizeMicrostructureEvidence(raw={},venue='Unknown',context={}){const now=context.now??Date.now(),symbol=String(raw.symbol??raw.instId??raw.market??'').toUpperCase(),baseAsset=String(raw.baseAsset||baseFromSymbol(symbol)).toUpperCase();if(!baseAsset)return null;const updatedAt=normalizeTs(raw.updatedAt??raw.timestamp??raw.time??raw.ts,now),book=bookMetrics({bids:raw.bids||raw.orderbook?.bids||[],asks:raw.asks||raw.orderbook?.asks||[],midPrice:raw.midPrice,depthLevels:context.depthLevels??10}),trades=tradeMetrics(raw.trades||[]),bidDepthUsd=finite(raw.bidDepthUsd)??book.bidDepthUsd,askDepthUsd=finite(raw.askDepthUsd)??book.askDepthUsd,bookImbalance=finite(raw.bookImbalance)??book.bookImbalance,topSpreadBps=finite(raw.topSpreadBps)??book.topSpreadBps,tradeBuyUsd=finite(raw.tradeBuyUsd)??trades.tradeBuyUsd,tradeSellUsd=finite(raw.tradeSellUsd)??trades.tradeSellUsd,tradeImbalance=finite(raw.tradeImbalance)??trades.tradeImbalance;return{venue,symbol,baseAsset,bidDepthUsd,askDepthUsd,bookImbalance,topSpreadBps,tradeBuyUsd,tradeSellUsd,tradeImbalance,sampleWindowMs:finite(raw.sampleWindowMs)??finite(context.sampleWindowMs)??15000,updatedAt,freshnessMs:Math.max(0,now-updatedAt),confidence:clamp(finite(raw.confidence??raw.sourceConfidence)??88)}}
module.exports={finite,clamp,baseFromSymbol,bookMetrics,tradeMetrics,isFresh,normalizeMicrostructureEvidence};