(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseDanteCloud=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const PERIODS=[5,15,112,224,448],finite=v=>v!=null&&v!==''&&Number.isFinite(Number(v));
function average(values,p,type='SMA'){const out=Array(values.length).fill(null);let sum=0,previous=null;for(let i=0;i<values.length;i++){sum+=values[i];if(i>=p)sum-=values[i-p];if(i>=p-1){previous=type==='EMA'&&previous!=null?values[i]*2/(p+1)+previous*(1-2/(p+1)):sum/p;out[i]=previous;}}return out;}
function normalize(candles,asOf){const rows=candles.map(x=>Array.isArray(x)?{openTime:Number(x[0]),time:Number(x[0]),closeTime:Number(x[6]),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5]),quoteVolume:Number(x[7]),takerBuyQuote:x[10]==null?null:Number(x[10])}:x).filter(x=>x&&x.partial!==true&&finite(x.closeTime)&&Number(x.closeTime)<asOf&&['open','high','low','close','volume'].every(k=>finite(x[k]))).map(x=>({...x,openTime:Number(x.openTime??x.time),closeTime:Number(x.closeTime),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close),volume:Number(x.volume)})).sort((a,b)=>a.openTime-b.openTime);const unique=new Map(rows.map(x=>[x.openTime,x]));return [...unique.values()];}
function midpoint(c,i,p){if(i<p-1)return null;const w=c.slice(i-p+1,i+1);return(Math.max(...w.map(x=>x.high))+Math.min(...w.map(x=>x.low)))/2;}
function series(candles,{asOf=Date.now(),maType='SMA'}={}){const c=normalize(candles,asOf),close=c.map(x=>x.close),ma=Object.fromEntries(PERIODS.map(p=>[p,average(close,p,maType)]));const cloud=c.map((_,i)=>{const source=i-26,tenkan=midpoint(c,source,9),kijun=midpoint(c,source,26),a=tenkan==null||kijun==null?null:(tenkan+kijun)/2,b=midpoint(c,source,52),ft=midpoint(c,i,9),fk=midpoint(c,i,26),fa=ft==null||fk==null?null:(ft+fk)/2,fb=midpoint(c,i,52);return{a,b,top:a==null||b==null?null:Math.max(a,b),bottom:a==null||b==null?null:Math.min(a,b),kijun:fk,kijunAtSource:kijun,futureA:fa,futureB:fb,futureTop:fa==null||fb==null?null:Math.max(fa,fb)};});return{candles:c,ma,cloud};}
function analyze({candles=[],asOf=Date.now(),maType='SMA',timeframe='1d'}={}){if(!['SMA','EMA'].includes(maType))throw Error('maType must be SMA or EMA');const s=series(candles,{asOf,maType}),c=s.candles,i=c.length-1,last=c[i],ma=Object.fromEntries(PERIODS.map(p=>[p,s.ma[p][i]??null])),cloud=s.cloud[i]||{};const base={version:'DANTE_CLOUD_v1',timeframe,maType,bars:c.length,asOf,lastClosedCloseTime:last?.closeTime??null,price:last?.close??null,ma,cloud,matched:false,setup:null,stage:'대기',status:'OK',rvol:null,reasons:[],checks:{}};if(c.length<448)return{...base,status:'INSUFFICIENT_HISTORY',stage:'장기선 판정 불가',reasons:[`448개 확정봉 필요 · 현재 ${c.length}개`]};
const price=last.close,volMean=c.slice(i-20,i).reduce((a,x)=>a+x.volume,0)/20,rvol=volMean>0?last.volume/volMean:null,pct=(a,b)=>(a/b-1)*100,slope112=pct(ma[112],s.ma[112][i-5]),slope224=pct(ma[224],s.ma[224][i-5]);
const above112=c.slice(-3).every((x,j)=>x.close>s.ma[112][i-2+j]),above224=c.slice(-3).every((x,j)=>x.close>s.ma[224][i-2+j]),reverse=ma[112]<ma[224]&&ma[224]<ma[448],aligned=ma[112]>ma[224]&&ma[224]>ma[448],shortUp=ma[5]>ma[15]&&ma[5]>s.ma[5][i-3];
function latestCross(p){for(let j=i;j>=Math.max(p,i-20);j--)if(c[j].close>s.ma[p][j]&&c[j-1].close<=s.ma[p][j-1])return j;return -1;}
function rvolAt(j){const v=c.slice(j-20,j),m=v.reduce((a,x)=>a+x.volume,0)/v.length;return m>0?c[j].volume/m:null;}
const cross112=latestCross(112),cross224=latestCross(224);let crossCloud=-1;for(let j=i;j>=Math.max(78,i-20);j--)if(c[j].close>s.cloud[j].top&&c[j-1].close<=s.cloud[j-1].top){crossCloud=j;break;}
function retest(p,cross){if(cross<0||cross>=i)return false;return c.slice(Math.max(cross+1,i-4),i+1).some((x,k)=>{const j=Math.max(cross+1,i-4)+k;return x.low<=s.ma[p][j]*1.01&&x.close>=s.ma[p][j];})&&c.slice(cross+1).every((x,k)=>x.close>=s.ma[p][cross+1+k]*.995);}
const rebound=last.close>last.open&&last.close>c[i-1].high,higherLow=Math.min(...c.slice(-5).map(x=>x.low))>=Math.min(...c.slice(-10,-5).map(x=>x.low))*.995,high20=Math.max(...c.slice(-20).map(x=>x.high)),pullback=pct(price,high20),aboveCloud=price>cloud.top,cloudUp=cloud.a>cloud.b&&cloud.futureA>cloud.futureB;
const recentVol=cross112>=0?rvolAt(cross112):null,volDecline=c.slice(-4,-1).reduce((a,x)=>a+x.volume,0)/3<volMean,space224=pct(ma[224],price),nearSupport=Math.abs(pct(price,ma[112]))<=3||Math.abs(pct(price,cloud.top))<=3,trendHold=last.low<=Math.max(ma[112],cloud.top)*1.01&&price>=ma[112]&&aboveCloud;
const checks={above112,above224,reverse,aligned,shortUp,higherLow,aboveCloud,cloudUp,slope112,slope224,space224,pullback,volDecline,rebound,retest112:retest(112,cross112),retest224:retest(224,cross224),breakoutRvol:recentVol,cross112BarsAgo:cross112<0?null:i-cross112,cross224BarsAgo:cross224<0?null:i-cross224};
let setup=null,stage='대기',matched=false;
if(reverse&&above112&&price<ma[224]&&space224>=3&&slope112>=-1&&Math.abs(pct(price,ma[112]))<=8&&cross112>=0){setup='112 회복형';stage=checks.retest112&&rebound?'눌림 후 재상승':checks.retest112?'눌림 지지':'돌파 안착';matched=recentVol>=1.3&&higherLow&&shortUp;}
if(above224&&aboveCloud&&slope224>=-1&&cross224>=0&&crossCloud>=0&&Math.abs(cross224-crossCloud)<=3){setup='224·구름 전환형';stage=checks.retest224&&rebound?'눌림 후 재상승':checks.retest224?'눌림 지지':'동시 돌파 안착';matched=Math.max(rvolAt(cross224)||0,rvolAt(crossCloud)||0)>=1.3&&higherLow&&shortUp;}
if(aligned&&aboveCloud&&cloudUp&&pullback<=-5&&pullback>=-15&&nearSupport&&trendHold){setup='정배열 눌림형';stage=rebound?'눌림 후 재상승':'눌림 지지';matched=volDecline&&higherLow&&shortUp;}
const resistances=[{label:'224선',price:ma[224]},{label:'448선',price:ma[448]},{label:'현재 구름 상단',price:cloud.top},{label:'최근 20봉 고점',price:high20}].filter(x=>x.price>price).sort((a,b)=>a.price-b.price),support=setup==='224·구름 전환형'?Math.max(ma[224],cloud.top):setup==='정배열 눌림형'?Math.max(ma[112],cloud.top):ma[112];
return{...base,rvol,setup,stage,matched,checks,distance112Pct:pct(price,ma[112]),resistances,invalidBelow:support,structuralLow:Math.min(...c.slice(-5).map(x=>x.low)),reasons:[`112선 3봉 유지 ${above112?'충족':'미충족'}`,`현재 구름 ${aboveCloud?'위':price<cloud.bottom?'아래':'내부'}`,`112선 5봉 기울기 ${slope112.toFixed(2)}%`,`RVOL ${rvol==null?'N/A':rvol.toFixed(2)+'x'}`,setup?`${setup} · ${stage}`:'단테 전용 조건 미충족']};}
return{PERIODS,average,normalize,series,analyze};
});
