(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseDanteMethods=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const GUIDE='https://contents.premium.naver.com/jusikdante/jusikdante1/contents/240816140129199cf';
const methods=[
{id:'bowl224',name:'밥그릇·224 돌파',group:'스윙·중장기',automation:'자동',tf:['1D','1W'],summary:'장기간 장기이평 아래에서 눌린 뒤 224일선 부근을 회복·돌파하는 구조를 관찰한다.',setup:['장기간 224일선 아래 체류','장기 이평 기울기 둔화 또는 바닥 형성','224일선 접근·돌파','돌파 뒤 안착/눌림 확인','거래량·수급 보조 확인'],invalid:['224일선 재이탈 후 회복 실패','돌파 직후 대량 매도와 저점 갱신'],targets:['다음 장기 매물대','448일선 또는 전고점 구간'],sources:[{label:'공식 강의 목록',url:GUIDE},{label:'224일선 장기이평 강의',url:'https://contents.premium.naver.com/jusikdante/jusikdante1/contents/250416182609507fn'}]},
{id:'ma-hit',name:'이평때리기',group:'스윙',automation:'자동',tf:['1D','4H'],summary:'큰 하락 뒤 역배열 상태에서 112일선을 회복하고 다음 장기이평으로 확장하는 구조를 본다.',setup:['장기 이평 역배열','112일선 돌파·안착','112~224 이격 존재','224 돌파 시 448까지 다음 구간 관찰','거래량 동반 여부 확인'],invalid:['112일선 종가 재이탈','돌파 뒤 대량 매도와 구조 저점 붕괴'],targets:['224일선','224 안착 시 448일선'],sources:[{label:'이평때리기 공식 강의',url:'https://contents.premium.naver.com/jusikdante/jusikdante1/contents/250401154145712bd'}]},
{id:'concrete',name:'공구리',group:'바닥·압축',automation:'근사 자동',tf:['1D','4H'],summary:'장기 하락 뒤 가격과 장기이평이 눌리고 압축되는 바닥 구조를 확인한다. 공개 자료의 형태를 정량화한 근사 판별이다.',setup:['장기이평 기울기 완화','224선 부근 가격 압축','ATR·변동성 감소','거래량 과열 없음','저점이 더 이상 크게 낮아지지 않는지 확인'],invalid:['압축 저점 이탈','장기이평 재하락 가속'],targets:['112/224 회복 구간','전고점·매물대'],sources:[{label:'공구리 공식 강의',url:'https://youtu.be/zbcOsTvmgGE'},{label:'공구리 응용',url:'https://youtu.be/iw7MDz18iV8'},{label:'新 공구리',url:'https://youtu.be/3zWm0BoSnMI'}]},
{id:'highheel',name:'하이힐',group:'반전',automation:'자동',tf:['1D','4H','1H'],summary:'급락 뒤 V자 회복과 전고점 재돌파를 통해 반전 에너지를 확인하는 패턴이다.',setup:['급락 구간 형성','V자 저점','빠른 가격 회복','전고점 돌파 여부 확인','거래량 동반 확인'],invalid:['V저점 재이탈','전고점 돌파 실패 뒤 매도 거래량 증가'],targets:['전고점 돌파 확장','다음 장기 저항'],sources:[{label:'하이힐 공식 강의',url:'https://contents.premium.naver.com/jusikdante/jusikdante1/contents/241015172919804ev'}]},
{id:'symmetry',name:'대칭이론',group:'파동·기간',automation:'근사 자동',tf:['1D','4H','1H'],summary:'이전 가격 파동과 시간 길이를 비교해 현재 조정/회복의 균형을 보는 방식이다. 정확한 사적 규칙 대신 공개적으로 확인 가능한 가격·기간 대칭을 근사한다.',setup:['기준 파동 선택','가격 변동폭 비교','기간 길이 비교','대칭 종료 지점과 구조 전환 동시 확인'],invalid:['기준 파동 자체가 재정의될 정도의 저점/고점 갱신'],targets:['대칭 완료 예상 구간'],sources:[{label:'공식 강의 목록',url:GUIDE}]},
{id:'share',name:'지분기법',group:'힘의 균형',automation:'근사 자동',tf:['1D','4H','1H'],summary:'60·112·224 등 기준 이평을 중심으로 이전 하락폭과 이후 상승폭의 1:1 균형을 확인한다.',setup:['기준 이평 선택','매도세 하락폭 측정','매수세 회복폭 측정','1:1 이상 회복 여부','다음 장기이평 목표 확인'],invalid:['기준 이평 재이탈','회복폭이 이전 하락폭 대비 현저히 약함'],targets:['224일선','448일선 또는 다음 매물대'],sources:[{label:'지분기법 공식 강의',url:'https://contents.premium.naver.com/jusikdante/jusikdante1/contents/241029151113268kz'},{label:'지분 실전 활용',url:'https://contents.premium.naver.com/jusikdante/jusikdante1/contents/250919151431347pa'}]},
{id:'kijun-scalp',name:'기준선 단타',group:'단타',automation:'조건부 자동',tf:['15m','5m','1H'],summary:'급등주가 5이평에서 반등하고 일목 기준선을 지키는지를 확인하는 단타 구조다. 코인은 24시간 시장이라 세션 기준을 별도 설정해야 한다.',setup:['5이평 반등','일목 기준선 유지','기준선과 가격의 힘 관계 확인','거래량 동반'],invalid:['기준선 종가 이탈','세션 시가 기준 손절 조건 훼손'],targets:['당일/세션 전고점','단기 공급 구간'],sources:[{label:'기준선 단타 공식 강의',url:'https://contents.premium.naver.com/jusikdante/jusikdante1/contents/241210150123286bu'}]},
{id:'256',name:'256기법',group:'바닥·수렴',automation:'수동 확인',tf:['1D','4H'],summary:'공개 자료에서 224선 부근 장기 압축·수렴 구간과 연계되어 소개되지만 세부 판정식은 유료 콘텐츠 범위가 있어 자동 공식화하지 않는다.',setup:['장기 하락/저평가 구간','장기이평 부근 수렴','돌파 전 에너지 압축','거래량·구조 보조 확인'],invalid:['수렴 하단 이탈'],targets:['224 돌파 이후 다음 장기이평'],sources:[{label:'256기법 공식 콘텐츠',url:'https://contents.premium.naver.com/jusikdante/jusikdante1/contents/251126154402336dn'}]},
{id:'reverse-wave',name:'역매공파',group:'역배열 전환',automation:'수동+보조',tf:['1D','4H'],summary:'역배열 상태에서 추세 돌파와 장기이평 회복, 작은 언덕/공구리 구조 등을 함께 보는 공개 사례가 확인된다.',setup:['역배열','추세 돌파','112일선 안착','공구리/작은 언덕','다음 장기이평 확인'],invalid:['112선 재이탈','추세 돌파 무효'],targets:['224일선','448일선'],sources:[{label:'공식 실전 사례',url:'https://contents.premium.naver.com/jusikdante/jusikdante1/contents/250919151431347pa'}]},
{id:'elliott',name:'엘리엇 파동',group:'파동',automation:'수동 확인',tf:['1W','1D','4H'],summary:'파동 구조를 큰 흐름과 조정/확장 단계로 읽는 보조 프레임. 자동 번호 매김은 오판 가능성이 커 수동 검증 중심으로 제공한다.',setup:['상위파동 방향','충격/조정 파동 구분','구조 고점·저점 확인','다른 기법과 중첩 확인'],invalid:['파동 카운트 무효화'],targets:['다음 파동 확장 구간'],sources:[{label:'공식 강의',url:'https://youtu.be/rsW7aocdtgw'}]},
{id:'dead-dive',name:'데드다이빙',group:'위험·반전',automation:'수동 확인',tf:['1D','4H'],summary:'공식 TOP 11 강의에 포함된 패턴. 공개된 무료 세부 규칙을 넘어 임의의 자동 판정식은 만들지 않는다.',setup:['공식 강의 패턴 형태 확인','거래량·추세·장기이평과 동시 검증'],invalid:['공식 체크 조건 미충족'],targets:['패턴별 대응 구간'],sources:[{label:'공식 강의',url:'https://youtu.be/iVZzQjUNAD0'}]},
{id:'open-price',name:'시초가 매매',group:'단타',automation:'수동 확인',tf:['5m','15m'],summary:'주식 정규장 시초가를 기준으로 힘과 방향을 판단하는 기법. 코인에서는 KST 09:00/UTC 00:00 등 세션 정의가 필요해 별도 변형으로만 사용한다.',setup:['세션 시가 정의','초반 거래량','시가 지지/이탈','전일 고저점 관계'],invalid:['시가 기준 반대 방향 확정'],targets:['세션 고점/저항'],sources:[{label:'공식 강의',url:'https://youtu.be/WwqDWLDxvt0'}]},
{id:'close-bet',name:'종가 베팅',group:'종가',automation:'수동+보조',tf:['1D','4H'],summary:'종가 위치와 거래량을 함께 보며 하루 동안의 매수·매도 힘의 결과를 해석한다.',setup:['종가가 캔들 상단에 위치','거래량 동반','중요 저항 돌파/유지','다음날 갭 리스크 확인'],invalid:['종가 기준 돌파 실패','대량 윗꼬리·분배'],targets:['다음 저항/전고점'],sources:[{label:'종가 베팅 공식 강의',url:'https://contents.premium.naver.com/jusikdante/jusikdante1/contents/241217165000216hw'}]},
{id:'force-balance',name:'힘의 균형',group:'기초 원리',automation:'수동+보조',tf:['ALL'],summary:'매수세와 매도세의 우위를 가격·거래량·기준선 관계로 읽는 기본 프레임이다.',setup:['가격 방향','거래량 에너지','기준선/이평선 관계','고점·저점 갱신 여부'],invalid:['반대 방향 구조 확정'],targets:['다음 균형/저항 구간'],sources:[{label:'공식 강의',url:'https://youtu.be/wyJhHjWFTHs'}]}
];
return{GUIDE,methods,get:id=>methods.find(x=>x.id===id)||methods[0]};
});