(()=>{'use strict';
const $=id=>document.getElementById(id),CD=window.PulseChartData,SE=window.PulseSmcEngine,LE=window.PulseLiquidityEngine,TA=window.PulseTraderAnalysis,SR=window.PulseSnapshotRenderer,DM=window.PulseDanteMethods;
const MULTI=['1d','4h','1h','15m'];let methodId=DM.methods[0].id,current=null,multiSeq=0;const cache=new Map();
function clean(v){v=String(v||'BTCUSDT').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');return v||'BTCUSDT'}
function fmt(v,d=4){return Number.isFinite(Number(v))?Number(v).toLocaleString('ko-KR',{maximumFractionDigits:d}):'-'}
function signalOf(t,id){return(t?.dante||[]).find(x=>x.id===id)||{score:0,reasons:[],invalidations:[],matched:false,automation:'수동 확인'}}
function build(raw,tf){const candles=raw.candles||[],smc=SE.analyzeSmcV2({candles,canonicalSwings:raw.canonicalSwings||[],canonicalEvents:raw.events||[],htf:{bias:null}}),liquidity=LE.analyzeLiquidity({candles,timeframe:tf,pivots:smc.canonicalSwings||raw.canonicalSwings||[],equalLevels:smc.equalLevels||[],sweeps:smc.sweeps||[],displacement:smc.displacements||[],mss:smc.mss||[],fvgs:smc.fvgs||[],orderBlocks:smc.orderBlocks||[]}),technical=TA.summarize({candles,analysis:raw,smc,liquidity});return{raw,candles,smc,liquidity,technical}}
async function get(tf,force=false){const s=clean($('symbol').value),key=s+':'+tf;if(!force&&cache.has(key))return cache.get(key);const raw=await CD.fetchStructure({symbol:s,interval:tf,limit:520}),data=build(raw,tf);cache.set(key,data);return data}
function renderMethod(){const m=DM.get(methodId);$('methodGroup').textContent=m.group;$('methodName').textContent=m.name;$('automation').textContent=m.automation;$('methodSummary').textContent=m.summary;$('setup').innerHTML=m.setup.map(x=>'<li>'+x+'</li>').join('');$('invalid').innerHTML=m.invalid.map(x=>'<li>'+x+'</li>').join('');$('targets').innerHTML=m.targets.map(x=>'<li>'+x+'</li>').join('');$('sources').innerHTML=m.sources.map(x=>'<a target="_blank" rel="noopener" href="'+x.url+'">'+x.label+'</a>').join('');document.querySelectorAll('.methodBtn').forEach(x=>x.classList.toggle('active',x.dataset.id===methodId));if(current){renderResult();multi(false)}}
function renderResult(){if(!current)return;const tf=$('tf').value,t=current.technical,s=signalOf(t,methodId),m=DM.get(methodId);$('score').textContent=s.score+'점';$('matchBadge').textContent=s.matched?'조건 일치':'관찰/미충족';$('matchBadge').classList.toggle('on',s.matched);$('reasons').innerHTML=(s.reasons?.length?s.reasons:['자동 판별 근거 부족 · 체크리스트 수동 확인']).map(x=>'<span class="reason">'+x+'</span>').join('');const ma=t.ma||{},periods=SR.maPeriodsFor?SR.maPeriodsFor(methodId):[20,60,112,224,448];$('maLadder').innerHTML=periods.map(p=>'<div class="maBox"><span>'+p+' 이평</span><b>'+fmt(ma[p],6)+'</b></div>').join('');$('chartLabel').textContent=clean($('symbol').value)+' · '+tf.toUpperCase()+' · '+m.name;$('snapshotCaption').textContent=m.name+' 전용 오버레이 · 관련 이평/핵심 구조만 강조 · SMC/유동성은 현재가 인접 항목만 보조 표시';SR.draw($('snapshot'),{symbol:clean($('symbol').value),timeframe:tf,candles:current.candles,analysis:current.raw,smc:current.smc,liquidity:current.liquidity,technical:t,focusMethod:methodId,show:{trend:true,smc:true,liquidity:true,profile:true,ma:true,dante:true}})}
async function run(force=false){$('status').textContent='분석 중…';try{current=await get($('tf').value,force);renderResult();$('status').textContent='완료 · '+new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});const u=new URL(location.href);u.searchParams.set('symbol',clean($('symbol').value));u.searchParams.set('tf',$('tf').value);u.searchParams.set('method',methodId);history.replaceState(null,'',u);multi(false)}catch(e){$('status').textContent='오류 · '+(e.message||e)}}
async function multi(force=true){const token=++multiSeq,g=$('multiGrid');g.innerHTML='';for(const tf of MULTI){const box=document.createElement('div');box.className='multiItem';box.innerHTML='<b>'+tf.toUpperCase()+'</b><div class="multiScore">…</div><p>분석 중</p>';g.append(box);try{const d=await get(tf,force),s=signalOf(d.technical,methodId);if(token!==multiSeq)return;box.querySelector('.multiScore').textContent=s.score+'점';box.dataset.state=s.matched?'match':'watch';box.querySelector('p').textContent=(s.reasons?.slice(0,2).join(' · ')||'수동 체크 필요')+' · '+d.technical.state}catch(e){if(token!==multiSeq)return;box.querySelector('.multiScore').textContent='-';box.querySelector('p').textContent='오류: '+(e.message||e)}}if(token===multiSeq)$('status').textContent='멀티TF 자동 비교 완료'}
function init(){const q=new URLSearchParams(location.search),m=q.get('method'),tf=q.get('tf');$('symbol').value=clean(q.get('symbol')||'BTCUSDT');if(DM.methods.some(x=>x.id===m))methodId=m;if(['1d','4h','1h','15m','5m'].includes(tf))$('tf').value=tf;$('methodCount').textContent=DM.methods.length+'개';for(const mth of DM.methods){const b=document.createElement('button');b.className='methodBtn';b.dataset.id=mth.id;b.innerHTML='<span>'+mth.name+'</span><small>'+mth.automation+'</small>';b.onclick=()=>{methodId=mth.id;renderMethod();const u=new URL(location.href);u.searchParams.set('method',methodId);history.replaceState(null,'',u)};$('methodTabs').append(b)}renderMethod();$('run').onclick=()=>run(true);$('multi').onclick=()=>multi(true);$('tf').onchange=()=>run();$('symbol').onkeydown=e=>{if(e.key==='Enter'){cache.clear();run(true)}};$('savePng').onclick=()=>{const a=document.createElement('a');a.download=clean($('symbol').value)+'-'+$('tf').value+'-'+methodId+'.png';a.href=$('snapshot').toDataURL('image/png');a.click()};run()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();