(function(){'use strict';
const $=s=>document.querySelector(s),D=ChartBroData,I=ChartBroIndicators,{price,time}=ChartBroRenderer,gate=ChartBroCoordinator.createCoordinator();let analysis=null,current=null,focus=null,replayGeneration=0,worker=null,loadGeneration=0;
const layers=()=>Object.fromEntries([...document.querySelectorAll('[data-layer]')].map(el=>[el.dataset.layer,el.checked]));
const renderer=ChartBroRenderer.createRenderer($('#chart'),id=>{focus=id;show(current);});
const names={ACTIVE_RESEARCH:'가상 추적 중',TRIGGER_CONFIRMED:'실행 봉 확인',WAIT_RETEST:'되돌림 대기',SETUP:'구조 확인',OBSERVE:'관찰',INVALIDATED:'가설 무효',EXPIRED:'기다림 종료'};
const typeNames={FVG:'3봉 가격 공백',OB:'구조 돌파의 기반 봉',BPR:'반대 공백의 중첩',SWING_HIGH:'확정 고점',SWING_LOW:'확정 저점',EQH:'비슷한 고점 군집',EQL:'비슷한 저점 군집'};
function dom(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;}
async function api(action,q={},signal){const qs=new URLSearchParams({route:'chartbro',action,...q});const r=await fetch('/api/index?'+qs,{cache:'no-store',signal}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'HTTP '+r.status);return j;}
function params(){return {symbol:$('#symbol').value.trim().toUpperCase(),market:$('#market').value,tf:$('#tf').value,flow:$('#flow').checked?'1':'0'};}
function draw(){if(current)renderer.render(current,{layers:layers(),zoom:$('#zoom').value,pan:$('#pan').value,focus});}
function show(a){if(!a)return;current=a;const set=[...(a.setups||[])].reverse().find(s=>!['INVALIDATED','EXPIRED'].includes(s.state)),last=a.bars.at(-1);$('#stage').textContent=set?names[set.state]||set.state:'관찰 · '+a.structure;
 $('#explanation').textContent=set?.state==='WAIT_RETEST'?'구조 확인 뒤 생성된 구간의 재방문을 기다립니다.':set?.state==='TRIGGER_CONFIRMED'?'닫힌 봉에서 회복이 확인되었습니다. 가상 체결은 다음 실행 시점부터 검사합니다.':set?'스윕과 구조 사건의 순서를 추적하고 있습니다.':'현재 확정된 실행 셋업은 없습니다. 위치와 가격 반응을 관찰합니다.';
 const list=$('#conditions');list.replaceChildren();for(const [key,v] of [['기준 시각',time(a.decision_at)+' KST'],['확인 조건',set?'구간 재방문 → 종가 회복':'스윕 → 변위 → 구조 확인'],['무효화',set?price(set.invalidation_level):'셋업 미생성'],['목표 후보',(a.targets||[]).slice(0,3).map(t=>price(t.price)).join(' / ')||'미확보'],['범위 위치',a.range?((a.range.location??(last.close-a.range.lower)/(a.range.upper-a.range.lower))*100).toFixed(1)+'%':'미확보'],['RVOL·압축',price(a.features?.rvol)+'배 / '+price(a.features?.compression_pct)+'%'],['수급 유형',(a.astra?.type||'미조회')+' · OI '+(a.data_quality?.oi||'missing')],['MACD 위치',a.features?.macd?.line==null?'준비 봉 부족':a.features.macd.line<0?'0선 아래':'0선 위']]){list.append(dom('dt',key),dom('dd',v));}
 const objects=$('#objects');objects.replaceChildren();const nearest=(a.objects||[]).filter(o=>!['EXPIRED','INVALIDATED','RECLAIMED','SUSTAINED_BREAK'].includes(o.state)).sort((a,b)=>Math.abs((a.price??a.mid)-last.close)-Math.abs((b.price??b.mid)-last.close)).slice(0,8);for(const o of nearest){const b=dom('button',(typeNames[o.kind]||o.kind)+' · '+(o.price!=null?price(o.price):price(o.lower)+' – '+price(o.upper)),'object'+(o.id===focus?' active':''));b.dataset.objectId=o.id;b.append(dom('small',o.state+' · '+time(o.known_at)));b.onclick=()=>{focus=o.id;show(a);};objects.append(b);}if(!nearest.length)objects.append(dom('p','활성 구간이 없습니다.'));
 const evidence=$('#evidence');evidence.replaceChildren();for(const e of (a.events||[]).filter(e=>!['LEVEL_CREATED','ZONE_CREATED','PIVOT_CONFIRMED'].includes(e.type)).slice(-6).reverse()){const el=dom('div',e.type+' · '+time(e.known_at),'event');el.dataset.eventId=e.id;evidence.append(el);}$('#pan').max=Math.max(0,a.bars.length-30);draw();}
async function load(){const generation=++loadGeneration;gate.cancelAll();if(worker){worker.terminate();worker=null;}replayGeneration++;analysis=null;current=null;focus=null;document.body.dataset.loading='true';$('#stage').textContent='조회 중';$('#explanation').textContent='확정 데이터를 기다리고 있습니다.';$('#conditions').replaceChildren();$('#objects').replaceChildren();$('#evidence').replaceChildren();$('#matrix-card').hidden=true;$('#status').textContent='확정봉과 구조를 계산하고 있습니다…';const p=params();$('#symbol').value=p.symbol;try{const result=await gate.run('analysis',signal=>api('analysis',p,signal));if(!result.accepted)return;analysis=result.value.analysis;analysis.feature_series=analysis.feature_series||I.features(analysis.bars);$('#replay').max=analysis.bars.length-1;$('#replay').value=analysis.bars.length-1;$('#pan').value=0;$('#replay-time').textContent=time(analysis.last_closed_bar_at)+' KST';show(analysis);$('#status').textContent=p.symbol+' · '+p.tf+' · 확정 '+time(analysis.decision_at)+' KST · '+analysis.bars.length+'봉 · 누락 '+(analysis.data_quality.gaps?.length||0)+'곳 · 가격 '+analysis.data_quality.price+' · OI '+analysis.data_quality.oi+' · 독립 연구 규칙';history.replaceState(null,'','?'+new URLSearchParams(p));}catch(e){$('#status').textContent='조회 실패: '+e.message+' · 이전 결과를 새 분석으로 표시하지 않습니다.';$('#stage').textContent='데이터 미확보';$('#objects').replaceChildren();$('#evidence').replaceChildren();$('#chart').getContext('2d').clearRect(0,0,$('#chart').width,$('#chart').height);}finally{if(generation===loadGeneration)document.body.dataset.loading='false';}}
$('#controls').onsubmit=e=>{e.preventDefault();load();};$('#tf').onchange=load;$('#market').onchange=load;document.querySelectorAll('[data-layer]').forEach(el=>el.onchange=draw);$('#zoom').oninput=draw;$('#pan').oninput=draw;
function replay(){if(!analysis)return;const index=Number($('#replay').value),at=analysis.bars[index].close_time;$('#replay-time').textContent=time(at)+' KST';if(index===analysis.bars.length-1){replayGeneration++;show(analysis);return;}if(!worker){worker=new Worker('/ui/chartbro/replay-worker.js');worker.onmessage=e=>{const v=e.data;if(v.generation!==replayGeneration)return;if(v.error){$('#status').textContent=v.error;return;}show({...v.snapshot,instrument:analysis.instrument,timeframe:analysis.timeframe,bars:v.bars,events:v.events,feature_series:v.feature_series,astra:{type:'리플레이 수급 미조회'},data_quality:{...v.snapshot.data_quality,oi:'missing'}});};worker.onerror=()=>{$('#status').textContent='리플레이 작업 오류. 분석 JSON을 저장하고 다시 조회하세요.';};}worker.postMessage({generation:++replayGeneration,bars:analysis.bars,config:analysis.config,at});}
$('#replay').onchange=replay;$('#latest').onclick=()=>{if(!analysis)return;$('#replay').value=analysis.bars.length-1;replay();};
function download(name,href){const a=dom('a');a.download=name;a.href=href;a.click();}
$('#png').onclick=()=>{if(current)download((analysis?.instrument.symbol||'chart')+'-'+current.decision_at+'.png',renderer.png());};$('#json').onclick=()=>{if(!current)return;const url=URL.createObjectURL(new Blob([JSON.stringify({snapshot:current,layers:layers()},null,2)],{type:'application/json'}));download('chartbro-'+current.decision_at+'.json',url);setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#matrix').onclick=async()=>{if(!analysis)return;const p=params();$('#matrix-card').hidden=false;$('#matrix-output').textContent='각 시간봉의 마지막 확정봉을 비교하고 있습니다…';try{const r=await gate.run('matrix',signal=>api('matrix',{...p,at:analysis.decision_at},signal));if(!r.accepted)return;const j=r.value,table=dom('table'),head=dom('tr');['시간봉 / 역할','구조','준비 / 교차','확정 시각'].forEach(x=>head.append(dom('th',x)));table.append(head);const roles={'1M':'장기 위치','1w':'환경','1d':'환경','12h':'중간 구조','4h':'셋업','1h':'셋업','15m':'실행','5m':'실행'};for(const tf of Object.keys(roles)){const f=j.frames[tf],tr=dom('tr');[tf+' / '+roles[tf],f?.structure||'미확보',f?('EMA '+(f.features?.last_cross?.ema?.direction||'없음')+' · MACD '+(f.features?.last_cross?.macd?.direction||'없음')):j.errors[tf],f?time(f.decision_at):'—'].forEach(x=>tr.append(dom('td',x)));table.append(tr);}const out=$('#matrix-output');out.replaceChildren(table);for(const c of j.crosses)out.append(dom('p',c.indicator+' 공통창 상승 교차: '+(c.confirmed?'확인':'미충족')+' · '+c.rows.map(x=>x.tf+' '+(x.at?time(x.at):'N/A')).join(' / ')));}catch(e){$('#matrix-output').textContent=e.message;}};
$('#coverage').onclick=async()=>{try{const j=await api('sources');const out=$('#coverage-output');out.replaceChildren();for(const s of j.sources){const a=dom('a',s.title);a.href=s.url;a.target='_blank';a.rel='noopener';const p=dom('p');p.append(a,document.createTextNode(' · '+s.access_status+' · 원문 정의 미검증'));out.append(p);}}catch(e){$('#coverage-output').textContent=e.message;}};
$('#risk-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);try{const r=ChartBroResearch.positionSize({equity:Number(f.get('equity')),risk_fraction:Number(f.get('risk'))/100,entry:Number(f.get('entry')),stop:Number(f.get('stop')),fee_rate:Number(f.get('fee'))/100,slippage:Number(f.get('slippage')),lot:Number(f.get('lot'))});$('#risk-output').textContent='가상 수량 '+price(r.quantity)+' · 계획 위험 '+price(r.risk_budget)+' USDT · 수수료·슬리피지 포함. 실제 손실은 예산을 넘을 수 있습니다.';}catch(e){$('#risk-output').textContent=e.message;}};
const query=new URLSearchParams(location.search);if(query.get('symbol'))$('#symbol').value=query.get('symbol');if(['spot','perpetual'].includes(query.get('market')))$('#market').value=query.get('market');if([...$('#tf').options].some(x=>x.value===query.get('tf')))$('#tf').value=query.get('tf');load();
})();
