(function(){'use strict';
const $=s=>document.querySelector(s),D=ChartBroData,I=ChartBroIndicators,{price,time}=ChartBroRenderer,gate=ChartBroCoordinator.createCoordinator();let analysis=null,current=null,focus=null,replayGeneration=0,worker=null,loadGeneration=0;const lastGood=new Map();
const layers=()=>Object.fromEntries([...document.querySelectorAll('[data-layer]')].map(el=>[el.dataset.layer,el.checked]));
const renderer=ChartBroRenderer.createRenderer($('#chart'),id=>{focus=id;show(current);});
const names={ACTIVE_RESEARCH:'가상 추적 중',TRIGGER_CONFIRMED:'실행 봉 확인',WAIT_RETEST:'되돌림 대기',SETUP:'구조 확인',OBSERVE:'관찰',INVALIDATED:'가설 무효',EXPIRED:'기다림 종료'};
const typeNames={FVG:'3봉 가격 공백',OB:'구조 돌파의 기반 봉',BPR:'반대 공백의 중첩',SWING_HIGH:'확정 고점',SWING_LOW:'확정 저점',EQH:'비슷한 고점 군집',EQL:'비슷한 저점 군집'};
function dom(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;}
async function api(action,q={},signal){const qs=new URLSearchParams({route:'chartbro',action,...q});const r=await fetch('/api/index?'+qs,{cache:'no-store',signal}),j=await r.json();if(!r.ok||!j.ok)throw Object.assign(new Error(j.error||'HTTP '+r.status),{code:j.code,retry_at:j.retry_at});return j;}
function params(){return {venue:$('#venue').value,symbol:$('#symbol').value.trim().toUpperCase(),market:$('#market').value,tf:$('#tf').value,flow:$('#flow').checked?'1':'0'};}
function draw(){if(current)renderer.render(current,{layers:layers(),zoom:$('#zoom').value,pan:$('#pan').value,focus});}
function show(a){if(!a)return;current=a;const set=[...(a.setups||[])].reverse().find(s=>!['INVALIDATED','EXPIRED'].includes(s.state)),last=a.bars.at(-1);$('#stage').textContent=a.stale?'마지막 정상 분석 · 새 확인 중지':set?names[set.state]||set.state:'관찰 · '+a.structure;
 $('#explanation').textContent=set?.state==='WAIT_RETEST'?'구조 확인 뒤 생성된 구간의 재방문을 기다립니다.':set?.state==='TRIGGER_CONFIRMED'?'닫힌 봉에서 회복이 확인되었습니다. 가상 체결은 다음 실행 시점부터 검사합니다.':set?'스윕과 구조 사건의 순서를 추적하고 있습니다.':'현재 확정된 실행 셋업은 없습니다. 위치와 가격 반응을 관찰합니다.';
 if(a.stale)$('#explanation').textContent='거래소 조회가 제한되어 이전 정상 데이터를 표시합니다. 현재 시점의 진입 확인이 아닙니다.';
 renderAssessment(a);
 const list=$('#conditions');list.replaceChildren();for(const [key,v] of [['거래소',a.instrument?.venue?.toUpperCase()||'미확보'],['기준 시각',time(a.decision_at)+' KST'],['확인 조건',set?'구간 재방문 → 종가 회복':'스윕 → 변위 → 구조 확인'],['무효화',set?price(set.invalidation_level):'셋업 미생성'],['목표 후보',(a.targets||[]).slice(0,3).map(t=>price(t.price)).join(' / ')||'미확보'],['범위 위치',a.range?((a.range.location??(last.close-a.range.lower)/(a.range.upper-a.range.lower))*100).toFixed(1)+'%':'미확보'],['RVOL·압축',price(a.features?.rvol)+'배 / '+price(a.features?.compression_pct)+'%'],['수급 유형',(a.astra?.type||'미조회')+' · OI '+(a.data_quality?.oi||'missing')],['OI 4H 변화',a.flow?.oi?.contracts_change_pct==null?'N/A · 변화율 이력 미확보':price(a.flow.oi.contracts_change_pct)+'% · '+(a.flow.oi.unit||'수량')],['현재 OI 참고',a.flow?.oi_snapshot?price(a.flow.oi_snapshot.quantity)+' '+a.flow.oi_snapshot.unit+' · '+(a.flow.oi_snapshot.eligible_at_decision?'현재값만 · A형 확인 불가':'분석 기준 시각 이후 참고값'):'미조회'],['정산 펀딩',a.flow?.funding?.rate==null?'N/A':price(a.flow.funding.rate*100)+'% · '+time(a.flow.funding.observed_at)],['체결 수급',a.flow?.taker?.length?'비율 '+price(a.flow.taker.at(-1).ratio):a.flow?.trade_sample?'최근 체결 일부 · 확인 미사용':'완전한 시간창 데이터 미확보'],['MACD 위치',a.features?.macd?.line==null?'준비 봉 부족':a.features.macd.line<0?'0선 아래':'0선 위']]){list.append(dom('dt',key),dom('dd',v));}
 const objects=$('#objects');objects.replaceChildren();const nearest=(a.objects||[]).filter(o=>!['EXPIRED','INVALIDATED','RECLAIMED','SUSTAINED_BREAK'].includes(o.state)).sort((a,b)=>Math.abs((a.price??a.mid)-last.close)-Math.abs((b.price??b.mid)-last.close)).slice(0,8);for(const o of nearest){const b=dom('button',(typeNames[o.kind]||o.kind)+' · '+(o.price!=null?price(o.price):price(o.lower)+' – '+price(o.upper)),'object'+(o.id===focus?' active':''));b.dataset.objectId=o.id;b.append(dom('small',o.state+' · '+time(o.known_at)));b.onclick=()=>{focus=o.id;show(a);};objects.append(b);}if(!nearest.length)objects.append(dom('p','활성 구간이 없습니다.'));
 const evidence=$('#evidence');evidence.replaceChildren();for(const e of (a.events||[]).filter(e=>!['LEVEL_CREATED','ZONE_CREATED','PIVOT_CONFIRMED'].includes(e.type)).slice(-6).reverse()){const el=dom('div',e.type+' · '+time(e.known_at),'event');el.dataset.eventId=e.id;evidence.append(el);}$('#pan').max=Math.max(0,a.bars.length-30);draw();}
function renderAssessment(a){
 const r=ChartBroAssessment.assess(a),out=$('#assessment');out.replaceChildren();
 out.append(dom('p',r.score_label+' '+(r.score==null?'N/A':r.score+'/100')+' · 데이터 신뢰도 '+r.confidence.grade));
 out.append(dom('p','단일 시간봉 롱 연구 조건입니다. 점수와 A–D 등급은 승률이 아닙니다. 등급은 가격·파생 데이터 품질이며 온체인은 포함하지 않습니다.'));
 for(const x of Object.values(r.breakdown))out.append(dom('p',x.label+' '+(x.value==null?'N/A':x.value+'/'+x.max)));
 for(const [label,xs,cls] of [['상승 근거',r.bullish,'positive'],['반대 근거',r.contradictions,'negative'],['아직 모르는 것',r.unknown,'unknown']]){out.append(dom('h3',label));if(!xs.length)out.append(dom('p','현재 기록 없음'));for(const x of xs){const el=dom('p',x.text+(x.value==null?'':' · '+price(x.value)),cls);el.dataset.factId=x.id;out.append(el);}}
}
$('#candidate-history').onclick=async()=>{
 const selected=current,output=$('#candidate-history-output');if(!selected?.analysis_id){output.textContent='리플레이 시점은 별도 서버 스냅샷이 없습니다. 최신 분석에서 기록을 조회하세요.';return;}
 output.textContent='당시까지의 기록 조회 중…';try{const r=await gate.run('candidate-history',signal=>api('candidate-history',{id:selected.analysis_id},signal));if(!r.accepted||current!==selected)return;const h=r.value;output.replaceChildren(dom('p',h.persistence==='durable'?'영속 저장 · 조회 시점 '+time(h.as_of):'임시 저장 · 서버 재시작 시 기록이 사라집니다.'));
 for(const c of h.items){const box=dom('div',null,'history-item');box.append(dom('h3',c.side+' · '+c.setup_id));let prev=null;for(const o of c.observations){if(o.state!==prev){box.append(dom('p',time(o.decision_at)+' · '+(names[o.state]||o.state)));prev=o.state;}}
 for(const x of c.outcomes)box.append(dom('p',(x.horizon_ms/3600000)+'H · '+x.result+' · MFE '+price(x.mfe*100)+'% / MAE '+price(x.mae*100)+'% · 비용 가정 후 '+price(x.conservative_net_return*100)+'%'+(x.ambiguous?' · 같은 봉 목표/손절 모호 · 보수적 손절 처리':'')));
 if(!c.outcomes.length)box.append(dom('p','결과 대기 · 실행 확인, 고정 목표 또는 이후 봉이 부족합니다.'));output.append(box);}
 if(!h.items.length)output.append(dom('p','이 거래소·시간봉·엔진의 후보 기록이 없습니다.'));
 }catch(e){if(current===selected)output.textContent=e.message;}
};
async function load(){const generation=++loadGeneration;gate.cancelAll();if(worker){worker.terminate();worker=null;}replayGeneration++;analysis=null;current=null;focus=null;document.body.dataset.loading='true';$('#stage').textContent='조회 중';$('#explanation').textContent='확정 데이터를 기다리고 있습니다.';$('#conditions').replaceChildren();$('#assessment').replaceChildren();$('#candidate-history-output').replaceChildren();$('#objects').replaceChildren();$('#evidence').replaceChildren();$('#matrix-card').hidden=true;$('#status').textContent='확정봉과 구조를 계산하고 있습니다…';const p=params();$('#symbol').value=p.symbol;try{const result=await gate.run('analysis',signal=>api('analysis',p,signal));if(!result.accepted)return;analysis=result.value.analysis;if(!analysis.stale){lastGood.set(JSON.stringify(p),analysis);if(lastGood.size>10)lastGood.delete(lastGood.keys().next().value);}analysis.feature_series=analysis.feature_series||I.features(analysis.bars);$('#replay').max=analysis.bars.length-1;$('#replay').value=analysis.bars.length-1;$('#pan').value=0;$('#replay-time').textContent=time(analysis.last_closed_bar_at)+' KST';show(analysis);$('#status').textContent=(analysis.stale?'이전 정상 데이터 · ':'')+analysis.instrument.venue.toUpperCase()+' · '+p.symbol+' · '+p.tf+' · 확정 '+time(analysis.decision_at)+' KST · '+analysis.bars.length+'봉 · 누락 '+(analysis.data_quality.gaps?.length||0)+'곳 · 가격 '+analysis.data_quality.price+' · OI '+analysis.data_quality.oi+' · 독립 연구 규칙'+(analysis.retry_at?' · 재시도 가능 '+time(analysis.retry_at)+' KST':'');history.replaceState(null,'','?'+new URLSearchParams(p));}catch(e){const prior=lastGood.get(JSON.stringify(p));if(prior){analysis={...prior,stale:true,retry_at:e.retry_at,data_quality:{...prior.data_quality,price:'stale'},operational:{eligible_for_confirmation:false}};show(analysis);$('#status').textContent='이전 정상 데이터 · '+analysis.instrument.venue.toUpperCase()+' · 기준 '+time(analysis.decision_at)+' KST · '+e.message;}else{$('#status').textContent=(['BINANCE_COOLDOWN','UPSTREAM_COOLDOWN'].includes(e.code)?'거래소가 요청을 잠시 제한했습니다. ': '조회 실패: ')+e.message+(e.retry_at?' · 재시도 가능 '+time(e.retry_at)+' KST':'')+' · 자동 또는 다른 거래소를 선택할 수 있습니다.';$('#stage').textContent='데이터 미확보';$('#objects').replaceChildren();$('#evidence').replaceChildren();$('#chart').getContext('2d').clearRect(0,0,$('#chart').width,$('#chart').height);}}finally{if(generation===loadGeneration)document.body.dataset.loading='false';}}
$('#controls').onsubmit=e=>{e.preventDefault();load();};$('#tf').onchange=load;$('#venue').onchange=load;$('#market').onchange=load;document.querySelectorAll('[data-layer]').forEach(el=>el.onchange=draw);$('#zoom').oninput=draw;$('#pan').oninput=draw;
function replay(){if(!analysis)return;const index=Number($('#replay').value),at=analysis.bars[index].close_time;$('#replay-time').textContent=time(at)+' KST';if(index===analysis.bars.length-1){replayGeneration++;show(analysis);return;}if(!worker){worker=new Worker('/ui/chartbro/replay-worker.js');worker.onmessage=e=>{const v=e.data;if(v.generation!==replayGeneration)return;if(v.error){$('#status').textContent=v.error;return;}show({...v.snapshot,instrument:analysis.instrument,timeframe:analysis.timeframe,bars:v.bars,events:v.events,feature_series:v.feature_series,astra:{type:'리플레이 수급 미조회'},data_quality:{...v.snapshot.data_quality,price:v.snapshot.data_quality.price==='available'?'fresh':'warming_up',tick_size:analysis.data_quality.tick_size,oi:'missing'}});};worker.onerror=()=>{$('#status').textContent='리플레이 작업 오류. 분석 JSON을 저장하고 다시 조회하세요.';};}worker.postMessage({generation:++replayGeneration,bars:analysis.bars,config:analysis.config,at});}
$('#replay').onchange=replay;$('#latest').onclick=()=>{if(!analysis)return;$('#replay').value=analysis.bars.length-1;replay();};
function download(name,href){const a=dom('a');a.download=name;a.href=href;a.click();}
$('#png').onclick=()=>{if(current)download((analysis?.instrument.symbol||'chart')+'-'+current.decision_at+'.png',renderer.png());};$('#json').onclick=()=>{if(!current)return;const url=URL.createObjectURL(new Blob([JSON.stringify({snapshot:current,layers:layers()},null,2)],{type:'application/json'}));download('chartbro-'+current.decision_at+'.json',url);setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#matrix').onclick=async()=>{if(!analysis)return;const p=params();$('#matrix-card').hidden=false;$('#matrix-output').textContent='각 시간봉의 마지막 확정봉을 비교하고 있습니다…';try{const r=await gate.run('matrix',signal=>api('matrix',{...p,venue:analysis.instrument.venue,at:analysis.decision_at},signal));if(!r.accepted)return;const j=r.value,table=dom('table'),head=dom('tr');['시간봉 / 역할','거래소','구조','준비 / 교차','확정 시각'].forEach(x=>head.append(dom('th',x)));table.append(head);const roles={'1M':'장기 위치','1w':'환경','1d':'환경','12h':'중간 구조','4h':'셋업','1h':'셋업','15m':'실행','5m':'실행'};for(const tf of Object.keys(roles)){const f=j.frames[tf],tr=dom('tr');[tf+' / '+roles[tf],f?.venue?.toUpperCase()||'미확보',f?.structure||'미확보',f?('EMA '+(f.features?.last_cross?.ema?.direction||'없음')+' · MACD '+(f.features?.last_cross?.macd?.direction||'없음')):j.errors[tf],f?time(f.decision_at):'—'].forEach(x=>tr.append(dom('td',x)));table.append(tr);}const out=$('#matrix-output');out.replaceChildren(table);for(const c of j.crosses)out.append(dom('p',c.indicator+' 공통창 상승 교차: '+(c.confirmed?'확인':'미충족')+' · '+c.rows.map(x=>x.tf+' '+(x.at?time(x.at):'N/A')).join(' / ')));}catch(e){$('#matrix-output').textContent=e.message;}};
$('#coverage').onclick=async()=>{try{const j=await api('sources');const out=$('#coverage-output');out.replaceChildren();for(const s of j.sources){const a=dom('a',s.title);a.href=s.url;a.target='_blank';a.rel='noopener';const p=dom('p');p.append(a,document.createTextNode(' · '+s.access_status+' · 원문 정의 미검증'));out.append(p);}}catch(e){$('#coverage-output').textContent=e.message;}};
$('#risk-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);try{const r=ChartBroResearch.positionSize({equity:Number(f.get('equity')),risk_fraction:Number(f.get('risk'))/100,entry:Number(f.get('entry')),stop:Number(f.get('stop')),fee_rate:Number(f.get('fee'))/100,slippage:Number(f.get('slippage')),lot:Number(f.get('lot'))});$('#risk-output').textContent='가상 수량 '+price(r.quantity)+' · 계획 위험 '+price(r.risk_budget)+' USDT · 수수료·슬리피지 포함. 실제 손실은 예산을 넘을 수 있습니다.';}catch(e){$('#risk-output').textContent=e.message;}};
const query=new URLSearchParams(location.search);if([...$('#venue').options].some(x=>x.value===query.get('venue')))$('#venue').value=query.get('venue');if(query.get('symbol'))$('#symbol').value=query.get('symbol');if(['spot','perpetual'].includes(query.get('market')))$('#market').value=query.get('market');if([...$('#tf').options].some(x=>x.value===query.get('tf')))$('#tf').value=query.get('tf');load();
})();
