(function(){'use strict';
const $=s=>document.querySelector(s),dom=(tag,text)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;return e;},time=ChartBroRenderer.time;let generation=0,resultGeneration=0;
async function api(action,q={}){const r=await fetch('/api/index?'+new URLSearchParams({route:'chartbro',action,...q}),{cache:'no-store',signal:AbortSignal.timeout(25000)}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'HTTP '+r.status);return j;}
async function results(job){const g=generation,rg=++resultGeneration,out=$('#server-results');out.textContent='작업 결과 조회 중…';try{const j=await api('results',{id:job.id});if(g!==generation||rg!==resultGeneration)return;out.replaceChildren(dom('h3',job.venue.toUpperCase()+' · 작업 기준 '+time(job.decision_at)+' KST'));const table=dom('table'),head=dom('tr');['종목','구조 확인','수급 확인','실패·결측'].forEach(t=>head.append(dom('th',t)));table.append(head);for(const r of j.items){const tr=dom('tr');[r.symbol,r.pass?'확인':'미확인',r.astra_eligible?'확인':'미확인',r.errors?.map(e=>e.tf+' '+e.error).join(' · ')||(r.missing?'일부 입력 미확보':'없음')].forEach(t=>tr.append(dom('td',t)));table.append(tr);}out.append(table);if(!j.items.length)out.append(dom('p','아직 완료된 종목 결과가 없습니다.'));}catch(e){if(g===generation&&rg===resultGeneration)out.textContent=e.message;}}
async function load(){const g=++generation,status=$('#server-status');try{const o=await api('operations');if(g!==generation)return;const workerRecent=o.worker?.last_tick_at!=null&&o.as_of-o.worker.last_tick_at<120000;
status.textContent=(o.durable?'영속 저장 '+o.storage:'임시 저장 · 서버 자동 실행 불가')+' · 예약 '+(o.scheduler.enabled?'켜짐':'꺼짐')+' · 워커 '+(workerRecent?'최근 동작 확인':o.worker_requested?'설정됨 · 동작 미확인':'꺼짐')+' · 후보 '+o.candidate_count+' · 가상 결과 '+o.outcome_count+(o.scheduler.next_slot_at?' · 다음 예약 슬롯 '+time(o.scheduler.next_slot_at)+' KST':'');
const out=$('#server-jobs');out.replaceChildren();out.append(dom('p','예약 거래소 '+(o.scheduler.venues.join(' / ')||'미설정')+' · 거래대금 컷 '+(o.scheduler.volume_cut?'사용':'제외')+' · 서버가 실행 중일 때 작업합니다. 무료 서버 절전 중에는 중단될 수 있습니다.'));
const table=dom('table'),head=dom('tr');['거래소 / 시각','상태','종목 진행','성공 / 실패','구조 확인','결과'].forEach(t=>head.append(dom('th',t)));table.append(head);for(const j of o.jobs){const tr=dom('tr');[j.venue.toUpperCase()+' / '+time(j.decision_at),j.state,j.processed+'/'+j.requested,j.success+' / '+j.failures,j.passed].forEach(t=>tr.append(dom('td',t)));const td=dom('td'),button=dom('button','결과 보기');button.onclick=()=>results(j);td.append(button);tr.append(td);table.append(tr);}out.append(table);if(!o.jobs.length)out.append(dom('p','등록된 서버 작업이 없습니다.'));
for(const r of o.runs.filter(r=>r.state==='FAILED'||r.state==='SKIPPED_BUSY'))out.append(dom('p',r.venue.toUpperCase()+' · '+r.state+' · '+(r.error||'이전 작업 진행 중')));
for(const p of o.polling)out.append(dom('p','결과 평가 '+p.instrument.venue.toUpperCase()+' '+p.instrument.symbol+' '+p.tf+' · '+p.state+' · '+time(p.checked_at)+(p.error?' · '+p.error:'')));
}catch(e){if(g===generation)status.textContent='서버 운영 조회 실패: '+e.message;}}
$('#server-refresh').onclick=load;load();
})();
