(function(root){'use strict';
const colors={long:'#5ddab2',short:'#ff8589',level:'#80b8ec',accent:'#e9c37f',muted:'#8da5bc'};
const price=v=>v==null?'N/A':new Intl.NumberFormat('en-US',{maximumSignificantDigits:7}).format(v);
const time=t=>new Date(t).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
function createRenderer(canvas,onSelect){let state=null,hits=[];const ctx=canvas.getContext('2d');
 function render(a,options={}){state={a,options};if(!a?.bars?.length)return;const width=canvas.clientWidth||900,height=canvas.clientHeight||680,dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#111c29';ctx.fillRect(0,0,width,height);hits=[];
 const layers=options.layers||{},size=Number(options.zoom)||100,offset=Number(options.pan)||0,end=Math.max(1,a.bars.length-offset),start=Math.max(0,end-size),bars=a.bars.slice(start,end),waves=layers.waves!==false,panelH=waves?55:0,top=40,bottom=height-35-panelH*3,left=15,right=width-85,span=Math.max(1,bars.at(-1).close_time-bars[0].open_time),tf=bars.length>1?bars[1].open_time-bars[0].open_time:1;
 let low=Math.min(...bars.map(b=>b.low)),high=Math.max(...bars.map(b=>b.high)),pad=(high-low)*.12||high*.01;low-=pad;high+=pad;const x=t=>left+(t-bars[0].open_time)/span*(right-left),y=p=>bottom-(p-low)/(high-low)*(bottom-top),line=(x0,y0,x1,y1,color,dash=[])=>{ctx.strokeStyle=color;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x1,y1);ctx.stroke();ctx.setLineDash([]);},text=(s,x0,y0,color='#a2b5c6',font=10)=>{ctx.font=font+'px system-ui';ctx.fillStyle=color;ctx.fillText(s,x0,y0);};
 text((a.instrument?.symbol||a.identity?.symbol||'')+' · '+(a.timeframe||a.identity?.timeframe||'')+' · 확정 '+time(a.decision_at),left,20,colors.accent,11);
 for(let k=0;k<=5;k++){const p=low+(high-low)*k/5,yy=y(p);line(left,yy,right,yy,'#233444');text(price(p),right+5,yy+3);}
 text((a.engine_version||'research')+' · '+(a.analysis_id||'replay').slice(0,12),left,33,colors.muted,8);ctx.save();ctx.beginPath();ctx.rect(left,top,right-left,bottom-top);ctx.clip();const visible=(p)=>p>=low&&p<=high;
 if(a.range){const l=Math.max(top,y(a.range.upper)),h=Math.min(bottom,y(a.range.lower));if(h>l){ctx.fillStyle='#7ca0ca0c';ctx.fillRect(left,l,right-left,h-l);line(left,y(a.range.eq),right,y(a.range.eq),'#7ca0ca66',[4,5]);text('범위 50%',left+3,y(a.range.eq)-3);}}
 const zwidth=Math.max(2,Math.min(10,tf/span*(right-left)*.7));
 bars.forEach(b=>{const xx=x((b.open_time+b.close_time)/2),color=b.close>=b.open?colors.long:colors.short;line(xx,y(b.high),xx,y(b.low),color);ctx.fillStyle=color;ctx.fillRect(xx-zwidth/2,Math.min(y(b.open),y(b.close)),zwidth,Math.max(1,Math.abs(y(b.open)-y(b.close))));});
 if(layers.ema!==false){[14,28,57,92].forEach((p,j)=>{const cs=['#e9c37f','#93b6ea','#c6a4dd','#a0b7aa'];ctx.strokeStyle=cs[j];ctx.beginPath();let began=false;bars.forEach((b,k)=>{const v=a.feature_series?.[start+k]?.['ema'+p];if(v==null){began=false;return;}if(!began){ctx.moveTo(x(b.close_time),y(v));began=true;}else ctx.lineTo(x(b.close_time),y(v));});ctx.stroke();text('EMA'+p,left+j*58,bottom+15,cs[j],9);});}
 const objs=a.objects||[],lastPrice=a.bars.at(-1).close,chosen=objs.filter(o=>o.known_at<=a.decision_at&&(!['INVALIDATED','EXPIRED','RECLAIMED','SUSTAINED_BREAK'].includes(o.state)||o.id===options.focus)).sort((a,b)=>Math.abs((a.price??a.mid)-lastPrice)-Math.abs((b.price??b.mid)-lastPrice)).slice(0,12);
 if(layers.zones!==false)for(const z of chosen.filter(o=>o.lower!=null&&o.upper!=null&&!o.price)){const yy=Math.max(top,y(z.upper)),hh=Math.min(bottom,y(z.lower))-yy,xx=Math.max(left,x(z.known_at));if(hh<=0||xx>right)continue;const color=colors[z.side]||colors.accent,stale=z.validity==='INVALIDATED'||z.state==='EXPIRED';ctx.fillStyle=stale?'#8da5bc12':color+'20';ctx.fillRect(xx,yy,right-xx,hh);ctx.strokeStyle=z.id===options.focus?colors.accent:color+'99';ctx.setLineDash(z.kind==='OB'?[]:[4,3]);ctx.strokeRect(xx,yy,right-xx,hh);ctx.setLineDash([]);if(z.kind==='BPR'){for(let d=xx;d<right;d+=10)line(d,yy,d+Math.min(8,right-d),Math.min(yy+8,yy+hh),color+'66');}text(z.kind,xx+3,yy+12,color,9);hits.push({id:z.id,x0:xx,x1:right,y0:yy,y1:yy+hh});}
 if(layers.levels!==false)for(const z of chosen.filter(o=>o.price!=null&&visible(o.price))){const yy=y(z.price),xx=Math.max(left,x(z.known_at));if(xx>right)continue;const color=z.id===options.focus?colors.accent:colors.level;line(xx,yy,right,yy,color,[3,5]);text((z.side==='BSL'?'위 고점':'아래 저점')+' '+price(z.price),Math.max(left,right-135),yy-4,color,9);hits.push({id:z.id,x0:xx,x1:right,y0:yy-6,y1:yy+6});}
 if(layers.structure!==false)for(const e of (a.events||[]).filter(e=>e.known_at>=bars[0].open_time&&e.known_at<=bars.at(-1).close_time&&['BOS','MSS','CHoCH','SWEEP_CANDIDATE','CISD_PROXY'].includes(e.type)).slice(-16)){const b=bars.find(b=>b.close_time===e.known_at),p=e.level??(e.side==='long'?b?.low:b?.high);if(p==null||!visible(p))continue;const xx=x(e.known_at),yy=y(p),color=colors[e.side]||colors.accent;if(e.type==='SWEEP_CANDIDATE'){ctx.strokeStyle=color;ctx.beginPath();ctx.arc(xx,yy,5,0,Math.PI*2);ctx.stroke();line(xx,yy,xx+12,yy+(e.side==='long'?-14:14),color);}else{line(Math.max(left,xx-35),yy,xx,yy,color);text(e.type.replace('_PROXY',''),Math.max(left,xx-35),yy-4,color,8);}}
 const setup=[...(a.setups||[])].reverse().find(s=>!['INVALIDATED','EXPIRED'].includes(s.state));if(setup&&visible(setup.invalidation_level)){const yy=y(setup.invalidation_level);line(left,yy,right,yy,colors.short,[8,5]);text('무효화 '+price(setup.invalidation_level),left+5,yy-4,colors.short,10);}
 for(const t of (a.targets||[]).slice(0,4))if(visible(t.price)){const yy=y(t.price);line(right-30,y(lastPrice),right-12,yy,colors.accent,[3,4]);line(right-12,yy,right-17,yy+Math.sign(lastPrice-t.price)*6,colors.accent);}
 if(visible(lastPrice)){line(left,y(lastPrice),right,y(lastPrice),'#eef3f666',[1,4]);text(price(lastPrice),right+4,y(lastPrice),colors.accent);}
 ctx.restore();if(waves)for(let j=0;j<3;j++){const pt=bottom+25+j*panelH,pb=pt+panelH-7,sy=v=>pb-v/100*(pb-pt);line(left,sy(20),right,sy(20),'#304558',[3,4]);line(left,sy(80),right,sy(80),'#304558',[3,4]);for(const [field,color] of [['k',colors.long],['d',colors.accent]]){ctx.strokeStyle=color;ctx.beginPath();let began=false;bars.forEach((b,k)=>{const v=a.feature_series?.[start+k]?.stochastic?.[j]?.[field];if(v==null){began=false;return;}if(!began){ctx.moveTo(x(b.close_time),sy(v));began=true;}else ctx.lineTo(x(b.close_time),sy(v));});ctx.stroke();}text(['대 20/12/12','중 10/6/6','소 5/3/3'][j],right+2,pt+15,colors.muted,9);}
 text(time(bars[0].open_time),left,height-8);text(time(bars.at(-1).close_time),Math.max(left,right-85),height-8);
 }
 const observer=new ResizeObserver(()=>{if(state)render(state.a,state.options);});observer.observe(canvas);
 canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),xx=e.clientX-r.left,yy=e.clientY-r.top;const hit=[...hits].reverse().find(h=>xx>=h.x0&&xx<=h.x1&&yy>=h.y0&&yy<=h.y1);if(hit)onSelect?.(hit.id);});
 return {render,destroy:()=>observer.disconnect(),png:()=>canvas.toDataURL('image/png')};
}
root.ChartBroRenderer={createRenderer,price,time};
})(globalThis);
