(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('../../lib/chartbro/models'));else root.ChartBroScanner=factory(root.ChartBroModels);})(globalThis,function(M){'use strict';
const KEY='chartbro-scan-v2',copy=x=>JSON.parse(JSON.stringify(x)),FULL=['1w','1d','12h','4h','1h','15m','5m'];
function createScanner({api,storage=null,onChange=()=>{}}){let state=null,busy=false,controller=null;
 try{const saved=JSON.parse(storage?.getItem(KEY)||'null');if(saved?.version===2&&Array.isArray(saved.tasks)&&Array.isArray(saved.results)){state=saved;if(['RUNNING','LOADING'].includes(state.state))state.state='PAUSED';}}catch{}
 function emit(){if(!state)return;try{storage?.setItem(KEY,JSON.stringify(state));state.checkpoint_saved=!!storage;}catch{state.checkpoint_saved=false;}onChange(copy(state));}
 function pack(a){return {analysis_id:a.analysis_id,instrument:a.instrument,last_closed_bar_at:a.last_closed_bar_at,decision_at:a.decision_at,features:a.features,structure:a.structure,range:a.range,objects:(a.objects||[]).filter(z=>z.lower!=null&&!['INVALIDATED','EXPIRED'].includes(z.state)),bars:a.bars?.length?[a.bars.at(-1)]:[],setups:(a.setups||[]).filter(s=>!['INVALIDATED','EXPIRED'].includes(s.state)),data_quality:a.data_quality,astra:a.astra,flow:a.flow,timeframe:a.timeframe,stale:a.stale};}
 async function run(){if(busy||!state)return;busy=true;state.state='RUNNING';emit();try{
  while(state.cursor<state.tasks.length&&state.state==='RUNNING'){
   const task=state.tasks[state.cursor],timeframes=state.timeframes,tf=timeframes.find(tf=>!state.frames[tf]);
   if(tf){controller=new AbortController();let frame;try{const r=await api('analysis',{venue:task.venue,market:task.market,symbol:task.symbol,tf,at:state.decision_at,flow:state.flow?'1':'0'},controller.signal),a=r.analysis;if(state.state==='CANCELLED')break;if(a.instrument?.venue!==task.venue||a.decision_at!==state.decision_at)throw Error('scan source or cutoff mismatch');frame={ok:true,analysis:pack(a)};}catch(e){if(state.state==='CANCELLED')break;frame={ok:false,error:e.message};if(e.retry_at){state.retry_at=e.retry_at;state.state='PAUSED';emit();break;}}state.frames[tf]=frame;emit();}
   if(timeframes.every(tf=>state.frames[tf])){
    const values=Object.values(state.frames).filter(x=>x.ok).map(x=>x.analysis),frames=Object.fromEntries(Object.entries(state.frames).filter(([,x])=>x.ok).map(([tf,x])=>[tf,x.analysis]));
    const complete=values.length===timeframes.length&&values.every(a=>!a.stale&&a.data_quality?.price==='fresh'),structural=timeframes.length>1?M.compose(frames,state.decision_at):{confirmed:values.some(a=>a.setups.some(s=>s.state==='TRIGGER_CONFIRMED'&&s.trigger_at===a.last_closed_bar_at)),role_model:'single_timeframe_research'};
    const anchor=frames['4h']||values[0],flow=frames['15m']?.flow||anchor?.flow,taker=flow?.taker?.at(-1),flowGood=taker?.coverage!=='partial'&&taker?.eligible_for_confirmation!==false&&taker?.ratio>=1.15&&taker.observed_at<=state.decision_at&&state.decision_at-taker.observed_at<=1800000;
    state.results.push({...task,ok:complete,partial:values.length>0&&!complete,confirmed:complete&&structural.confirmed,astra_eligible:complete&&structural.confirmed&&flowGood&&values.some(a=>['A','A+B','B','C'].includes(a.astra?.type)),type:anchor?.astra?.type||'OBSERVE',structure:anchor?.structure||'N/A',rvol:anchor?.features?.rvol??null,compression_pct:anchor?.features?.compression_pct??null,oi:flow?.oi||null,funding:flow?.funding||null,structural,frames:state.frames});state.cursor++;state.frames={};emit();
   }
  }
  if(state.cursor>=state.tasks.length)state.state=state.universe_errors?.length?(state.results.length?'PARTIAL':'FAILED'):state.results.every(r=>r.ok)?'COMPLETED':state.results.some(r=>r.ok||r.partial)?'PARTIAL':'FAILED';
 }finally{controller=null;busy=false;emit();}}
 async function start(q={}){if(busy)return;state={version:2,state:'LOADING',tasks:[],results:[],frames:{},cursor:0,decision_at:null,timeframes:q.mode==='full'?FULL:[q.tf||'4h'],flow:q.flow!==false,config:q};emit();controller=new AbortController();busy=true;try{const u=await api('universe',{venue:q.venue||'auto',market:q.market||'perpetual',volume_cut:q.volume_cut===false?'0':'1'},controller.signal);if(state.state==='CANCELLED')return;state.decision_at=u.decision_at;state.groups=u.groups;state.universe_errors=u.errors;state.tasks=u.groups.flatMap(g=>g.symbols.map(symbol=>({venue:g.venue,market:g.market||q.market||'perpetual',symbol})));}catch(e){if(state.state!=='CANCELLED'){state.state='FAILED';state.error=e.message;}emit();return;}finally{busy=false;controller=null;}if(state.state!=='CANCELLED')await run();}
 return {get:()=>state?copy(state):null,start,pause(){if(state?.state==='RUNNING'){state.state='PAUSED';emit();}},cancel(){if(state){state.state='CANCELLED';controller?.abort();emit();}},async resume(){if(state&&['PAUSED','CANCELLED'].includes(state.state)&&!busy){if(state.decision_at==null)await start(state.config);else await run();}},notify:emit};
}
return {createScanner};
});
