const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const profile=require('../lib/calibration-profile.js'),chart=require('../lib/chart-patterns.js');
const {buildFreezeManifest}=require('../lib/calibration-freeze.js');
const ROOT=path.resolve(__dirname,'..');
const required=['api/index.js','handlers/pattern-validation.js','handlers/calibration-health.js','handlers/calibration-freeze.js','lib/pattern-validation.js','lib/calibration-governance.js','pattern-validation-client.js','calibration-readiness-client.js','analysis-shell-v12.html','vercel.json'];
function read(p){return fs.readFileSync(path.join(ROOT,p),'utf8')}
function main(){for(const p of required)assert.ok(fs.existsSync(path.join(ROOT,p)),`missing ${p}`);assert.equal(chart.ENGINE_VERSION,profile.ENGINE_VERSION);assert.equal(chart.CALIBRATION_VERSION,profile.CALIBRATION_VERSION);const freeze=buildFreezeManifest();assert.match(freeze.sha256,/^[a-f0-9]{64}$/);const api=read('api/index.js'),vercel=JSON.parse(read('vercel.json')),shell=read('analysis-shell-v12.html');for(const route of ['pattern-validation','calibration-health','calibration-freeze']){assert.ok(api.includes(`'${route}'`)||api.includes(`${route}:`),`dispatcher missing ${route}`);assert.ok(vercel.rewrites.some(x=>x.source===`/api/${route}`),`rewrite missing ${route}`)}assert.equal(vercel.git?.deploymentEnabled?.['calibration-lab'],false,'work branch deployment must stay disabled');for(const src of ['pattern-validation-client.js?v=3','calibration-readiness-client.js?v=2'])assert.ok(shell.includes(src),`analysis shell missing ${src}`);assert.equal(profile.SPLIT_RATIOS.dev+profile.SPLIT_RATIOS.valid+profile.SPLIT_RATIOS.holdout,1);for(const params of Object.values(profile.TUNABLES))assert.ok(params.length<=3,'free parameter budget exceeded');console.log(JSON.stringify({ok:true,gate:'PASS',engineVersion:profile.ENGINE_VERSION,calibrationVersion:profile.CALIBRATION_VERSION,freezeSha256:freeze.sha256,requiredFiles:required.length,routes:3,branchDeploymentDisabled:true},null,2))}
try{main()}catch(e){console.error(JSON.stringify({ok:false,gate:'FAIL',error:e.message},null,2));process.exitCode=1}
