(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.PulseDriftMonitor=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
const DAY=86400000;
function num(v){v=Number(v);return Number.isFinite(v)?v:null}
function contribution(rows=[]){const a=rows.map(x=>({x:num(x.featureValue),y:num(x.outcome)})).filter(x=>x.x!=null&&(x.y===0||x.y===1));if(a.length<2)return null;const mx=a.reduce((s,r)=>s+r.x,0)/a.length,my=a.reduce((s,r)=>s+r.y,0)/a.length;let cov=0,vx=0,vy=0;for(const r of a){const dx=r.x-mx,dy=r.y-my;cov+=dx*dy;vx+=dx*dx;vy+=dy*dy}if(vx===0||vy===0)return 0;return cov/Math.sqrt(vx*vy)}
function compareContribution(rows=[],opts={}){const nowMs=num(opts.nowMs)??Date.now(),recentDays=Math.max(1,Number(opts.recentDays)||30),historyDays=Math.max(recentDays+1,Number(opts.historyDays)||180),minRecent=Math.max(1,Number(opts.minRecent)||20),minHistorical=Math.max(1,Number(opts.minHistorical)||50),warningDrop=Math.max(0,Number(opts.warningDrop)||.25);const recentStart=nowMs-recentDays*DAY,historyStart=nowMs-historyDays*DAY;const recent=rows.filter(r=>{const t=num(r.atMs??r.timestamp);return t!=null&&t>=recentStart&&t<=nowMs});const historical=rows.filter(r=>{const t=num(r.atMs??r.timestamp);return t!=null&&t>=historyStart&&t<recentStart});if(recent.length<minRecent||historical.length<minHistorical)return{status:'insufficient',recentN:recent.length,historicalN:historical.length,recentContribution:null,historicalContribution:null,delta:null,recentDays,historyDays};const rc=contribution(recent),hc=contribution(historical);if(rc==null||hc==null)return{status:'insufficient',recentN:recent.length,historicalN:historical.length,recentContribution:rc,historicalContribution:hc,delta:null,recentDays,historyDays};const delta=rc-hc,drop=Math.abs(hc)>1e-9?(hc-rc)/Math.abs(hc):hc-rc,status=drop>=warningDrop?'warning':'stable';return{status,recentN:recent.length,historicalN:historical.length,recentContribution:rc,historicalContribution:hc,delta,drop,recentDays,historyDays}}
function compareWindows(rows=[],opts={}){const windows=Array.isArray(opts.windows)&&opts.windows.length?opts.windows:[30,90],out={};for(const days of windows){const recentDays=Math.max(1,Number(days)||30);out[String(recentDays)]=compareContribution(rows,{...opts,recentDays})}const statuses=Object.values(out).map(x=>x.status),status=statuses.includes('warning')?'warning':statuses.every(x=>x==='insufficient')?'insufficient':statuses.includes('stable')?'stable':'insufficient';return{status,windows:out}}
function fromOutcomeRows(rows=[],feature,opts={}){const mapped=[];for(const row of rows){const snap=row?.snapshot||row,outcome=row?.outcome??row?.outcomes?.[String(opts.horizon||20)]?.success;const value=feature&&snap?.features?snap.features[feature]:snap?.[feature];if(value==null||outcome==null)continue;mapped.push({atMs:Number(snap.asOfTime||snap.createdAt),featureValue:Number(value),outcome:outcome===true||Number(outcome)===1?1:0})}return compareWindows(mapped,opts)}
return{DAY,contribution,compareContribution,compareWindows,fromOutcomeRows};
});
