(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./calibration'):root.PulseCalibration);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.PulsePerformance=api;})(typeof globalThis!=='undefined'?globalThis:this,function(Calibration){
function num(v){v=Number(v);return Number.isFinite(v)?v:null}
function median(a){if(!a.length)return null;const s=[...a].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
function invPrice(s){const v=s?.invalidation;if(v&&typeof v==='object')return num(v.price);return num(v)}
function rowMetric(row,horizon){const s=row?.snapshot||row,o=row?.outcomes?.[String(horizon)]||row?.outcomeObj||null;if(!o&&row?.outcome==null)return null;const outcome=o?Boolean(o.success):Boolean(row.outcome),ret=num(o?.returnPct??row.returnPct),score=num(s?.modelScore??row.score),p=score==null?num(row.probability):Math.max(0,Math.min(1,score/100)),entry=num(s?.entryPrice??row.entryPrice),inv=invPrice(s),risk=entry!=null&&inv!=null?Math.abs(entry-inv):null,r=ret!=null&&risk&&entry?ret/(risk/entry*100):null;return{snapshot:s,outcome:outcome?1:0,returnPct:ret,probability:p,r,validationSource:s?.validationSource||row.validationSource||'LIVE_VALIDATED',abstained:Boolean(s?.abstained??row.abstained)}}
function drawdownProxy(returns){let equity=0,peak=0,maxDD=0;for(const r of returns){equity+=r;peak=Math.max(peak,equity);maxDD=Math.min(maxDD,equity-peak)}return maxDD}
function keyFor(s,dimensions){return dimensions.map(d=>String(s?.[d]??'unknown')).join('¦')}
function aggregate(rows=[],dimensions=['validationSource'],opts={}){const horizon=Number(opts.horizon||20),groups=new Map();for(const raw of rows){const s=raw?.snapshot||raw,m=rowMetric(raw,horizon);if(!m)continue;const key=keyFor(s,dimensions);if(!groups.has(key))groups.set(key,{dims:Object.fromEntries(dimensions.map(d=>[d,s?.[d]??'unknown'])),metrics:[]});groups.get(key).metrics.push(m)}const out=[];for(const g of groups.values()){const ms=g.metrics,rets=ms.map(x=>x.returnPct).filter(x=>x!=null),rs=ms.map(x=>x.r).filter(x=>x!=null),samples=ms.filter(x=>x.probability!=null).map(x=>({probability:x.probability,outcome:x.outcome})),cal=Calibration?.report?Calibration.report(samples,{minSamples:1,adequateSamples:100,confidence:.9}):{};out.push({...g.dims,n:ms.length,hitRate:ms.reduce((s,x)=>s+x.outcome,0)/ms.length,averageReturn:rets.length?rets.reduce((a,b)=>a+b,0)/rets.length:null,medianReturn:median(rets),averageR:rs.length?rs.reduce((a,b)=>a+b,0)/rs.length:null,drawdownProxy:rets.length?drawdownProxy(rets):null,brier:cal.brier??null,ece:cal.ece??null,precisionTop20:cal.precisionTop20??null,ci:cal.ci??null})}return out.sort((a,b)=>b.n-a.n)}
function stat(items){const rets=items.map(x=>x.returnPct).filter(x=>x!=null);return{n:items.length,hitRate:items.length?items.reduce((s,x)=>s+x.outcome,0)/items.length:null,averageReturn:rets.length?rets.reduce((a,b)=>a+b,0)/rets.length:null,medianReturn:median(rets)}}
function abstentionComparison(rows=[],opts={}){const horizons=Array.isArray(opts.horizons)?opts.horizons:[20,50],sources=['LIVE_VALIDATED','BACKTESTED'],out={};for(const source of sources){const sourceRows=rows.filter(r=>String((r.snapshot||r)?.validationSource||'LIVE_VALIDATED')===source);const primary=horizons[0],mapped=sourceRows.map(r=>rowMetric(r,primary)).filter(Boolean),accepted=mapped.filter(x=>!x.abstained),abstained=mapped.filter(x=>x.abstained);out[source]={accepted:stat(accepted),abstained:stat(abstained),abstentionRate:mapped.length?abstained.length/mapped.length:0,horizons:{}};for(const h of horizons){const hm=sourceRows.map(r=>rowMetric(r,h)).filter(Boolean);out[source].horizons[String(h)]={accepted:stat(hm.filter(x=>!x.abstained)),abstained:stat(hm.filter(x=>x.abstained))}}}return out}
return{aggregate,abstentionComparison,median,drawdownProxy,rowMetric};
});
