(()=>{'use strict';
const TF=['1w','3d','1d','12h','4h','1h','15m','5m'],LABEL={'1w':'1W','3d':'3D','1d':'1D','12h':'12H','4h':'4H','1h':'1H','15m':'15m','5m':'5m'};
const $=id=>document.getElementById(id),CD=window.PulseChartData,SE=window.PulseSmcEngine,LE=window.PulseLiquidityEngine,E=window.PulseIctTrainerEngine,D=window.PulseDataState;
let seq=0,all={};
function clean(v){v=String(v||'BTCUSDT').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');if(!v)return'BTCUSDT';if(!v.endsWith('USDT')&&v.length<=12)v+='USDT';return v}
function fmt(v,d=2){return Number.isFinite(Number(v))?Number(v).toLocaleString('ko-KR',{maximumFractionDigits:d}):'-'}
function pct(v){return Number.isFinite(Number(v))?fmt(v,0)+'%':'-'}
function setState(id){if(!D)return;const m=D.formatDataState(id),el=$('dataState');el.dataset.pulseDataState=m.id;el.dataset.severity=m.severity;el.textContent=m.label}
function build(raw,tf){const candles=raw.candles||[],smc=SE.analyzeSmcV2({candles,canonicalSwings:raw.canonicalSwings||[],canonicalEvents:raw.events||[],htf:{bias:null}}),liquidity=LE.analyzeLiquidity({candles,timeframe:tf,pivots:smc.canonicalSwings||raw.canonicalSwings||[],equalLevels:smc.equalLevels||[],sweeps:smc.sweeps||[],displacement:smc.displacements||[],mss:smc.mss||[],fvgs:smc.fvgs||[],orderBlocks:smc.orderBlocks||[]});return E.analyzeTimeframe({candles,smc,liquidity,tf})}
async function get(tf,symbol){const raw=await CD.fetchStructure({symbol,interval:tf,limit:560});return build(raw,tf)}
function badge(text,kind=''){const s=document.createElement('span');s.className='ictBadge '+kind;s.textContent=text;return s}
function kv(k,v){const d=document.createElement('div');d.className='kv';const a=document.createElement('span');a.textContent=k;const b=document.createElement('b');b.textContent=v;d.append(a,b);return d}
function moduleCard(name,m){const d=document.createElement('div');d.className='moduleCard';const h=document.createElement('div');h.className='moduleHead';const b=document.createElement('b');b.textContent=name;const sc=document.createElement('span');sc.textContent=Math.round(m.score)+'점';h.append(b,sc);const bar=document.createElement('div');bar.className='meter';const fill=document.createElement('i');fill.style.width=Math.max(2,Math.min(100,m.score))+'%';bar.append(fill);const p=document.createElement('p');p.textContent=m.note;d.append(h,bar,p);return d}
function tfCard(x){const a=document.createElement('article');a.className='tfCard';a.dataset.tf=x?.tf||'';if(!x?.available){a.textContent=(x?.tf||'TF')+' · 데이터 부족';return a}const top=document.createElement('div');top.className='tfTop';const h=document.createElement('h3');h.textContent=LABEL[x.tf];const bs=badge(x.bias==='bullish'?'강세':x.bias==='bearish'?'약세':'중립',x.bias);top.append(h,bs);a.append(top,kv('ICT 준비도',pct(x.readiness)),kv('구조',x.structure.trend),kv('Dealing Range',`${x.dealingRange.zone} · ${fmt(x.dealingRange.position,0)}%`),kv('IPDA 단계',x.delivery.phase),kv('DOL',x.liquidity.drawOnLiquidity?`${x.liquidity.drawOnLiquidity.kind} · ${fmt(x.liquidity.drawOnLiquidity.price,6)}`:'-'),kv('최근 Sweep',x.liquidity.lastSweep?.kind||'없음'),kv('CISD',x.delivery.cisd?`${x.delivery.cisd.dir} 근사`:'미확인'),kv('PD Array',x.nearestPd?`${x.nearestPd.type} · ${fmt(x.nearestPd.mid,6)}`:'근접 후보 없음'),kv('MMXM',x.mmxm.model==='none'?'미완성':`${x.mmxm.model.toUpperCase()} · ${x.mmxm.stage} · ${x.mmxm.score}`));const foot=document.createElement('p');foot.className='coachLine';foot.textContent='기다릴 것: '+x.trainer.waitFor;a.append(foot);a.onclick=()=>selectTf(x.tf);return a}
function selectTf(tf){document.querySelectorAll('.tfCard').forEach(x=>x.classList.toggle('selected',x.dataset.tf===tf));const x=all[tf];if(!x?.available)return;const box=$('detail');box.innerHTML='';const h=document.createElement('h2');h.textContent=`${LABEL[tf]} · 전문 트레이너 해설`;box.append(h);const tags=document.createElement('div');tags.className='tagRow';x.evidence.forEach(t=>tags.append(badge(t,'evidence')));x.contradiction.forEach(t=>tags.append(badge(t,'warn')));box.append(tags);const grid=document.createElement('div');grid.className='moduleGrid';const map=[['유동성',x.modules.liquidity],['시장 구조',x.modules.structure],['PD Array',x.modules.pdArray],['가격 전달',x.modules.delivery],['시간·세션',x.modules.time],['MMXM',x.modules.mmxm]];map.forEach(([n,m])=>grid.append(moduleCard(n,m)));box.append(grid);const notes=document.createElement('div');notes.className='trainerNotes';notes.append(kv('현재 서사',x.trainer.summary),kv('다음 확인',x.trainer.waitFor),kv('무효화',x.trainer.invalidation),kv('세션 참고',`${x.delivery.session.label} · UTC ${x.delivery.session.utc}`));box.append(notes);const pd=document.createElement('div');pd.className='pdTable';const title=document.createElement('h3');title.textContent='PD Array 근접 후보';pd.append(title);x.pdArrays.slice(0,12).forEach(z=>pd.append(kv(`${z.type}${z.subtype?' · '+z.subtype:''}`,`${z.dir} · ${fmt(z.mid,6)} · Q${Math.round(z.quality||0)}`)));box.append(pd);box.scrollIntoView({behavior:'smooth',block:'start'})}
function renderSummary(f){$('bias').textContent=f.directional==='bullish'?'강세':f.directional==='bearish'?'약세':'혼합';$('alignment').textContent=f.alignment+'%';$('dol').textContent=f.drawOnLiquidity;$('readiness').textContent=f.readiness+'%';$('htf').textContent=f.topDown;$('ltf').textContent=f.trigger;$('confluence').textContent=f.confluence?'정렬':'불일치/중립';$('primaryModel').textContent=f.primaryModel?`${LABEL[f.primaryModel.tf]} ${f.primaryModel.model.toUpperCase()} · ${f.primaryModel.score}`:'완성 후보 없음';const c=$('coach');c.innerHTML='';f.coach.forEach((t,i)=>{const d=document.createElement('div');d.className='coachStep';d.innerHTML='<span></span><p></p>';d.querySelector('span').textContent=i+1;d.querySelector('p').textContent=t;c.append(d)});const flow=$('flow');flow.innerHTML='';[['1','유동성','BSL·SSL / ERL·IRL'],['2','조작','Sweep / Stop Hunt'],['3','상태전환','MSS·CISD / Displacement'],['4','재가격','PD Array / Premium·Discount'],['5','전달','반대편 유동성 DOL']].forEach(([no,t,s])=>{const d=document.createElement('div');d.className='flowStep';d.innerHTML='<span></span><div><b></b><small></small></div>';d.querySelector('span').textContent=no;d.querySelector('b').textContent=t;d.querySelector('small').textContent=s;flow.append(d)})}
function renderCurriculum(){const box=$('curriculum');box.innerHTML='';E.curriculum.forEach((m,i)=>{const d=document.createElement('details');d.className='curriculumCard';if(i<2)d.open=true;const s=document.createElement('summary');s.textContent=m.title;const p=document.createElement('p');p.textContent=m.topics.join(' · ');d.append(s,p);box.append(d)})}
function renderAll(){const g=$('tfGrid');g.innerHTML='';TF.forEach(tf=>g.append(tfCard(all[tf]||{tf,available:false})));const f=E.analyzeFractal(all);if(f.available)renderSummary(f);const sym=clean($('symbol').value);$('chartLink').href='/unified-chart.html?symbol='+encodeURIComponent(sym)+'&tf=1h&preset=smc';$('snapshotLink').href='/mtf-snapshot-pro.html?symbol='+encodeURIComponent(sym)+'&tf=4h';$('reportLink').href='/coin-report.html?symbol='+encodeURIComponent(sym)}
async function run(){const token=++seq,symbol=clean($('symbol').value);$('symbol').value=symbol;all={};$('tfGrid').innerHTML='';$('detail').innerHTML='<div class="emptyState">8개 시간봉을 분석 중입니다.</div>';setState('live');$('status').textContent='1W → 5m ICT 트레이너 분석 중…';for(let i=0;i<TF.length;i+=2){const batch=TF.slice(i,i+2),rs=await Promise.allSettled(batch.map(tf=>get(tf,symbol)));if(token!==seq)return;batch.forEach((tf,j)=>{all[tf]=rs[j].status==='fulfilled'?rs[j].value:{tf,available:false,reason:rs[j].reason?.message||'불러오기 실패'}});$('status').textContent=`ICT 분석 ${Math.min(i+2,TF.length)}/${TF.length}`;renderAll()}const ok=Object.values(all).filter(x=>x.available).length;if(!ok){setState('api-degraded');$('status').textContent='분석 가능한 시간봉이 없습니다.';return}setState('confirmed');$('status').textContent=`${symbol} · ${ok}/8 TF 분석 완료`;const u=new URL(location.href);u.searchParams.set('symbol',symbol);history.replaceState(null,'',u);const first=['4h','1h','1d','15m'].find(tf=>all[tf]?.available);if(first)selectTf(first);if(new URLSearchParams(location.search).get('shell')==='1'&&parent!==window)parent.postMessage({type:'pulse-symbol-sync',symbol},'*')}
function init(){if(!CD||!SE||!LE||!E){$('status').textContent='ICT 트레이너 모듈 로드 실패';setState('api-degraded');return}renderCurriculum();$('symbol').value=clean(new URLSearchParams(location.search).get('symbol')||'BTCUSDT');$('run').onclick=run;$('symbol').addEventListener('keydown',e=>{if(e.key==='Enter')run()});run()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();