(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PulseIctTrainerEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const VERSION='ICT_TRAINER_v1';
const TF_ORDER=['1w','3d','1d','12h','4h','1h','15m','5m'];
const finite=v=>Number.isFinite(Number(v));
const n=(v,d=0)=>finite(v)?Number(v):d;
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const mean=a=>a.length?a.reduce((s,v)=>s+n(v),0)/a.length:0;
function norm(c=[]){return(Array.isArray(c)?c:[]).filter(x=>x&&finite(x.close)&&finite(x.high)&&finite(x.low)).map((x,i)=>({index:i,time:x.time,open:n(x.open,x.close),high:n(x.high),low:n(x.low),close:n(x.close),volume:n(x.volume)}));}
function ema(a,p){if(!a.length)return[];const k=2/(p+1),out=[n(a[0])];for(let i=1;i<a.length;i++)out.push(n(a[i])*k+out[i-1]*(1-k));return out;}
function atr(c,p=14){c=norm(c);if(!c.length)return[];const tr=c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)):x.high-x.low);return ema(tr,p);}
function pivots(c,left=2,right=2){c=norm(c);const highs=[],lows=[];for(let i=left;i<c.length-right;i++){let hi=true,lo=true;for(let j=i-left;j<=i+right;j++){if(j===i)continue;if(c[j].high>=c[i].high)hi=false;if(c[j].low<=c[i].low)lo=false;}if(hi)highs.push({type:'H',index:i,price:c[i].high,time:c[i].time});if(lo)lows.push({type:'L',index:i,price:c[i].low,time:c[i].time});}return{highs,lows,all:[...highs,...lows].sort((a,b)=>a.index-b.index)};}
function trendFromPivots(p){const hs=p.highs.slice(-2),ls=p.lows.slice(-2);if(hs.length<2||ls.length<2)return'neutral';if(hs[1].price>hs[0].price&&ls[1].price>ls[0].price)return'bullish';if(hs[1].price<hs[0].price&&ls[1].price<ls[0].price)return'bearish';return'neutral';}
function volumeRatio(c,p=20){c=norm(c);if(c.length<2)return null;const w=c.slice(Math.max(0,c.length-p-1),-1),base=mean(w.map(x=>x.volume));return base>0?c.at(-1).volume/base:null;}
function recentRange(c,p=120){c=norm(c);const w=c.slice(-p);if(!w.length)return null;const high=Math.max(...w.map(x=>x.high)),low=Math.min(...w.map(x=>x.low)),eq=(high+low)/2,last=c.at(-1).close,pos=(last-low)/(high-low||1);return{high,low,eq,position:clamp(pos*100),zone:pos<.45?'discount':pos>.55?'premium':'equilibrium'};}
function equalPools(points,atrNow,side){if(!points.length||!(atrNow>0))return[];const tol=atrNow*.18,out=[];for(let i=Math.max(0,points.length-12);i<points.length;i++){const a=points[i],matches=points.slice(i+1).filter(b=>Math.abs(b.price-a.price)<=tol);if(matches.length){const xs=[a,...matches],price=mean(xs.map(x=>x.price));out.push({side,price,count:xs.length,index:Math.max(...xs.map(x=>x.index)),kind:side==='buy'?'EQH/BSL':'EQL/SSL'});}}return out.sort((a,b)=>b.index-a.index).filter((x,i,a)=>i===a.findIndex(y=>Math.abs(y.price-x.price)<=tol));}
function detectSweeps(c,p,lookback=24){c=norm(c);const out=[];for(let i=Math.max(lookback,c.length-16);i<c.length;i++){const prev=c.slice(i-lookback,i),ph=Math.max(...prev.map(x=>x.high)),pl=Math.min(...prev.map(x=>x.low)),x=c[i];if(x.high>ph&&x.close<ph)out.push({index:i,time:x.time,side:'buy',dir:'bearish',level:ph,extreme:x.high,kind:'BSL sweep'});if(x.low<pl&&x.close>pl)out.push({index:i,time:x.time,side:'sell',dir:'bullish',level:pl,extreme:x.low,kind:'SSL sweep'});}return out;}
function displacement(c,a){c=norm(c);const out=[];for(let i=Math.max(1,c.length-24);i<c.length;i++){const x=c[i],av=a[i]||a.at(-1)||0;if(!(av>0))continue;const body=Math.abs(x.close-x.open),range=x.high-x.low||1,edge=x.close>x.open?(x.high-x.close)/range:(x.close-x.low)/range,prev=c.slice(Math.max(0,i-20),i),vbase=mean(prev.map(z=>z.volume)),rv=vbase>0?x.volume/vbase:0;if(body/av>=.85&&range/av>=1.05&&edge<=.3&&rv>=1.1)out.push({index:i,time:x.time,dir:x.close>x.open?'bullish':'bearish',bodyAtr:body/av,rangeAtr:range/av,rvol:rv});}return out;}
function detectFvgs(c,a){c=norm(c);const out=[];for(let i=2;i<c.length;i++){let z=null;if(c[i].low>c[i-2].high)z={type:'FVG',dir:'bullish',index:i,time:c[i].time,low:c[i-2].high,high:c[i].low};else if(c[i].high<c[i-2].low)z={type:'FVG',dir:'bearish',index:i,time:c[i].time,low:c[i].high,high:c[i-2].low};if(!z)continue;z.mid=(z.low+z.high)/2;z.sizeAtr=(z.high-z.low)/(a[i]||a.at(-1)||1);const after=c.slice(i+1),filled=z.dir==='bullish'?after.some(x=>x.low<=z.low):after.some(x=>x.high>=z.high);z.state=filled?'mitigated':'active';out.push(z);}return out;}
function inferOrderBlocks(c,disps,a){c=norm(c);const out=[];for(const d of disps.slice(-12)){for(let j=d.index-1;j>=Math.max(0,d.index-6);j--){const x=c[j],opp=d.dir==='bullish'?x.close<x.open:x.close>x.open;if(!opp)continue;const range=x.high-x.low,av=a[j]||a.at(-1)||1;out.push({type:'ORDER_BLOCK',dir:d.dir,index:j,time:x.time,low:x.low,high:x.high,mid:(x.low+x.high)/2,quality:Math.round(clamp(50+d.bodyAtr*15+Math.min(15,range/av*8)))});break;}}return out;}
function rejectionBlocks(c,a){c=norm(c);const out=[];for(let i=Math.max(5,c.length-100);i<c.length;i++){const x=c[i],range=x.high-x.low||1,up=x.high-Math.max(x.open,x.close),dn=Math.min(x.open,x.close)-x.low,av=a[i]||a.at(-1)||1;if(range/av<.65)continue;if(up/range>=.55)out.push({type:'REJECTION_BLOCK',dir:'bearish',index:i,time:x.time,low:Math.max(x.open,x.close),high:x.high,mid:(Math.max(x.open,x.close)+x.high)/2,quality:Math.round(clamp(up/range*100))});if(dn/range>=.55)out.push({type:'REJECTION_BLOCK',dir:'bullish',index:i,time:x.time,low:x.low,high:Math.min(x.open,x.close),mid:(x.low+Math.min(x.open,x.close))/2,quality:Math.round(clamp(dn/range*100))});}return out;}
function liquidityVoids(c,a){c=norm(c);const out=[];let run=null;for(let i=Math.max(1,c.length-120);i<c.length;i++){const x=c[i],av=a[i]||a.at(-1)||1,dir=x.close>x.open?'bullish':'bearish',large=(x.high-x.low)/av>=1.15&&Math.abs(x.close-x.open)/av>=.7;if(large&&(!run||run.dir===dir)){run=run||{type:'LIQUIDITY_VOID',dir,start:i,end:i,low:x.low,high:x.high};run.end=i;run.low=Math.min(run.low,x.low);run.high=Math.max(run.high,x.high);}else{if(run&&run.end-run.start>=1)out.push({...run,index:run.start,time:c[run.start].time,mid:(run.low+run.high)/2,quality:Math.round(clamp(55+(run.end-run.start)*12))});run=null;}}if(run&&run.end-run.start>=1)out.push({...run,index:run.start,time:c[run.start].time,mid:(run.low+run.high)/2,quality:Math.round(clamp(55+(run.end-run.start)*12))});return out;}
function bprZones(fvgs){const bulls=fvgs.filter(x=>x.dir==='bullish').slice(-12),bears=fvgs.filter(x=>x.dir==='bearish').slice(-12),out=[];for(const a of bulls)for(const b of bears){const low=Math.max(a.low,b.low),high=Math.min(a.high,b.high);if(high>low)out.push({type:'BPR',dir:'balanced',index:Math.max(a.index,b.index),low,high,mid:(low+high)/2,quality:70,source:[a.index,b.index]});}return out.sort((a,b)=>b.index-a.index).slice(0,6);}
function cisdApprox(c,sweep,disp){c=norm(c);if(!sweep)return null;const dir=sweep.dir,after=c.slice(sweep.index+1,Math.min(c.length,sweep.index+10));if(!after.length)return null;const before=c.slice(Math.max(0,sweep.index-5),sweep.index+1);if(dir==='bullish'){const bearish=before.filter(x=>x.close<x.open),ref=bearish.length?Math.max(...bearish.map(x=>Math.max(x.open,x.close))):Math.max(...before.map(x=>x.close));const hit=after.find(x=>x.close>ref);return hit?{dir,index:hit.index,time:hit.time,level:ref,confirmed:!!disp&&disp.dir===dir,approximation:true}:null;}const bullish=before.filter(x=>x.close>x.open),ref=bullish.length?Math.min(...bullish.map(x=>Math.min(x.open,x.close))):Math.min(...before.map(x=>x.close));const hit=after.find(x=>x.close<ref);return hit?{dir,index:hit.index,time:hit.time,level:ref,confirmed:!!disp&&disp.dir===dir,approximation:true}:null;}
function structureFromSmc(smc,p){const lastMss=(smc?.mss||[]).at(-1),lastEvent=(smc?.canonicalEvents||[]).at(-1);let trend=trendFromPivots(p);const dir=String(lastMss?.dir||lastEvent?.dir||'').toLowerCase();if(/up|bull/.test(dir))trend='bullish';if(/down|bear/.test(dir))trend='bearish';return{trend,lastMss:lastMss||null,lastEvent:lastEvent||null,lastHigh:p.highs.at(-1)||null,lastLow:p.lows.at(-1)||null};}
function mitigationCandidate(c,obs){c=norm(c);const out=[];for(const ob of obs.slice(-10)){const after=c.slice(ob.index+1),touched=after.find(x=>x.low<=ob.high&&x.high>=ob.low);if(touched&&touched.index<c.length-1)out.push({type:'MITIGATION_BLOCK',dir:ob.dir,index:ob.index,time:ob.time,low:ob.low,high:ob.high,mid:ob.mid,quality:Math.min(90,(ob.quality||60)+8)});}return out;}
function breakerCandidates(c,obs,sweeps){c=norm(c);const out=[];for(const ob of obs.slice(-12)){const after=c.slice(ob.index+1),invalid=ob.dir==='bullish'?after.find(x=>x.close<ob.low):after.find(x=>x.close>ob.high);if(!invalid)continue;const sw=sweeps.find(x=>Math.abs(x.index-ob.index)<=12);if(sw)out.push({type:'BREAKER_BLOCK',dir:ob.dir==='bullish'?'bearish':'bullish',index:ob.index,time:ob.time,low:ob.low,high:ob.high,mid:ob.mid,quality:72});}return out;}
function pdArrayCatalog({p,obs,rejections,fvgs,voids,mitigations,breakers,bprs,smc}){const list=[];for(const x of p.highs.slice(-4))list.push({type:'OLD_HIGH_LOW',subtype:'OLD_HIGH',dir:'bearish',index:x.index,low:x.price,high:x.price,mid:x.price,quality:60});for(const x of p.lows.slice(-4))list.push({type:'OLD_HIGH_LOW',subtype:'OLD_LOW',dir:'bullish',index:x.index,low:x.price,high:x.price,mid:x.price,quality:60});list.push(...obs,...rejections,...fvgs.map(x=>({...x,type:'FVG',quality:Math.round(clamp(55+x.sizeAtr*25))})),...voids,...mitigations,...breakers,...bprs);for(const x of smc?.breakers||[])if(finite(x.low)&&finite(x.high))list.push({type:'BREAKER_BLOCK',dir:x.dir||x.side||'unknown',index:n(x.index??x.startIndex),low:n(x.low),high:n(x.high),mid:(n(x.low)+n(x.high))/2,quality:n(x.quality,75),source:'smc'});return list.sort((a,b)=>b.index-a.index||n(b.quality)-n(a.quality));}
function nearestPd(list,price,dir){return list.filter(x=>finite(x.mid)&&(!dir||x.dir===dir||x.dir==='balanced')).map(x=>({...x,distance:Math.abs(x.mid-price)})).sort((a,b)=>a.distance-b.distance||n(b.quality)-n(a.quality))[0]||null;}
function sessionContext(time){let ms=n(time);if(ms<1e12)ms*=1000;const d=new Date(ms||Date.now()),h=d.getUTCHours()+d.getUTCMinutes()/60;let label='비주요 시간대';if(h>=0&&h<5)label='아시아 참고 구간';else if(h>=7&&h<10)label='런던 참고 구간';else if(h>=13&&h<16)label='뉴욕 AM 참고 구간';else if(h>=18&&h<20)label='뉴욕 PM 참고 구간';return{utcHour:h,label,utc:d.toISOString().slice(11,16),note:'크립토 24/7용 고정 UTC 참고 구간이며 DST/원본 ICT Killzone을 그대로 복제한 값이 아닙니다.'};}
function analyzeTimeframe(input={}){const c=norm(input.candles),tf=String(input.tf||''),smc=input.smc||{},liq=input.liquidity||{};if(c.length<40)return{tf,available:false,reason:'확정봉 부족'};const a=atr(c),av=a.at(-1)||0,p=pivots(c),structure=structureFromSmc(smc,p),range=recentRange(c,Math.min(160,c.length)),sweeps=detectSweeps(c,p),lastSweep=sweeps.at(-1)||null,disps=displacement(c,a),lastDisp=disps.at(-1)||null,fvgs=detectFvgs(c,a),obs=inferOrderBlocks(c,disps,a),rejections=rejectionBlocks(c,a),voids=liquidityVoids(c,a),mitigations=mitigationCandidate(c,obs),breakers=breakerCandidates(c,obs,sweeps),bprs=bprZones(fvgs),pdArrays=pdArrayCatalog({p,obs,rejections,fvgs,voids,mitigations,breakers,bprs,smc}),price=c.at(-1).close,rvol=volumeRatio(c),cisd=cisdApprox(c,lastSweep,lastDisp),eqh=equalPools(p.highs,av,'buy'),eql=equalPools(p.lows,av,'sell');
const externalHigh=p.highs.slice(-8).sort((x,y)=>y.price-x.price)[0]||{price:range.high,index:c.length-1},externalLow=p.lows.slice(-8).sort((x,y)=>x.price-y.price)[0]||{price:range.low,index:c.length-1};const bsl=[...eqh,{side:'buy',price:externalHigh.price,index:externalHigh.index,kind:'ERL High'}].sort((x,y)=>x.price-y.price),ssl=[...eql,{side:'sell',price:externalLow.price,index:externalLow.index,kind:'ERL Low'}].sort((x,y)=>y.price-x.price);const nearestBsl=bsl.filter(x=>x.price>price).sort((x,y)=>x.price-y.price)[0]||bsl.at(-1),nearestSsl=ssl.filter(x=>x.price<price).sort((x,y)=>y.price-x.price)[0]||ssl.at(-1);
let bias=structure.trend;if(lastSweep&&cisd&&lastSweep.dir===cisd.dir)bias=lastSweep.dir;else if(lastDisp&&lastDisp.index>=c.length-8)bias=lastDisp.dir;
const draw=bias==='bullish'?nearestBsl:bias==='bearish'?nearestSsl:(Math.abs((nearestBsl?.price??Infinity)-price)<=Math.abs(price-(nearestSsl?.price??-Infinity))?nearestBsl:nearestSsl),pd=nearestPd(pdArrays,price,bias);let phase='전환/중립';const recent=c.slice(-24),atrPct=price?av/price*100:0,rangePct=price?(Math.max(...recent.map(x=>x.high))-Math.min(...recent.map(x=>x.low)))/price*100:0;if(rangePct<atrPct*5)phase='통합/설계';if(lastSweep&&lastSweep.index>=c.length-12)phase='유동성 조작/스윕';if(lastDisp&&lastDisp.index>=c.length-10)phase='확장/가격전달';if(lastDisp&&lastDisp.index<c.length-5&&pd&&Math.abs(price-pd.mid)<=Math.max(av*1.2,price*.005))phase='되돌림/PD Array 재가격';if(cisd&&lastDisp&&cisd.dir===lastDisp.dir&&Math.max(cisd.index,lastDisp.index)>=c.length-8)phase='재전달/구조 전환';
let model='none',modelStage='관찰',modelScore=0,reasons=[],invalidations=[];const bullSweep=lastSweep?.dir==='bullish',bearSweep=lastSweep?.dir==='bearish',bullShift=(cisd?.dir==='bullish'||lastDisp?.dir==='bullish'),bearShift=(cisd?.dir==='bearish'||lastDisp?.dir==='bearish');if(bullSweep||bearSweep){model=bullSweep?'buy':'sell';modelScore+=30;reasons.push(bullSweep?'SSL 스윕':'BSL 스윕');modelStage='조작';}if((model==='buy'&&bullShift)||(model==='sell'&&bearShift)){modelScore+=30;reasons.push('스윕 이후 전달 상태 전환/변위');modelStage='구조 전환';}if(pd&&((model==='buy'&&pd.dir==='bullish')||(model==='sell'&&pd.dir==='bearish')||pd.dir==='balanced')){modelScore+=20;reasons.push(pd.type+' 재가격 후보');modelStage='되돌림 대기/진행';}if(draw){modelScore+=10;reasons.push('반대편 유동성 타겟 존재');}if(range&&((model==='buy'&&range.zone==='discount')||(model==='sell'&&range.zone==='premium'))){modelScore+=10;reasons.push('Dealing Range 위치 일치');}const modelBias=model==='buy'?'bullish':model==='sell'?'bearish':null;if(modelBias&&structure.trend!=='neutral'&&modelBias!==structure.trend){modelScore=Math.max(0,modelScore-20);reasons.push('현재 구조와 반대 방향 — 역추세 감점');}if(model==='buy')invalidations.push('최근 SSL 스윕 저점 종가 재이탈','상승 CISD/MSS 실패 후 하락 변위');if(model==='sell')invalidations.push('최근 BSL 스윕 고점 종가 재돌파','하락 CISD/MSS 실패 후 상승 변위');if(modelScore>=70)modelStage='재가격 후 전달 준비';
const modules={liquidity:{score:clamp((bsl.length+ssl.length)*8+(lastSweep?25:0),0,100),note:lastSweep?'외부/내부 유동성과 최근 Sweep을 함께 확인':'유동성 풀은 보이나 최근 Sweep은 미확인'},structure:{score:structure.trend==='neutral'?45:75,note:`${structure.trend} 구조${structure.lastMss?' · MSS 존재':''}`},pdArray:{score:clamp(pdArrays.filter(x=>x.index>=c.length-100).length*7+(pd?20:0),0,100),note:pd?`가까운 ${pd.type} 후보 확인`:'근접 PD Array 약함'},delivery:{score:clamp((lastDisp?30:0)+(cisd?30:0)+(lastSweep?20:0)+(phase.includes('전달')?20:0),0,100),note:`${phase}${cisd?' · CISD 근사 확인':''}`},time:{score:50,note:sessionContext(c.at(-1).time).label},mmxm:{score:modelScore,note:model==='none'?'MMXM 완성 시퀀스 미확인':`${model.toUpperCase()} 모델 · ${modelStage}`}};
const evidence=[];if(lastSweep)evidence.push(lastSweep.kind);if(cisd)evidence.push(`CISD ${cisd.dir} 근사`);if(lastDisp)evidence.push(`${lastDisp.dir} Displacement ${lastDisp.bodyAtr.toFixed(2)} ATR`);if(pd)evidence.push(`${pd.type} 근접`);if(range)evidence.push(`${range.zone} ${range.position.toFixed(0)}%`);if(draw)evidence.push(`DOL ${draw.kind||draw.side} ${draw.price}`);const contradiction=[];if(bias==='bullish'&&range.zone==='premium')contradiction.push('강세 편향이지만 Premium 위치');if(bias==='bearish'&&range.zone==='discount')contradiction.push('약세 편향이지만 Discount 위치');if(lastSweep&&lastDisp&&lastSweep.dir!==lastDisp.dir)contradiction.push('Sweep 방향과 Displacement 방향 불일치');if(rvol!=null&&rvol<.7)contradiction.push('현재 거래량이 20봉 평균 대비 약함');
const readiness=Math.round(mean(Object.values(modules).filter((_,i)=>i!==4).map(x=>x.score)));return{version:VERSION,tf,available:true,price,atr:av,rvol,bias,structure,dealingRange:range,liquidity:{bsl,ssl,externalHigh,externalLow,lastSweep,drawOnLiquidity:draw,sourceLevels:liq.levels||[]},delivery:{phase,displacement:lastDisp,cisd,session:sessionContext(c.at(-1).time)},pdArrays,pdArrayGroups:['OLD_HIGH_LOW','ORDER_BLOCK','REJECTION_BLOCK','FVG','LIQUIDITY_VOID','MITIGATION_BLOCK','BREAKER_BLOCK'],bpr:bprs,nearestPd:pd,mmxm:{model,stage:modelStage,score:Math.round(modelScore),reasons,invalidations},modules,readiness,evidence,contradiction,trainer:{summary:`${tf.toUpperCase()} ${bias} · ${phase} · ${range.zone}`,waitFor:model==='none'?'Sweep → CISD/MSS → Displacement → PD Array 재가격 순서를 기다림':modelStage.includes('전달 준비')?'PD Array 방어와 반대편 유동성 전달 확인':'다음 시퀀스 확인',invalidation:invalidations[0]||'Dealing Range 외부 구조가 반대로 확정되면 현재 서사 무효'}};}
function analyzeFractal(results={}){const rows=TF_ORDER.map(tf=>results[tf]).filter(x=>x?.available);if(!rows.length)return{available:false};const weights={'1w':5,'3d':4.5,'1d':4,'12h':3.5,'4h':3,'1h':2,'15m':1.2,'5m':.8};let bull=0,bear=0,neutral=0,total=0;for(const x of rows){const w=weights[x.tf]||1;total+=w;if(x.bias==='bullish')bull+=w;else if(x.bias==='bearish')bear+=w;else neutral+=w;}const directional=bull>bear*1.25?'bullish':bear>bull*1.25?'bearish':'mixed',alignment=Math.round(clamp(Math.max(bull,bear,neutral)/(total||1)*100)),htf=rows.filter(x=>['1w','3d','1d','12h','4h'].includes(x.tf)),ltf=rows.filter(x=>['1h','15m','5m'].includes(x.tf)),htfBias=mean(htf.map(x=>x.bias==='bullish'?1:x.bias==='bearish'?-1:0)),ltfBias=mean(ltf.map(x=>x.bias==='bullish'?1:x.bias==='bearish'?-1:0)),topDown=htfBias>.2?'bullish':htfBias<-.2?'bearish':'mixed',trigger=ltfBias>.2?'bullish':ltfBias<-.2?'bearish':'mixed',confluence=topDown!=='mixed'&&trigger===topDown,readiness=Math.round(mean(rows.map(x=>x.readiness))),dols=rows.map(x=>x.liquidity?.drawOnLiquidity).filter(Boolean),above=dols.filter(x=>x.side==='buy').length,below=dols.filter(x=>x.side==='sell').length,dol=above>below?'상단 BSL/ERL':below>above?'하단 SSL/ERL':'양방향/혼합',modelRows=rows.filter(x=>x.mmxm?.model!=='none').sort((a,b)=>(b.mmxm.score+(topDown!=='mixed'&&((b.mmxm.model==='buy'?'bullish':'bearish')===topDown)?20:-20)+(weights[b.tf]||1))-(a.mmxm.score+(topDown!=='mixed'&&((a.mmxm.model==='buy'?'bullish':'bearish')===topDown)?20:-20)+(weights[a.tf]||1))),primary=modelRows[0]||null,coach=[];coach.push(topDown==='mixed'?'HTF 방향이 섞여 있으므로 LTF 진입 논리보다 먼저 상위 Dealing Range를 재확인':`HTF 주문흐름은 ${topDown}`);coach.push(confluence?'HTF와 LTF 방향이 일치':'HTF-LTF 방향 불일치 또는 중립 — 하위 신호 단독 추격 금지');coach.push(primary?`${primary.tf.toUpperCase()} ${primary.mmxm.model.toUpperCase()} MMXM 후보 ${primary.mmxm.score}점`:'완성도 높은 MMXM 후보 없음');return{version:VERSION,available:true,directional,alignment,topDown,trigger,confluence,readiness,drawOnLiquidity:dol,primaryModel:primary?{tf:primary.tf,...primary.mmxm}:null,coach,rows:rows.map(x=>({tf:x.tf,bias:x.bias,phase:x.delivery.phase,zone:x.dealingRange.zone,readiness:x.readiness,mmxm:x.mmxm.score,dol:x.liquidity?.drawOnLiquidity?.kind||'-'}))};}
const curriculum=[
{id:'liquidity',title:'유동성',topics:['BSL/SSL','Old High/Low','Liquidity Pool','Sweep','ERL/IRL']},
{id:'pd-array',title:'PD Array',topics:['Old High/Low','Order Block','Rejection Block','FVG','Liquidity Void','Mitigation Block','Breaker Block','BPR']},
{id:'order-flow',title:'기관 주문흐름',topics:['HH/HL/LH/LL','MSS/CHoCH/BOS','Displacement','CISD','Premium/Discount','EQ']},
{id:'delivery',title:'시장 효율성·IPDA',topics:['Consolidation','Manipulation/Sweep','Expansion','Retracement','Reversal','가격 전달 시퀀스']},
{id:'time',title:'거래시간',topics:['UTC 세션 컨텍스트','HTF/MTF/LTF 역할 분리','24/7 크립토 보정']},
{id:'mmxm',title:'마켓메이커 모델',topics:['Buy Model','Sell Model','Sweep→Shift→Reprice→DOL','프레임워크','프로젝션']},
{id:'fractal',title:'프랙탈·타임프레임',topics:['1W→3D→1D→12H→4H→1H→15m→5m','상위 서사','하위 트리거','반증/무효화']}
];
return{VERSION,TF_ORDER,curriculum,analyzeTimeframe,analyzeFractal,_internals:{norm,atr,pivots,detectFvgs,detectSweeps,displacement,rejectionBlocks,liquidityVoids,bprZones,cisdApprox}};
});