const LARGE=100000,VERY_LARGE=1000000;
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:0));
const isLargeTransfer=r=>num(r?.amountUsd)>=LARGE;
const isVeryLargeTransfer=r=>num(r?.amountUsd)>=VERY_LARGE;
function signed(r){const a=num(r.amountUsd);if(!a)return 0;if(r.direction==='exchange-outflow'||r.direction==='dex-outflow')return a;if(r.direction==='exchange-inflow'||r.direction==='dex-inflow')return-a;return 0}
function walletVolatility(records=[]){if(!records.length)return 0;const amounts=records.map(r=>Math.log10(Math.max(1,num(r.amountUsd)))),avg=amounts.reduce((a,b)=>a+b,0)/amounts.length,variance=amounts.reduce((s,x)=>s+(x-avg)*(x-avg),0)/amounts.length;const large=records.filter(isLargeTransfer).length/records.length;const dirs=Math.abs(records.reduce((s,r)=>s+Math.sign(signed(r)),0))/records.length;return clamp(Math.sqrt(variance)*22+large*45+dirs*25+Math.min(20,records.length/3))}
function windowRows(rows,now,ms){return rows.filter(r=>now-new Date(r.timestamp).getTime()<=ms&&now-new Date(r.timestamp).getTime()>=0)}
function summarize(rows,now){const windows={h1:windowRows(rows,now,3600000),h4:windowRows(rows,now,14400000),h24:windowRows(rows,now,86400000)};const net=x=>x.reduce((s,r)=>s+signed(r),0),large=x=>x.filter(isLargeTransfer).reduce((s,r)=>s+signed(r),0),ex=x=>x.reduce((s,r)=>s+(r.direction==='exchange-inflow'?-num(r.amountUsd):r.direction==='exchange-outflow'?num(r.amountUsd):0),0),dx=x=>x.reduce((s,r)=>s+(r.direction==='dex-inflow'?-num(r.amountUsd):r.direction==='dex-outflow'?num(r.amountUsd):0),0);const addresses=x=>new Set(x.flatMap(r=>[r.fromAddress,r.toAddress]).filter(Boolean));return {netFlow1hUsd:net(windows.h1),netFlow4hUsd:net(windows.h4),netFlow24hUsd:net(windows.h24),largeWalletNetFlowUsd:large(windows.h24),exchangeNetFlowUsd:ex(windows.h24),dexNetFlowUsd:dx(windows.h24),activeWalletCount:addresses(windows.h24).size,activeWalletDelta:addresses(windows.h1).size-addresses(windowRows(rows,now-3600000,3600000)).size,newLargeWalletCount:new Set(windows.h1.filter(isLargeTransfer).flatMap(r=>[r.fromAddress,r.toAddress]).filter(Boolean)).size,walletVolatility:walletVolatility(windows.h24),dataConfidence:rows.length?Math.round(rows.reduce((s,r)=>s+num(r.confidence),0)/rows.length):0}}
function aggregateFlows(records=[],options={}){const now=Number(options.now||Date.now()),seen=new Set(),clean=[];for(const r of records){const k=`${r.chain}:${r.txHash}:${r.eventIndex??0}`;if(!r?.tokenAddress||seen.has(k))continue;seen.add(k);clean.push(r)}const byToken=new Map();for(const r of clean){const k=`${r.chain}:${String(r.tokenAddress).toLowerCase()}`;if(!byToken.has(k))byToken.set(k,[]);byToken.get(k).push(r)}const tokenFlows=[];for(const [key,rows] of byToken){const [chain,...rest]=key.split(':'),tokenAddress=rest.join(':'),s=summarize(rows,now);tokenFlows.push({chain,tokenAddress,symbol:rows.find(r=>r.symbol)?.symbol||null,theme:options.themeForToken?options.themeForToken({chain,tokenAddress,symbol:rows.find(r=>r.symbol)?.symbol||null}):'Other / Unclassified',...s})}const byTheme=new Map();for(const t of tokenFlows){const k=t.theme||'Other / Unclassified';if(!byTheme.has(k))byTheme.set(k,[]);byTheme.get(k).push(t)}const themeFlows=[];for(const [theme,rows] of byTheme){const sum=k=>rows.reduce((s,r)=>s+num(r[k]),0),avg=k=>rows.length?rows.reduce((s,r)=>s+num(r[k]),0)/rows.length:0;themeFlows.push({theme,netFlow1hUsd:sum('netFlow1hUsd'),netFlow4hUsd:sum('netFlow4hUsd'),netFlow24hUsd:sum('netFlow24hUsd'),largeWalletNetFlowUsd:sum('largeWalletNetFlowUsd'),exchangeNetFlowUsd:sum('exchangeNetFlowUsd'),dexNetFlowUsd:sum('dexNetFlowUsd'),activeWalletDelta:sum('activeWalletDelta'),walletVolatility:avg('walletVolatility'),walletFlowConfidence:avg('dataConfidence'),positiveTokenCount:rows.filter(r=>r.netFlow24hUsd>0).length,negativeTokenCount:rows.filter(r=>r.netFlow24hUsd<0).length})}const totalAbs=themeFlows.reduce((s,t)=>s+Math.abs(t.netFlow24hUsd),0);for(const t of themeFlows)t.flowConcentrationShare=totalAbs?Math.abs(t.netFlow24hUsd)/totalAbs:0;themeFlows.sort((a,b)=>Math.abs(b.netFlow24hUsd)-Math.abs(a.netFlow24hUsd));return {tokenFlows,themeFlows}}
module.exports={LARGE,VERY_LARGE,isLargeTransfer,isVeryLargeTransfer,walletVolatility,aggregateFlows};
