const evm=require('./evm');
const sol=require('./solana');

const CHAINS=['solana','ethereum','base','bsc'];
async function fetchJson(url,options={},ms=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{...options,signal:c.signal,headers:{'content-type':'application/json','user-agent':'PulseRadar-Pro-v3',...(options.headers||{})}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function parseAssets(input){const out=[];for(const x of input||[]){if(!x)continue;if(typeof x==='string'){const i=x.indexOf(':');if(i>0)out.push({chain:x.slice(0,i).toLowerCase(),address:x.slice(i+1)})}else if(x.chain&&x.address)out.push({chain:String(x.chain).toLowerCase(),address:String(x.address),symbol:x.symbol||null})}return out.filter(x=>CHAINS.includes(x.chain)).slice(0,24)}
async function pricesFor(assets){const map=new Map(),groups={};for(const a of assets)(groups[a.chain]??=[]).push(a.address);for(const [chain,addresses] of Object.entries(groups)){for(let i=0;i<addresses.length;i+=30){try{const rows=await fetchJson(`https://api.dexscreener.com/tokens/v1/${encodeURIComponent(chain)}/${addresses.slice(i,i+30).join(',')}`,{},5000);for(const p of rows||[]){const token=String(p.baseToken?.address||'').toLowerCase(),price=Number(p.priceUsd);if(token&&Number.isFinite(price)&&price>0)map.set(`${chain}:${token}`,price)}}catch{}}}return map}
function withPrice(records,prices){return records.map(r=>{if(Number.isFinite(Number(r.amountUsd)))return r;const p=prices.get(`${r.chain}:${String(r.tokenAddress||'').toLowerCase()}`),a=Number(r.amountToken);return {...r,amountUsd:Number.isFinite(p)&&Number.isFinite(a)?p*a:null}})}
async function fetchGenericFeed(assets){const url=process.env.ONCHAIN_FLOW_FEED_URL;if(!url)return[];const u=new URL(url);if(assets.length)u.searchParams.set('assets',assets.map(a=>`${a.chain}:${a.address}`).join(','));const d=await fetchJson(u.toString(),{},8000);return Array.isArray(d)?d:(d.records||d.transfers||[])}
function alchemyBase(chain,key){const overrides={ethereum:process.env.ALCHEMY_ETHEREUM_URL,base:process.env.ALCHEMY_BASE_URL,bsc:process.env.ALCHEMY_BSC_URL};if(overrides[chain])return overrides[chain];const host={ethereum:'eth-mainnet',base:'base-mainnet',bsc:'bnb-mainnet'}[chain];return host&&key?`https://${host}.g.alchemy.com/v2/${key}`:null}
async function fetchAlchemy(chain,assets,key){const url=alchemyBase(chain,key),records=[];if(!url)return records;for(const a of assets.filter(x=>x.chain===chain).slice(0,8)){try{const body={jsonrpc:'2.0',id:1,method:'alchemy_getAssetTransfers',params:[{fromBlock:'0x0',toBlock:'latest',contractAddresses:[a.address],category:['erc20'],withMetadata:true,excludeZeroValue:true,maxCount:'0x32',order:'desc'}]};const d=await fetchJson(url,{method:'POST',body:JSON.stringify(body)},8000);for(const x of d?.result?.transfers||[]){const r=evm.normalizeEvmTransfer({hash:x.hash,blockTimestamp:x.metadata?.blockTimestamp,contractAddress:x.rawContract?.address||a.address,from:x.from,to:x.to,value:x.value,asset:x.asset,usdValue:null,logIndex:x.uniqueId?parseInt(String(x.uniqueId).split(':').pop(),16)||0:0,confidence:80},{chain,confidence:80});if(r)records.push(r)}}catch{}}
  return records}
async function fetchHelius(assets,key){const records=[];if(!key)return records;for(const a of assets.filter(x=>x.chain==='solana').slice(0,8)){try{const d=await fetchJson(`https://api.helius.xyz/v0/addresses/${encodeURIComponent(a.address)}/transactions?api-key=${encodeURIComponent(key)}&limit=50`,{},8000);for(const tx of d||[])for(let i=0;i<(tx.tokenTransfers||[]).length;i++){const x=tx.tokenTransfers[i];if(String(x.mint||'')!==a.address)continue;const r=sol.normalizeSolanaTransfer({signature:tx.signature,timestamp:tx.timestamp,mint:x.mint,from:x.fromUserAccount||x.fromTokenAccount,to:x.toUserAccount||x.toTokenAccount,amount:x.tokenAmount,symbol:a.symbol,index:i,confidence:82},{confidence:82});if(r)records.push(r)}}catch{}}
  return records}
async function fetchOnchainEvents(options={}){const assets=parseAssets(options.assets),health={solana:'degraded',ethereum:'degraded',base:'degraded',bsc:'degraded'},records=[];const keyA=process.env.ALCHEMY_API_KEY||'',keyH=process.env.HELIUS_API_KEY||'';
  try{const generic=await fetchGenericFeed(assets);if(generic.length){records.push(...generic);for(const c of CHAINS)if(generic.some(r=>String(r.chain).toLowerCase()===c))health[c]='live'}}catch{}
  const prices=await pricesFor(assets);
  const evmResults=await Promise.all(['ethereum','base','bsc'].map(async chain=>{const r=await fetchAlchemy(chain,assets,keyA);if(r.length)health[chain]='live';else if(keyA||alchemyBase(chain,keyA))health[chain]='configured';return r}));
  const sr=await fetchHelius(assets,keyH);if(sr.length)health.solana='live';else if(keyH)health.solana='configured';
  records.push(...evmResults.flat(),...sr);return {records:withPrice(records,prices),providerHealth:health,configured:{generic:Boolean(process.env.ONCHAIN_FLOW_FEED_URL),alchemy:Boolean(keyA),helius:Boolean(keyH)}}}
module.exports={CHAINS,parseAssets,fetchOnchainEvents};
