const evm=require('./evm');
const sol=require('./solana');

const CHAINS=['solana','ethereum','base','bsc'];
const TRANSFER_TOPIC='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
const EVM_BLOCK_SECONDS={ethereum:12,base:2,bsc:3};
const EVM_BLOCK_SPAN={ethereum:360,base:1800,bsc:1200};

async function fetchJson(url,options={},ms=7000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{...options,signal:c.signal,headers:{'content-type':'application/json','user-agent':'PulseRadar-Pro-v3',...(options.headers||{})}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function rpc(url,method,params=[],ms=7000){const d=await fetchJson(url,{method:'POST',body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})},ms);if(d&&d.error)throw new Error(d.error.message||`RPC ${method} failed`);return d?.result}
function publicRpcFor(chain){const c=String(chain||'').toLowerCase();if(c==='solana')return process.env.SOLANA_PUBLIC_RPC_URL||'https://api.mainnet-beta.solana.com';if(c==='ethereum')return process.env.ETHEREUM_PUBLIC_RPC_URL||'https://cloudflare-eth.com';if(c==='base')return process.env.BASE_PUBLIC_RPC_URL||'https://mainnet.base.org';if(c==='bsc')return process.env.BSC_PUBLIC_RPC_URL||'https://bsc-dataseed.binance.org';return null}
function parseAssets(input){const out=[];for(const x of input||[]){if(!x)continue;if(typeof x==='string'){const i=x.indexOf(':');if(i<=0)continue;const chain=x.slice(0,i).toLowerCase(),parts=x.slice(i+1).split('~');out.push({chain,address:parts[0],pairAddress:parts[1]||null,symbol:parts[2]||null})}else if(x.chain&&x.address)out.push({chain:String(x.chain).toLowerCase(),address:String(x.address),pairAddress:x.pairAddress?String(x.pairAddress):null,symbol:x.symbol||null})}return out.filter(x=>CHAINS.includes(x.chain)&&x.address).slice(0,24)}
async function pricesFor(assets){const map=new Map(),groups={};for(const a of assets)(groups[a.chain]??=[]).push(a.address);for(const [chain,addresses] of Object.entries(groups)){for(let i=0;i<addresses.length;i+=30){try{const rows=await fetchJson(`https://api.dexscreener.com/tokens/v1/${encodeURIComponent(chain)}/${addresses.slice(i,i+30).join(',')}`,{},5000);for(const p of rows||[]){const token=String(p.baseToken?.address||'').toLowerCase(),price=Number(p.priceUsd);if(token&&Number.isFinite(price)&&price>0)map.set(`${chain}:${token}`,price)}}catch{}}}return map}
function withPrice(records,prices){return records.map(r=>{if(Number.isFinite(Number(r.amountUsd)))return r;const p=prices.get(`${r.chain}:${String(r.tokenAddress||'').toLowerCase()}`),a=Number(r.amountToken);return {...r,amountUsd:Number.isFinite(p)&&Number.isFinite(a)?p*a:null}})}
function topicAddress(address){const h=String(address||'').toLowerCase().replace(/^0x/,'');return /^([0-9a-f]{40})$/.test(h)?'0x'+h.padStart(64,'0'):null}
function topicToAddress(topic){const h=String(topic||'').toLowerCase().replace(/^0x/,'');return h.length>=40?'0x'+h.slice(-40):null}
function hexInt(v){const n=parseInt(String(v||'0x0'),16);return Number.isFinite(n)?n:0}
function tokenAmount(hex,decimals){try{const raw=BigInt(String(hex||'0x0')),d=Math.max(0,Math.min(30,Number(decimals)||0));return Number(raw)/Math.pow(10,d)}catch{return null}}
function parsePublicEvmLog(log={},asset={},context={}){if(!Array.isArray(log.topics)||log.topics.length<3||String(log.topics[0]).toLowerCase()!==TRANSFER_TOPIC)return null;const from=topicToAddress(log.topics[1]),to=topicToAddress(log.topics[2]);if(!from||!to)return null;const amountToken=tokenAmount(log.data,context.decimals??18);if(!Number.isFinite(amountToken)||amountToken<=0)return null;const latest=Number(context.latestBlock||0),bn=hexInt(log.blockNumber),secs=Number(EVM_BLOCK_SECONDS[asset.chain]||3),now=Number(context.now||Date.now()),timestamp=new Date(now-Math.max(0,latest-bn)*secs*1000).toISOString();const r=evm.normalizeEvmTransfer({hash:log.transactionHash,logIndex:hexInt(log.logIndex),blockTimestamp:timestamp,contractAddress:asset.address,from,to,value:amountToken,asset:asset.symbol||null,confidence:64},{chain:asset.chain,confidence:64});if(!r)return null;const pair=String(asset.pairAddress||'').toLowerCase();if(pair&&String(to).toLowerCase()===pair){r.toType='dex';r.toLabel='Tracked DEX Pool';r.direction='dex-inflow';r.confidence=Math.max(r.confidence,68)}else if(pair&&String(from).toLowerCase()===pair){r.fromType='dex';r.fromLabel='Tracked DEX Pool';r.direction='dex-outflow';r.confidence=Math.max(r.confidence,68)}r.source='public-rpc';return r}
async function evmDecimals(url,address){try{const x=await rpc(url,'eth_call',[{to:address,data:'0x313ce567'},'latest'],4500),n=hexInt(x);return n>=0&&n<=30?n:18}catch{return 18}}
async function fetchPublicEvm(chain,assets){const url=publicRpcFor(chain),rows=assets.filter(a=>a.chain===chain&&/^0x[0-9a-fA-F]{40}$/.test(a.address)&&/^0x[0-9a-fA-F]{40}$/.test(a.pairAddress||'')).slice(0,5);if(!url||!rows.length)return {records:[],ok:false};let latest;try{latest=hexInt(await rpc(url,'eth_blockNumber',[],5000))}catch{return {records:[],ok:false}}const from='0x'+Math.max(0,latest-(EVM_BLOCK_SPAN[chain]||600)).toString(16),to='0x'+latest.toString(16),records=[];for(const a of rows){try{const decimals=await evmDecimals(url,a.address),pairTopic=topicAddress(a.pairAddress);if(!pairTopic)continue;const filters=[{fromBlock:from,toBlock:to,address:a.address,topics:[TRANSFER_TOPIC,pairTopic]},{fromBlock:from,toBlock:to,address:a.address,topics:[TRANSFER_TOPIC,null,pairTopic]}];const got=await Promise.allSettled(filters.map(f=>rpc(url,'eth_getLogs',[f],6500)));for(const result of got)if(result.status==='fulfilled')for(const log of (result.value||[]).slice(-180)){const r=parsePublicEvmLog(log,a,{decimals,latestBlock:latest,now:Date.now()});if(r)records.push(r)}}catch{}}
  return {records,ok:true}}
function accountPubkey(x){return typeof x==='string'?x:String(x?.pubkey||'')}
function uiAmount(x){const u=x?.uiTokenAmount||{};const n=Number(u.uiAmountString??u.uiAmount);return Number.isFinite(n)?n:null}
function parseSolanaWhaleDelta(tx={},asset={},tokenAccount){const keys=tx?.transaction?.message?.accountKeys||[],index=keys.findIndex(k=>accountPubkey(k)===tokenAccount);if(index<0)return null;const pre=(tx?.meta?.preTokenBalances||[]).find(x=>x.accountIndex===index&&String(x.mint)===String(asset.address)),post=(tx?.meta?.postTokenBalances||[]).find(x=>x.accountIndex===index&&String(x.mint)===String(asset.address));const before=uiAmount(pre),after=uiAmount(post);if(before==null&&after==null)return null;const delta=(after||0)-(before||0);if(!Number.isFinite(delta)||Math.abs(delta)<1e-15)return null;const owner=String(post?.owner||pre?.owner||tokenAccount),incoming=delta>0,placeholder='unattributed';const r=sol.normalizeSolanaTransfer({signature:tx?.transaction?.signatures?.[0]||'',timestamp:tx.blockTime,mint:asset.address,from:incoming?placeholder:owner,to:incoming?owner:placeholder,amount:Math.abs(delta),symbol:asset.symbol||null,index,confidence:58},{confidence:58});if(!r)return null;r.direction=incoming?'wallet-inflow':'wallet-outflow';r.fromAddress=incoming?null:owner;r.toAddress=incoming?owner:null;r.fromLabel=incoming?null:r.fromLabel;r.toLabel=incoming?r.toLabel:null;r.source='solana-public-rpc';return r}
async function fetchPublicSolana(assets){const url=publicRpcFor('solana'),rows=assets.filter(a=>a.chain==='solana').slice(0,2);if(!url||!rows.length)return {records:[],ok:false};const records=[];let ok=false;for(const a of rows){try{const largest=await rpc(url,'getTokenLargestAccounts',[a.address,{commitment:'confirmed'}],5500);ok=true;for(const holder of (largest?.value||[]).slice(0,2)){try{const sigs=await rpc(url,'getSignaturesForAddress',[holder.address,{limit:1,commitment:'confirmed'}],4500);for(const s of sigs||[]){try{const tx=await rpc(url,'getTransaction',[s.signature,{encoding:'jsonParsed',commitment:'confirmed',maxSupportedTransactionVersion:0}],5500);const r=parseSolanaWhaleDelta(tx,a,holder.address);if(r)records.push(r)}catch{}}}catch{}}}catch{}}
  return {records,ok}}
async function fetchGenericFeed(assets){const url=process.env.ONCHAIN_FLOW_FEED_URL;if(!url)return[];const u=new URL(url);if(assets.length)u.searchParams.set('assets',assets.map(a=>`${a.chain}:${a.address}`).join(','));const d=await fetchJson(u.toString(),{},8000);return Array.isArray(d)?d:(d.records||d.transfers||[])}
function alchemyBase(chain,key){const overrides={ethereum:process.env.ALCHEMY_ETHEREUM_URL,base:process.env.ALCHEMY_BASE_URL,bsc:process.env.ALCHEMY_BSC_URL};if(overrides[chain])return overrides[chain];const host={ethereum:'eth-mainnet',base:'base-mainnet',bsc:'bnb-mainnet'}[chain];return host&&key?`https://${host}.g.alchemy.com/v2/${key}`:null}
async function fetchAlchemy(chain,assets,key){const url=alchemyBase(chain,key),records=[];if(!url)return records;for(const a of assets.filter(x=>x.chain===chain).slice(0,8)){try{const body={jsonrpc:'2.0',id:1,method:'alchemy_getAssetTransfers',params:[{fromBlock:'0x0',toBlock:'latest',contractAddresses:[a.address],category:['erc20'],withMetadata:true,excludeZeroValue:true,maxCount:'0x32',order:'desc'}]};const d=await fetchJson(url,{method:'POST',body:JSON.stringify(body)},8000);for(const x of d?.result?.transfers||[]){const r=evm.normalizeEvmTransfer({hash:x.hash,blockTimestamp:x.metadata?.blockTimestamp,contractAddress:x.rawContract?.address||a.address,from:x.from,to:x.to,value:x.value,asset:x.asset,usdValue:null,logIndex:x.uniqueId?parseInt(String(x.uniqueId).split(':').pop(),16)||0:0,confidence:80},{chain,confidence:80});if(r)records.push(r)}}catch{}}
  return records}
async function fetchHelius(assets,key){const records=[];if(!key)return records;for(const a of assets.filter(x=>x.chain==='solana').slice(0,8)){try{const d=await fetchJson(`https://api.helius.xyz/v0/addresses/${encodeURIComponent(a.address)}/transactions?api-key=${encodeURIComponent(key)}&limit=50`,{},8000);for(const tx of d||[])for(let i=0;i<(tx.tokenTransfers||[]).length;i++){const x=tx.tokenTransfers[i];if(String(x.mint||'')!==a.address)continue;const r=sol.normalizeSolanaTransfer({signature:tx.signature,timestamp:tx.timestamp,mint:x.mint,from:x.fromUserAccount||x.fromTokenAccount,to:x.toUserAccount||x.toTokenAccount,amount:x.tokenAmount,symbol:a.symbol,index:i,confidence:82},{confidence:82});if(r)records.push(r)}}catch{}}
  return records}
async function fetchOnchainEvents(options={}){const assets=parseAssets(options.assets),health={solana:'degraded',ethereum:'degraded',base:'degraded',bsc:'degraded'},records=[];const keyA=process.env.ALCHEMY_API_KEY||'',keyH=process.env.HELIUS_API_KEY||'';
  try{const generic=await fetchGenericFeed(assets);if(generic.length){records.push(...generic);for(const c of CHAINS)if(generic.some(r=>String(r.chain).toLowerCase()===c))health[c]='live'}}catch{}
  const [prices,solPublic,...evmPublic]=await Promise.all([pricesFor(assets),fetchPublicSolana(assets),...['ethereum','base','bsc'].map(c=>fetchPublicEvm(c,assets))]);if(solPublic.ok)health.solana='live';records.push(...solPublic.records);for(let i=0;i<evmPublic.length;i++){const chain=['ethereum','base','bsc'][i],result=evmPublic[i];if(result.ok)health[chain]='live';records.push(...result.records)}
  const evmResults=await Promise.all(['ethereum','base','bsc'].map(async chain=>{const r=await fetchAlchemy(chain,assets,keyA);if(r.length)health[chain]='live';else if(keyA||alchemyBase(chain,keyA))health[chain]=health[chain]==='live'?'live':'configured';return r}));
  const sr=await fetchHelius(assets,keyH);if(sr.length)health.solana='live';else if(keyH&&health.solana!=='live')health.solana='configured';
  records.push(...evmResults.flat(),...sr);return {records:withPrice(records,prices),providerHealth:health,configured:{publicRpc:true,generic:Boolean(process.env.ONCHAIN_FLOW_FEED_URL),alchemy:Boolean(keyA),helius:Boolean(keyH)}}}
module.exports={CHAINS,TRANSFER_TOPIC,parseAssets,publicRpcFor,parsePublicEvmLog,parseSolanaWhaleDelta,fetchOnchainEvents};
