(()=>{'use strict';
const $=id=>document.getElementById(id),state={running:false,controller:null,rows:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'-';
const pct=v=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}%`:'-';
const chunks=(a,n)=>{const out=[];for(let i=0;i<a.length;i+=n)out.push(a.slice(i,i+n));return out};
async function get(stage,symbols=[]){const q=new URLSearchParams({stage,fresh:'1'});if(symbols.length)q.set('symbols',symbols.join(','));const r=await fetch('/api/astra-scan?'+q,{cache:'no-store',signal:state.controller.signal});const x=await r.json().catch(()=>({status:'error',error:'invalid response'}));if(!r.ok||x.status!=='ok')throw new Error(x.error||`HTTP ${r.status}`);return x}
function setStatus(s){$('astraStatus').textContent=s}
function tfLine(x){const tf=x.tf||{},one=k=>{const m=tf[k]||{};return `${k.toUpperCase()} RSI ${fmt(m.rsi14,1)} · RVOL ${fmt(m.rvol,2)}x${m.above20===true?' · >20':' '}`};return [one('4h'),one('1h'),one('15m'),one('5m')].join('<br>')}
function card(x){const v=x.verdict||{},reasons=(v.reasons||[]).slice(0,5).map(r=>`<li>${esc(r)}</li>`).join('');return `<article class="card ${esc(v.key||'HOLD')}"><div class="cardTop"><div class="symbol">${esc(x.symbol)}</div><div class="badge">${esc(v.label||'보류')}</div></div><div class="score">Astra ${fmt(v.score,0)}점 · 24H ${pct(x.priceChange24h)} · $${Number(x.quoteVolume24h||0).toLocaleString('en-US',{maximumFractionDigits:0})}</div><div class="metrics"><div class="metric"><span>OI 4H</span><b>${pct(x.oi4hPct)}</b></div><div class="metric"><span>OI 8H</span><b>${pct(x.oi8hPct)}</b></div><div class="metric"><span>15m taker</span><b>${fmt(x.taker15m,2)}</b></div><div class="metric"><span>5m taker</span><b>${fmt(x.taker5m,2)}</b></div><div class="metric"><span>15m RVOL</span><b>${fmt(x.tf?.['15m']?.rvol,2)}x</b></div><div class="metric"><span>5m RVOL</span><b>${fmt(x.tf?.['5m']?.rvol,2)}x</b></div></div><div class="tf">${tfLine(x)}</div><ul class="reasons">${reasons}</ul></article>`}
function render(){const box=$('astraResults');if(!state.rows.length){box.innerHTML='<div class="empty">OI +1% 통과 종목이 없거나 정밀 결과가 없습니다.</div>';return}box.innerHTML=state.rows.map(card).join('')}
async function run(){if(state.running)return;state.running=true;state.controller=new AbortController();$('astraRun').disabled=true;state.rows=[];render();try{
 setStatus('1/3 · Binance USDT 무기한 전체와 가격·유동성을 확인 중…');const u=await get('universe');$('universeCount').textContent=u.universeCount;$('filteredCount').textContent=u.filteredCount;$('oiCount').textContent='0';$('deepCount').textContent='0';const b=u.breadth||{};$('astraBreadth').textContent=`시장 폭 ${b.total||0}개 중 상승 ${b.up||0} · 하락 ${b.down||0} · BTC ${pct(u.majors?.BTCUSDT?.priceChange24h)} · ETH ${pct(u.majors?.ETHUSDT?.priceChange24h)}`;
 const filtered=u.items||[],oiRows=[];let done=0;for(const chunk of chunks(filtered.map(x=>x.symbol),16)){const x=await get('oi',chunk);oiRows.push(...(x.items||[]));done+=chunk.length;setStatus(`2/3 · 4H OI 계약수 전수검사 ${done}/${filtered.length}`)}
 const pass=oiRows.filter(x=>x.pass).map(x=>x.symbol);$('oiCount').textContent=pass.length;if(!pass.length){setStatus('완료 · 4H OI +1% 통과 종목 없음');render();return}
 const deep=[];done=0;for(const chunk of chunks(pass,2)){const x=await get('deep',chunk);deep.push(...(x.items||[]));done+=chunk.length;$('deepCount').textContent=done;setStatus(`3/3 · 주봉~5분봉 정밀검사 ${done}/${pass.length}`)}
 const order={IGNITION_CONFIRMED:0,WATCH_PRIORITY:1,WAIT:2,HOLD:3,PROGRESSED:4};state.rows=deep.sort((a,b)=>(order[a.verdict?.key]??9)-(order[b.verdict?.key]??9)||(b.verdict?.score||0)-(a.verdict?.score||0));render();const ign=state.rows.filter(x=>x.verdict?.key==='IGNITION_CONFIRMED').length,watch=state.rows.filter(x=>x.verdict?.key==='WATCH_PRIORITY').length;setStatus(`완료 · ${u.universeCount} → ${u.filteredCount} → OI 통과 ${pass.length} → 점화 확정 ${ign} · 관찰 우선 ${watch}`)
 }catch(e){if(e?.name!=='AbortError')setStatus('스캔 실패 · '+String(e?.message||e))}finally{state.running=false;$('astraRun').disabled=false}}
$('astraRun')?.addEventListener('click',run);
})();