(()=>{'use strict';
const $=id=>document.getElementById(id),state={running:false,controller:null,rows:[],method:'astra'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'-';
const pct=v=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(2)}%`:'-';
const chunks=(a,n)=>{const out=[];for(let i=0;i<a.length;i+=n)out.push(a.slice(i,i+n));return out};
const quantile=(a,p=.5)=>{const x=a.map(Number).filter(Number.isFinite).sort((m,n)=>m-n);if(!x.length)return null;const i=(x.length-1)*Math.max(0,Math.min(1,p)),lo=Math.floor(i),hi=Math.ceil(i);return lo===hi?x[lo]:x[lo]+(x[hi]-x[lo])*(i-lo)};
const MODE={
 astra:{description:'Binance USDT 무기한 전체 → ±10%·거래대금 1,000만 USDT → 4H OI +1% → 1W·3D·1D·12H·4H·2H·1H·15m·5m 확정봉 정밀검사',hint:'빠르게 OI·RVOL·Taker 점화 조건을 찾는 현재 Astra 방식입니다.',legend:'<span class="ignite">🔥 점화 확정</span><span class="watch">🟡 관찰 우선</span><span>⚪ 점화 대기</span><span>⏸ 보류</span><span>🔵 이미 진행</span>'},
 manus:{description:'전체 선물 유니버스 → OI 전수검사 감사 → 1W·1D·4H·1H·15m·5m 확정봉 → Taker 2소스 → 현물·펀딩·breadth → 100점 전문 분류',hint:'Manus 설계 기준으로 검색 후보 → Trade Setup → Execution-ready Signal을 분리하고 A_FIRE / B_PREPARE / C_WATCH / HOLD / EXCLUDE로 분류합니다.',legend:'<span class="fire">🔥 A_FIRE</span><span class="prepare">🟡 B_PREPARE</span><span>⚪ C_WATCH</span><span>⏸ HOLD</span><span>⛔ EXCLUDE</span>'},
 perplexity:{description:'동일 server-time 스냅샷 → 필터 전 종목 OI 종결상태 → 1W·1D·4H·1H·15m·5m 확정봉 → true taker 구간 정렬 → 현물·펀딩·breadth → 반증 포함 단계 분류',hint:'Perplexity 방식은 OI를 후보 자격으로만 쓰고 1H·15m가 라벨과 방향을 결정합니다. 5m는 실행 참고만 하며 PRE-SURGE와 IGNITION의 RVOL 기준을 분리합니다.',legend:'<span>⚪ OI_BUILD</span><span class="accum">🟢 ACCUMULATION</span><span class="prepare">🟡 TRANSITION</span><span class="fire">🔥 IGNITION</span><span class="risk">🟠 SHORT_BUILD_RISK</span><span>🔵 OVERHEATED</span><span>⚠ DATA_DEGRADED</span>'},
 grok:{description:'동적 거래대금 필터 → OI 상대 상위 20% 또는 절대 +1.5% → OI 절대규모 → 세션 정규화 RVOL → HTF 정렬 → Taker 5봉 연속성 → Basis·Funding·Spot/Futures 거래대금 괴리 → 게이트+점수',hint:'Grok 방식은 절대 컷을 고정하지 않고 시장 유동성·OI 상대랭킹·연속 체결강도를 함께 봅니다. 동적 파라미터는 전진검증 전까지 가설값입니다.',legend:'<span class="fire">🔥 GROK_FIRE</span><span class="prepare">🟡 GROK_READY</span><span>⚪ GROK_INTEREST</span><span>⏸ GROK_HOLD</span><span>⛔ GROK_EXCLUDE</span>'},
 gemini:{description:'기본 Astra 필터 → 시장 breadth별 동적 OI 컷 → 가격/OI 상대 모멘텀 → 1W~5m 확정봉 → 시간대 정규화 RVOL → Taker 연속성 → Sweep+Taker 결합 → 현물·Funding',hint:'Gemini 방식은 강세장/중립/약세장마다 OI 문턱을 바꾸고, 가격 대비 OI 증가와 Sweep 순간 체결강도를 결합합니다.',legend:'<span class="fire">🔥 GEMINI_ALPHA</span><span class="prepare">🟡 GEMINI_READY</span><span>⚪ GEMINI_WATCH</span><span>⏸ GEMINI_HOLD</span><span class="risk">🟠 GEMINI_RISK</span>'},
 claude:{description:'거래대금 퍼센타일 필터 → OI 0~4H / 4~8H / 8~12H 경로 분해 → +/+/+ BUILD·-/+/+ CLEAN→REBUILD만 승격 → HTF discount/premium → 1W~5m 확정봉 → 보수적 Taker → DIRECTION_CONFIRM → A-pre~NFB 라벨',hint:'Claude 방식은 Astra의 수집·교차검증과 SURGE v2 판정을 합친 v3입니다. 1H·15m가 방향을 결정하고 5m는 참고용입니다.',legend:'<span class="prepare">A-pre</span><span>A</span><span>A→A+B</span><span class="fire">A+B</span><span>B</span><span class="accum">C</span><span>NFB</span><span>NFB-SQ</span><span class="risk">NFB-SC</span><span>미완성</span>'}
};
function method(){const v=$('scanMethod')?.value;return v==='manus'?'manus':v==='perplexity'?'perplexity':v==='grok'?'grok':v==='gemini'?'gemini':v==='claude'?'claude':'astra'}
function syncMethod(){state.method=method();const m=MODE[state.method];$('methodDescription').textContent=m.description;$('methodHint').textContent=m.hint;$('astraLegend').innerHTML=m.legend;$('oiGateLabel').textContent=state.method==='grok'?'OI 상대/절대':state.method==='gemini'?'OI 동적컷':state.method==='claude'?'OI 경로':'OI +1%';$('astraAudit').textContent=state.method==='perplexity'?'OI 조회 감사: 요청·성공·실패·결측·구간불일치·통과 수를 모두 종결 상태로 기록합니다.':state.method==='grok'?'OI 조회 감사: 성공 종목 전체에서 상대 상위 20% 컷 + OI 가치 500만 USDT 조건을 적용합니다.':state.method==='gemini'?'OI 조회 감사: breadth에 따라 4H OI 컷을 1.0% / 1.5% / 2.5%로 조절합니다.':state.method==='claude'?'OI 조회 감사: 0~4H / 4~8H / 8~12H 경로를 분해해 +/+/+ 또는 -/+/+만 정밀검사로 승격합니다.':state.method==='manus'?'OI 조회 감사: 실행 시 요청·성공·실패·결측·통과 수를 모두 기록합니다.':'OI 조회 감사: 실행 시 전수 조회 수와 통과 수를 표시합니다.'}
async function get(stage,symbols=[],context={}){const q=new URLSearchParams({stage,method:state.method,fresh:'1'});if(symbols.length)q.set('symbols',symbols.join(','));for(const [k,v] of Object.entries(context||{}))if(v!==null&&v!==undefined&&v!=='')q.set(k,String(v));const local='/api/astra-scan?'+q,render='https://pulseradar-selector-runtime.onrender.com/api/astra-scan?'+q,urls=location.hostname==='pulseradar-selector-runtime.onrender.com'?[local]:[local,render];let last=null;for(const url of urls){try{const r=await fetch(url,{cache:'no-store',signal:state.controller.signal});const x=await r.json().catch(()=>({status:'error',error:'invalid response'}));if(r.ok&&x.status==='ok')return x;last=new Error(x.error||`HTTP ${r.status}`)}catch(e){if(e?.name==='AbortError')throw e;last=e}}throw last||new Error('scanner api unavailable')}
function setStatus(s){$('astraStatus').textContent=s}
function tfLine(x){const tf=x.tf||{},keys=state.method==='astra'?['4h','1h','15m','5m']:['1d','4h','1h','15m','5m'],one=k=>{const m=tf[k]||{};return `${k.toUpperCase()} RSI ${fmt(m.rsi14,1)} · RVOL ${fmt(m.rvol,2)}x${m.above20===true?' · >20':''}`};return keys.map(one).join('<br>')}
function layerLabel(v){return v==='EXECUTION_READY_SIGNAL'?'Execution-ready':v==='TRADE_SETUP'?'Trade Setup':'Screened Candidate'}
function astraCard(x){const v=x.verdict||{},reasons=(v.reasons||[]).slice(0,5).map(r=>`<li>${esc(r)}</li>`).join('');return `<article class="card ${esc(v.key||'HOLD')}"><div class="cardTop"><div class="symbol">${esc(x.symbol)}</div><div class="badge">${esc(v.label||'보류')}</div></div><div class="score">Astra ${fmt(v.score,0)}점 · 24H ${pct(x.priceChange24h)} · $${Number(x.quoteVolume24h||0).toLocaleString('en-US',{maximumFractionDigits:0})}</div><div class="metrics"><div class="metric"><span>OI 4H</span><b>${pct(x.oi4hPct)}</b></div><div class="metric"><span>OI 8H</span><b>${pct(x.oi8hPct)}</b></div><div class="metric"><span>15m taker</span><b>${fmt(x.taker15m,2)}</b></div><div class="metric"><span>5m taker</span><b>${fmt(x.taker5m,2)}</b></div><div class="metric"><span>15m RVOL</span><b>${fmt(x.tf?.['15m']?.rvol,2)}x</b></div><div class="metric"><span>5m RVOL</span><b>${fmt(x.tf?.['5m']?.rvol,2)}x</b></div></div><div class="tf">${tfLine(x)}</div><ul class="reasons">${reasons}</ul></article>`}
function crossText(c){if(!c)return'N/A';return `${c.status} · K ${fmt(c.klineRatio,2)} / E ${fmt(c.endpointRatio,2)} · Δ${fmt(c.difference,2)}`}
function manusCard(x){const v=x.verdict||{},b=v.scoreBreakdown||{},q=v.dataQuality||{},spot=v.spotFutures||{},setup=v.tradeSetup||{},reasons=(v.reasons||[]).slice(0,6).map(r=>`<li>${esc(r)}</li>`).join(''),blocks=(v.blocks||[]).slice(0,5).map(r=>`<span>${esc(r)}</span>`).join('');return `<article class="card manus ${esc(v.key||'HOLD')}"><div class="cardTop"><div><div class="symbol">${esc(x.symbol)}</div><div class="layer">${esc(layerLabel(v.layer))}</div></div><div class="badge">${esc(v.label||'HOLD')}</div></div><div class="score">Manus ${fmt(v.score,0)}/100 · 24H ${pct(x.priceChange24h)} · OI4H ${pct(x.oi4hPct)}</div><div class="scoreGrid"><span>시장 <b>${fmt(b.market,0)}/10</b></span><span>가격/OI <b>${fmt(b.priceOi,0)}/15</b></span><span>1W·1D <b>${fmt(b.htf1w1d,0)}/20</b></span><span>4H·1H <b>${fmt(b.mid4h1h,0)}/20</b></span><span>15m·5m <b>${fmt(b.ignition15m5m,0)}/15</b></span><span>현물 <b>${fmt(b.spotCross,0)}/10</b></span><span>펀딩 <b>${fmt(b.funding,0)}/5</b></span><span>품질 <b>${fmt(b.dataQuality,0)}/5</b></span></div><div class="metrics"><div class="metric"><span>15m Taker 교차</span><b>${esc(crossText(x.takerCross?.['15m']))}</b></div><div class="metric"><span>5m Taker 교차</span><b>${esc(crossText(x.takerCross?.['5m']))}</b></div><div class="metric"><span>현물 24H</span><b>${pct(x.spotPriceChange24h)}</b></div><div class="metric"><span>Spot-Futures gap</span><b>${pct(spot.gapPct)}</b></div><div class="metric"><span>Funding</span><b>${pct(x.fundingRatePct)}</b></div><div class="metric"><span>Data Quality</span><b>${esc(q.status||'N/A')}</b></div></div><div class="tf">${tfLine(x)}</div><div class="setup"><b>구조 셋업</b> Entry ${fmt(setup.entry,6)} · Stop ${fmt(setup.stop,6)} · Target ${fmt(setup.target,6)} · R:R ${fmt(setup.riskReward,2)}</div>${blocks?'<div class="blocks">'+blocks+'</div>':''}<ul class="reasons">${reasons}</ul></article>`}
function tagList(xs=[],cls='evidence'){return xs.slice(0,6).map(v=>`<span>${esc(v)}</span>`).join('')}
function perplexityCard(x){const v=x.verdict||{},q=v.dataQuality||{},flags=v.flags||{},pz=v.takerZones||{},positive=tagList(v.positiveEvidence||[],'positive'),counter=tagList(v.counterEvidence||[],'counter'),patterns=tagList(v.patternTags||[]),htf=[];if(flags.htfDiscount)htf.push('1W HTF_DISCOUNT');if(flags.midTermPremium)htf.push('1D MID_TERM_PREMIUM');if(flags.nfbHint)htf.push('NFB_HINT');return `<article class="card perplexity ${esc(v.key||'INCOMPLETE')}"><div class="cardTop"><div><div class="symbol">${esc(x.symbol)}</div><div class="layer">${esc(v.stage||'INCOMPLETE')} · ${esc(v.direction||'NEUTRAL')} · 우선도 ${fmt(v.priority,0)}</div></div><div class="badge">${esc(v.label||'INCOMPLETE')}</div></div><div class="score">Perplexity · 24H ${pct(x.priceChange24h)} · OI4H ${pct(x.oi4hPct)} · OI8H ${pct(x.oi8hPct)}</div><div class="metrics"><div class="metric"><span>1H true taker</span><b>${esc(crossText(x.takerCross?.['1h']))}<br>${esc(pz['1h']||'N/A')}</b></div><div class="metric"><span>15m true taker</span><b>${esc(crossText(x.takerCross?.['15m']))}<br>${esc(pz['15m']||'N/A')}</b></div><div class="metric"><span>15m RVOL</span><b>${fmt(x.tf?.['15m']?.rvol,2)}x</b></div><div class="metric"><span>5m 참고 전용</span><b>RVOL ${fmt(x.tf?.['5m']?.rvol,2)}x · ${esc(pz['5m']||'N/A')}</b></div><div class="metric"><span>현물 24H</span><b>${pct(x.spotPriceChange24h)} · ${esc(q.spotStatus||'N/A')}</b></div><div class="metric"><span>Funding</span><b>${pct(x.fundingRatePct)}</b></div><div class="metric"><span>OKX 상태</span><b>${esc(x.crossExchange?.okxStatus||'N/A')}</b></div><div class="metric"><span>Data Quality</span><b>${esc(q.status||'N/A')} / ${esc(v.crossValidationQuality||'N/A')}</b></div></div><div class="tf">${tfLine(x)}</div>${patterns?'<div class="patterns"><b>패턴</b><div class="patternTags">'+patterns+'</div></div>':''}${htf.length?'<div class="flags">'+tagList(htf)+'</div>':''}<div class="evidenceBox"><b>긍정 근거</b><div class="positiveTags">${positive||'<span>없음</span>'}</div></div><div class="counterBox"><b>정량 반증</b><div class="counterTags">${counter}</div></div><div class="next"><b>다음 확인</b> ${esc(v.nextConfirmation||'-')} · <b>무효화</b> ${fmt(v.invalidationLevel,6)}</div></article>`}
function grokCard(x){const v=x.verdict||{},tc=v.takerContinuity||{},rv=v.sessionRvol||{},dyn=v.dynamic||{},reasons=tagList(v.reasons||[]),risks=tagList(v.risks||[]);return `<article class="card grok ${esc(v.key||'GROK_HOLD')}"><div class="cardTop"><div><div class="symbol">${esc(x.symbol)}</div><div class="layer">동적·상대랭킹 · ${fmt(v.score,0)}/100</div></div><div class="badge">${esc(v.label||'GROK_HOLD')}</div></div><div class="score">OI4H ${pct(x.oi4hPct)} · OI 가치 ${Number(x.oiValueUsdt||0).toLocaleString('en-US',{maximumFractionDigits:0})} · Basis ${pct(x.basisPct)}</div><div class="metrics"><div class="metric"><span>15m 세션 RVOL</span><b>${fmt(rv['15m'],2)}x</b></div><div class="metric"><span>5m 세션 RVOL</span><b>${fmt(rv['5m'],2)}x</b></div><div class="metric"><span>Taker 5봉</span><b>${fmt(tc.avg,2)} · ${esc(tc.trend||'N/A')} · 강 ${tc.strongCount||0}/5</b></div><div class="metric"><span>Taker 매수점유</span><b>${Number.isFinite(Number(tc.buyShare))?(Number(tc.buyShare)*100).toFixed(1)+'%':'-'}</b></div><div class="metric"><span>선물/현물 거래대금</span><b>${fmt(dyn.spotFuturesVolumeRatio,2)}x</b></div><div class="metric"><span>Funding</span><b>${pct(x.fundingRatePct)}</b></div><div class="metric"><span>Basis</span><b>${pct(x.basisPct)}</b></div><div class="metric"><span>OI 상대랭킹</span><b>${x.grokOiRelativePass?'PASS':x.grokOiAbsolutePass?'ABS PASS':'-'}</b></div></div><div class="tf">${tfLine(x)}</div><div class="evidenceBox"><b>가산 근거</b><div class="positiveTags">${reasons||'<span>없음</span>'}</div></div><div class="counterBox"><b>리스크</b><div class="counterTags">${risks||'<span>없음</span>'}</div></div></article>`}
function geminiCard(x){const v=x.verdict||{},rv=v.timeWeightedRvol||{},tt=v.takerTrend||{},delta=v.priceOiDelta||{},ev=tagList(v.evidence||[]),risks=tagList(v.risks||[]);return `<article class="card gemini ${esc(v.key||'GEMINI_HOLD')}"><div class="cardTop"><div><div class="symbol">${esc(x.symbol)}</div><div class="layer">레짐·델타 · ${fmt(v.score,0)}/100</div></div><div class="badge">${esc(v.label||'GEMINI_HOLD')}</div></div><div class="score">OI4H ${pct(x.oi4hPct)} / 동적컷 ${pct(v.marketOiThresholdPct)} · ${esc(delta.label||'MISSING')}</div><div class="metrics"><div class="metric"><span>OI/가격 상대모멘텀</span><b>${fmt(delta.ratio,2)}</b></div><div class="metric"><span>15m 시간대 RVOL</span><b>${fmt(rv['15m'],2)}x</b></div><div class="metric"><span>5m 시간대 RVOL</span><b>${fmt(rv['5m'],2)}x</b></div><div class="metric"><span>Taker 연속성</span><b>${fmt(tt.avg,2)} · ${esc(tt.trend||'N/A')} · 강 ${tt.strongCount||0}/5</b></div><div class="metric"><span>Sweep+Taker</span><b>${v.sweepTakerConfirmed?'CONFIRMED':'-'}</b></div><div class="metric"><span>현물 24H</span><b>${pct(x.spotPriceChange24h)}</b></div><div class="metric"><span>Funding</span><b>${pct(x.fundingRatePct)}</b></div><div class="metric"><span>15m Taker</span><b>${fmt(x.takerCross?.['15m']?.endpointRatio,2)}</b></div></div><div class="tf">${tfLine(x)}</div><div class="evidenceBox"><b>알파 근거</b><div class="positiveTags">${ev||'<span>없음</span>'}</div></div><div class="counterBox"><b>리스크</b><div class="counterTags">${risks||'<span>없음</span>'}</div></div></article>`}
function claudeCard(x){const v=x.verdict||{},p=v.oiPath||x.claudeOiPath||{},seg=p.segments||{},dc=v.directionConfirm||{},r=v.rvol||{},t=v.taker||{},htf=v.htf||{},ev=tagList(v.evidence||[]),risks=tagList(v.risks||[]);return `<article class="card claude ${esc(v.key||'CLAUDE_INCOMPLETE')}"><div class="cardTop"><div><div class="symbol">${esc(x.symbol)}</div><div class="layer">Claude v3 · ${esc(v.direction||'NONE')} · 우선도 ${fmt(v.priority,0)}</div></div><div class="badge">${esc(v.label||'미완성')}</div></div><div class="score">OI 경로 ${esc(p.path||'N/A')} · ${esc(p.pattern||'OTHER')} · 24H ${pct(x.priceChange24h)}</div><div class="metrics"><div class="metric"><span>OI 0~4H</span><b>${pct(seg.h0_4)}</b></div><div class="metric"><span>OI 4~8H</span><b>${pct(seg.h4_8)}</b></div><div class="metric"><span>OI 8~12H</span><b>${pct(seg.h8_12)}</b></div><div class="metric"><span>1H DIRECTION</span><b>${dc.confirmed?'CONFIRMED':'NONE'} · ${dc.improveCount||0}/3 · STRONG ${dc.strongCount||0}</b></div><div class="metric"><span>15m RVOL</span><b>${fmt(r['15m']?.value,2)}x · ${esc(r['15m']?.zone||'MISSING')}</b></div><div class="metric"><span>5m RVOL</span><b>${fmt(r['5m']?.value,2)}x · ${esc(r['5m']?.zone||'MISSING')}</b></div><div class="metric"><span>15m 보수 Taker</span><b>${fmt(t['15m']?.conservative,2)} · ${esc(t['15m']?.zone||'MISSING')}</b></div><div class="metric"><span>5m 보수 Taker</span><b>${fmt(t['5m']?.conservative,2)} · ${esc(t['5m']?.zone||'MISSING')}</b></div><div class="metric"><span>1W 위치</span><b>${fmt(htf.weeklyRangePositionPct,1)}% · ${htf.htfDiscount?'HTF_DISCOUNT':'-'}</b></div><div class="metric"><span>1D 위치</span><b>${fmt(htf.dailyRangePositionPct,1)}% · ${htf.midTermPremium?'MID_TERM_PREMIUM':'-'}</b></div><div class="metric"><span>Funding</span><b>${pct(x.fundingRatePct)}</b></div><div class="metric"><span>Spot 동행</span><b>${v.spotAligned?'YES':'NO/N/A'}</b></div></div><div class="tf">${tfLine(x)}</div><div class="evidenceBox"><b>승격 근거</b><div class="positiveTags">${ev||'<span>없음</span>'}</div></div><div class="counterBox"><b>강등/위험</b><div class="counterTags">${risks||'<span>없음</span>'}</div></div></article>`}
function render(){const box=$('astraResults');if(!state.rows.length){box.innerHTML='<div class="empty">OI 필터 통과 종목이 없거나 정밀 결과가 없습니다.</div>';return}box.innerHTML=state.rows.map(x=>state.method==='manus'?manusCard(x):state.method==='perplexity'?perplexityCard(x):state.method==='grok'?grokCard(x):state.method==='gemini'?geminiCard(x):state.method==='claude'?claudeCard(x):astraCard(x)).join('')}
function marketQuery(u){const m=u.marketState||u.breadth||{};return{asOf:u.asOf,regime:m.regime||'NEUTRAL',breadth:m.breadthRatio,btc:m.btc24hChange,eth:m.eth24hChange,median:m.median24hChange,positiveVolumeRatio:m.positiveVolumeRatio,volumeWeightedBreadth:m.volumeWeightedBreadth}}
function showBreadth(u){const b=u.marketState||u.breadth||{};if(state.method==='claude')$('astraBreadth').textContent=`시장 ${b.regime||'NEUTRAL'} · breadth ${Number.isFinite(Number(b.breadthRatio))?(Number(b.breadthRatio)*100).toFixed(1)+'%':'-'} · 거래대금 퍼센타일 컷 ${Number(u.dynamicFilter?.quoteVolumeThreshold||0).toLocaleString('en-US',{maximumFractionDigits:0})} · BTC ${pct(b.btc24hChange)} · ETH ${pct(b.eth24hChange)}`;else if(state.method==='grok')$('astraBreadth').textContent=`시장 ${b.regime||'NEUTRAL'} · breadth ${Number.isFinite(Number(b.breadthRatio))?(Number(b.breadthRatio)*100).toFixed(1)+'%':'-'} · 동적 거래대금 컷 ${Number(u.dynamicFilter?.quoteVolumeThreshold||0).toLocaleString('en-US',{maximumFractionDigits:0})} · BTC ${pct(b.btc24hChange)} · ETH ${pct(b.eth24hChange)}`;else if(state.method==='gemini')$('astraBreadth').textContent=`시장 ${b.regime||'NEUTRAL'} · breadth ${Number.isFinite(Number(b.breadthRatio))?(Number(b.breadthRatio)*100).toFixed(1)+'%':'-'} · OI 문턱 1.0/1.5/2.5% 동적 적용 · BTC ${pct(b.btc24hChange)} · ETH ${pct(b.eth24hChange)}`;else if(state.method==='perplexity')$('astraBreadth').textContent=`시장 ${b.regime||'NEUTRAL'} · breadth ${Number.isFinite(Number(b.breadthRatio))?(Number(b.breadthRatio)*100).toFixed(1)+'%':'-'} · 거래대금 가중 ${Number.isFinite(Number(b.volumeWeightedBreadth))?(Number(b.volumeWeightedBreadth)*100).toFixed(1)+'%':'-'} · 상승 ${b.up||0}/${b.total||0} · BTC ${pct(b.btc24hChange)} · ETH ${pct(b.eth24hChange)} · snapshot ${u.serverTime?new Date(u.serverTime).toISOString():'N/A'}`;else if(state.method==='manus')$('astraBreadth').textContent=`시장 ${b.regime||'NEUTRAL'} · breadth ${Number.isFinite(Number(b.breadthRatio))?(Number(b.breadthRatio)*100).toFixed(1)+'%':'-'} · 상승 ${b.up||0}/${b.total||0} · 중앙값 ${pct(b.median24hChange)} · BTC ${pct(b.btc24hChange)} · ETH ${pct(b.eth24hChange)}`;else $('astraBreadth').textContent=`시장 폭 ${b.total||0}개 중 상승 ${b.up||0} · 하락 ${b.down||0} · BTC ${pct(b.btc24hChange??u.majors?.BTCUSDT?.priceChange24h)} · ETH ${pct(b.eth24hChange??u.majors?.ETHUSDT?.priceChange24h)}`}
function modeName(){return state.method==='claude'?'Claude Astra+SURGE v3':state.method==='grok'?'Grok 동적·상대랭킹형':state.method==='gemini'?'Gemini 레짐·델타형':state.method==='perplexity'?'Perplexity 전수·반증형':state.method==='manus'?'Manus 전문 검증형':'Astra 점화형'}
async function run(){if(state.running)return;syncMethod();state.running=true;state.controller=new AbortController();$('astraRun').disabled=true;$('scanMethod').disabled=true;state.rows=[];render();try{
 setStatus(`1/3 · ${modeName()} · 전체 선물과 가격·유동성 확인 중…`);const u=await get('universe');$('universeCount').textContent=u.universeCount;$('filteredCount').textContent=u.filteredCount;$('oiCount').textContent='0';$('deepCount').textContent='0';showBreadth(u);
 const filtered=u.items||[],oiRows=[],marketCtx=marketQuery(u);let done=0,oiRequested=0,oiSuccess=0,oiFailed=0,oiMissing=0,oiMismatch=0,degraded=false;
 for(const chunk of chunks(filtered.map(x=>x.symbol),16)){const x=await get('oi',chunk,{...marketCtx,asOf:u.asOf});oiRows.push(...(x.items||[]));done+=chunk.length;oiRequested+=Number(x.requested)||0;oiSuccess+=Number(x.success)||0;oiFailed+=Number(x.failed)||0;oiMissing+=Number(x.missing)||0;oiMismatch+=Number(x.mismatchedWindow)||0;degraded=degraded||Boolean(x.degraded);$('astraAudit').textContent=`OI 조회 감사 · 요청 ${oiRequested} · 성공 ${oiSuccess} · 실패 ${oiFailed} · 결측 ${oiMissing}${state.method==='perplexity'?` · 구간불일치 ${oiMismatch}`:''} · 현재 처리 ${done}/${filtered.length}`;setStatus(`2/3 · 4H OI 계약수 전수검사 ${done}/${filtered.length}`)}
 let grokOiCut=null,passRows=oiRows;
 if(state.method==='grok'){grokOiCut=quantile(oiRows.filter(x=>x.status==='SUCCESS').map(x=>x.oi4hPct),.80);passRows=oiRows.map(x=>({...x,pass:x.status==='SUCCESS'&&Number(x.oiValueUsdt)>=5000000&&((Number.isFinite(Number(grokOiCut))&&Number(x.oi4hPct)>=Number(grokOiCut))||Number(x.oi4hPct)>=1.5)}))}
 const pass=passRows.filter(x=>x.pass).map(x=>x.symbol);$('oiCount').textContent=pass.length;
 const geminiThreshold=passRows.find(x=>Number.isFinite(Number(x.geminiOiThresholdPct)))?.geminiOiThresholdPct;
 $('astraAudit').textContent=`OI 조회 감사 · 요청 ${oiRequested} · 성공 ${oiSuccess} · 실패 ${oiFailed} · 결측 ${oiMissing}${state.method==='grok'?` · 상대컷 ${pct(grokOiCut)} · OI가치≥$5M`:state.method==='claude'?` · +/+/+ BUILD 또는 -/+/+ CLEAN→REBUILD`:state.method==='perplexity'?` · 구간불일치 ${oiMismatch} · 품질 ${degraded?'DEGRADED':'NORMAL'}`:state.method==='gemini'?` · 동적컷 ${pct(geminiThreshold)}`:''} · 필터 통과 ${pass.length}`;
 if(!pass.length){setStatus('완료 · OI 조건 통과 종목 없음');render();return}
 const deep=[],ctx={...marketCtx,oiDegraded:degraded,grokOiCut};done=0;
 for(const chunk of chunks(pass,2)){const x=await get('deep',chunk,ctx);deep.push(...(x.items||[]));done+=chunk.length;$('deepCount').textContent=done;setStatus(`3/3 · ${state.method==='claude'?'OI 경로·HTF 위치·보수적 Taker·DIRECTION_CONFIRM·A~NFB 라벨':state.method==='grok'?'세션 RVOL·OI 상대랭킹·Taker 연속성·Basis':state.method==='gemini'?'동적 OI·가격/OI 델타·Sweep+Taker':state.method==='perplexity'?'1H·15m 라벨·true taker·반증·데이터품질':state.method==='manus'?'확정봉·Taker 교차·현물·Funding·100점 검증':'주봉~5분봉 정밀검사'} ${done}/${pass.length}`)}
 const order=state.method==='manus'?{A_FIRE:0,B_PREPARE:1,C_WATCH:2,HOLD:3,EXCLUDE:4}:state.method==='perplexity'?{IGNITION_CONFIRMED:0,TRANSITION_WATCH:1,ACCUMULATION_CANDIDATE:2,OI_BUILD:3,INCOMPLETE:4,SHORT_BUILD_RISK:5,OVERHEATED:6,DATA_DEGRADED:7}:state.method==='grok'?{GROK_FIRE:0,GROK_READY:1,GROK_INTEREST:2,GROK_HOLD:3,GROK_EXCLUDE:4}:state.method==='gemini'?{GEMINI_ALPHA:0,GEMINI_READY:1,GEMINI_WATCH:2,GEMINI_HOLD:3,GEMINI_RISK:4}:state.method==='claude'?{CLAUDE_A_B:0,CLAUDE_A_TO_AB:1,CLAUDE_A:2,CLAUDE_NFB_SQ:3,CLAUDE_C:4,CLAUDE_NFB:5,CLAUDE_A_PRE:6,CLAUDE_B:7,CLAUDE_NFB_SC:8,CLAUDE_INCOMPLETE:9}:{IGNITION_CONFIRMED:0,WATCH_PRIORITY:1,WAIT:2,HOLD:3,PROGRESSED:4};
 state.rows=deep.sort((a,b)=>(order[a.verdict?.key]??9)-(order[b.verdict?.key]??9)||((b.verdict?.priority??b.verdict?.score)||0)-((a.verdict?.priority??a.verdict?.score)||0));render();
 const count=k=>state.rows.filter(x=>x.verdict?.key===k).length;
 if(state.method==='claude')setStatus(`완료 · ${u.universeCount} → ${u.filteredCount} → OI경로 ${pass.length} → A+B ${count('CLAUDE_A_B')} · A→A+B ${count('CLAUDE_A_TO_AB')} · A ${count('CLAUDE_A')} · A-pre ${count('CLAUDE_A_PRE')} · C ${count('CLAUDE_C')} · NFB계열 ${count('CLAUDE_NFB')+count('CLAUDE_NFB_SQ')+count('CLAUDE_NFB_SC')} · 미완성 ${count('CLAUDE_INCOMPLETE')}`);
 else if(state.method==='grok')setStatus(`완료 · ${u.universeCount} → ${u.filteredCount} → OI ${pass.length} → FIRE ${count('GROK_FIRE')} · READY ${count('GROK_READY')} · INTEREST ${count('GROK_INTEREST')} · HOLD ${count('GROK_HOLD')}`);
 else if(state.method==='gemini')setStatus(`완료 · ${u.universeCount} → ${u.filteredCount} → OI ${pass.length} → ALPHA ${count('GEMINI_ALPHA')} · READY ${count('GEMINI_READY')} · WATCH ${count('GEMINI_WATCH')} · RISK ${count('GEMINI_RISK')}`);
 else if(state.method==='perplexity')setStatus(`완료 · ${u.universeCount} → ${u.filteredCount} → OI ${pass.length} → IGNITION ${count('IGNITION_CONFIRMED')} · TRANSITION ${count('TRANSITION_WATCH')} · ACCUMULATION ${count('ACCUMULATION_CANDIDATE')} · OI_BUILD ${count('OI_BUILD')} · RISK ${count('SHORT_BUILD_RISK')} · DATA_DEGRADED ${count('DATA_DEGRADED')}`);
 else if(state.method==='manus')setStatus(`완료 · ${u.universeCount} → ${u.filteredCount} → OI ${pass.length} → A_FIRE ${count('A_FIRE')} · B_PREPARE ${count('B_PREPARE')} · C_WATCH ${count('C_WATCH')} · HOLD ${count('HOLD')} · EXCLUDE ${count('EXCLUDE')}`);
 else{const ign=count('IGNITION_CONFIRMED'),watch=count('WATCH_PRIORITY');setStatus(`완료 · ${u.universeCount} → ${u.filteredCount} → OI 통과 ${pass.length} → 점화 확정 ${ign} · 관찰 우선 ${watch}`)}
 }catch(e){if(e?.name!=='AbortError')setStatus('스캔 실패 · '+String(e?.message||e))}finally{state.running=false;$('astraRun').disabled=false;$('scanMethod').disabled=false}}
$('astraRun')?.addEventListener('click',run);$('scanMethod')?.addEventListener('change',()=>{if(state.running)return;state.rows=[];syncMethod();render();setStatus('방식 변경됨 · 전체스캔 실행을 눌러 원점에서 검사합니다.')});syncMethod();
})();