(()=>{'use strict';
const $=id=>document.getElementById(id);const DEEP_CHUNK=6;const state={category:'전체',sector:'전체',query:'',items:[],meta:null,loading:false,deepLoading:false,deepDone:0,deepTotal:0,error:null,deepError:null,refreshSeq:0};
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtTime(v){const n=Number(v);if(!Number.isFinite(n))return'-';try{return new Date(n).toLocaleString('ko-KR',{hour12:false})}catch{return'-'}}
function fmtNum(v,d=1){const n=Number(v);return Number.isFinite(n)?n.toFixed(d):'-'}
function matchesCategory(item){const c=state.category;if(c==='전체')return true;if(c==='급등 전조')return String(item.category).startsWith('급등 전조');return item.category===c}
function filtered(){const q=state.query.trim().toUpperCase();return state.items.filter(x=>matchesCategory(x)&&(state.sector==='전체'||x.sector===state.sector)&&(!q||String(x.symbol).includes(q)))}
function renderMeta(){const m=state.meta||{},h=m.dataHealth||{};$('updatedAt').textContent=fmtTime(m.updatedAt);$('scanCount').textContent=String(m.scanCount||0);$('deepCount').textContent=String(state.deepDone||m.deepScanCount||0);$('liveCount').textContent=String(h.live||0);$('delayedCount').textContent=String(h.delayed||0);$('blockedCount').textContent=String(h.blocked||0);$('status').textContent=state.loading?'1차 전체 스캔 중…':state.error?`데이터 갱신 실패 · 이전 결과 유지 · ${state.error}`:state.deepLoading?`1차 스캔 완료 · 정밀 분석 ${state.deepDone}/${state.deepTotal}`:state.deepError?`1차 스캔 완료 · 정밀 분석 일부 실패 · ${state.deepError}`:`${filtered().length}개 표시 · 60초마다 자동 갱신`}
function reportUrl(symbol){return `/coin-report.html?symbol=${encodeURIComponent(symbol||'')}&shell=1`}
function snapshotUrl(symbol){return `/snapshot-analysis-restored.html?symbol=${encodeURIComponent(symbol||'')}&shell=1`}
function openReport(symbol){const s=String(symbol||'').toUpperCase();if(!s)return;try{parent.postMessage({type:'pulse-nav',view:'report',symbol:s},'*')}catch{}if(window===parent)location.href=reportUrl(s)}
function tradeSignalMarkup(x){const s=x.tradeSignal||{};const level=String(s.level||'제외');const confidence=Number.isFinite(Number(s.confidence))?Math.max(0,Math.min(100,Math.round(Number(s.confidence)))):0;const confirmations=Number.isFinite(Number(s.confirmations))?Math.max(0,Math.round(Number(s.confirmations))):0;const cls=level==='매수 후보'?'candidate':level==='관찰'?'watch':'blocked';const invalid=Array.isArray(s.invalidations)&&s.invalidations[0]?`<div class="signalInvalid">${escapeHtml(s.invalidations[0])}</div>`:'';return `<div class="tradeSignal ${cls}"><span class="signalBadge">${escapeHtml(level)}</span><span class="signalMeta">신뢰도 ${confidence}% · 확인 ${confirmations}</span>${invalid}</div>`}
function momentumMarkup(x){const m=x.momentumSignals;if(!m)return'';const state=m.overheated?'과열':m.aligned?'정렬':'혼조';const cls=m.overheated?'hot':m.aligned?'aligned':'mixed';return `<div class="momentumLine ${cls}"><b>모멘텀 ${escapeHtml(state)}</b><span>RSI 1H ${fmtNum(m.rsi1h)} · 15m ${fmtNum(m.rsi15m)}</span><span>MACD ${fmtNum(m.macd1h,3)} / ${fmtNum(m.macd15m,3)}</span><span>StochRSI ${fmtNum(m.stochRsi1h)} / ${fmtNum(m.stochRsi15m)}</span></div>`}
function card(x){const reasons=(Array.isArray(x.reasons)?x.reasons:[]).slice(0,3).map(r=>`<li>${escapeHtml(r)}</li>`).join('');const tf=x.tfState||{};return `<article class="scanCard" data-symbol="${escapeHtml(x.symbol)}" tabindex="0"><div class="cardTop"><div><div class="symbol">${escapeHtml(x.symbol)}</div><div class="meta">${escapeHtml(x.sector||'기타')} · 우선순위 ${escapeHtml(x.priority??0)} · 후보점수 ${escapeHtml(x.candidateScore??'-')}</div></div><span class="category">${escapeHtml(x.category)}</span></div>${tradeSignalMarkup(x)}${momentumMarkup(x)}<div class="tf">4H ${escapeHtml(tf['4h']||'-')} · 1H ${escapeHtml(tf['1h']||'-')} · 15m ${escapeHtml(tf['15m']||'-')}</div>${reasons?`<ul class="reason">${reasons}</ul>`:''}<div class="summary">${escapeHtml(x.summary||'요약 정보 없음')}</div><div class="cardFoot"><span class="state ${escapeHtml(x.dataState)}">● ${escapeHtml(x.dataState||'unknown')}</span><span><a class="detail reportLink" href="${reportUrl(x.symbol)}">종합 분석</a> · <a class="detail snapshotLink" href="${snapshotUrl(x.symbol)}">스냅샷</a></span></div></article>`}
function render(){renderMeta();const rows=filtered();$('results').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">현재 조건에 맞는 종목이 없습니다.</div>'}
function mergeDeep(data){const map=new Map(state.items.map(x=>[x.symbol,x]));for(const item of Array.isArray(data?.items)?data.items:[])map.set(item.symbol,item);state.items=Array.from(map.values()).sort((a,b)=>(Number(b.tradeSignal?.confidence)||0)-(Number(a.tradeSignal?.confidence)||0)||(Number(b.priority)||0)-(Number(a.priority)||0)||(Number(b.candidateScore)||0)-(Number(a.candidateScore)||0)||String(a.symbol).localeCompare(String(b.symbol)))}
async function enrich(candidates,seq){state.deepTotal=candidates.length;state.deepDone=0;state.deepError=null;state.deepLoading=candidates.length>0;render();for(let i=0;i<candidates.length;i+=DEEP_CHUNK){if(seq!==state.refreshSeq)return;const chunk=candidates.slice(i,i+DEEP_CHUNK);try{const u='/api/coin-scan?mode=deep&limit='+DEEP_CHUNK+'&symbols='+encodeURIComponent(chunk.join(','));const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(!data||data.status!=='ok'||!Array.isArray(data.items))throw new Error(data?.error||'정밀 응답 형식 오류');mergeDeep(data)}catch(e){state.deepError=String(e?.message||e)}finally{state.deepDone=Math.min(state.deepTotal,i+chunk.length);render()}}state.deepLoading=false;render()}
async function refresh(){if(state.loading)return;const seq=++state.refreshSeq;state.loading=true;state.deepLoading=false;state.error=null;state.deepError=null;state.deepDone=0;state.deepTotal=0;renderMeta();try{const r=await fetch('/api/coin-scan?mode=summary&limit=250',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(!data||data.status!=='ok'||!Array.isArray(data.items))throw new Error(data?.error||'응답 형식 오류');state.items=data.items;state.meta=data;state.loading=false;render();const candidates=Array.isArray(data.candidateSymbols)?data.candidateSymbols.slice(0,40):[];await enrich(candidates,seq)}catch(e){if(seq===state.refreshSeq)state.error=String(e?.message||e)}finally{if(seq===state.refreshSeq){state.loading=false;state.deepLoading=false;render()}}}
function init(){document.querySelectorAll('#categoryTabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('#categoryTabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.category=btn.dataset.category||'전체';render()}));$('sector').addEventListener('change',e=>{state.sector=e.target.value;render()});$('query').addEventListener('input',e=>{state.query=e.target.value;render()});$('query').addEventListener('keydown',e=>{if(e.key==='Enter'){const first=filtered()[0];if(first)openReport(first.symbol)}});$('results').addEventListener('click',e=>{const reportLink=e.target.closest('.reportLink'),snapshotLink=e.target.closest('.snapshotLink'),card=e.target.closest('.scanCard');if(reportLink){e.preventDefault();return openReport(card?.dataset.symbol)}if(snapshotLink){e.stopPropagation();return}if(card)openReport(card.dataset.symbol)});$('results').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.scanCard')){e.preventDefault();openReport(e.target.closest('.scanCard').dataset.symbol)}});$('refreshBtn').addEventListener('click',refresh);refresh();setInterval(refresh,60000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
