(()=>{'use strict';
const $=id=>document.getElementById(id);const DEEP_CHUNK=6;const MEMORY_KEY='pulse.sample-dormancy.v2';
const CLASS_ORDER=['PRE-SURGE','ACCUMULATION-PRE','META-PRE','SECTOR-ROTATION','ANOMALY','POST-SURGE','DISTRIBUTION-RISK','PUMP-RISK','STALE'];
const CLASS_LABELS={'PRE-SURGE':'🔥 급등 직전','ACCUMULATION-PRE':'🟢 잠복 축적','META-PRE':'🟢 메타 선행','SECTOR-ROTATION':'🟣 섹터 순환매','ANOMALY':'🟠 이상징후','POST-SURGE':'🔵 급등 완료','DISTRIBUTION-RISK':'⚫ 분배 위험','PUMP-RISK':'🔴 펌프 위험','STALE':'⚪ 판단 보류'};
const state={category:'전체',sector:'전체',query:'',items:[],meta:null,loading:false,deepLoading:false,deepDone:0,deepTotal:0,error:null,deepError:null,refreshSeq:0};
function readMemory(){try{const x=JSON.parse(localStorage.getItem(MEMORY_KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return{}}}
function writeMemory(x){try{localStorage.setItem(MEMORY_KEY,JSON.stringify(x))}catch{}}
function decorateDormancy(items){const now=Date.now(),mem=readMemory();for(const [s,m] of Object.entries(mem)){if(!m||!Number.isFinite(Number(m.firstSeen))||now-Number(m.firstSeen)>24*3600000)delete mem[s]}for(const x of items||[]){const p=x.samplePattern;if(!p)continue;const s=String(x.symbol||'');if(['PROGRESSED','BROKEN'].includes(String(p.phase||''))){delete mem[s];continue}if(p.dormancy?.eligible&&!mem[s])mem[s]={firstSeen:now,phase:p.phase,score:p.score};const m=mem[s];if(m){const age=Math.max(0,(now-Number(m.firstSeen))/3600000);if(age<=24)x.dormancyMemory={firstSeen:m.firstSeen,ageHours:Number(age.toFixed(1)),windowHours:24}}}writeMemory(mem);return items}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtTime(v){const n=Number(v);if(!Number.isFinite(n))return'-';try{return new Date(n).toLocaleString('ko-KR',{hour12:false})}catch{return'-'}}
function fmtNum(v,d=1){const n=Number(v);return Number.isFinite(n)?n.toFixed(d):'-'}
function classKey(item){return String(item?.scanClass?.key||'STALE')}
function matchesCategory(item){return state.category==='전체'||classKey(item)===state.category}
function filtered(){const q=state.query.trim().toUpperCase();return state.items.filter(x=>matchesCategory(x)&&(state.sector==='전체'||x.sector===state.sector)&&(!q||String(x.symbol).includes(q)))}
function renderMeta(){const m=state.meta||{},h=m.dataHealth||{},b=m.marketBreadth||{};$('updatedAt').textContent=fmtTime(m.updatedAt);$('scanCount').textContent=String(m.scanCount||0);$('deepCount').textContent=String(state.deepDone||m.deepScanCount||0);$('liveCount').textContent=String(h.live||0);$('delayedCount').textContent=String(h.delayed||0);$('blockedCount').textContent=String(h.blocked||0);$('status').textContent=state.loading?'1차 전체 스캔 중…':state.error?`데이터 갱신 실패 · 이전 결과 유지 · ${state.error}`:state.deepLoading?`1차 스캔 완료 · 정밀 분석 ${state.deepDone}/${state.deepTotal}`:state.deepError?`1차 스캔 완료 · 정밀 분석 일부 실패 · ${state.deepError}`:`코어 ${m.scanCount||0}개 · 현재 ${filtered().length}개 표시 · 60초마다 자동 갱신`;const breadth=$('marketBreadth');if(breadth)breadth.textContent=Number.isFinite(Number(b.median))?`시장 breadth · 상승 ${b.up||0} / 하락 ${b.down||0} · 중앙값 ${Number(b.median)>=0?'+':''}${fmtNum(b.median,2)}% · +5% ${b.gt5||0}개 · -5% ${b.lt5||0}개`:'시장 breadth 계산 중…'}
function reportUrl(symbol){return `/coin-report.html?symbol=${encodeURIComponent(symbol||'')}&shell=1`}
function snapshotUrl(symbol){return `/mtf-snapshot-pro.html?symbol=${encodeURIComponent(symbol||'')}&shell=1`}
function openReport(symbol){const s=String(symbol||'').toUpperCase();if(!s)return;try{parent.postMessage({type:'pulse-nav',view:'report',symbol:s},'*')}catch{}if(window===parent)location.href=reportUrl(s)}
function v2Markup(x){const v=x.v2Flow;if(!v)return'';const oi4=Number(x.oi4hChangePct),oi8=Number(x.oi8hChangePct),tk=Number(x.trueTakerRatio),fr=Number(x.fundingRate);const fmtPct=n=>Number.isFinite(n)?(n>=0?'+':'')+n.toFixed(2)+'%':'N/A';const dir=v.direction||'none';const subtype=x.sampleSubtype?' · '+x.sampleSubtype:'';const transition=x.stageTransition&&x.stageTransition!=='unknown'?' · '+x.stageTransition:'';return '<div class="v2Flow"><b>v2 '+escapeHtml(v.type)+' · '+escapeHtml(v.stageLabel)+'</b><span>direction '+escapeHtml(dir)+'</span><span>OI 4H '+escapeHtml(fmtPct(oi4))+' / 8H '+escapeHtml(fmtPct(oi8))+'</span><span>true taker '+escapeHtml(Number.isFinite(tk)?tk.toFixed(3):'N/A')+(v.deadBand?' · dead band':'')+'</span><span>funding '+escapeHtml(Number.isFinite(fr)?fmtPct(fr):'N/A')+escapeHtml(subtype)+escapeHtml(transition)+'</span></div>'}
function tradeSignalMarkup(x){const s=x.tradeSignal||{};const level=String(s.level||'제외');const confidence=Number.isFinite(Number(s.confidence))?Math.max(0,Math.min(100,Math.round(Number(s.confidence)))):0;const confirmations=Number.isFinite(Number(s.confirmations))?Math.max(0,Math.round(Number(s.confirmations))):0;const cls=level==='매수 후보'?'candidate':level==='관찰'?'watch':'blocked';const invalid=Array.isArray(s.invalidations)&&s.invalidations[0]?`<div class="signalInvalid">${escapeHtml(s.invalidations[0])}</div>`:'';return `<div class="tradeSignal ${cls}"><span class="signalBadge">${escapeHtml(level)}</span><span class="signalMeta">신뢰도 ${confidence}% · 확인 ${confirmations}</span>${invalid}</div>`}
function sampleMarkup(x){const p=x.samplePattern;if(!p)return'';const oi=p.oiProfile||{},tk=p.takerProfile||{},liq=p.liquidity||{},sw=p.sweep||{},t15=p.timeSymmetry?.m15||{},h1=p.timeSymmetry?.h1||{},reset=p.resetReignition||{},best=Array.isArray(p.similarity)?p.similarity[0]:null,mem=x.dormancyMemory;const oiText=Number.isFinite(Number(oi.changePct))?`OI ${Number(oi.changePct)>=0?'+':''}${fmtNum(oi.changePct,2)}%`:'OI -';const ddText=Number.isFinite(Number(oi.drawdownPct))?`DD ${fmtNum(oi.drawdownPct,2)}%`:'DD -';const takerText=Number.isFinite(Number(tk.min))&&Number.isFinite(Number(tk.max))?`taker ${fmtNum(tk.min,2)}↔${fmtNum(tk.max,2)}`:'taker -';const sweepText=sw.label?`스윕 · ${sw.label}`:(liq.label||'유동성 -');const timeText=t15.tag&&t15.tag!=='UNKNOWN'?`기간 15m ${t15.tag} R=${fmtNum(t15.ratio,2)} · 1H ${h1.tag||'-'} ${Number.isFinite(Number(h1.ratio))?`R=${fmtNum(h1.ratio,2)}`:''}`:'기간 -';const resetText=reset.key&&reset.key!=='NO_RESET'?`리셋 · ${reset.label}`:'';const matchText=best&&Number(best.score)>=45?`유사도 · ${best.name} ${best.score}%`:'';const memoryText=mem?`잠복 메모리 ${fmtNum(mem.ageHours,1)}h / 24h`:'';return `<div class="sampleDNA"><span class="dnaBadge">${escapeHtml(p.archetypeLabel||p.archetype||'샘플')}</span><span class="dnaPhase">${escapeHtml(p.phaseLabel||p.phase||'-')}</span><span>DNA ${escapeHtml(p.score??'-')}점</span><span>${escapeHtml(oiText)}</span><span>${escapeHtml(ddText)}</span><span>${escapeHtml(takerText)}</span><span>${escapeHtml(sweepText)}</span><span>${escapeHtml(timeText)}</span>${resetText?`<span>${escapeHtml(resetText)}</span>`:''}${matchText?`<span class="dnaMatch">${escapeHtml(matchText)}</span>`:''}${memoryText?`<span class="dnaMemory">${escapeHtml(memoryText)}</span>`:''}</div>`}
function momentumMarkup(x){const m=x.momentumSignals;if(!m)return'';const stateText=m.overheated?'보조지표 과열':m.aligned?'보조지표 정렬':'보조지표 혼조';const cls=m.overheated?'hot':m.aligned?'aligned':'mixed';const macd=Number(m.macd15m);const macdArrow=Number.isFinite(macd)?(macd>0?'↑':macd<0?'↓':'→'):'-';const st=Number(m.stochRsi15m);const stText=Number.isFinite(st)?(st>=80?'과열':st<=20?'저점권':'상승 구간'):'-';const j=Number(m.kdj15m?.j),d=Number(m.kdj15m?.d);const kdjArrow=Number.isFinite(j)&&Number.isFinite(d)?(j>d?'↑':j<d?'↓':'→'):'-';return `<div class="momentumLine ${cls}"><b>${escapeHtml(stateText)}</b><span>RSI ${fmtNum(m.rsi15m)}</span><span>MACD ${macdArrow}</span><span>Stoch RSI ${escapeHtml(stText)}</span><span>KDJ J선 ${kdjArrow}</span></div>`}
function card(x){const reasons=(Array.isArray(x.reasons)?x.reasons:[]).slice(0,3).map(r=>`<li>${escapeHtml(r)}</li>`).join('');const tf=x.tfState||{};const cls=x.scanClass||{};const label=cls.label||CLASS_LABELS[classKey(x)]||'⚪ 판단 보류';return `<article class="scanCard" data-symbol="${escapeHtml(x.symbol)}" tabindex="0"><div class="cardTop"><div><div class="symbol">${escapeHtml(x.symbol)}</div><div class="meta">${escapeHtml(x.sector||'기타')} · 후보점수 ${escapeHtml(x.candidateScore??'-')} · 24시간 ${fmtNum(x.priceChange24h)}%</div></div><span class="category">${escapeHtml(label)}</span></div>${v2Markup(x)}${tradeSignalMarkup(x)}<div class="summary">${escapeHtml(x.summary||'요약 정보 없음')}</div><details class="cardDetail"><summary>상세 근거 보기</summary>${sampleMarkup(x)}${momentumMarkup(x)}<div class="tf">4시간 ${escapeHtml(tf['4h']||'-')} · 1시간 ${escapeHtml(tf['1h']||'-')} · 15분 ${escapeHtml(tf['15m']||'-')}</div>${reasons?`<ul class="reason">${reasons}</ul>`:''}</details><div class="cardFoot"><span class="state ${escapeHtml(x.dataState)}">● ${escapeHtml(x.dataState||'unknown')}</span><span><a class="detail reportLink" href="${reportUrl(x.symbol)}">종합 분석</a> · <a class="detail snapshotLink" href="${snapshotUrl(x.symbol)}">스냅샷</a></span></div></article>`}
function classSection(key,rows){const label=CLASS_LABELS[key]||key;return `<section class="classSection class-${escapeHtml(key)}"><div class="classHeading"><h2>${escapeHtml(label)}</h2><span>${rows.length}개</span></div><div class="classGrid">${rows.map(card).join('')}</div></section>`}
function render(){renderMeta();const rows=filtered();if(!rows.length){$('results').innerHTML='<div class="empty">현재 조건에 맞는 종목이 없습니다.</div>';return}const keys=state.category==='전체'?CLASS_ORDER:[state.category];$('results').innerHTML=keys.map(k=>{const group=rows.filter(x=>classKey(x)===k);return group.length?classSection(k,group):''}).join('')}
function sortItems(items){const rank=new Map(CLASS_ORDER.map((k,i)=>[k,i])),v2rank=new Map([['A→A+B',0],['A',1],['A-pre',2],['NFB-SQ',3],['NFB',4],['C',5],['B',6],['A+B',7],['미완성',8],['PROGRESSED',9],['NFB-SC',10]]);return items.sort((a,b)=>(v2rank.get(a.v2Type)??99)-(v2rank.get(b.v2Type)??99)||(Number(b.isTransitionEvent)||0)-(Number(a.isTransitionEvent)||0)||(rank.get(classKey(a))??99)-(rank.get(classKey(b))??99)||(Number(b.tradeSignal?.confidence)||0)-(Number(a.tradeSignal?.confidence)||0)||(Number(b.candidateScore)||0)-(Number(a.candidateScore)||0)||String(a.symbol).localeCompare(String(b.symbol)))}
function mergeDeep(data){const map=new Map(state.items.map(x=>[x.symbol,x]));for(const item of Array.isArray(data?.items)?data.items:[])map.set(item.symbol,item);state.items=sortItems(decorateDormancy(Array.from(map.values())))}
async function enrich(candidates,seq){state.deepTotal=candidates.length;state.deepDone=0;state.deepError=null;state.deepLoading=candidates.length>0;render();for(let i=0;i<candidates.length;i+=DEEP_CHUNK){if(seq!==state.refreshSeq)return;const chunk=candidates.slice(i,i+DEEP_CHUNK);try{const u='/api/coin-scan?mode=deep&limit='+DEEP_CHUNK+'&symbols='+encodeURIComponent(chunk.join(','));const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(!data||data.status!=='ok'||!Array.isArray(data.items))throw new Error(data?.error||'정밀 응답 형식 오류');mergeDeep(data)}catch(e){state.deepError=String(e?.message||e)}finally{state.deepDone=Math.min(state.deepTotal,i+chunk.length);render()}}state.deepLoading=false;render()}
async function refresh(){if(state.loading)return;const seq=++state.refreshSeq;state.loading=true;state.deepLoading=false;state.error=null;state.deepError=null;state.deepDone=0;state.deepTotal=0;renderMeta();try{const r=await fetch('/api/coin-scan?mode=summary&limit=500',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(!data||data.status!=='ok'||!Array.isArray(data.items))throw new Error(data?.error||'응답 형식 오류');state.items=sortItems(data.items);state.meta=data;state.loading=false;render();const candidates=Array.isArray(data.candidateSymbols)?data.candidateSymbols.slice(0,40):[];await enrich(candidates,seq)}catch(e){if(seq===state.refreshSeq)state.error=String(e?.message||e)}finally{if(seq===state.refreshSeq){state.loading=false;state.deepLoading=false;render()}}}
function init(){document.querySelectorAll('#categoryTabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('#categoryTabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.category=btn.dataset.category||'전체';render()}));$('sector').addEventListener('change',e=>{state.sector=e.target.value;render()});$('query').addEventListener('input',e=>{state.query=e.target.value;render()});$('query').addEventListener('keydown',e=>{if(e.key==='Enter'){const first=filtered()[0];if(first)openReport(first.symbol)}});$('results').addEventListener('click',e=>{const reportLink=e.target.closest('.reportLink'),snapshotLink=e.target.closest('.snapshotLink'),card=e.target.closest('.scanCard');if(reportLink){e.preventDefault();return openReport(card?.dataset.symbol)}if(snapshotLink){e.stopPropagation();return}if(card)openReport(card.dataset.symbol)});$('results').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.scanCard')){e.preventDefault();openReport(e.target.closest('.scanCard').dataset.symbol)}});$('refreshBtn').addEventListener('click',refresh);refresh();setInterval(refresh,60000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
