(()=>{'use strict';const $=id=>document.getElementById(id),TF=['1w','1d','4h','1h','15m'];let report=null;const text=v=>String(v??'');function fmt(v,d=6){const n=Number(v);if(!Number.isFinite(n))return'-';return Math.abs(n)>=100?n.toFixed(2):n.toFixed(d).replace(/0+$/,'').replace(/\.$/,'')}function row(k,v){const d=document.createElement('div');d.className='item';const b=document.createElement('b');b.textContent=k;const s=document.createElement('span');s.textContent=v;d.append(b,s);return d}function clear(el){while(el.firstChild)el.removeChild(el.firstChild)}function decisionLabel(v){return v==='OBSERVE'?'관찰':v==='DATA_WARNING'?'데이터 주의':'NO SIGNAL'}function trendLabel(v){return v==='bullish'?'상승':v==='bearish'?'하락':v==='neutral'?'중립':'데이터 부족'}function calibration(){try{const OR=window.PulseOutcomeRecorder,C=window.PulseCalibration;if(!OR||!C||!report)return{status:'insufficient',N:0};const samples=OR.resolvedSamples({symbol:report.symbol,horizon:'20',validationSource:'LIVE_VALIDATED'});return C.resolveHierarchical(samples,{symbol:report.symbol,tf:'4h',pattern:report.pattern?.name||'none',regime:report.multiTimeframe?.['4h']?.trend||'unknown',venue:'BINANCE_SPOT'},{validationSource:'LIVE_VALIDATED'})}catch{return{status:'insufficient',N:0}}}
function renderCalibration(){const c=calibration(),badge=$('calBadge'),notice=$('calNotice');badge.textContent=`Calibration ${c.status} · N=${c.N??c.n??0}`;badge.dataset.state=c.status;notice.textContent=c.status==='insufficient'?'표본 수집 중 · 검증 표본이 부족해 방향성 신뢰 배지를 만들지 않습니다. 현재 결과는 시장 구조 관찰용입니다.':c.status==='weak'?'검증 표본이 아직 약합니다. 구조 해석은 가능하지만 과도한 확신은 피해야 합니다.':'기존 LIVE_VALIDATED 표본 기준으로 calibration이 충분한 구간입니다.';if(c.status==='insufficient')$('decisionBadge').textContent='NO SIGNAL'}
function renderSummary(){const r=report;$('symbolTitle').textContent=r.symbol;$('updated').textContent=`업데이트 ${new Date(r.updatedAt).toLocaleString('ko-KR')} · Binance 현물`;$('decisionBadge').textContent=decisionLabel(r.decisionState);$('decisionBadge').dataset.state=r.decisionState;$('headline').textContent=r.beginnerSummary?.headline||'-';$('easyText').textContent=r.beginnerSummary?.text||'-';const lv=$('levels');clear(lv);lv.append(row('주요 지지',fmt(r.levels?.support)),row('주요 저항',fmt(r.levels?.resistance)),row('수요 구간',r.levels?.supportZone?.map(x=>fmt(x)).join(' ~ ')||'-'),row('공급 구간',r.levels?.resistanceZone?.map(x=>fmt(x)).join(' ~ ')||'-'));const an=$('anomalies');clear(an);(r.anomalies?.length?r.anomalies:[{label:'특이 신호',value:'뚜렷한 거래량/체결 이상 없음'}]).forEach(x=>an.append(row(x.label,x.value)));$('pattern').innerHTML='';$('pattern').append(row(r.pattern?.label||'패턴 없음',r.pattern?.state||'관찰'));renderCalibration()}
function renderMtf(){const el=$('mtfCards');clear(el);for(const tf of TF){const x=report.multiTimeframe?.[tf]||{},d=document.createElement('div');d.className=`tfCard ${x.trend||'unknown'}`;const h=document.createElement('div');h.className='tfTop';const b=document.createElement('b');b.textContent=tf.toUpperCase();const s=document.createElement('span');s.textContent=`${x.role||''} · ${trendLabel(x.trend)}`;h.append(b,s);const p=document.createElement('p');p.textContent=x.summary||'데이터 없음';d.append(h,p);el.append(d)}}

function pctFmt(v,d=2){const n=Number(v);return Number.isFinite(n)?`${n>0?'+':''}${n.toFixed(d)}%`:'확인 불가'}
function zoneFmt(z){return z&&Number.isFinite(+z.from)&&Number.isFinite(+z.to)?`${fmt(z.from)} ~ ${fmt(z.to)}`:'확인 불가'}
function judgmentKo(v){return v==='bullish'?'강세':v==='bearish'?'약세':'중립'}
function macdKo(x){if(!x)return'확인 불가';const cross=x.cross==='bull_cross'?'상승 크로스':x.cross==='bear_cross'?'하락 크로스':'크로스 없음';return `${cross} · 0선 ${x.zero==='above'?'위':'아래'} · Hist ${fmt(x.hist,6)}`}
function renderProTf(id,m){const el=$(id);clear(el);if(!m?.available){el.append(row('상태','확인 불가'));return}el.append(row('추세',trendLabel(m.trend)),row('확정봉 종가',fmt(m.last?.c)),row('범위 위치',m.rangePosition20==null?'확인 불가':`최근 20봉 하단에서 ${Math.round(m.rangePosition20*100)}%`),row('RSI-14',fmt(m.rsi14,2)),row('MACD',macdKo(m.macd)),row('ATR',m.atrPct==null?'확인 불가':`${fmt(m.atr14)} · ${fmt(m.atrPct,2)}%`),row('거래량',m.volume?.ratio20==null?'확인 불가':`20봉 평균 대비 ${fmt(m.volume.ratio20,2)}x`))}
function renderLevelList(id,levels,empty){const el=$(id);clear(el);if(!levels?.length){el.append(row('상태',empty));return}levels.slice(0,4).forEach((z,i)=>el.append(row(`#${i+1} · 점수 ${fmt(z.score,1)}`,`${zoneFmt(z)} · ${(z.reasons||[]).slice(0,3).join(' + ')||'단일 근거'}`)))}
function renderIndicators(p){const el=$('proIndicators');clear(el);for(const tf of ['1h','4h','1d']){const m=p.timeframes?.[tf];if(!m?.available){el.append(row(tf.toUpperCase(),'확인 불가'));continue}const e=[20,50,100,200].map(n=>`E${n} ${m.ema?.[n]?.value==null?'-':fmt(m.ema[n].value)}`).join(' · ');el.append(row(tf.toUpperCase(),`${e} | RSI ${fmt(m.rsi14,1)} | MACD H ${fmt(m.macd?.hist,6)}`))}}
function renderPro(){
 const p=report.professional;if(!p){$('proTldr').textContent='전문 분석 데이터 확인 불가';return}
 const j=p.judgement||{},s=p.levels?.supports?.[0],r=p.levels?.resistances?.[0],badge=$('proJudgement');badge.textContent=judgmentKo(j.state);badge.dataset.state=String(j.state||'neutral').toUpperCase();
 $('proTldr').textContent=`현재 ${fmt(p.currentPrice)} · 1H ${trendLabel(p.timeframes?.['1h']?.trend)}, 4H ${trendLabel(p.timeframes?.['4h']?.trend)}, 1D ${trendLabel(p.timeframes?.['1d']?.trend)}. 핵심 지지 ${zoneFmt(s)}, 핵심 저항 ${zoneFmt(r)}. 현재 판단은 ${judgmentKo(j.state)}이며, 판단 변경 조건은 ${j.changeCondition||'확인 불가'}입니다.`;
 const ms=$('proMarket');clear(ms);[['현재가',fmt(p.market?.currentPrice)],['24h',pctFmt(p.market?.change24hPct)],['7d',pctFmt(p.market?.change7dPct)],['24h 거래대금',p.market?.quoteVolume24h==null?'확인 불가':`${Number(p.market.quoteVolume24h).toLocaleString('en-US',{maximumFractionDigits:0})}`]].forEach(([k,v])=>{const d=document.createElement('div');d.className='proStat';const a=document.createElement('span');a.textContent=k;const b=document.createElement('b');b.textContent=v;d.append(a,b);ms.append(d)});
 renderProTf('proTf1h',p.timeframes?.['1h']);renderProTf('proTf4h',p.timeframes?.['4h']);renderProTf('proTf1d',p.timeframes?.['1d']);
 renderLevelList('proSupports',p.levels?.supports,'지지 구간 확인 불가');renderLevelList('proResistances',p.levels?.resistances,'저항 구간 확인 불가');renderIndicators(p);
 const fp=$('proFibPivot');clear(fp);if(p.fibonacci?.levels){fp.append(row('Fib 스윙',`${fmt(p.fibonacci.low?.price)} → ${fmt(p.fibonacci.high?.price)}`));for(const k of['23.6','38.2','50','61.8','78.6'])fp.append(row(`Fib ${k}%`,fmt(p.fibonacci.levels[k])))}else fp.append(row('Fibonacci','확인 불가'));if(p.pivot){for(const k of['p','s1','s2','s3','r1','r2','r3'])fp.append(row(k.toUpperCase(),fmt(p.pivot[k])))}else fp.append(row('Pivot','확인 불가'));
 const d=$('proDerivatives'),dv=p.derivatives||{};clear(d);d.append(row('OI 1H',pctFmt(dv.oi1hPct)),row('OI 4H',pctFmt(dv.oi4hPct)),row('OI 24H',pctFmt(dv.oi24hPct)),row('Funding',pctFmt(dv.fundingPct,4)),row('Taker 1H',dv.taker1hRatio==null?'확인 불가':fmt(dv.taker1hRatio,3)),row('전체 Long/Short',dv.globalLongShortRatio==null?'확인 불가':fmt(dv.globalLongShortRatio,3)),row('Top Position L/S',dv.topTraderPositionRatio==null?'확인 불가':fmt(dv.topTraderPositionRatio,3)),row('해석',dv.oiInterpretation||'확인 불가'));
 const rs=$('proRelative'),rv=p.relativeStrength||{};clear(rs);rs.append(row('DOGE/대상 24H',pctFmt(rv.asset24hPct)),row('BTC 24H',pctFmt(rv.btc24hPct)),row('ETH 24H',pctFmt(rv.eth24hPct)),row('BTC 대비 24H',pctFmt(rv.vsBtc24hPct)),row('ETH 대비 24H',pctFmt(rv.vsEth24hPct)),row('BTC 대비 7D',pctFmt(rv.vsBtc7dPct)),row('ETH 대비 7D',pctFmt(rv.vsEth7dPct)));
 const sg=$('proScenarios');clear(sg);for(const [key,title] of[['bullish','강세'],['neutral','중립'],['bearish','약세']]){const x=p.scenarios?.[key]||{},box=document.createElement('div');box.className=`scenario ${key}`;const h=document.createElement('b');h.textContent=title;const q=document.createElement('p');q.textContent=key==='neutral'?`박스 ${fmt(x.boxLow)} ~ ${fmt(x.boxHigh)} · ${x.reason||''}`:`${x.trigger||''} · 다음 ${x.next||'-'} · 무효화 ${x.invalidatedBy||'-'}${x.volumeCondition?' · '+x.volumeCondition:''}`;box.append(h,q);sg.append(box)}
 const risk=$('proRisk');clear(risk);risk.append(row('현재 판단',judgmentKo(j.state)),row('판단 변경',j.changeCondition||'확인 불가'),row('4H 변동성',p.risk?.volatility4hPct==null?'확인 불가':`${fmt(p.risk.volatility4hPct,2)}%`),row('레버리지 과밀',p.risk?.leverageCrowding==null?'확인 불가':p.risk.leverageCrowding?'주의':'뚜렷하지 않음'),row('데이터 경고',(p.risk?.dataWarnings||[]).join(' · ')||'없음'))
}
function renderSmart(){const st=$('structure');clear(st);st.append(row('구조 신호',text(report.smartMoney?.structure?.type||'none')),row('구조 기준 가격',fmt(report.smartMoney?.structure?.price)));const sm=$('smartMoney');clear(sm);const ob=report.smartMoney?.orderBlockLike||{};sm.append(row('수요/방어 구간',ob.demand?.map(x=>fmt(x)).join(' ~ ')||'-'),row('공급/매도 구간',ob.supply?.map(x=>fmt(x)).join(' ~ ')||'-'));for(const f of report.smartMoney?.fvg||[])sm.append(row(`${f.type==='bullish'?'상승':'하락'} FVG`,`${fmt(f.from)} ~ ${fmt(f.to)}`));for(const l of report.smartMoney?.liquidity||[])sm.append(row(l.type==='buy_side'?'상단 유동성':'하단 유동성',`${fmt(l.price)} · ${l.touches}회 근접`))}
function priceMapper(candles,H,pad){const lo=Math.min(...candles.map(x=>x.l)),hi=Math.max(...candles.map(x=>x.h)),range=hi-lo||1;return p=>pad+(hi-p)/range*(H-pad*2)}
function drawPattern(ctx,geometry,y,W,pad,label){if(!geometry)return false;ctx.save();ctx.strokeStyle='#f4c56a';ctx.lineWidth=3;ctx.setLineDash([12,7]);let drew=false;for(const key of['upper','lower']){const L=geometry[key];if(!L||![L.x1,L.x2,L.y1,L.y2].every(Number.isFinite))continue;ctx.beginPath();ctx.moveTo(pad+L.x1*(W-pad*2),y(L.y1));ctx.lineTo(pad+L.x2*(W-pad*2),y(L.y2));ctx.stroke();drew=true}if(drew){ctx.setLineDash([]);ctx.fillStyle='#f4c56a';ctx.font='bold 18px system-ui';ctx.fillText(label,pad+8,30)}ctx.restore();return drew}
function drawSnapshot(){const cv=$('snapshot'),ctx=cv.getContext('2d'),r=report.snapshot||{},c=r.candles||[];ctx.clearRect(0,0,cv.width,cv.height);ctx.fillStyle='#07111d';ctx.fillRect(0,0,cv.width,cv.height);if(!c.length){ctx.fillStyle='#8ea4bc';ctx.font='32px system-ui';ctx.fillText('차트 데이터 없음',40,80);return}const W=cv.width,H=cv.height,pad=58,y=priceMapper(c,H,pad),step=(W-pad*2)/c.length,bw=Math.max(3,step*.55);for(let i=0;i<c.length;i++){const x=pad+i*step+step/2,k=c[i],up=k.c>=k.o;ctx.strokeStyle=up?'#42d392':'#ff6b7a';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y(k.h));ctx.lineTo(x,y(k.l));ctx.stroke();ctx.fillRect(x-bw/2,Math.min(y(k.o),y(k.c)),bw,Math.max(2,Math.abs(y(k.o)-y(k.c))))}ctx.font='bold 18px system-ui';for(const o of(r.overlays||[]).slice(0,8)){if(o.kind==='pattern'){drawPattern(ctx,o.geometry,y,W,pad,o.label);continue}const zone=Number.isFinite(o.from)&&Number.isFinite(o.to),py=zone?Math.min(y(o.from),y(o.to)):y(o.price);if(!Number.isFinite(py))continue;ctx.save();if(zone){ctx.globalAlpha=.18;ctx.fillStyle=o.kind==='demand'?'#3ddc97':o.kind==='supply'?'#ff7b72':'#66aaff';const py2=Math.max(y(o.from),y(o.to));ctx.fillRect(pad,py,W-pad*2,Math.max(3,py2-py));ctx.globalAlpha=1}else{ctx.strokeStyle=o.kind==='support'?'#50d890':o.kind==='resistance'?'#ff7b72':'#7aa2ff';ctx.setLineDash(o.kind==='liquidity'?[10,8]:[]);ctx.beginPath();ctx.moveTo(pad,py);ctx.lineTo(W-pad,py);ctx.stroke()}ctx.fillStyle='#e8f1fb';ctx.fillText(`${o.label} ${zone?`${fmt(o.from)}–${fmt(o.to)}`:fmt(o.price)}`,pad+8,Math.max(24,py-7));ctx.restore()}ctx.fillStyle='#9bb0c5';ctx.font='16px system-ui';ctx.fillText(`${report.symbol} · ${String(r.timeframe||'4h').toUpperCase()} · 자동 분석 합본`,pad,H-20);$('snapshotCaption').textContent=`${String(r.timeframe||'4h').toUpperCase()} · 지지/저항·수급·패턴·FVG·유동성 중 중요도 상위 8개만 표시`;const leg=$('overlayLegend');clear(leg);(r.overlays||[]).slice(0,8).forEach(o=>leg.append(row(o.label,o.kind==='pattern'?'차트 위 점선 오버레이':Number.isFinite(o.price)?fmt(o.price):`${fmt(o.from)} ~ ${fmt(o.to)}`)))}
function renderEvidence(){const w=$('warnings');clear(w);(report.dataWarnings?.length?report.dataWarnings:['데이터 경고 없음']).forEach(x=>w.append(row(report.dataWarnings?.length?'주의':'상태',x)));$('conflict').textContent=report.conflict?.active?`시간봉 충돌 있음 · 상승 ${report.conflict.bullishCount} / 하락 ${report.conflict.bearishCount}`:'주요 시간봉 간 강한 방향 충돌 없음';const d=$('derivatives');clear(d);d.append(row('OI 변화',report.derivatives?.oiChangePct==null?'-':`${fmt(report.derivatives.oiChangePct,2)}%`),row('Funding',report.derivatives?.fundingPct==null?'-':`${fmt(report.derivatives.fundingPct,4)}%`))}
async function loadNews(){try{const r=await fetch(`/api/coin-report?mode=news&symbol=${encodeURIComponent(report.symbol)}`,{cache:'no-store'}),j=await r.json();$('newsSummary').textContent=j.summary||'뉴스 연결 상태 · 확인된 뉴스 요약 없음';const items=$('newsItems');clear(items);(j.items?.length?j.items:['확인된 뉴스 항목 없음']).forEach(x=>items.append(row('뉴스',typeof x==='string'?x:text(x.title||x.summary||JSON.stringify(x)))));const src=$('newsSources');clear(src);for(const x of j.sources||[]){const a=document.createElement('a');a.href=x.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=x.title||x.url;src.append(a)}}catch(e){$('newsSummary').textContent=`뉴스 연결 상태 · 보강 실패: ${e.message}`}}
function render(){renderSummary();renderMtf();renderPro();renderSmart();drawSnapshot();renderEvidence();const s=encodeURIComponent(report.symbol);$('legacySnapshot').href=`/snapshot-hub.html?mode=board&symbol=${s}&shell=1`;$('unifiedChart').href=`/unified-chart.html?symbol=${s}&shell=1`;$('danteLab').href=`/dante-lab.html?symbol=${s}&shell=1`;loadNews()}
async function load(){const q=new URLSearchParams(location.search),symbol=(q.get('symbol')||'BTCUSDT').toUpperCase();try{const r=await fetch(`/api/coin-report?symbol=${encodeURIComponent(symbol)}`,{cache:'no-store'}),j=await r.json();if(!r.ok||j.status!=='ok')throw new Error(j.error||`HTTP ${r.status}`);report=j;render()}catch(e){const box=$('errorBox');box.classList.remove('hidden');box.textContent=`종합 분석을 불러오지 못했습니다: ${e.message}`}}
function tabs(){document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab));if(b.dataset.tab==='snapshot'&&report)setTimeout(drawSnapshot,0)})}tabs();load();})();