(()=>{'use strict';const $=id=>document.getElementById(id);let data=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function filtered(){const q=$('query').value.trim().toUpperCase(),c=$('classification').value;return data.filter(x=>(!q||String(x.symbol).includes(q))&&(!c||x.classification===c))}
function render(){const rows=filtered();$('snapCount').textContent=data.length;$('candidateCount').textContent=data.filter(x=>x.classification==='CANDIDATE').length;$('watchCount').textContent=data.filter(x=>x.classification==='WATCHLIST').length;$('eventCount').textContent=data.filter(x=>x.classification==='EVENT_RISK').length;$('riskCount').textContent=data.filter(x=>x.classification==='RISK_FILTERED').length;$('blockedCount').textContent=data.filter(x=>['INSUFFICIENT_DATA','REJECTED'].includes(x.classification)).length;$('rows').innerHTML=rows.map(x=>{const s=x.scores||{},ev=(x.evidence||[]).slice(0,3).map(e=>esc(e.value||e.type)).join(' · ');return '<article class="row"><div><div class="sym">'+esc(x.symbol)+'</div><div class="class '+esc(x.classification)+'">'+esc(x.classification)+'</div></div><div>'+esc(new Date(x.decision_time).toLocaleString('ko-KR',{hour12:false}))+'</div><div class="scores"><span>최종 '+esc(s.final_score??'-')+'</span><span>시장 '+esc(s.market_quality??'-')+'</span><span>ICT '+esc(s.ict_setup??'-')+'</span><span>체결 '+esc(s.execution_quality??'-')+'</span><span>품질 '+esc(s.data_quality??'-')+'</span></div><button class="replayBtn" data-id="'+esc(x.snapshot_id)+'">Replay</button><div class="evidence">'+ev+'</div><div class="meta">'+esc(x.snapshot_id)+' · '+esc(x.input_hash)+'</div></article>'}).join('')||'<div class="status">조건에 맞는 snapshot이 없습니다.</div>'}
async function load(){try{$('status').textContent='원장 불러오는 중…';const r=await fetch('/api/coin-scan?mode=selector-history&action=list&limit=500',{cache:'no-store'}),d=await r.json();if(!r.ok||d.status!=='ok')throw new Error(d.error||'load failed');data=d.items||[];$('status').textContent='append-only snapshot '+data.length+'개';render()}catch(e){$('status').textContent='불러오기 실패 · '+e.message}}
async function replay(id){try{const r=await fetch('/api/coin-scan?mode=selector-history&action=replay&id='+encodeURIComponent(id),{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'replay failed');$('replayOut').textContent=JSON.stringify(d.replay,null,2);$('replayDialog').showModal()}catch(e){$('replayOut').textContent=String(e.message);$('replayDialog').showModal()}}
async function transitions(){try{const r=await fetch('/api/coin-scan?mode=selector-history&action=transitions&limit=300',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'transition load failed');$('replayOut').textContent=JSON.stringify(d.items,null,2);$('replayDialog').showModal()}catch(e){$('replayOut').textContent=String(e.message);$('replayDialog').showModal()}}
async function evidence(){try{const r=await fetch('/api/coin-scan?mode=selector-history&action=evidence&limit=500',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'evidence load failed');$('replayOut').textContent=JSON.stringify(d.items,null,2);$('replayDialog').showModal()}catch(e){$('replayOut').textContent=String(e.message);$('replayDialog').showModal()}}
async function ablation(){try{const r=await fetch('/api/coin-scan?mode=selector-history&action=ablation&horizon=h24&feeBps=4&slippageBps=6&fundingBps=1',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'ablation failed');$('replayOut').textContent=JSON.stringify(d.report,null,2);$('replayDialog').showModal()}catch(e){$('replayOut').textContent=String(e.message);$('replayDialog').showModal()}}
function init(){$('refresh').onclick=load;$('query').oninput=render;$('classification').onchange=render;$('loadTransitions').onclick=transitions;$('loadEvidence').onclick=evidence;$('loadAblation').onclick=ablation;$('rows').addEventListener('click',e=>{const b=e.target.closest('.replayBtn');if(b)replay(b.dataset.id)});load()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init()})();