'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../../ui/dante/cloud-engine.js');
function bars(n=520){return Array.from({length:n},(_,i)=>({openTime:i*86400000,time:i*86400000,closeTime:(i+1)*86400000-1,open:100,high:101,low:99,close:100,volume:100}));}
test('no fabricated long average for a young listing',()=>{const r=E.analyze({candles:bars(200),asOf:201*86400000});assert.equal(r.status,'INSUFFICIENT_HISTORY');assert.equal(r.ma[448],null);assert.equal(r.matched,false)});
test('current cloud is shifted 26 candles and prefix causal',()=>{const c=bars();for(let i=480;i<520;i++){c[i].high=201;c[i].low=199;c[i].close=200;}const r=E.analyze({candles:c,asOf:520*86400000});const source=c.slice(519-26-25,519-26+1);assert.equal(r.cloud.kijunAtSource,(Math.max(...source.map(x=>x.high))+Math.min(...source.map(x=>x.low)))/2);assert.notEqual(r.cloud.top,r.cloud.futureTop);const a=E.analyze({candles:c.slice(0,490),asOf:490*86400000}),b=E.analyze({candles:c,asOf:490*86400000});assert.deepEqual(a,b)});
test('RVOL excludes signal bar; forming bars cannot change signal',()=>{const c=bars();c.at(-1).volume=500;const r=E.analyze({candles:c,asOf:520*86400000});assert.equal(r.rvol,5);assert.deepEqual(E.analyze({candles:[...c,{...c.at(-1),openTime:520*86400000,closeTime:521*86400000-1,close:999,partial:true}],asOf:520*86400000}),r)});
test('SMA and seeded EMA require their full window',()=>{assert.equal(E.average([1,2],3,'EMA').at(-1),null);assert.equal(E.average([1,2,3,9],3,'SMA').at(-1),14/3);assert.equal(E.average([1,2,3,9],3,'EMA').at(-1),5.5)});
test('flat averages are not a trend pullback',()=>{const r=E.analyze({candles:bars(),asOf:520*86400000});assert.equal(r.matched,false);assert.equal(r.setup,null)});
test('bear-to-recovery setup, volume evidence, and close invalidation',()=>{const c=bars();for(let i=0;i<520;i++){const v=i<300?200:i<400?200-(i-300)*1.5:i<514?50:53;c[i]={...c[i],open:v-1,high:v+1,low:v-1,close:v};}c[514].volume=400;const r=E.analyze({candles:c,asOf:520*86400000});assert.equal(r.setup,'112 회복형');assert.equal(r.matched,true);c.at(-1).close=40;const bad=E.analyze({candles:c,asOf:520*86400000});assert.equal(bad.matched,false);assert.equal(bad.checks.above112,false)});
test('execution rejects stale candles and unavailable taker',()=>{const api=require('../../handlers/dante-cloud.js')._test;const c=bars(300),raw=c.map(x=>[x.openTime,x.open,x.high,x.low,x.close,x.volume,x.closeTime,10000,null,null,null]);const x=api.execution(raw,'15m',301*86400000);assert.equal(x.fresh,false);assert.equal(x.taker,null);assert.equal(x.pass,false);assert.equal(api.fresh({lastClosedCloseTime:86400000-1},'1d',86400001),true)});
test('universe has no volume or price-change prefilter and keeps actual source',async()=>{const u=await require('../../handlers/dante-cloud.js')._test.universe({getFuturesUniverse:async()=>({_fallbackSource:'BYBIT_LINEAR',symbols:[{symbol:'LOWUSDT',status:'TRADING',quoteAsset:'USDT',contractType:'PERPETUAL'},{symbol:'HIGHUSDT',status:'TRADING',quoteAsset:'USDT',contractType:'PERPETUAL'},{symbol:'BADUSDC',status:'TRADING',quoteAsset:'USDC',contractType:'PERPETUAL'}]})});assert.deepEqual(u.symbols,['HIGHUSDT','LOWUSDT']);assert.equal(u.source,'BYBIT_LINEAR');assert.equal(u.minQuoteVolume,0)});
test('crypto universe excludes stock, forex, commodity and ETF contracts',async()=>{const p={getFuturesUniverse:async()=>({_fallbackSource:'BYBIT_LINEAR',symbols:['innovation','stock','forex','commodity','ETF'].map((symbolType,i)=>({symbol:'TEST'+i+'USDT',symbolType,status:'TRADING',quoteAsset:'USDT',contractType:'PERPETUAL'}))})};const u=await require('../../handlers/dante-cloud.js')._test.universe(p);assert.deepEqual(u.symbols,['TEST0USDT']);assert.equal(u.excludedTradFi,4);});
test('preflight replaces cached Binance universe when candles fall back to Bybit',async()=>{const symbol=type=>({symbol:type+'USDT',status:'TRADING',quoteAsset:'USDT',contractType:'PERPETUAL'});const p={getFuturesUniverse:async()=>({symbols:[symbol('BINANCEONLY')]}),getFuturesKlines:async()=>Object.assign([],{_source:'BYBIT_LINEAR'}),getBybitUniverse:async()=>({_fallbackSource:'BYBIT_LINEAR',symbols:[symbol('BYBITONLY')]}),getSourceState:()=>({})};const u=await require('../../handlers/dante-cloud.js')._test.universe(p);assert.equal(u.source,'BYBIT_LINEAR');assert.deepEqual(u.symbols,['BYBITONLYUSDT']);});
