'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const code=fs.readFileSync('ui/dante/cloud-ui.js','utf8');
async function screen(job,{remembered=null}={}){const calls=[],nodes={},buttons=[],storage=new Map(remembered?[['danteCloudJob',remembered]]:[]);const get=id=>nodes[id]||(nodes[id]={value:({filter:'all',tf:'4h',maType:'SMA',symbol:'BTCUSDT'})[id]||'',textContent:'',getContext:()=>({})});Object.defineProperty(get('rows'),'innerHTML',{get(){return this.html;},set(v){this.html=v;buttons.length=0;for(const m of v.matchAll(/data-symbol="([^"]+)" data-tf="([^"]+)"/g))buttons.push({dataset:{symbol:m[1],tf:m[2]}});}});const fetch=async url=>{const q=new URL(url,'https://test').searchParams;calls.push(Object.fromEntries(q));if(q.get('action')==='chart')return{ok:true,status:200,json:async()=>({ok:true,symbol:q.get('symbol'),tf:q.get('tf'),source:job.source,candles:[],analysis:{maType:q.get('maType'),bars:550,reasons:[]}})};if(q.get('id')==='expired')return{ok:false,status:404,json:async()=>({ok:false,error:'expired'})};return{ok:true,status:200,json:async()=>({ok:true,...job})};};vm.runInNewContext(code,{document:{getElementById:get,querySelectorAll:()=>buttons},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},fetch,URLSearchParams,clearTimeout(){},setTimeout(){},console});await new Promise(r=>setImmediate(r));return{nodes,buttons,calls,storage};}
function result(){return{id:'latest',status:'DONE',source:'BYBIT_LINEAR',maType:'EMA',asOf:Date.now(),total:1,completed:1,errors:[],stale:0,insufficientHistory:0,rows:[{symbol:'ALGOUSDT',matched:true,frames:{'1d':{setup:'전환',matched:true,resistances:[]},'4h':{setup:null,matched:false}},execution:{confirmed:false,status:'실행 대기'}}]};}
test('expired remembered job recovers latest result and MA type',async()=>{const s=await screen(result(),{remembered:'expired'});assert.equal(s.storage.get('danteCloudJob'),'latest');assert.match(s.nodes.rows.innerHTML,/ALGO/);assert.equal(s.nodes.maType.value,'EMA');assert.equal(s.nodes.error.textContent,'');});
test('daily matched row opens daily chart with scan MA type',async()=>{const s=await screen(result());s.buttons[0].onclick();await new Promise(r=>setImmediate(r));assert.equal(s.calls.at(-1).tf,'1d');assert.equal(s.calls.at(-1).maType,'EMA');assert.equal(s.calls.at(-1).symbol,'ALGOUSDT');});
test('failed scan is described as missing data rather than no matching conditions',async()=>{const j=result();j.rows=[];j.errors=[{symbol:'ALGOUSDT'}];const s=await screen(j);assert.match(s.nodes.rows.innerHTML,/가격 조회 오류/);assert.match(s.nodes.rows.innerHTML,/판단할 수 없습니다/);});
test('zero execution results explains how to see chart candidates',async()=>{const s=await screen(result());s.nodes.filter.value='confirmed';s.nodes.filter.onchange();assert.match(s.nodes.rows.innerHTML,/차트 후보는 표시 필터/);});
