const BASES=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];
async function getJson(path,params={}){let last;const qs=new URLSearchParams(params).toString();for(const base of BASES){try{const r=await fetch(base+path+(qs?'?'+qs:''),{headers:{'User-Agent':'PulseRadar-Pro/3.4'}});const t=await r.text();if(!r.ok)throw new Error(`Binance ${r.status}: ${t.slice(0,180)}`);return JSON.parse(t)}catch(e){last=e}}throw last||new Error('Binance request failed')}
const n=v=>Number(v)||0, clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
function ema(a,p){const k=2/(p+1),o=[];let x=a[0]||0;for(let i=0;i<a.length;i++){x=i?a[i]*k+x*(1-k):a[i];o.push(x)}return o}
function sma(a,p){let o=Array(a.length).fill(null),s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)o[i]=s/p}return o}
function rsi(a,p=14){const out=Array(a.length).fill(null);if(a.length<=p)return out;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;out[p]=l?100-100/(1+g/l):100;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;out[i]=l?100-100/(1+g/l):100}return out}
function sd(a){if(!a.length)return 0;const m=a.reduce((s,x)=>s+x,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}
function atr(h,l,c,p=14){const tr=h.map((x,i)=>i?Math.max(x-l[i],Math.abs(x-c[i-1]),Math.abs(l[i]-c[i-1])):x-l[i]);return ema(tr,p)}
function macdHist(a){const a12=ema(a,12),a26=ema(a,26),line=a.map((_,i)=>a12[i]-a26[i]),sig=ema(line,9);return line.map((x,i)=>x-sig[i])}
function avg(a){return a.length?a.reduce((s,x)=>s+x,0)/a.length:null}
function med(a){if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function pct(a,b){return b?((a/b)-1)*100:0}
function build(raw){const o=raw.map(k=>n(k[1])),h=raw.map(k=>n(k[2])),l=raw.map(k=>n(k[3])),c=raw.map(k=>n(k[4])),v=raw.map(k=>n(k[5])),q=raw.map(k=>n(k[7])),taker=raw.map(k=>n(k[10]));const e5=ema(c,5),e20=ema(c,20),e60=ema(c,60),rr=rsi(c),aa=atr(h,l,c),vs=sma(v,20),mh=macdHist(c);return{o,h,l,c,v,q,taker,e5,e20,e60,rr,aa,vs,mh}}
function state(d,i){const {o,h,l,c,v,q,taker,e5,e20,e60,rr,aa,vs,mh}=d;if(i<80)return null;const price=c[i],atrPct=price?aa[i]/price*100:0,volRatio=vs[i]?v[i]/vs[i]:0;const maxE=Math.max(e5[i],e20[i],e60[i]),minE=Math.min(e5[i],e20[i],e60[i]),gap=maxE?(maxE-minE)/maxE*100:0;const w=c.slice(i-19,i+1),mid=avg(w),bw=mid?4*sd(w)/mid:0;const prev=[];for(let z=i-40;z<=i-20;z++){const s=c.slice(z-19,z+1);if(s.length===20){const m=avg(s);if(m)prev.push(4*sd(s)/m)}}const prevAvg=avg(prev)||bw;let bq=0,tq=0;for(let z=i-4;z<=i;z++){bq+=taker[z]||0;tq+=q[z]||0}const buyRatio=tq?bq/tq:.5,lastRange=o[i]?(h[i]-l[i])/o[i]*100:0;const squeeze=bw<prevAvg*.82,converging=gap<1.3;let score=0;if(squeeze)score+=22;if(converging)score+=20;if(volRatio>=1.1&&volRatio<=2.5)score+=18;if(rr[i]>=47&&rr[i]<=62)score+=15;if(mh[i]>0)score+=15;if(buyRatio>=.52)score+=10;let penalty=0;if(rr[i]>72||volRatio>4||atrPct>8)penalty+=12;score=clamp(score-penalty);const hard=rr[i]>=82||gap>=8||atrPct>=9||volRatio>=6||lastRange>=10;return{score,hard,rsi:rr[i],volRatio,atrPct,gap,buyRatio,squeeze,converging}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=120');try{const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase();const interval=String(req.query.interval||'1h');const friction=Math.max(0,Math.min(2,Number(req.query.friction??0.2)));const raw=await getJson('/api/v3/klines',{symbol,interval,limit:'1000'});if(!Array.isArray(raw)||raw.length<150)throw new Error('Not enough candle history');const d=build(raw);const events=[];for(let i=80;i<raw.length-41;i++){const s=state(d,i);if(!s||s.hard||s.score<55)continue;const entry=d.o[i+1];if(!entry)continue;const r10=pct(d.c[i+10],entry)-friction,r20=pct(d.c[i+20],entry)-friction,r40=pct(d.c[i+40],entry)-friction;let maxH=-Infinity,minL=Infinity;for(let z=i+1;z<=i+40;z++){maxH=Math.max(maxH,d.h[z]);minL=Math.min(minL,d.l[z])}events.push({time:raw[i][0],score:Math.round(s.score),entry,r10,r20,r40,mfe40:pct(maxH,entry),mae40:pct(minL,entry),rsi:s.rsi,volRatio:s.volRatio,atrPct:s.atrPct,buyRatio:s.buyRatio})}
const summarize=(key)=>{const a=events.map(e=>e[key]);return{mean:avg(a),median:med(a),positiveRate:a.length?a.filter(x=>x>0).length/a.length*100:null}};const dd=[];let eq=100,peak=100,mdd=0;for(const e of events){eq*=1+e.r40/100;peak=Math.max(peak,eq);const x=(eq/peak-1)*100;mdd=Math.min(mdd,x);dd.push(x)}res.status(200).json({ok:true,symbol,interval,assumptions:{signal:'PRE-SURGE-like score >=55, hard risk gate excluded',referenceEntry:'next candle open',frictionPct:friction,holding:'10/20/40 candles, no stop/target'},sampleSize:events.length,summary:{r10:summarize('r10'),r20:summarize('r20'),r40:summarize('r40'),mfe40:{mean:avg(events.map(e=>e.mfe40)),median:med(events.map(e=>e.mfe40))},mae40:{mean:avg(events.map(e=>e.mae40)),median:med(events.map(e=>e.mae40))},maxDrawdown40Sequence:mdd},events:events.slice(-60).reverse()})}catch(e){res.status(502).json({ok:false,error:e?.message||'Backtest failed'})}}
