'use strict';
const {randomUUID}=require('node:crypto');
const {createBinanceProvider}=require('../lib/coin-scan/binance-provider.js');
const E=require('../ui/dante/cloud-engine.js');
let provider;const jobs=new Map();let active=null,starting=false;
function getProvider(){return provider||(provider=createBinanceProvider({concurrency:1,intervalConcurrency:1,futuresMinIntervalMs:350,disableSpotRest:false,disableFuturesFallback:false}));}
const sourceOf=(raw,p)=>raw._source||(p.getSourceState().futuresFallbackSource==='bybit'?'BYBIT_LINEAR':'UNKNOWN');
function fresh(r,tf,asOf){const ms={'1d':86400000,'4h':14400000,'1h':3600000,'15m':900000,'5m':300000}[tf];return r.lastClosedCloseTime===Math.floor(asOf/ms)*ms-1;}
function summary(j){return{...j,rows:j.rows.slice().sort((a,b)=>Number(b.matched)-Number(a.matched)||Number(b.frames?.['1d']?.matched)-Number(a.frames?.['1d']?.matched)),sourceState:getProvider().getSourceState()};}
async function universe(p){const u=await p.getFuturesUniverse();return{source:u._fallbackSource||'BINANCE_FUTURES',symbols:(u.symbols||[]).filter(x=>x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.contractType==='PERPETUAL').map(x=>x.symbol).sort(),asOf:Date.now(),minQuoteVolume:0};}
async function fetchFrame(p,symbol,tf,source,asOf,maType){const raw=source==='BINANCE_FUTURES'?await p.getFuturesKlines(symbol,tf,550):await p.getFallbackFuturesKlines(symbol,tf,550),actual=sourceOf(raw,p);if(actual!==source)throw Error(`SOURCE_MISMATCH ${source} / ${actual}`);const r=E.analyze({candles:raw,asOf,maType,timeframe:tf});return{...r,source:actual,fresh:fresh(r,tf,asOf)};}
function execution(raw,tf,asOf){const c=E.normalize(raw,asOf),i=c.length-1;if(c.length<100)return{available:false};const close=c.map(x=>x.close),ma=Object.fromEntries([14,28,57,92].map(p=>[p,E.average(close,p,'EMA')])),last=c[i],baseline=c.slice(i-20,i).reduce((a,x)=>a+x.volume,0)/20,rvol=baseline>0?last.volume/baseline:null,level=Math.max(...c.slice(i-12,i).map(x=>x.high)),buy=Number(last.takerBuyQuote),quote=Number(last.quoteVolume),taker=last.takerBuyQuote!=null&&quote>buy&&buy>=0?buy/(quote-buy):null,hl=Math.min(...c.slice(-3).map(x=>x.low))>=Math.min(...c.slice(-6,-3).map(x=>x.low))*.995;
const e12=E.average(close,12,'EMA'),e26=E.average(close,26,'EMA'),macd=close.map((_,j)=>e12[j]==null||e26[j]==null?null:e12[j]-e26[j]),valid=macd.slice(25),signal=E.average(valid,9,'EMA'),hist=valid.map((v,j)=>signal[j]==null?null:v-signal[j]),macdImproving=hist.at(-1)>=hist.at(-2);
const aboveAll=Object.values(ma).every(x=>last.close>x[i]),above14=last.close>ma[14][i],reclaim=last.close>ma[14][i]&&c[i-1].close<=ma[14][i-1],breakout=last.close>level;return{available:true,fresh:fresh({lastClosedCloseTime:last.closeTime},tf,asOf),rvol,taker,hl,macdImproving,aboveAll,above14,breakout,reclaim,pass:tf==='1h'?above14&&hl&&macdImproving:tf==='15m'?above14&&ma[14][i]>ma[28][i]&&breakout&&rvol>=1.5&&taker>=1.15:aboveAll&&hl&&(breakout||reclaim)&&rvol>=1.2&&taker>=1.15};}
async function confirm(p,row,j){const asOf=Date.now(),frames={};for(const tf of ['1h','15m','5m']){const raw=j.source==='BINANCE_FUTURES'?await p.getFuturesKlines(row.symbol,tf,300):await p.getFallbackFuturesKlines(row.symbol,tf,300);if(sourceOf(raw,p)!==j.source)throw Error('execution source mismatch');frames[tf]=execution(raw,tf,asOf);}
const oi=await p.getOiChange(row.symbol),funding=await p.getFundingMap().catch(()=>new Map());let spot=null;try{const raw=await p.getSpotKlines(row.symbol,'15m',100);spot=execution(raw,'15m',asOf);}catch{}
const confirmed=j.source==='BINANCE_FUTURES'&&oi!=null&&spot?.fresh&&spot.above14&&frames['1h'].pass&&frames['15m'].pass&&frames['5m'].pass&&Object.values(frames).every(x=>x.fresh);
return{asOf,frames,oi60Pct:oi,fundingPct:funding.get(row.symbol)??null,spot,status:confirmed?'실행 조건 충족':'실행 대기',confirmed,note:oi==null?'OI 미조회 · 승격 없음':j.source!=='BINANCE_FUTURES'?'대체 거래소 차트 · Binance 실행 승격 없음':'확정봉·현물·수급 동시 확인'};}
async function run(j,p){try{for(const symbol of j.symbols){if(j.cancelRequested){j.status='CANCELLED';return;}j.currentSymbol=symbol;const frames={},errors=[];for(const tf of ['1d','4h']){try{frames[tf]=await fetchFrame(p,symbol,tf,j.source,j.asOf,j.maType);}catch(e){errors.push({tf,error:String(e.message||e)});}}
const values=Object.values(frames),candidate=values.some(x=>x.setup&&x.fresh&&x.status==='OK');if(candidate)j.rows.push({symbol,frames,matched:values.some(x=>x.matched&&x.fresh),execution:{status:'미검사',confirmed:false}});if(errors.length)j.errors.push({symbol,errors});if(values.length&&values.every(x=>x.status==='INSUFFICIENT_HISTORY'))j.insufficientHistory++;if(values.some(x=>!x.fresh))j.stale++;j.completed++;j.updatedAt=Date.now();}
j.status='CONFIRMING';const shortlist=j.rows.filter(x=>x.matched).slice().sort((a,b)=>Number(b.frames['1d']?.matched)-Number(a.frames['1d']?.matched)).slice(0,20);j.confirmTotal=shortlist.length;j.confirmCompleted=0;for(const row of shortlist){if(j.cancelRequested){j.status='CANCELLED';return;}j.currentSymbol=row.symbol;try{row.execution=await confirm(p,row,j);}catch(e){row.execution={status:'실행 조회 실패',confirmed:false,error:String(e.message||e)};}j.confirmCompleted++;j.updatedAt=Date.now();}j.status=j.errors.length||j.stale?'DONE_WITH_GAPS':'DONE';}catch(e){j.status='FAILED';j.error=String(e.message||e);}finally{j.finishedAt=Date.now();j.updatedAt=Date.now();if(active===j.id)active=null;}}
module.exports=async function(req,res,ctx={}){res.setHeader('Cache-Control','no-store');const p=ctx.provider||getProvider(),q=req.query||{},action=q.action||'status';try{if(action==='chart'){const symbol=String(q.symbol||'BTCUSDT').toUpperCase();if(!/^[A-Z0-9]{2,30}USDT$/.test(symbol)||!['1d','4h','1h','15m','5m'].includes(q.tf||'4h'))return res.status(400).json({ok:false,error:'invalid symbol or timeframe'});const tf=q.tf||'4h',raw=await p.getFuturesKlines(symbol,tf,550),asOf=Date.now();return res.status(200).json({ok:true,symbol,tf,source:sourceOf(raw,p),...E.series(raw,{asOf,maType:q.maType==='EMA'?'EMA':'SMA'}),analysis:E.analyze({candles:raw,asOf,maType:q.maType==='EMA'?'EMA':'SMA',timeframe:tf})});}if(action==='universe')return res.status(200).json({ok:true,...await universe(p)});if(action==='start'){if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});if(active)return res.status(200).json({ok:true,existing:true,...summary(jobs.get(active))});if(starting)return res.status(409).json({ok:false,error:'유니버스 조회 중 · 잠시 후 재시도'});starting=true;let u;try{u=await universe(p);}finally{starting=false;}const maType=req.body?.maType||'SMA';if(!['SMA','EMA'].includes(maType))return res.status(400).json({ok:false,error:'SMA or EMA required'});for(const [id,j] of jobs)if(j.finishedAt&&Date.now()-j.finishedAt>86400000)jobs.delete(id);if(jobs.size>=6){const finished=[...jobs.values()].filter(x=>x.finishedAt).sort((a,b)=>a.finishedAt-b.finishedAt);if(finished[0])jobs.delete(finished[0].id);}const j={id:randomUUID(),version:'DANTE_CLOUD_SCAN_v1',status:'RUNNING',source:u.source,symbols:u.symbols,total:u.symbols.length,asOf:u.asOf,maType,minQuoteVolume:0,completed:0,insufficientHistory:0,stale:0,rows:[],errors:[],updatedAt:Date.now(),closedOnly:true};jobs.set(j.id,j);active=j.id;void run(j,p);return res.status(202).json({ok:true,...summary(j)});}const j=jobs.get(q.id||active);if(!j)return res.status(404).json({ok:false,error:'스캔 기록 없음 · 서버 재시작 시 다시 시작'});if(action==='cancel'){if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});j.cancelRequested=true;}return res.status(200).json({ok:true,...summary(j)});}catch(e){return res.status(502).json({ok:false,error:String(e.message||e)});}};
module.exports._test={execution,fresh,fetchFrame,universe};
