const BASES=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];
async function getJson(path,params={}){let last;const qs=new URLSearchParams(params).toString();for(const base of BASES){try{const r=await fetch(base+path+(qs?'?'+qs:''),{headers:{'User-Agent':'PulseRadar-Pro/3.3'}});const t=await r.text();if(!r.ok)throw new Error(`Binance ${r.status}: ${t.slice(0,180)}`);return JSON.parse(t)}catch(e){last=e}}throw last||new Error('Binance request failed')}
const n=v=>Number(v)||0, clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
function ema(a,p){const k=2/(p+1),o=[];let x=a[0]||0;for(let i=0;i<a.length;i++){x=i? a[i]*k+x*(1-k):a[i];o.push(x)}return o}
function sma(a,p){let o=Array(a.length).fill(null),s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)o[i]=s/p}return o}
function rsi(a,p=14){const out=Array(a.length).fill(null);if(a.length<=p)return out;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;out[p]=l?100-100/(1+g/l):100;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;out[i]=l?100-100/(1+g/l):100}return out}
function atr(h,l,c,p=14){const tr=h.map((x,i)=>i?Math.max(x-l[i],Math.abs(x-c[i-1]),Math.abs(l[i]-c[i-1])):x-l[i]);return ema(tr,p)}
function sd(a){const m=a.reduce((s,x)=>s+x,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)}
function macd(a){const a12=ema(a,12),a26=ema(a,26),line=a.map((_,i)=>a12[i]-a26[i]),sig=ema(line,9),hist=line.map((x,i)=>x-sig[i]);return{line:line.at(-1),signal:sig.at(-1),hist:hist.at(-1)}}
function analyze(raw,tf){const h=raw.map(k=>n(k[2])),l=raw.map(k=>n(k[3])),c=raw.map(k=>n(k[4])),v=raw.map(k=>n(k[5]));const price=c.at(-1),e5=ema(c,5).at(-1),e20=ema(c,20).at(-1),e60=ema(c,60).at(-1),rr=rsi(c,14).at(-1),aa=atr(h,l,c,14).at(-1),atrPct=price?aa/price*100:0,vs=sma(v,20).at(-1)||1,volRatio=v.at(-1)/vs,m=macd(c);const w=c.slice(-20),mid=w.reduce((s,x)=>s+x,0)/Math.max(1,w.length),s=sd(w),upper=mid+2*s,bbWidth=mid?(upper-(mid-2*s))/mid:0;const prev=[];for(let i=40;i>=21;i--){const q=c.slice(-i,-i+20),qm=q.reduce((x,y)=>x+y,0)/20,qs=sd(q);if(qm)prev.push((4*qs)/qm)}const prevAvg=prev.length?prev.reduce((x,y)=>x+y,0)/prev.length:bbWidth;const buy=raw.slice(-5).reduce((x,k)=>x+n(k[10]),0),q=raw.slice(-5).reduce((x,k)=>x+n(k[7]),0),buyRatio=q?buy/q:.5;const maxE=Math.max(e5,e20,e60),minE=Math.min(e5,e20,e60),gap=maxE?(maxE-minE)/maxE*100:0;const lastOpen=n(raw.at(-1)?.[1]),lastHigh=n(raw.at(-1)?.[2]),lastLow=n(raw.at(-1)?.[3]),lastRangePct=lastOpen?(lastHigh-lastLow)/lastOpen*100:0;return{tf,price,ema5:e5,ema20:e20,ema60:e60,rsi14:rr,macdHist:m.hist,atrPct,volRatio,buyRatio,emaGapPct:gap,bbWidth,squeeze:bbWidth<prevAvg*.82,breakout:price>upper,trendAligned:price>e5&&e5>e20&&e20>e60,converging:gap<1.3,lastRangePct}}
function riskGate(frames){const hard=[],warn=[];for(const f of frames){if(f.rsi14>=82)hard.push(`${f.tf} RSI ${f.rsi14.toFixed(1)} 극과열`);else if(f.rsi14>=75)warn.push(`${f.tf} RSI 과열`);if(f.emaGapPct>=8)hard.push(`${f.tf} EMA 이격 ${f.emaGapPct.toFixed(1)}%`);else if(f.emaGapPct>=5)warn.push(`${f.tf} EMA 이격 확대`);if(f.atrPct>=9)hard.push(`${f.tf} ATR ${f.atrPct.toFixed(1)}% 급변동`);else if(f.atrPct>=6)warn.push(`${f.tf} ATR 변동성 높음`);if(f.volRatio>=6)hard.push(`${f.tf} 거래량 ${f.volRatio.toFixed(1)}× 과폭증`);else if(f.volRatio>=4)warn.push(`${f.tf} 거래량 급증`);if(f.lastRangePct>=10)hard.push(`${f.tf} 단일 캔들 변동폭 ${f.lastRangePct.toFixed(1)}%`);else if(f.lastRangePct>=6)warn.push(`${f.tf} 단일 캔들 변동폭 확대`)}return{hard,warn,excluded:hard.length>0}}
function preSurge(frames){const count=fn=>frames.filter(fn).length;let score=0;const reasons=[];if(count(f=>f.squeeze)>=2){score+=22;reasons.push('볼린저 압축이 여러 시간대에서 확인됨')}if(count(f=>f.converging)>=2){score+=20;reasons.push('EMA 5/20/60 수렴')}if(count(f=>f.volRatio>=1.1&&f.volRatio<=2.5)>=1){score+=18;reasons.push('거래량이 평균 대비 활성화 시작')}if(count(f=>f.rsi14>=47&&f.rsi14<=62)>=2){score+=15;reasons.push('RSI 중립→강세 구간')}if(count(f=>f.macdHist>0)>=2){score+=15;reasons.push('MACD 모멘텀이 양수 방향')}if(count(f=>f.buyRatio>=.52)>=2){score+=10;reasons.push('매수 체결 비중 우위')}let penalty=0;frames.forEach(f=>{if(f.rsi14>72||f.volRatio>4||f.atrPct>8)penalty+=12});if(penalty){score-=penalty;reasons.push(`과열/급변동 감점 -${penalty}`)}score=Math.round(clamp(score));const stage=score>=75?'압축 해제 임박 후보':score>=55?'준비 단계 후보':score>=35?'관찰 단계':'초기 조건 부족';return{score,stage,reasons}}
function surge(frames){const aligned=frames.filter(f=>f.trendAligned).length;const trend=Math.round(clamp(aligned/3*100));const volume=Math.round(clamp(frames.reduce((s,f)=>s+clamp((f.volRatio-1)*35,0,100),0)/3));const momentum=Math.round(clamp(frames.reduce((s,f)=>s+(f.rsi14>=55&&f.rsi14<=72?80:f.rsi14>72?55:f.rsi14>=50?60:25)+(f.macdHist>0?20:0),0)/3));const volatility=Math.round(clamp(frames.reduce((s,f)=>s+(f.squeeze?40:0)+(f.breakout?30:0)+(f.atrPct>=1&&f.atrPct<=6?30:0),0)/3));const mtf=Math.round(aligned/3*100);return{score:Math.round(clamp(trend*.2+volume*.2+momentum*.2+volatility*.15+mtf*.15)),axes:{trend,volume,momentum,volatility,multiTf:mtf},aligned}}
function confidence(pre,surge,risk,frames){if(risk.excluded)return{grade:'EXCLUDE',label:'위험 게이트',reason:risk.hard.join(' · ')};const agree=frames.filter(f=>f.trendAligned||f.squeeze||f.converging).length;let grade='C',label='혼합/초기';if((pre.score>=70||surge.score>=70)&&risk.warn.length===0&&agree>=2){grade='A';label='다중요인 강한 합의'}else if((pre.score>=55||surge.score>=60)&&risk.warn.length<=1){grade='B';label='양호, 일부 약점'}return{grade,label,reason:risk.warn.length?risk.warn.join(' · '):'하드 위험 게이트 없음'}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=15, stale-while-revalidate=30');try{const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase();const tfs=['5m','15m','1h'];const raws=await Promise.all(tfs.map(interval=>getJson('/api/v3/klines',{symbol,interval,limit:'220'})));const frames=raws.map((raw,i)=>analyze(raw,tfs[i]));const pre=preSurge(frames),sg=surge(frames),risk=riskGate(frames),conf=confidence(pre,sg,risk,frames);res.status(200).json({ok:true,symbol,timeframes:frames,preSurge:pre,surge:sg,riskGate:risk,confidence:conf})}catch(e){res.status(502).json({ok:false,error:e?.message||'Detail fetch failed'})}}
