const spot=require('../lib/spot-detail.js');
const futures=require('../lib/futures-data.js');
function capture(){let code=200,body=null;return{res:{setHeader(){},status(c){code=c;return this},json(v){body=v;return this}},get:()=>({code,body})}}
async function runSpot(req){const c=capture();try{await spot(req,c.res)}catch(e){return{code:500,body:{ok:false,error:e?.message||String(e)}}}return c.get()}
function stripHtml(s=''){return String(s).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function decode(s=''){return String(s).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<!\[CDATA\[|\]\]>/g,'').trim()}
function category(title=''){const t=title.toLowerCase();if(/burn|burning|소각|deflation/.test(t))return'소각/공급';if(/unlock|vesting|token release|언락|베스팅/.test(t))return'언락/공급';if(/mainnet|upgrade|hard fork|migration|migrate|bridge|shutdown|sunset|전환|마이그레이션|브리지|종료/.test(t))return'네트워크/전환';if(/list|listing|delist|perpetual|futures|spot market|상장|선물/.test(t))return'거래소/파생';if(/airdrop|snapshot|claim|에어드롭/.test(t))return'에어드롭';if(/governance|proposal|vote|dao|거버넌스|투표/.test(t))return'거버넌스';if(/partnership|partner|integration|launch|adoption|제휴|통합|출시/.test(t))return'사업/파트너십';return'관련 뉴스'}
function eventLike(title=''){return /will|plans?|scheduled|deadline|upcoming|launch|starts?|ends?|shutdown|migration|bridge|vote|proposal|airdrop|unlock|burn|list|\b20\d{2}\b|예정|일정|마감|종료|소각|언락|상장|출시|투표/i.test(title)}
function parseRss(xml=''){const out=[];for(const block of String(xml).match(/<item>[\s\S]*?<\/item>/g)||[]){const pick=tag=>{const m=block.match(new RegExp(`<${tag}(?: [^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decode(stripHtml(m[1])):''};const sm=block.match(/<source(?: [^>]*)?>([\s\S]*?)<\/source>/i),title=pick('title');if(title)out.push({title,link:pick('link'),pubDate:pick('pubDate'),source:sm?decode(stripHtml(sm[1])):'',category:category(title),isEvent:eventLike(title)})}return out}
async function getJson(url){const r=await fetch(url,{headers:{'User-Agent':'PulseRadar/1.0','Accept':'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function getText(url){const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 PulseRadar/1.0','Accept':'application/rss+xml,text/xml,*/*'}});if(!r.ok)throw Error('HTTP '+r.status);return r.text()}
function dedupe(a){const seen=new Set();return a.filter(x=>{const k=x.title.toLowerCase().replace(/[^a-z0-9가-힣]/g,'');if(seen.has(k))return false;seen.add(k);return true})}
async function intel(symbol){const base=String(symbol||'BTCUSDT').toUpperCase().replace(/USDT$/,''),warnings=[];let coin=null,news=[];try{const s=await getJson('https://api.coingecko.com/api/v3/search?query='+encodeURIComponent(base));const exact=(s.coins||[]).find(x=>String(x.symbol).toUpperCase()===base)||(s.coins||[])[0];if(exact)coin=await getJson(`https://api.coingecko.com/api/v3/coins/${encodeURIComponent(exact.id)}?localization=false&tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false`)}catch(e){warnings.push('프로젝트 메타데이터를 불러오지 못했습니다.')}
const name=coin?.name||base;try{const xml=await getText('https://news.google.com/rss/search?q='+encodeURIComponent(`${name} ${base} crypto token`)+'&hl=en-US&gl=US&ceid=US:en');news=dedupe(parseRss(xml)).slice(0,16)}catch(e){warnings.push('최신 뉴스 피드를 불러오지 못했습니다.')}
const events=news.filter(x=>x.isEvent||x.category!=='관련 뉴스').slice(0,8),burns=news.filter(x=>x.category==='소각/공급'||x.category==='언락/공급').slice(0,5),exchange=news.filter(x=>x.category==='거래소/파생').slice(0,5),links=coin?.links||{},official=[];(links.homepage||[]).filter(Boolean).slice(0,1).forEach(url=>official.push({label:'공식 홈페이지',url}));(links.announcement_url||[]).filter(Boolean).slice(0,2).forEach((url,i)=>official.push({label:i?'공식 공지 2':'공식 공지',url}));if(links.twitter_screen_name)official.push({label:'공식 X',url:'https://x.com/'+links.twitter_screen_name});const md=coin?.market_data||{};return{ok:true,intel:true,symbol:base+'USDT',base,name,updatedAt:new Date().toISOString(),project:{name,symbol:base,description:stripHtml(coin?.description?.en||'').slice(0,700),marketCapUsd:md.market_cap?.usd??null,circulating:md.circulating_supply??null,totalSupply:md.total_supply??null,maxSupply:md.max_supply??null},summary:{headline:events[0]?.title||news[0]?.title||'최근 주요 이벤트 없음',eventCount:events.length,burnCount:burns.length,exchangeCount:exchange.length,newsCount:news.length},events,burns,exchange,news:news.slice(0,10),official,warnings,note:'공개 뉴스 RSS와 프로젝트 메타데이터를 자동 수집·키워드 분류한 결과입니다. 일정·소각·언락·상장 여부는 원문과 공식 공지를 함께 확인하세요.'}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=300');try{if(String(req.query.intel||'')==='1')return res.status(200).json(await intel(req.query.symbol));const s=await runSpot(req);if(s.code<400&&s.body?.ok)return res.status(200).json({...s.body,market:'spot'});const f=await futures.detail(String(req.query.symbol||'BTCUSDT').toUpperCase());return res.status(200).json(f)}catch(e){return res.status(502).json({ok:false,error:e?.message||'Detail fetch failed'})}}
