const spot=require('../lib/spot-detail.js');
const futures=require('../lib/futures-data.js');
function capture(){let code=200,body=null;return{res:{setHeader(){},status(c){code=c;return this},json(v){body=v;return this}},get:()=>({code,body})}}
async function runSpot(req){const c=capture();try{await spot(req,c.res)}catch(e){return{code:500,body:{ok:false,error:e?.message||String(e)}}}return c.get()}
function stripHtml(s=''){return String(s).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function decode(s=''){return String(s).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/<!\[CDATA\[|\]\]>/g,'').trim()}
function hasKo(s=''){return /[가-힣]/.test(String(s))}
function category(title=''){const t=title.toLowerCase();if(/burn|burning|소각|deflation/.test(t))return'소각/공급';if(/unlock|vesting|token release|언락|베스팅/.test(t))return'언락/공급';if(/mainnet|upgrade|hard fork|migration|migrate|bridge|shutdown|sunset|전환|마이그레이션|브리지|종료/.test(t))return'네트워크/전환';if(/list|listing|delist|perpetual|futures|spot market|상장|선물/.test(t))return'거래소/파생';if(/airdrop|snapshot|claim|에어드롭/.test(t))return'에어드롭';if(/governance|proposal|vote|dao|거버넌스|투표/.test(t))return'거버넌스';if(/partnership|partner|integration|launch|adoption|제휴|통합|출시/.test(t))return'사업/파트너십';return'관련 뉴스'}
function eventLike(title=''){return /will|plans?|scheduled|deadline|upcoming|launch|starts?|ends?|shutdown|migration|bridge|vote|proposal|airdrop|unlock|burn|list|\b20\d{2}\b|예정|일정|마감|종료|소각|언락|상장|출시|투표/i.test(title)}
function parseRss(xml=''){const out=[];for(const block of String(xml).match(/<item>[\s\S]*?<\/item>/g)||[]){const pick=tag=>{const m=block.match(new RegExp(`<${tag}(?: [^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decode(stripHtml(m[1])):''};const sm=block.match(/<source(?: [^>]*)?>([\s\S]*?)<\/source>/i),title=pick('title');if(title)out.push({title,link:pick('link'),pubDate:pick('pubDate'),source:sm?decode(stripHtml(sm[1])):'',category:category(title),isEvent:eventLike(title)})}return out}
async function getJson(url){const r=await fetch(url,{headers:{'User-Agent':'PulseRadar/1.0','Accept':'application/json'}});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function getText(url){const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 PulseRadar/1.0','Accept':'application/rss+xml,text/xml,*/*'}});if(!r.ok)throw Error('HTTP '+r.status);return r.text()}
function dedupe(a){const seen=new Set();return a.filter(x=>{const k=x.title.toLowerCase().replace(/[^a-z0-9가-힣]/g,'');if(seen.has(k))return false;seen.add(k);return true})}
async function translateKo(text){if(!text||hasKo(text))return text;try{const url='https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=ko&dt=t&q='+encodeURIComponent(text);const j=await getJson(url);const out=(j?.[0]||[]).map(x=>x?.[0]||'').join('').trim();return out||text}catch{return text}}
function parseAmount(title,base){const t=String(title);const re=new RegExp('([0-9]+(?:\\.[0-9]+)?)\\s*(K|M|B|million|billion|thousand)?\\s*'+base+'\\b','i');const m=t.match(re);if(!m)return null;let n=Number(m[1]),u=(m[2]||'').toLowerCase();if(u==='k'||u==='thousand')n*=1e3;if(u==='m'||u==='million')n*=1e6;if(u==='b'||u==='billion')n*=1e9;return Number.isFinite(n)?n:null}
function extractEventDate(title,pubDate){const t=String(title);let m=t.match(/\b(20\d{2})[-\/.](\d{1,2})[-\/.](\d{1,2})\b/);if(m){const d=new Date(`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}T00:00:00Z`);if(!isNaN(d))return d.toISOString()}m=t.match(/\b(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)\s+(\d{1,2})(?:st|nd|rd|th)?,?\s+(20\d{2})\b/i);if(m){const d=new Date(`${m[1]} ${m[2]}, ${m[3]} 00:00:00 UTC`);if(!isNaN(d))return d.toISOString()}m=t.match(/\b(20\d{2})년\s*(\d{1,2})월\s*(\d{1,2})일/);if(m){const d=new Date(`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}T00:00:00Z`);if(!isNaN(d))return d.toISOString()}return null}
function importance(x){let s=20;if(x.category==='소각/공급'||x.category==='언락/공급')s+=35;if(x.category==='네트워크/전환')s+=30;if(x.category==='거래소/파생')s+=20;if(x.category==='거버넌스')s+=15;if(x.isEvent)s+=10;if(/official|foundation|labs|dao/i.test(x.source||''))s+=10;return Math.min(100,s)}
function catalystSummary(news,change24){const cats=new Set(news.slice(0,12).map(x=>x.category));const factors=[];if(cats.has('소각/공급'))factors.push('소각·공급 감소 기대');if(cats.has('언락/공급'))factors.push('언락·베스팅 공급 변화');if(cats.has('네트워크/전환'))factors.push('메인넷·마이그레이션·네트워크 전환');if(cats.has('거래소/파생'))factors.push('거래소 상장·파생상품 이슈');if(cats.has('거버넌스'))factors.push('DAO·거버넌스 결정');if(cats.has('사업/파트너십'))factors.push('출시·제휴·사업 확장');let direction='가격 변동';if(Number.isFinite(change24))direction=change24>=8?'급등':change24<=-8?'급락':change24>=2?'상승':change24<=-2?'하락':'보합권';const intro=Number.isFinite(change24)?`최근 24시간 가격은 ${change24>=0?'+':''}${change24.toFixed(2)}%로 ${direction} 흐름입니다.`:'최근 가격 변동률을 확인하지 못했습니다.';const reason=factors.length?` 공개 뉴스에서 ${factors.slice(0,4).join(', ')}가 동시에 관측됩니다.`:' 최근 뉴스만으로 뚜렷한 단일 촉매는 확인되지 않습니다.';return{direction,summary:intro+reason+' 이는 원인 확정이 아니라 공개 정보 기반의 가능 요인 정리입니다.',factors}}
async function intel(symbol){const base=String(symbol||'BTCUSDT').toUpperCase().replace(/USDT$/,''),warnings=[];let coin=null,news=[];try{const s=await getJson('https://api.coingecko.com/api/v3/search?query='+encodeURIComponent(base));const exact=(s.coins||[]).find(x=>String(x.symbol).toUpperCase()===base)||(s.coins||[])[0];if(exact)coin=await getJson(`https://api.coingecko.com/api/v3/coins/${encodeURIComponent(exact.id)}?localization=true&tickers=false&market_data=true&community_data=false&developer_data=false&sparkline=false`)}catch(e){warnings.push('프로젝트 메타데이터를 불러오지 못했습니다.')}
const name=coin?.name||base;try{const [en,ko]=await Promise.allSettled([getText('https://news.google.com/rss/search?q='+encodeURIComponent(`${name} ${base} crypto token`)+'&hl=en-US&gl=US&ceid=US:en'),getText('https://news.google.com/rss/search?q='+encodeURIComponent(`${name} ${base} 코인`)+'&hl=ko&gl=KR&ceid=KR:ko')]);let all=[];if(en.status==='fulfilled')all.push(...parseRss(en.value));if(ko.status==='fulfilled')all.push(...parseRss(ko.value));news=dedupe(all).slice(0,20)}catch(e){warnings.push('최신 뉴스 피드를 불러오지 못했습니다.')}
const toTranslate=news.filter(x=>!hasKo(x.title)).slice(0,12);await Promise.all(toTranslate.map(async x=>{x.titleKo=await translateKo(x.title)}));news.forEach(x=>{x.titleKo=x.titleKo||x.title;x.eventDate=extractEventDate(x.title,x.pubDate);x.importance=importance(x);x.amount=parseAmount(x.title,base)});
const md=coin?.market_data||{},supply=md.total_supply??md.circulating_supply??null;news.forEach(x=>{x.supplyRatio=x.amount&&supply?x.amount/supply*100:null});
const events=news.filter(x=>x.isEvent||x.category!=='관련 뉴스').sort((a,b)=>{const ad=a.eventDate?new Date(a.eventDate).getTime():0,bd=b.eventDate?new Date(b.eventDate).getTime():0;return(bd-ad)||(b.importance-a.importance)}).slice(0,10),burns=news.filter(x=>x.category==='소각/공급'||x.category==='언락/공급').sort((a,b)=>b.importance-a.importance).slice(0,7),exchange=news.filter(x=>x.category==='거래소/파생').sort((a,b)=>b.importance-a.importance).slice(0,7),links=coin?.links||{},official=[];(links.homepage||[]).filter(Boolean).slice(0,1).forEach(url=>official.push({label:'공식 홈페이지',url}));(links.announcement_url||[]).filter(Boolean).slice(0,2).forEach((url,i)=>official.push({label:i?'공식 공지 2':'공식 공지',url}));if(links.twitter_screen_name)official.push({label:'공식 X',url:'https://x.com/'+links.twitter_screen_name});const change24=Number(md.price_change_percentage_24h),catalyst=catalystSummary(news,Number.isFinite(change24)?change24:null),descKo=stripHtml(coin?.description?.ko||''),descEn=stripHtml(coin?.description?.en||'');let description=descKo||descEn.slice(0,700);if(!descKo&&descEn)description=await translateKo(descEn.slice(0,700));const timeline=events.map(x=>({title:x.title,titleKo:x.titleKo,category:x.category,source:x.source,link:x.link,pubDate:x.pubDate,eventDate:x.eventDate,importance:x.importance,amount:x.amount,supplyRatio:x.supplyRatio}));return{ok:true,intel:true,version:'coin-intel-v2',symbol:base+'USDT',base,name,updatedAt:new Date().toISOString(),project:{name,symbol:base,description,marketCapUsd:md.market_cap?.usd??null,circulating:md.circulating_supply??null,totalSupply:md.total_supply??null,maxSupply:md.max_supply??null,priceUsd:md.current_price?.usd??null,change24:Number.isFinite(change24)?change24:null},summary:{headline:events[0]?.titleKo||news[0]?.titleKo||'최근 주요 이벤트 없음',eventCount:events.length,burnCount:burns.length,exchangeCount:exchange.length,newsCount:news.length},catalyst,timeline,events,burns,exchange,news:news.slice(0,14),official,warnings,note:'공개 뉴스 RSS와 프로젝트 메타데이터를 자동 수집·번역·키워드 분류한 결과입니다. 급등/급락 원인 요약은 상관관계 기반의 가능 요인이며 인과관계를 확정하지 않습니다. 일정·소각·언락·상장 여부는 반드시 공식 원문에서 재확인하세요.'}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=300');try{if(String(req.query.intel||'')==='1')return res.status(200).json(await intel(req.query.symbol));const s=await runSpot(req);if(s.code<400&&s.body?.ok)return res.status(200).json({...s.body,market:'spot'});const f=await futures.detail(String(req.query.symbol||'BTCUSDT').toUpperCase());return res.status(200).json(f)}catch(e){return res.status(502).json({ok:false,error:e?.message||'Detail fetch failed'})}}
