const spot=require('../lib/spot-market.js');
const futures=require('../lib/futures-data.js');
const REQUIRED_FUTURES=['XPINUSDT'];
function capture(){let code=200,body=null;return{res:{setHeader(){},status(c){code=c;return this},json(v){body=v;return this}},get:()=>({code,body})}}
async function runSpot(req){const c=capture();try{await spot(req,c.res)}catch(e){return{code:500,body:{ok:false,error:e?.message||String(e)}}}return c.get()}
async function fetchJson(bases,path,timeout=5000){let last;for(const base of bases){const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(base+path,{signal:ctl.signal,headers:{accept:'application/json','user-agent':'PulseRadar-Pro/Catalog'}}),t=await r.text();clearTimeout(to);if(!r.ok||!t.trim())throw Error('HTTP '+r.status);return JSON.parse(t)}catch(e){clearTimeout(to);last=e}}throw last||Error('catalog fetch failed')}
async function catalog(){const SPOT=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];const FUT=['https://fapi.binance.com','https://fapi1.binance.com','https://fapi2.binance.com'];const [sR,fR]=await Promise.allSettled([fetchJson(SPOT,'/api/v3/exchangeInfo'),fetchJson(FUT,'/fapi/v1/exchangeInfo')]);const map=new Map();if(sR.status==='fulfilled')for(const x of sR.value?.symbols||[]){if(x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.isSpotTradingAllowed!==false)map.set(x.symbol,{symbol:x.symbol,spot:true,futures:false})}if(fR.status==='fulfilled')for(const x of fR.value?.symbols||[]){if(x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.contractType==='PERPETUAL'){const q=map.get(x.symbol)||{symbol:x.symbol,spot:false,futures:false};q.futures=true;map.set(x.symbol,q)}}for(const symbol of REQUIRED_FUTURES){const q=map.get(symbol)||{symbol,spot:false,futures:false};q.futures=true;map.set(symbol,q)}const symbols=[...map.values()].sort((a,b)=>a.symbol.localeCompare(b.symbol));return{ok:true,version:'catalog-v3-futures-fallback',total:symbols.length,spotCount:symbols.filter(x=>x.spot).length,futuresCount:symbols.filter(x=>x.futures).length,futuresOnlyCount:symbols.filter(x=>x.futures&&!x.spot).length,symbols,requiredFutures:REQUIRED_FUTURES,updatedAt:new Date().toISOString()}}
function fallbackFutureRow(symbol){return{symbol,market:'futures',contractType:'PERPETUAL',change24:0,quoteVol24:0,change1h:0,change4h:0,velocity:0,pass:false,preScore:0,surgeScore:0,preRank:null,preTopPct:null,dataStatus:'symbol-only',dataNote:'실시간 선물 시세 피드 일시 미사용'}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=20, stale-while-revalidate=40');try{if(String(req.query.catalog||'')==='1')return res.status(200).json(await catalog());const min=Number(req.query.minVolume)||500000;const [s,f]=await Promise.all([runSpot(req),futures.market(min).catch(e=>({ok:false,error:e.message}))]);const sr=s.body?.ok?(s.body.results||[]).map(x=>({...x,market:'spot'})):[];const spotSymbols=new Set(sr.map(x=>x.symbol));let fr=f?.ok?(f.results||[]).filter(x=>!spotSymbols.has(x.symbol)):[];let futuresFallback=false;if(!f?.ok||!fr.length){futuresFallback=true;let c;try{c=await catalog()}catch{}const syms=(c?.symbols||[]).filter(x=>x.futures&&!x.spot).map(x=>x.symbol);for(const symbol of REQUIRED_FUTURES)if(!syms.includes(symbol)&&!spotSymbols.has(symbol))syms.push(symbol);const existing=new Set(fr.map(x=>x.symbol));for(const symbol of syms)if(!existing.has(symbol)&&!spotSymbols.has(symbol))fr.push(fallbackFutureRow(symbol))}else{const existing=new Set(fr.map(x=>x.symbol));for(const symbol of REQUIRED_FUTURES)if(!existing.has(symbol)&&!spotSymbols.has(symbol))fr.push(fallbackFutureRow(symbol))}const rows=[...sr,...fr];rows.sort((a,b)=>Math.max(Number(b.surgeScore)||0,Number(b.preScore)||0)-Math.max(Number(a.surgeScore)||0,Number(a.preScore)||0)||Number(b.quoteVol24||0)-Number(a.quoteVol24||0)||String(a.symbol).localeCompare(String(b.symbol)));return res.status(200).json({ok:true,version:'spot+futures-auto-v2-fallback',market:'spot+futures',updatedAt:new Date().toISOString(),total:rows.length,eligible:rows.filter(x=>x.pass).length,results:rows,spotCount:sr.length,futuresOnlyCount:fr.length,futuresFeedOk:!!f?.ok,futuresFallback,futuresError:f?.ok?null:(f?.error||'futures feed unavailable'),note:'현물 우선 + Binance USD-M 무기한 선물. 선물 시세 피드 실패 시에도 선물 종목 목록은 유지'});}catch(e){return res.status(502).json({ok:false,error:e?.message||'Data fetch failed'})}}
