const dex=require('../lib/market-flow/dex');
const cex=require('../lib/market-flow/cex');
const aggregate=require('../lib/market-flow/aggregate');
const anomaly=require('../lib/market-flow/coin-anomaly');
const themes=require('../ui/radar-themes.js');
let cache={ts:0,data:null};
const SEARCH_TERMS=['USDT','USDC','SOL','ETH','BNB','BTC','new','launch','pump','meme','ai','agent','rwa','defi','gaming','depin','privacy'];
const dexLiquidityCache=new Map(),assetVolumeHistory=new Map();
const chunk=(arr,size=80)=>{const out=[];for(let i=0;i<(arr||[]).length;i+=size)out.push(arr.slice(i,i+size));return out};
const finite=v=>v==null||v===''?null:(Number.isFinite(Number(v))?Number(v):null);

async function getJson(url,ms=6500,headers={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{accept:'application/json','user-agent':'PulseRadar-Pro-v3',...headers}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function dexFromPair(p){const t=p.txns?.m5||{},r={chain:p.chainId,venue:p.dexId,pairAddress:p.pairAddress,tokenAddress:p.baseToken?.address,symbol:`${p.baseToken?.symbol||'?'} / ${p.quoteToken?.symbol||'?'}`,baseAsset:p.baseToken?.symbol,quoteAsset:p.quoteToken?.symbol,liquidityUsd:p.liquidity?.usd,volume5mUsd:p.volume?.m5,volume1hUsd:p.volume?.h1,volume24hUsd:p.volume?.h24,buys5m:t.buys,sells5m:t.sells,sourceConfidence:80};return dex.normalizeDexMarket(r,'dexscreener')}
function dexFromGt(p){const a=p.attributes||{},parts=String(a.name||'? / ?').split('/').map(x=>x.trim()),t=a.transactions?.m5||{};return dex.normalizeDexMarket({chain:p.relationships?.network?.data?.id||String(p.id||'').split('_')[0],venue:p.relationships?.dex?.data?.id||'DEX',pairAddress:a.address||String(p.id||'').split('_').slice(1).join('_'),symbol:a.name,baseAsset:parts[0],quoteAsset:parts[1],liquidityUsd:a.reserve_in_usd,volume5mUsd:a.volume_usd?.m5,volume1hUsd:a.volume_usd?.h1,volume24hUsd:a.volume_usd?.h24,buys5m:t.buys,sells5m:t.sells,sourceConfidence:84},'geckoterminal')}
function addLiquidityImpulse(r,now=Date.now()){if(!r)return r;const key=`${String(r.chain||'').toLowerCase()}:${r.pairAddress||r.symbol||''}`,liq=finite(r.liquidityUsd),prev=dexLiquidityCache.get(key);let impulse=null;if(liq!=null&&prev&&prev.liq>0&&now-prev.ts>=10000&&now-prev.ts<=10*60*1000)impulse=(liq-prev.liq)/prev.liq;if(liq!=null)dexLiquidityCache.set(key,{liq,ts:now});if(dexLiquidityCache.size>2500)for(const [k,v] of dexLiquidityCache)if(now-v.ts>2*60*60*1000)dexLiquidityCache.delete(k);return{...r,liquidityImpulse:impulse}}
async function collectDex(){const health={dexscreener:'down',geckoterminal:'down'},rows=[];const searches=await Promise.allSettled(SEARCH_TERMS.map(q=>getJson('https://api.dexscreener.com/latest/dex/search?q='+encodeURIComponent(q),5000)));for(const x of searches)if(x.status==='fulfilled'){health.dexscreener='live';for(const p of x.value?.pairs||[])rows.push(dexFromPair(p))}
 const gtUrls=[];for(const page of [1,2]){gtUrls.push(`https://api.geckoterminal.com/api/v2/networks/trending_pools?include=base_token%2Cquote_token&page=${page}`);gtUrls.push(`https://api.geckoterminal.com/api/v2/networks/new_pools?include=base_token%2Cquote_token&page=${page}`)}const gt=await Promise.allSettled(gtUrls.map(u=>getJson(u,6000,{'accept':'application/json;version=20230203'})));for(const x of gt)if(x.status==='fulfilled'){health.geckoterminal='live';for(const p of x.value?.data||[])rows.push(dexFromGt(p))}
 const m=new Map();for(const r of rows){if(!r)continue;const k=`${r.chain}:${r.pairAddress||r.symbol}`;const old=m.get(k);if(!old||Number(r.sourceConfidence||0)>Number(old.sourceConfidence||0)||(Number(r.sourceConfidence||0)===Number(old.sourceConfidence||0)&&Number(r.liquidityUsd||0)>Number(old.liquidityUsd||0)))m.set(k,r)}const now=Date.now();return{rows:[...m.values()].map(r=>addLiquidityImpulse(r,now)).sort((a,b)=>Number(b.volume5mUsd||b.volume1hUsd||0)-Number(a.volume5mUsd||a.volume1hUsd||0)).slice(0,900),health}}
function normMany(list,venue,marketType='spot',fx={}){return(list||[]).map(x=>cex.normalizeCexTicker(x,venue,marketType,fx)).filter(Boolean)}
async function usdKrw(){try{const d=await getJson('https://api.upbit.com/v1/ticker?markets=KRW-USDT',4500);const p=Number(d?.[0]?.trade_price);return Number.isFinite(p)&&p>500?p:null}catch{return null}}
async function collectCex(){const health={binance:'down',upbit:'down',bithumb:'down',okx:'down',bybit:'down',coinbase:'down'},rows=[],fx={usdKrw:await usdKrw()};
 const jobs=[];
 jobs.push((async()=>{try{const [spot,fut]=await Promise.allSettled([getJson('https://api.binance.com/api/v3/ticker/24hr'),getJson('https://fapi.binance.com/fapi/v1/ticker/24hr')]);if(spot.status==='fulfilled'){health.binance='live';rows.push(...normMany(spot.value.filter(x=>/(USDT|USDC|FDUSD)$/.test(x.symbol)),'Binance','spot',fx))}if(fut.status==='fulfilled'){health.binance='live';rows.push(...normMany(fut.value.filter(x=>/USDT$/.test(x.symbol)),'Binance','futures',fx))}}catch{}})());
 jobs.push((async()=>{try{const mk=await getJson('https://api.upbit.com/v1/market/all?is_details=false');const ids=(mk||[]).filter(x=>String(x.market).startsWith('KRW-')).map(x=>x.market),groups=chunk(ids,80),res=await Promise.allSettled(groups.map(g=>getJson('https://api.upbit.com/v1/ticker?markets='+encodeURIComponent(g.join(',')),6000)));let ok=0;for(const x of res)if(x.status==='fulfilled'){ok++;rows.push(...normMany(x.value,'Upbit','spot',fx))}if(ok)health.upbit='live'}catch{}})());
 jobs.push((async()=>{try{const d=await getJson('https://api.bithumb.com/public/ticker/ALL_KRW');if(d?.status==='0000'){health.bithumb='live';for(const [sym,v] of Object.entries(d.data||{}))if(sym!=='date')rows.push(cex.normalizeCexTicker({market:`KRW-${sym}`,trade_price:v.closing_price,acc_trade_price_24h:v.acc_trade_value_24H,change24h:v.fluctate_rate_24H},'Bithumb','spot',fx))}}catch{}})());
 jobs.push((async()=>{try{const d=await getJson('https://www.okx.com/api/v5/market/tickers?instType=SPOT');health.okx='live';rows.push(...normMany((d.data||[]).filter(x=>/-USDT$|-USDC$/.test(x.instId)).map(x=>({...x,last:x.last,quoteVolume:x.volCcy24h,change24h:x.open24h&&x.last?(Number(x.last)/Number(x.open24h)-1)*100:null})),'OKX','spot',fx))}catch{}})());
 jobs.push((async()=>{try{const d=await getJson('https://api.bybit.com/v5/market/tickers?category=spot');health.bybit='live';rows.push(...normMany((d.result?.list||[]).filter(x=>/USDT$/.test(x.symbol)).map(x=>({...x,lastPrice:x.lastPrice,quoteVolume:x.turnover24h,change24h:Number(x.price24hPcnt)*100})),'Bybit','spot',fx))}catch{}})());
 jobs.push((async()=>{const syms=['BTC-USD','ETH-USD','SOL-USD','XRP-USD','DOGE-USD','ADA-USD','AVAX-USD','LINK-USD','LTC-USD','BCH-USD','SUI-USD','UNI-USD'];let ok=0;const res=await Promise.allSettled(syms.map(async s=>{const d=await getJson(`https://api.exchange.coinbase.com/products/${s}/stats`,4200);return cex.normalizeCexTicker({product_id:s,last:d.last,quote_volume:d.volume&&d.last?Number(d.volume)*Number(d.last):null,change24h:d.open&&d.last?(Number(d.last)/Number(d.open)-1)*100:null},'Coinbase','spot',fx)}));for(const x of res)if(x.status==='fulfilled'&&x.value){rows.push(x.value);ok++}if(ok)health.coinbase='live'})());
 await Promise.all(jobs);return{rows:rows.filter(Boolean).slice(0,4000),health,fx}}
function themeForMarket(m){const x=themes.classifyMarket({baseAsset:m.baseAsset||'',symbol:m.symbol||'',chain:m.chain||null,tokenAddress:m.tokenAddress||null});return x.primaryTheme||x.theme||'Other / Unclassified'}
function themeForAsset(asset){const x=themes.classifyMarket({baseAsset:asset||'',symbol:asset||''});return x.primaryTheme||x.theme||'Other / Unclassified'}
function recordServerHistory(dexRows=[],now=Date.now()){const totals=new Map();for(const r of dexRows){const a=String(r.baseAsset||'').toUpperCase();if(!a)continue;const v=finite(r.volume5mUsd);if(v!=null)totals.set(a,(totals.get(a)||0)+v)}for(const [asset,value] of totals){const arr=assetVolumeHistory.get(asset)||[],last=arr.at(-1);if(last&&now-last.ts<12000)last.value=value;else arr.push({ts:now,value});while(arr.length&&now-arr[0].ts>40*60*1000)arr.shift();if(arr.length>160)arr.splice(0,arr.length-160);assetVolumeHistory.set(asset,arr)}if(assetVolumeHistory.size>1000)for(const [a,arr] of assetVolumeHistory)if(!arr.length||now-arr.at(-1).ts>60*60*1000)assetVolumeHistory.delete(a)}
function serverHistoryByAsset(now=Date.now()){const out={};for(const [asset,arr] of assetVolumeHistory){const prior=arr.filter(x=>now-x.ts>=60000&&now-x.ts<=35*60*1000).map(x=>x.value);if(prior.length)out[asset]={volume1m:[],volume5m:prior,volume15m:[],current15m:null}}return out}
function buildFrom({providerHealth={},dexFlows=[],cexFlows=[],onchainThemeFlows=[],liveRows=[],historyByAsset={},onchainByAsset={}}){const a=aggregate.aggregateMarketFlow({dexFlows,cexFlows,onchainThemeFlows,themeForMarket});const coinFlows=anomaly.buildCoinFlows({dexFlows,cexFlows,liveRows,historyByAsset,onchainByAsset,themeForAsset});const live=Object.values(providerHealth).filter(x=>x==='live').length,total=Math.max(1,Object.keys(providerHealth).length),confidence=Math.round(Math.min(100,(live/total)*75+(dexFlows.length?10:0)+(cexFlows.length?15:0)));return{updatedAt:new Date().toISOString(),stale:false,providerHealth,dexFlows,cexFlows,tokenFlows:a.tokenFlows,themeFlows:a.themeFlows,coinFlows,coinFlowCoverage:{coins:coinFlows.length,altcoins:coinFlows.filter(x=>x.altcoin).length,highConfidence:coinFlows.filter(x=>x.confidence>=70).length,preSurge:coinFlows.filter(x=>x.signal==='PRE-SURGE').length,surge:coinFlows.filter(x=>x.signal==='SURGE').length,risk:coinFlows.filter(x=>x.signal==='RISK').length},coverage:{dexMarkets:dexFlows.length,cexMarkets:cexFlows.length,themes:a.themeFlows.length,venues:new Set(cexFlows.map(x=>x.venue)).size},confidence}}
async function build(){if(cache.data&&Date.now()-cache.ts<20000)return cache.data;const [d,c]=await Promise.all([collectDex(),collectCex()]);const now=Date.now();recordServerHistory(d.rows,now);const data=buildFrom({providerHealth:{...d.health,...c.health},dexFlows:d.rows,cexFlows:c.rows,onchainThemeFlows:[],historyByAsset:serverHistoryByAsset(now)});cache={ts:Date.now(),data};return data}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=20, stale-while-revalidate=90');try{return res.status(200).json(await build())}catch(e){if(cache.data)return res.status(200).json({...cache.data,stale:true,error:String(e?.message||e)});return res.status(200).json({updatedAt:new Date().toISOString(),stale:true,providerHealth:{},dexFlows:[],cexFlows:[],tokenFlows:[],themeFlows:[],coinFlows:[],coinFlowCoverage:{coins:0,altcoins:0,highConfidence:0,preSurge:0,surge:0,risk:0},coverage:{dexMarkets:0,cexMarkets:0,themes:0,venues:0},confidence:0,error:'market flow degraded'})}}
module.exports._buildFrom=buildFrom;module.exports._collectDex=collectDex;module.exports._collectCex=collectCex;module.exports._searchTerms=SEARCH_TERMS;module.exports._chunk=chunk;module.exports._recordServerHistory=recordServerHistory;module.exports._serverHistoryByAsset=serverHistoryByAsset;
