const dex=require('../lib/market-flow/dex');
const cex=require('../lib/market-flow/cex');
const aggregate=require('../lib/market-flow/aggregate');
const themes=require('../ui/radar-themes.js');
let cache={ts:0,data:null};

async function getJson(url,ms=6500,headers={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{accept:'application/json','user-agent':'PulseRadar-Pro-v3',...headers}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function dexFromPair(p){const t=p.txns?.m5||{},r={chain:p.chainId,venue:p.dexId,pairAddress:p.pairAddress,tokenAddress:p.baseToken?.address,symbol:`${p.baseToken?.symbol||'?'} / ${p.quoteToken?.symbol||'?'}`,baseAsset:p.baseToken?.symbol,quoteAsset:p.quoteToken?.symbol,liquidityUsd:p.liquidity?.usd,volume5mUsd:p.volume?.m5,volume1hUsd:p.volume?.h1,volume24hUsd:p.volume?.h24,buys5m:t.buys,sells5m:t.sells,sourceConfidence:80};return dex.normalizeDexMarket(r,'dexscreener')}
function dexFromGt(p){const a=p.attributes||{},parts=String(a.name||'? / ?').split('/').map(x=>x.trim()),t=a.transactions?.m5||{};return dex.normalizeDexMarket({chain:p.relationships?.network?.data?.id||String(p.id||'').split('_')[0],venue:p.relationships?.dex?.data?.id||'DEX',pairAddress:a.address||String(p.id||'').split('_').slice(1).join('_'),symbol:a.name,baseAsset:parts[0],quoteAsset:parts[1],liquidityUsd:a.reserve_in_usd,volume5mUsd:a.volume_usd?.m5,volume1hUsd:a.volume_usd?.h1,volume24hUsd:a.volume_usd?.h24,buys5m:t.buys,sells5m:t.sells,sourceConfidence:84},'geckoterminal')}
async function collectDex(){const health={dexscreener:'down',geckoterminal:'down'},rows=[];const ds=await Promise.allSettled(['USDT','SOL','ETH','meme','ai'].map(q=>getJson('https://api.dexscreener.com/latest/dex/search?q='+encodeURIComponent(q),5000)));for(const x of ds)if(x.status==='fulfilled'){health.dexscreener='live';for(const p of x.value?.pairs||[])rows.push(dexFromPair(p))}try{const g=await getJson('https://api.geckoterminal.com/api/v2/networks/trending_pools?include=base_token%2Cquote_token&page=1',6000,{'accept':'application/json;version=20230203'});health.geckoterminal='live';for(const p of g.data||[])rows.push(dexFromGt(p))}catch{}
 const m=new Map();for(const r of rows){const k=`${r.chain}:${r.pairAddress||r.symbol}`;const old=m.get(k);if(!old||Number(r.sourceConfidence||0)>Number(old.sourceConfidence||0))m.set(k,r)}return{rows:[...m.values()].slice(0,500),health}}
function normMany(list,venue,marketType='spot',fx={}){return(list||[]).map(x=>cex.normalizeCexTicker(x,venue,marketType,fx)).filter(Boolean)}
async function usdKrw(){try{const d=await getJson('https://api.upbit.com/v1/ticker?markets=KRW-USDT',4500);const p=Number(d?.[0]?.trade_price);return Number.isFinite(p)&&p>500?p:null}catch{return null}}
async function collectCex(){const health={binance:'down',upbit:'down',bithumb:'down',okx:'down',bybit:'down',coinbase:'down'},rows=[],fx={usdKrw:await usdKrw()};
 const jobs=[];
 jobs.push((async()=>{try{const a=await getJson('https://api.binance.com/api/v3/ticker/24hr');health.binance='live';rows.push(...normMany(a.filter(x=>/(USDT|USDC|FDUSD)$/.test(x.symbol)),'Binance','spot',fx));const f=await getJson('https://fapi.binance.com/fapi/v1/ticker/24hr');rows.push(...normMany(f.filter(x=>/USDT$/.test(x.symbol)),'Binance','futures',fx))}catch{}})());
 jobs.push((async()=>{try{const mk=await getJson('https://api.upbit.com/v1/market/all?is_details=false');const ids=(mk||[]).filter(x=>String(x.market).startsWith('KRW-')).slice(0,100).map(x=>x.market);if(ids.length){const t=await getJson('https://api.upbit.com/v1/ticker?markets='+encodeURIComponent(ids.join(',')));health.upbit='live';rows.push(...normMany(t,'Upbit','spot',fx))}}catch{}})());
 jobs.push((async()=>{try{const d=await getJson('https://api.bithumb.com/public/ticker/ALL_KRW');if(d?.status==='0000'){health.bithumb='live';for(const [sym,v] of Object.entries(d.data||{}))if(sym!=='date')rows.push(cex.normalizeCexTicker({market:`KRW-${sym}`,trade_price:v.closing_price,acc_trade_price_24h:v.acc_trade_value_24H,change24h:v.fluctate_rate_24H},'Bithumb','spot',fx))}}catch{}})());
 jobs.push((async()=>{try{const d=await getJson('https://www.okx.com/api/v5/market/tickers?instType=SPOT');health.okx='live';rows.push(...normMany((d.data||[]).filter(x=>/-USDT$|-USDC$/.test(x.instId)).map(x=>({...x,last:x.last,quoteVolume:x.volCcy24h,change24h:x.open24h&&x.last?(Number(x.last)/Number(x.open24h)-1)*100:null})),'OKX','spot',fx))}catch{}})());
 jobs.push((async()=>{try{const d=await getJson('https://api.bybit.com/v5/market/tickers?category=spot');health.bybit='live';rows.push(...normMany((d.result?.list||[]).filter(x=>/USDT$/.test(x.symbol)).map(x=>({...x,lastPrice:x.lastPrice,quoteVolume:x.turnover24h,change24h:Number(x.price24hPcnt)*100})),'Bybit','spot',fx))}catch{}})());
 jobs.push((async()=>{const syms=['BTC-USD','ETH-USD','SOL-USD','XRP-USD','DOGE-USD','ADA-USD'];let ok=0;for(const s of syms){try{const d=await getJson(`https://api.exchange.coinbase.com/products/${s}/stats`,4200);rows.push(cex.normalizeCexTicker({product_id:s,last:d.last,quote_volume:d.volume&&d.last?Number(d.volume)*Number(d.last):null,change24h:d.open&&d.last?(Number(d.last)/Number(d.open)-1)*100:null},'Coinbase','spot',fx));ok++}catch{}}if(ok)health.coinbase='live'})());
 await Promise.all(jobs);return{rows:rows.filter(Boolean).slice(0,2500),health,fx}}
function themeForMarket(m){const x=themes.classifyMarket({baseAsset:m.baseAsset||'',symbol:m.symbol||'',chain:m.chain||null,tokenAddress:m.tokenAddress||null});return x.primaryTheme||x.theme||'Other / Unclassified'}
function buildFrom({providerHealth={},dexFlows=[],cexFlows=[],onchainThemeFlows=[]}){const a=aggregate.aggregateMarketFlow({dexFlows,cexFlows,onchainThemeFlows,themeForMarket});const live=Object.values(providerHealth).filter(x=>x==='live').length,total=Math.max(1,Object.keys(providerHealth).length),confidence=Math.round(Math.min(100,(live/total)*75+(dexFlows.length?10:0)+(cexFlows.length?15:0)));return{updatedAt:new Date().toISOString(),stale:false,providerHealth,dexFlows,cexFlows,tokenFlows:a.tokenFlows,themeFlows:a.themeFlows,coverage:{dexMarkets:dexFlows.length,cexMarkets:cexFlows.length,themes:a.themeFlows.length,venues:new Set(cexFlows.map(x=>x.venue)).size},confidence}}
async function build(){if(cache.data&&Date.now()-cache.ts<20000)return cache.data;const [d,c]=await Promise.all([collectDex(),collectCex()]);const data=buildFrom({providerHealth:{...d.health,...c.health},dexFlows:d.rows,cexFlows:c.rows,onchainThemeFlows:[]});cache={ts:Date.now(),data};return data}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=20, stale-while-revalidate=90');try{return res.status(200).json(await build())}catch(e){if(cache.data)return res.status(200).json({...cache.data,stale:true,error:String(e?.message||e)});return res.status(200).json({updatedAt:new Date().toISOString(),stale:true,providerHealth:{},dexFlows:[],cexFlows:[],tokenFlows:[],themeFlows:[],coverage:{dexMarkets:0,cexMarkets:0,themes:0,venues:0},confidence:0,error:'market flow degraded'})}}
module.exports._buildFrom=buildFrom;module.exports._collectDex=collectDex;module.exports._collectCex=collectCex;
