const providers=require('../lib/onchain/providers');
const aggregate=require('../lib/onchain/aggregate');
const themes=require('../ui/radar-themes.js');
let cache={ts:0,key:'',data:null};
function parseAssets(q){return String(q||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,24)}
function confidenceFor(health,tokenFlows){const live=Object.values(health||{}).filter(x=>x==='live').length,configured=Object.values(health||{}).filter(x=>x==='configured').length,flowConf=tokenFlows.length?tokenFlows.reduce((s,x)=>s+Number(x.dataConfidence||0),0)/tokenFlows.length:0;return Math.round(Math.min(100,live*18+configured*5+flowConf*.35))}
async function build(req){const assets=parseAssets(req.query?.assets),key=assets.sort().join(',');if(cache.data&&cache.key===key&&Date.now()-cache.ts<60000)return cache.data;const fetched=await providers.fetchOnchainEvents({assets});const result=aggregate.aggregateFlows(fetched.records,{themeForToken:t=>themes.classifyMarket({baseAsset:t.symbol||'',tokenAddress:t.tokenAddress,chain:t.chain}).primaryTheme});const coverageChains=new Set(fetched.records.map(r=>r.chain));const data={updatedAt:new Date().toISOString(),stale:false,providerHealth:fetched.providerHealth,tokenFlows:result.tokenFlows,themeFlows:result.themeFlows,coverage:{chains:coverageChains.size,tokens:result.tokenFlows.length,requestedAssets:assets.length},confidence:confidenceFor(fetched.providerHealth,result.tokenFlows),configured:fetched.configured};cache={ts:Date.now(),key,data};return data}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=30, stale-while-revalidate=120');try{return res.status(200).json(await build(req))}catch(e){if(cache.data)return res.status(200).json({...cache.data,stale:true,error:String(e?.message||e)});return res.status(200).json({updatedAt:new Date().toISOString(),stale:true,providerHealth:{solana:'degraded',ethereum:'degraded',base:'degraded',bsc:'degraded'},tokenFlows:[],themeFlows:[],coverage:{chains:0,tokens:0,requestedAssets:parseAssets(req.query?.assets).length},confidence:0,error:'onchain flow degraded'})}}
module.exports._build=build;
