const {analyzeFallingWedge}=require('../lib/pattern-engine.js');
const SPOT=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];
const FUT=['https://fapi.binance.com','https://fapi1.binance.com','https://fapi2.binance.com','https://www.binance.com'];
const num=(v,f=0)=>{v=Number(v);return Number.isFinite(v)?v:f};
async function fetchAny(bases,path,timeout=5000){let last;for(const base of bases){const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(base+path,{signal:ctl.signal,headers:{accept:'application/json','user-agent':'PulseRadar-Pro/3.14'}});const t=await r.text();clearTimeout(to);if(!r.ok){last=Error('HTTP '+r.status);continue}if(!t.trim())throw Error('Empty response');return JSON.parse(t)}catch(e){clearTimeout(to);last=e}}throw last||Error('market fetch failed')}
function ema(a,p){if(!a.length)return[];const k=2/(p+1),o=[];let x=a[0];for(let i=0;i<a.length;i++){x=i?a[i]*k+x*(1-k):a[i];o.push(x)}return o}
function rsi(a,p=14){const out=Array(a.length).fill(null);if(a.length<=p)return out;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(0,d);l+=Math.max(0,-d)}g/=p;l/=p;out[p]=l?100-100/(1+g/l):100;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(p-1)+Math.max(0,d))/p;l=(l*(p-1)+Math.max(0,-d))/p;out[i]=l?100-100/(1+g/l):100}return out}
function atr(h,l,c,p=14){const tr=h.map((x,i)=>i?Math.max(x-l[i],Math.abs(x-c[i-1]),Math.abs(l[i]-c[i-1])):x-l[i]);return ema(tr,p)}
function rawPivots(h,l,left=3,right=3){const out=[];for(let i=left;i<h.length-right;i++){let ph=true,pl=true;for(let j=i-left;j<=i+right;j++){if(j===i)continue;if(h[j]>=h[i])ph=false;if(l[j]<=l[i])pl=false}if(ph)out.push({id:`P-H-${i}`,i,type:'H',price:h[i],confirmedAt:i+right,status:'confirmed'});if(pl)out.push({id:`P-L-${i}`,i,type:'L',price:l[i],confirmedAt:i+right,status:'confirmed'})}return out.sort((a,b)=>a.confirmedAt-b.confirmedAt||a.i-b.i)}
function canonical(raw){const out=[];for(const p of raw){const s={index:p.i,pivotIndex:p.i,type:p.type,price:p.price,confirmed:true,confirmedAt:p.confirmedAt,status:'active'};if(!out.length||out.at(-1).type!==s.type){out.push(s);continue}const last=out.at(-1),more=s.type==='H'?s.price>last.price:s.price<last.price;if(more)out[out.length-1]=s}return out}
function zones(swings,close,atrNow){const vals=swings.slice(-30).map(s=>s.price),tol=Math.max(close*.0025,atrNow*.35),groups=[];for(const p of vals){let g=groups.find(x=>Math.abs(x.center-p)<=tol);if(!g){g={center:p,vals:[]};groups.push(g)}g.vals.push(p);g.center=g.vals.reduce((a,b)=>a+b,0)/g.vals.length}return{support:groups.map(g=>g.center).filter(x=>x<close).sort((a,b)=>b-a).slice(0,4),resistance:groups.map(g=>g.center).filter(x=>x>close).sort((a,b)=>a-b).slice(0,4),atr:atrNow}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=15, stale-while-revalidate=30');try{const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase().replace(/[^A-Z0-9]/g,''),interval=String(req.query.interval||'4h'),market=String(req.query.market||'auto'),limit=Math.max(120,Math.min(500,Number(req.query.limit)||240));let raw=null,usedMarket='spot',errSpot=null;if(market!=='futures'){try{raw=await fetchAny(SPOT,`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}&limit=${limit}`)}catch(e){errSpot=e}}if(!Array.isArray(raw)||!raw.length){raw=await fetchAny(FUT,`/fapi/v1/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}&limit=${limit}`);usedMarket='futures'}if(!Array.isArray(raw)||raw.length<80)throw Error('Not enough kline data');const klines=raw.map(k=>({time:num(k[0]),open:num(k[1]),high:num(k[2]),low:num(k[3]),close:num(k[4]),volume:num(k[5])})),h=klines.map(k=>k.high),l=klines.map(k=>k.low),c=klines.map(k=>k.close),aa=atr(h,l,c),rr=rsi(c),swings=canonical(rawPivots(h,l)),atrNow=aa.at(-1),zz=zones(swings,c.at(-1),atrNow),pattern=analyzeFallingWedge({klines,swings,atrByIndex:aa,rsi:rr,structure:null,zones:zz,lookbackSwings:12});return res.status(200).json({ok:true,version:'pattern-v1.1',symbol,interval,market:usedMarket,pattern,meta:{bars:klines.length,confirmedSwings:swings.length,atr:atrNow,spotFallbackError:errSpot?.message||null,rule:'confirmed canonical swings + ATR-normalized regression + convergence + apex + breach integrity + spaced touches'}})}catch(e){return res.status(502).json({ok:false,error:e?.message||'Pattern analysis failed'})}}
