const cache={ts:0,data:null};
const BASE='https://api.binance.com';
const HEADERS={accept:'application/json','user-agent':'PulseRadar-Pro-v3'};
const CFG={stage1Limit:60,deepLimit:10,minQuoteVolumeUsd:250000,maxAbs24hForPresurge:10,hotExclusion24h:15,volume15Trigger:3,buyRatioTrigger:.60};
async function getJson(path,ms=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(BASE+path,{headers:HEADERS,signal:c.signal});if(!r.ok)throw new Error(`binance ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function median(a){const v=a.filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!v.length)return 0;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2}
function pct(a,b){return a?((b-a)/a)*100:0}
function completed(rows,now=Date.now()){return (rows||[]).filter(x=>num(x[6])<now-1000)}
function kline(x){return{openTime:num(x[0]),open:num(x[1]),high:num(x[2]),low:num(x[3]),close:num(x[4]),volume:num(x[5]),closeTime:num(x[6]),quoteVolume:num(x[7]),trades:num(x[8]),takerBuyQuote:num(x[10])}}
function ratio(v,b){return b>0?v/b:0}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function round(v,d=2){const p=10**d;return Math.round(v*p)/p}
function tfStats(rows){const a=completed(rows).map(kline);if(!a.length)return{candles:[],last:null,volMedian:0,volRatio:0,buyRatio:0,priceChange:0};const last=a[a.length-1],prev=a.slice(Math.max(0,a.length-21),-1),volMedian=median(prev.map(x=>x.quoteVolume));return{candles:a,last,volMedian,volRatio:ratio(last.quoteVolume,volMedian),buyRatio:last.quoteVolume?last.takerBuyQuote/last.quoteVolume:0,priceChange:a.length>1?pct(a[a.length-2].close,last.close):0}}
function structure4h(a){if(a.length<18)return{higherLow:false,choch:false,score:0};const recent=a.slice(-8),prior=a.slice(-16,-8);const recentLow=Math.min(...recent.map(x=>x.low)),priorLow=Math.min(...prior.map(x=>x.low));const priorHigh=Math.max(...prior.map(x=>x.high)),last=recent[recent.length-1];const higherLow=recentLow>priorLow,choch=higherLow&&last.close>priorHigh;return{higherLow,choch,score:choch?1:higherLow?.65:0}}
function baseContext(daily,weekly){if(daily.length<12)return{nearBase:false,downtrendSlowing:false,score:0};const d=daily.slice(-30),last=d[d.length-1],lo=Math.min(...d.map(x=>x.low)),hi=Math.max(...d.map(x=>x.high));const pos=hi>lo?(last.close-lo)/(hi-lo):.5;const r1=d.slice(-10),r0=d.slice(-20,-10);const slope=x=>x.length>1?pct(x[0].close,x[x.length-1].close):0;const s0=slope(r0),s1=slope(r1),downtrendSlowing=s0<0&&s1>s0;const nearBase=pos<=.38;const w=weekly.slice(-8),weeklyStable=w.length<2?true:pct(w[0].close,w[w.length-1].close)>-25;const score=clamp((nearBase?.5:0)+(downtrendSlowing?.35:0)+(weeklyStable?.15:0),0,1);return{nearBase,downtrendSlowing,weeklyStable,score,rangePosition:round(pos,3)}}
function fiveMinAcceleration(a){if(a.length<16)return{threeUp:false,ratio:0,series:[]};const last3=a.slice(-3),base=median(a.slice(-15,-3).map(x=>x.quoteVolume));const threeUp=last3[0].quoteVolume<last3[1].quoteVolume&&last3[1].quoteVolume<last3[2].quoteVolume;return{threeUp,ratio:ratio(last3[2].quoteVolume,base),series:last3.map(x=>round(x.quoteVolume,0))}}
function persistence15(a){if(a.length<8)return{ratio:0,holding:false};const base=median(a.slice(-20,-3).map(x=>x.quoteVolume));const mean=a.slice(-3).reduce((s,x)=>s+x.quoteVolume,0)/3;return{ratio:ratio(mean,base),holding:ratio(mean,base)>=1.5}}
function firstShock15(a){if(a.length<10)return{exists:false,maxRatio:0,index:-1};let best={exists:false,maxRatio:0,index:-1};for(let i=Math.max(5,a.length-20);i<a.length-2;i++){const base=median(a.slice(Math.max(0,i-12),i).map(x=>x.quoteVolume));const r=ratio(a[i].quoteVolume,base);if(r>best.maxRatio)best={exists:r>=3,maxRatio:r,index:i}}return best}
function highBreakout15(a){if(a.length<10)return{breakout:false,nearHigh:false,referenceHigh:0};const last=a[a.length-1],referenceHigh=Math.max(...a.slice(-9,-1).map(x=>x.high));return{breakout:last.close>referenceHigh,nearHigh:referenceHigh>0&&last.close>=referenceHigh*.995,referenceHigh}}
function scoreParts(ctx){const structure=round(20*clamp(ctx.base.score*.45+ctx.s4.score*.55,0,1),1);const volume=round(25*clamp(ctx.s15.volRatio/5,0,1),1);const acceleration=round(15*clamp((ctx.acc.threeUp?.55:0)+clamp(ctx.acc.ratio/3,0,1)*.45,0,1),1);const buyPressure=round(20*clamp((ctx.buyRatio-.45)/.25,0,1),1);const compression=round(15*clamp(1-Math.abs(ctx.price24)/12,0,1),1);const persistence=round(5*clamp(ctx.persist.ratio/2,0,1),1);return{structure,volume,acceleration,buyPressure,compression,persistence,total:round(structure+volume+acceleration+buyPressure+compression+persistence,1)}}
async function fetchKlines(symbol,interval,limit){return getJson(`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${interval}&limit=${limit}`,7000)}
async function deepInspect(c){const[m5,h1,h4,d1,w1]=await Promise.all([fetchKlines(c.symbol,'5m',36),fetchKlines(c.symbol,'1h',48),fetchKlines(c.symbol,'4h',40),fetchKlines(c.symbol,'1d',35),fetchKlines(c.symbol,'1w',14)]);const s5=tfStats(m5),s1=tfStats(h1),s4tf=tfStats(h4),sd=tfStats(d1),sw=tfStats(w1);const s4=structure4h(s4tf.candles),base=baseContext(sd.candles,sw.candles),acc=fiveMinAcceleration(s5.candles),persist=persistence15(c.s15.candles),shock=firstShock15(c.s15.candles),br=highBreakout15(c.s15.candles);const buyRatio=c.s15.buyRatio,oneHourLead=s1.volRatio>=1.5&&Math.abs(s1.priceChange)<=3;const priceCompressed=Math.abs(c.price24)<=CFG.maxAbs24hForPresurge;const hot=Math.abs(c.price24)>CFG.hotExclusion24h;const primary=[base.score>=.5,s4.higherLow||s4.choch,oneHourLead,c.s15.volRatio>=CFG.volume15Trigger,acc.threeUp&&acc.ratio>=1.5,buyRatio>=CFG.buyRatioTrigger,priceCompressed,persist.holding];const confirmations=primary.filter(Boolean).length;const secondary=shock.exists&&c.s15.volRatio<2.25&&acc.threeUp&&acc.ratio>=1.5;const ignition=secondary&&buyRatio>=CFG.buyRatioTrigger&&br.nearHigh;let state='NORMAL';if(hot)state='COOLDOWN';else if(ignition)state='IGNITION';else if(confirmations>=6&&c.s15.volRatio>=3&&buyRatio>=.60)state='PRE_SURGE';else if(shock.exists||confirmations>=4)state='WATCH';const parts=scoreParts({base,s4,s15:c.s15,acc,buyRatio,price24:c.price24,persist});const reasons=[];if(shock.exists)reasons.push(`15m 1차 거래량 충격 ${round(shock.maxRatio,2)}×`);if(c.s15.volRatio>=3)reasons.push(`15m 거래량 ${round(c.s15.volRatio,2)}×`);if(acc.threeUp)reasons.push('5m 거래량 3봉 연속 증가');if(buyRatio>=.60)reasons.push(`taker-buy ${round(buyRatio*100,1)}%`);if(s4.choch)reasons.push('4H CHoCH');else if(s4.higherLow)reasons.push('4H 저점 상승');if(oneHourLead)reasons.push('1H 거래량 선행');if(persist.holding)reasons.push('거래량 지속');if(secondary)reasons.push('2차 점화 대기 구조');if(ignition)reasons.push('최근 고점 재시험/돌파');return{symbol:c.symbol,state,score:parts.total,scoreParts:parts,confirmations,price:c.price,price24:round(c.price24,2),quoteVolume24:round(c.quoteVolume24,0),metrics:{volume15x:round(c.s15.volRatio,2),buyRatioPct:round(buyRatio*100,1),volume5x:round(acc.ratio,2),volume5Series:acc.series,volume1hx:round(s1.volRatio,2),persistence15x:round(persist.ratio,2),referenceHigh:round(br.referenceHigh,8)},flags:{longBase:base.score>=.5,higherLow4h:s4.higherLow,choch4h:s4.choch,volumeLead1h:oneHourLead,volumeShock15:c.s15.volRatio>=3,volumeAccel5:acc.threeUp,buyPressure:buyRatio>=.60,priceCompressed,persistence:persist.holding,secondaryIgnition:secondary,breakout:br.breakout,nearHigh:br.nearHigh},reasons}}
async function snapshot(){if(cache.data&&Date.now()-cache.ts<30000)return cache.data;const started=Date.now();const[exchange,tickers]=await Promise.all([getJson('/api/v3/exchangeInfo',7000),getJson('/api/v3/ticker/24hr',7000)]);const tickerMap=new Map((tickers||[]).map(t=>[t.symbol,t]));const universe=(exchange.symbols||[]).filter(s=>s.status==='TRADING'&&s.isSpotTradingAllowed!==false&&s.quoteAsset==='USDT').map(s=>{const t=tickerMap.get(s.symbol)||{};return{symbol:s.symbol,price:num(t.lastPrice),price24:num(t.priceChangePercent),quoteVolume24:num(t.quoteVolume),trades:num(t.count)}}).filter(x=>x.price>0);const stage1=universe.filter(x=>x.quoteVolume24>=CFG.minQuoteVolumeUsd&&Math.abs(x.price24)<=12).sort((a,b)=>{const pa=(1-Math.min(Math.abs(a.price24),12)/12)*.35,pb=(1-Math.min(Math.abs(b.price24),12)/12)*.35;const va=Math.log10(Math.max(1,a.quoteVolume24))*.5,vb=Math.log10(Math.max(1,b.quoteVolume24))*.5;const ta=Math.log10(Math.max(1,a.trades))*.15,tb=Math.log10(Math.max(1,b.trades))*.15;return(vb+pb+tb)-(va+pa+ta)}).slice(0,CFG.stage1Limit);const stage2Settled=await Promise.allSettled(stage1.map(async x=>{const rows=await fetchKlines(x.symbol,'15m',40),s15=tfStats(rows);return{...x,s15,preScore:s15.volRatio*3+(s15.buyRatio>=.55?1.5:0)+(Math.abs(x.price24)<=5?1:0)}}));const stage2=stage2Settled.filter(x=>x.status==='fulfilled').map(x=>x.value).filter(x=>x.s15.candles.length>=20).sort((a,b)=>b.preScore-a.preScore);const deepInput=stage2.filter(x=>x.s15.volRatio>=1.25||x.s15.buyRatio>=.58).slice(0,CFG.deepLimit);const deepSettled=await Promise.allSettled(deepInput.map(deepInspect));const rows=deepSettled.filter(x=>x.status==='fulfilled').map(x=>x.value).sort((a,b)=>{const rank=s=>s.state==='IGNITION'?4:s.state==='PRE_SURGE'?3:s.state==='WATCH'?2:s.state==='COOLDOWN'?1:0;return rank(b)-rank(a)||b.score-a.score});const data={updatedAt:new Date().toISOString(),engine:'PRE-SURGE Spot v3',coverage:{spotUsdtUniverse:universe.length,stage1Candidates:stage1.length,stage2Validated:stage2.length,deepValidated:rows.length,stage2Failures:stage2Settled.length-stage2.length,deepFailures:deepSettled.length-rows.length},thresholds:{volume15x:CFG.volume15Trigger,takerBuyPct:CFG.buyRatioTrigger*100,maxPriceExpansionPct:CFG.maxAbs24hForPresurge,hotExclusionPct:CFG.hotExclusion24h},rows,elapsedMs:Date.now()-started,note:'전체 Binance USDT 현물 유니버스를 1차 압축한 뒤 15m 검증과 5m/1H/4H/1D/1W 정밀검증을 수행합니다. 모든 종목에 모든 TF를 동시에 계산한 완전 백테스트는 아닙니다.'};cache.ts=Date.now();cache.data=data;return data}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=20, stale-while-revalidate=60');try{return res.status(200).json(await snapshot())}catch(e){if(cache.data)return res.status(200).json({...cache.data,stale:true,error:String(e?.message||e)});return res.status(503).json({updatedAt:new Date().toISOString(),engine:'PRE-SURGE Spot v3',rows:[],error:String(e?.message||e)})}};
