let cache={ts:0,data:null};
const CHAINS=['solana','ethereum','bsc','base','arbitrum','optimism','polygon','avalanche','sui','aptos','ton','tron','linea','zksync','blast','mantle','scroll','sonic','berachain','sei','injective','arc'];
const SEARCH_TERMS=['USDC','USDT','SOL','ETH','BNB','BTC','new','launch','pump','meme','ai','agent','rwa','defi','gaming','gamefi','depin','privacy'];
const GT_HEADERS={accept:'application/json;version=20230203','user-agent':'PulseRadar-Pro-v3'};
async function getJson(url,ms=5000,headers){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:headers||{accept:'application/json','user-agent':'PulseRadar-Pro-v3'},signal:c.signal});if(!r.ok)throw new Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
function dexRecord(p){const t=p.txns?.m5||p.txns?.h1||{};return {id:`${p.chainId}:${p.pairAddress}`,source:'dexscreener',venue:p.dexId||'DEX',chain:String(p.chainId||'unknown').toLowerCase(),marketType:'dex',symbol:`${p.baseToken?.symbol||'?'} / ${p.quoteToken?.symbol||'?'}`,baseAsset:p.baseToken?.symbol||'',quoteAsset:p.quoteToken?.symbol||'',tokenAddress:p.baseToken?.address||null,pairAddress:p.pairAddress||null,eventType:'snapshot',eventTime:Date.now(),receivedTime:Date.now(),price:Number(p.priceUsd||0),priceUsd:Number(p.priceUsd||0),quoteVolumeUsd:Number(p.volume?.m5||p.volume?.h1||p.volume?.h24||0),liquidityUsd:Number(p.liquidity?.usd||0),fdvUsd:Number(p.fdv||0),marketCapUsd:Number(p.marketCap||0),buys:Number(t.buys||0),sells:Number(t.sells||0),txCount:Number(t.buys||0)+Number(t.sells||0),change5m:Number(p.priceChange?.m5||0),priceChange1h:Number(p.priceChange?.h1||0),pairCreatedAt:p.pairCreatedAt?new Date(p.pairCreatedAt).toISOString():null,sourceConfidence:80,url:p.url||null,boosts:Number(p.boosts?.active||0)} }
function gtRecord(p){const a=p?.attributes||{},rel=p?.relationships||{};const chain=String(rel.network?.data?.id||a.network_id||String(p?.id||'').split('_')[0]||'unknown').toLowerCase();const tx=a.transactions?.m5||a.transactions?.h1||a.transactions?.h24||{};const name=String(a.name||a.pool_name||'? / ?');const parts=name.split('/').map(x=>x.trim());const address=a.address||String(p?.id||'').replace(`${chain}_`,'')||null;return {id:`${chain}:${address}`,source:'geckoterminal',venue:rel.dex?.data?.id||a.dex_id||'DEX',chain,marketType:'dex',symbol:name,baseAsset:parts[0]||'',quoteAsset:parts[1]||'',tokenAddress:rel.base_token?.data?.id||null,pairAddress:address,eventType:'snapshot',eventTime:Date.now(),receivedTime:Date.now(),price:Number(a.base_token_price_usd||0),priceUsd:Number(a.base_token_price_usd||0),quoteVolumeUsd:Number(a.volume_usd?.m5||a.volume_usd?.h1||a.volume_usd?.h24||0),liquidityUsd:Number(a.reserve_in_usd||0),fdvUsd:Number(a.fdv_usd||0),marketCapUsd:Number(a.market_cap_usd||0),buys:Number(tx.buys||0),sells:Number(tx.sells||0),txCount:Number(tx.buys||0)+Number(tx.sells||0),change5m:Number(a.price_change_percentage?.m5||0),priceChange1h:Number(a.price_change_percentage?.h1||0),pairCreatedAt:a.pool_created_at||null,sourceConfidence:84,url:null,boosts:0}}
function cexRecord(t,marketType){return {id:`binance:${marketType}:${t.symbol}`,source:'binance',venue:'Binance',chain:null,marketType,symbol:t.symbol,baseAsset:t.symbol?.replace(/(USDT|USDC|FDUSD|BTC|ETH)$/,''),quoteAsset:(t.symbol?.match(/(USDT|USDC|FDUSD|BTC|ETH)$/)||[])[1]||'',eventType:'snapshot',eventTime:Date.now(),receivedTime:Date.now(),price:Number(t.lastPrice||0),quoteVolumeUsd:Number(t.quoteVolume||0),priceChange24h:Number(t.priceChangePercent||0),txCount:Number(t.count||0),sourceConfidence:95}}
function betterMarket(next,prev){
  if(!prev)return true;
  const nc=Number(next.sourceConfidence||0),pc=Number(prev.sourceConfidence||0);if(nc!==pc)return nc>pc;
  const nl=Number(next.liquidityUsd||0),pl=Number(prev.liquidityUsd||0);if(nl!==pl)return nl>pl;
  return Number(next.quoteVolumeUsd||0)>Number(prev.quoteVolumeUsd||0);
}
function uniqMarkets(a){const m=new Map();for(const x of a){if(!x?.id)continue;const key=x.marketType==='dex'?`${x.chain}:${x.pairAddress||x.id}`:x.id;const prev=m.get(key);if(betterMarket(x,prev))m.set(key,x)}return [...m.values()]}
async function fetchBinance(){const out=[],health={spot:'down',futures:'down'};await Promise.allSettled([
 getJson('https://api.binance.com/api/v3/ticker/24hr',6500).then(a=>{health.spot='live';for(const t of a)if(/(USDT|USDC|FDUSD|BTC|ETH)$/.test(t.symbol))out.push(cexRecord(t,'spot'))}),
 getJson('https://fapi.binance.com/fapi/v1/ticker/24hr',6500).then(a=>{health.futures='live';for(const t of a)out.push(cexRecord(t,'futures'))})
]);return {out,health}}
async function fetchDexScreener(){const health={dexscreener:'down'},pairs=[];const searches=await Promise.allSettled(SEARCH_TERMS.map(q=>getJson('https://api.dexscreener.com/latest/dex/search?q='+encodeURIComponent(q),4500)));for(const r of searches)if(r.status==='fulfilled'){health.dexscreener='live';for(const p of r.value?.pairs||[])pairs.push(dexRecord(p))}
 const feeds=await Promise.allSettled([getJson('https://api.dexscreener.com/token-profiles/latest/v1',4500),getJson('https://api.dexscreener.com/token-boosts/latest/v1',4500),getJson('https://api.dexscreener.com/token-boosts/top/v1',4500)]);const tokens=[];for(const r of feeds)if(r.status==='fulfilled')for(const x of (Array.isArray(r.value)?r.value:[r.value]))if(x?.chainId&&x?.tokenAddress)tokens.push(x);const byChain={};for(const x of tokens){(byChain[x.chainId]??=[]).push(x.tokenAddress)}const detailJobs=[];for(const [chain,addresses] of Object.entries(byChain))for(let i=0;i<addresses.length;i+=30)detailJobs.push(getJson(`https://api.dexscreener.com/tokens/v1/${encodeURIComponent(chain)}/${addresses.slice(i,i+30).join(',')}`,4500));for(const r of await Promise.allSettled(detailJobs.slice(0,36)))if(r.status==='fulfilled'){health.dexscreener='live';for(const p of r.value||[])pairs.push(dexRecord(p))}return {out:uniqMarkets(pairs),health}}
async function fetchGeckoTerminal(){const health={geckoterminal:'down'},pairs=[];const urls=[];for(const page of [1,2]){urls.push(`https://api.geckoterminal.com/api/v2/networks/new_pools?include=base_token%2Cquote_token&page=${page}`);urls.push(`https://api.geckoterminal.com/api/v2/networks/trending_pools?include=base_token%2Cquote_token&page=${page}`)}for(const r of await Promise.allSettled(urls.map(u=>getJson(u,5500,GT_HEADERS))))if(r.status==='fulfilled'){health.geckoterminal='live';for(const p of r.value?.data||[])pairs.push(gtRecord(p))}return {out:uniqMarkets(pairs),health}}
async function fetchDex(){const [d,g]=await Promise.all([fetchDexScreener(),fetchGeckoTerminal()]);return {out:uniqMarkets([...d.out,...g.out]),health:{...d.health,...g.health}}}
async function snapshot(){if(cache.data&&Date.now()-cache.ts<12000)return cache.data;const [b,d]=await Promise.all([fetchBinance(),fetchDex()]);const cex=b.out,dex=d.out,newPairs=dex.filter(x=>x.pairCreatedAt&&Date.now()-new Date(x.pairCreatedAt).getTime()<6*3600000).sort((a,b)=>new Date(b.pairCreatedAt)-new Date(a.pairCreatedAt));const chains=[...new Set([...CHAINS,...dex.map(x=>x.chain).filter(Boolean)])].sort();const data={updatedAt:new Date().toISOString(),sources:{binance:true,dexscreener:true,geckoterminal:true},chains,cex,dex,newPairs,health:{...b.health,...d.health}};cache={ts:Date.now(),data};return data}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=10, stale-while-revalidate=30');const mode=String(req.query?.mode||'snapshot');try{const data=await snapshot();if(mode==='health')return res.status(200).json({updatedAt:data.updatedAt,health:data.health,counts:{cex:data.cex.length,dex:data.dex.length,newPairs:data.newPairs.length}});return res.status(200).json(data)}catch(e){if(cache.data)return res.status(200).json({...cache.data,stale:true,error:String(e?.message||e)});return res.status(503).json({updatedAt:new Date().toISOString(),error:'radar unavailable',health:{binance:'down',dexscreener:'down',geckoterminal:'down'},cex:[],dex:[],newPairs:[]})}}
