let cache={ts:0,data:null};
const CHAINS=['solana','ethereum','bsc','base','arbitrum','optimism','polygon','avalanche','sui','aptos','ton','tron','linea','zksync','blast','mantle','scroll','sonic','berachain','sei','injective','arc'];
const SEARCH_TERMS=['USDC','USDT','SOL','ETH','BNB','BTC','new','meme','ai','rwa'];
async function getJson(url,ms=5000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:{accept:'application/json','user-agent':'PulseRadar-Pro-v3'},signal:c.signal});if(!r.ok)throw new Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
function dexRecord(p){const t=p.txns?.m5||p.txns?.h1||{};return {id:`${p.chainId}:${p.pairAddress}`,source:'dexscreener',venue:p.dexId||'DEX',chain:p.chainId,marketType:'dex',symbol:`${p.baseToken?.symbol||'?'} / ${p.quoteToken?.symbol||'?'}`,baseAsset:p.baseToken?.symbol||'',quoteAsset:p.quoteToken?.symbol||'',tokenAddress:p.baseToken?.address||null,pairAddress:p.pairAddress||null,eventType:'snapshot',eventTime:Date.now(),receivedTime:Date.now(),price:Number(p.priceUsd||0),priceUsd:Number(p.priceUsd||0),quoteVolumeUsd:Number(p.volume?.m5||p.volume?.h1||p.volume?.h24||0),liquidityUsd:Number(p.liquidity?.usd||0),fdvUsd:Number(p.fdv||0),marketCapUsd:Number(p.marketCap||0),buys:Number(t.buys||0),sells:Number(t.sells||0),txCount:Number(t.buys||0)+Number(t.sells||0),change5m:Number(p.priceChange?.m5||0),priceChange1h:Number(p.priceChange?.h1||0),pairCreatedAt:p.pairCreatedAt?new Date(p.pairCreatedAt).toISOString():null,sourceConfidence:80,url:p.url||null,boosts:Number(p.boosts?.active||0)} }
function cexRecord(t,marketType){return {id:`binance:${marketType}:${t.symbol}`,source:'binance',venue:'Binance',chain:null,marketType,symbol:t.symbol,baseAsset:t.symbol?.replace(/(USDT|USDC|FDUSD|BTC|ETH)$/,''),quoteAsset:(t.symbol?.match(/(USDT|USDC|FDUSD|BTC|ETH)$/)||[])[1]||'',eventType:'snapshot',eventTime:Date.now(),receivedTime:Date.now(),price:Number(t.lastPrice||0),quoteVolumeUsd:Number(t.quoteVolume||0),priceChange24h:Number(t.priceChangePercent||0),txCount:Number(t.count||0),sourceConfidence:95}}
function uniq(a){const m=new Map();for(const x of a)if(x?.id)m.set(x.id,x);return [...m.values()]}
async function fetchBinance(){const out=[],health={spot:'down',futures:'down'};await Promise.allSettled([
 getJson('https://api.binance.com/api/v3/ticker/24hr',6500).then(a=>{health.spot='live';for(const t of a)if(/(USDT|USDC|FDUSD|BTC|ETH)$/.test(t.symbol))out.push(cexRecord(t,'spot'))}),
 getJson('https://fapi.binance.com/fapi/v1/ticker/24hr',6500).then(a=>{health.futures='live';for(const t of a)out.push(cexRecord(t,'futures'))})
]);return {out,health}}
async function fetchDex(){const health={dexscreener:'down'},pairs=[];const searches=await Promise.allSettled(SEARCH_TERMS.map(q=>getJson('https://api.dexscreener.com/latest/dex/search?q='+encodeURIComponent(q),4500)));for(const r of searches)if(r.status==='fulfilled'){health.dexscreener='live';for(const p of r.value?.pairs||[])if(CHAINS.includes(String(p.chainId||'').toLowerCase()))pairs.push(dexRecord(p))}
 const feeds=await Promise.allSettled([getJson('https://api.dexscreener.com/token-profiles/latest/v1',4500),getJson('https://api.dexscreener.com/token-boosts/latest/v1',4500),getJson('https://api.dexscreener.com/token-boosts/top/v1',4500)]);const tokens=[];for(const r of feeds)if(r.status==='fulfilled')for(const x of (Array.isArray(r.value)?r.value:[r.value]))if(x?.chainId&&x?.tokenAddress&&CHAINS.includes(String(x.chainId).toLowerCase()))tokens.push(x);const byChain={};for(const x of tokens){(byChain[x.chainId]??=[]).push(x.tokenAddress)}const detailJobs=[];for(const [chain,addresses] of Object.entries(byChain))for(let i=0;i<addresses.length;i+=30)detailJobs.push(getJson(`https://api.dexscreener.com/tokens/v1/${encodeURIComponent(chain)}/${addresses.slice(i,i+30).join(',')}`,4500));for(const r of await Promise.allSettled(detailJobs.slice(0,24)))if(r.status==='fulfilled'){health.dexscreener='live';for(const p of r.value||[])pairs.push(dexRecord(p))}return {out:uniq(pairs),health}}
async function snapshot(){if(cache.data&&Date.now()-cache.ts<12000)return cache.data;const [b,d]=await Promise.all([fetchBinance(),fetchDex()]);const cex=b.out,dex=d.out,newPairs=dex.filter(x=>x.pairCreatedAt&&Date.now()-new Date(x.pairCreatedAt).getTime()<6*3600000).sort((a,b)=>new Date(b.pairCreatedAt)-new Date(a.pairCreatedAt));const data={updatedAt:new Date().toISOString(),sources:{binance:true,dexscreener:true},chains:CHAINS,cex,dex,newPairs,health:{...b.health,...d.health}};cache={ts:Date.now(),data};return data}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=10, stale-while-revalidate=30');const mode=String(req.query?.mode||'snapshot');try{const data=await snapshot();if(mode==='health')return res.status(200).json({updatedAt:data.updatedAt,health:data.health,counts:{cex:data.cex.length,dex:data.dex.length,newPairs:data.newPairs.length}});return res.status(200).json(data)}catch(e){if(cache.data)return res.status(200).json({...cache.data,stale:true,error:String(e?.message||e)});return res.status(503).json({updatedAt:new Date().toISOString(),error:'radar unavailable',health:{binance:'down',dexscreener:'down'},cex:[],dex:[],newPairs:[]})}}
