const BASES=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];
const n=(v,f=0)=>{v=Number(v);return Number.isFinite(v)?v:f};
async function getJson(path,params={}){let last;const qs=new URLSearchParams(params).toString();for(const base of BASES){try{const r=await fetch(base+path+(qs?'?'+qs:''),{headers:{'User-Agent':'PulseRadar-Pro/3.12'}});const t=await r.text();if(!r.ok)throw Error(`Binance ${r.status}: ${t.slice(0,120)}`);return JSON.parse(t)}catch(e){last=e}}throw last||Error('Binance failed')}
function rsi(a,p=14){const out=Array(a.length).fill(null);if(a.length<=p)return out;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;out[p]=l?100-100/(1+g/l):100;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;out[i]=l?100-100/(1+g/l):100}return out}
function pivots(h,l,left=3,right=3){const out=[];for(let i=left;i<h.length-right;i++){let ph=true,pl=true;for(let j=i-left;j<=i+right;j++){if(j===i)continue;if(h[j]>=h[i])ph=false;if(l[j]<=l[i])pl=false}if(ph)out.push({i,type:'H',price:h[i]});if(pl)out.push({i,type:'L',price:l[i]})}return out.sort((a,b)=>a.i-b.i)}
function classify(ps){let lastH=null,lastL=null;return ps.map(p=>{let label=p.type;if(p.type==='H'){label=lastH==null?'H':p.price>lastH?'HH':'LH';lastH=p.price}else{label=lastL==null?'L':p.price>lastL?'HL':'LL';lastL=p.price}return{...p,label}})}
function zones(ps,close){const span=Math.max(...ps.map(x=>x.price),close)-Math.min(...ps.map(x=>x.price),close),tol=Math.max(close*.003,span*.015);const pts=ps.slice(-18).map(x=>x.price).sort((a,b)=>a-b),groups=[];for(const p of pts){let g=groups.find(x=>Math.abs(x.center-p)<=tol);if(g){g.values.push(p);g.center=g.values.reduce((s,v)=>s+v,0)/g.values.length}else groups.push({center:p,values:[p]})}return groups.filter(g=>g.values.length>=2).map(g=>({price:g.center,touches:g.values.length,type:g.center>=close?'resistance':'support'})).sort((a,b)=>Math.abs(a.price-close)-Math.abs(b.price-close)).slice(0,6)}
function structureEvents(ps,c){const e=[];let swingHigh=null,swingLow=null,trend='neutral';for(let i=0;i<c.length;i++){for(const p of ps.filter(x=>x.i===i)){if(p.type==='H')swingHigh=p.price;else swingLow=p.price}if(swingHigh&&c[i]>swingHigh){e.push({i,type:trend==='down'?'CHOCH':'BOS',dir:'up',level:swingHigh});trend='up';swingHigh=null}if(swingLow&&c[i]<swingLow){e.push({i,type:trend==='up'?'CHOCH':'BOS',dir:'down',level:swingLow});trend='down';swingLow=null}}return e.slice(-12)}
function divergence(ps,rr,c){const lows=ps.filter(x=>x.type==='L').slice(-6),highs=ps.filter(x=>x.type==='H').slice(-6),out=[];for(let k=1;k<lows.length;k++){const a=lows[k-1],b=lows[k];if(b.price<a.price&&rr[b.i]>rr[a.i]+2)out.push({type:'bullish',from:a.i,to:b.i,priceFrom:a.price,priceTo:b.price,rsiFrom:rr[a.i],rsiTo:rr[b.i]})}for(let k=1;k<highs.length;k++){const a=highs[k-1],b=highs[k];if(b.price>a.price&&rr[b.i]<rr[a.i]-2)out.push({type:'bearish',from:a.i,to:b.i,priceFrom:a.price,priceTo:b.price,rsiFrom:rr[a.i],rsiTo:rr[b.i]})}return out.slice(-4)}
function trendlines(ps){const hs=ps.filter(x=>x.type==='H').slice(-3),ls=ps.filter(x=>x.type==='L').slice(-3),line=a=>a.length>=2?{from:{i:a[0].i,price:a[0].price},to:{i:a.at(-1).i,price:a.at(-1).price},slope:(a.at(-1).price-a[0].price)/(a.at(-1).i-a[0].i||1)}:null;return{resistance:line(hs),support:line(ls)}}
function scenario(close,zs,events,ps){const above=zs.filter(z=>z.price>close).sort((a,b)=>a.price-b.price),below=zs.filter(z=>z.price<close).sort((a,b)=>b.price-a.price),last=events.at(-1),lastLow=ps.filter(x=>x.type==='L').at(-1),lastHigh=ps.filter(x=>x.type==='H').at(-1);return{bias:last?.dir==='up'?'bullish-structure':last?.dir==='down'?'bearish-structure':'neutral',up:{condition:`최근 저항 ${above[0]?above[0].price.toPrecision(7):lastHigh?.price?.toPrecision(7)||'-'} 회복 후 유지`,targets:above.slice(0,3).map(x=>x.price)},down:{condition:`최근 지지 ${below[0]?below[0].price.toPrecision(7):lastLow?.price?.toPrecision(7)||'-'} 이탈`,targets:below.slice(0,3).map(x=>x.price)}}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=15, stale-while-revalidate=30');try{const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase(),interval=String(req.query.interval||'15m'),limit=Math.max(150,Math.min(500,n(req.query.limit,260)));const raw=await getJson('/api/v3/klines',{symbol,interval,limit:String(limit)});const closed=raw.filter(k=>n(k[6])<Date.now()),o=closed.map(k=>n(k[1])),h=closed.map(k=>n(k[2])),l=closed.map(k=>n(k[3])),c=closed.map(k=>n(k[4])),v=closed.map(k=>n(k[5])),rr=rsi(c),ps=classify(pivots(h,l,3,3)),zs=zones(ps,c.at(-1)),events=structureEvents(ps,c),divs=divergence(ps,rr,c),lines=trendlines(ps),sc=scenario(c.at(-1),zs,events,ps);res.status(200).json({ok:true,version:'3.12',symbol,interval,candles:closed.map((k,i)=>({time:n(k[0]),open:o[i],high:h[i],low:l[i],close:c[i],volume:v[i],rsi:rr[i]})),pivots:ps.slice(-24),events,zones:zs,trendlines:lines,divergences:divs,scenario:sc,disclaimer:'Educational market-structure visualization only. Not a trading signal.'})}catch(e){res.status(502).json({ok:false,error:e.message})}}
