const BASES=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];
const n=(v,f=0)=>{v=Number(v);return Number.isFinite(v)?v:f};
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
async function getJson(path,params={}){let last;const qs=new URLSearchParams(params).toString();for(const base of BASES){try{const r=await fetch(base+path+(qs?'?'+qs:''),{headers:{'User-Agent':'PulseRadar-Pro/3.12.1'}});const t=await r.text();if(!r.ok)throw Error(`Binance ${r.status}: ${t.slice(0,120)}`);return JSON.parse(t)}catch(e){last=e}}throw last||Error('Binance failed')}
function ema(a,p){const k=2/(p+1),o=[];let x=a[0]||0;for(let i=0;i<a.length;i++){x=i?a[i]*k+x*(1-k):a[i];o.push(x)}return o}
function sma(a,p){const o=Array(a.length).fill(null);let s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)o[i]=s/p}return o}
function rsi(a,p=14){const out=Array(a.length).fill(null);if(a.length<=p)return out;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;out[p]=l?100-100/(1+g/l):100;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;out[i]=l?100-100/(1+g/l):100}return out}
function atr(h,l,c,p=14){const tr=h.map((x,i)=>i?Math.max(x-l[i],Math.abs(x-c[i-1]),Math.abs(l[i]-c[i-1])):x-l[i]);return ema(tr,p)}
function confirmedPivots(h,l,left=3,right=3){const out=[];for(let i=left;i<h.length-right;i++){let ph=true,pl=true;for(let j=i-left;j<=i+right;j++){if(j===i)continue;if(h[j]>=h[i])ph=false;if(l[j]<=l[i])pl=false}if(ph)out.push({i,type:'H',price:h[i],status:'confirmed',left,right,confirmedAt:i+right});if(pl)out.push({i,type:'L',price:l[i],status:'confirmed',left,right,confirmedAt:i+right})}return out.sort((a,b)=>a.i-b.i)}
function provisionalPivots(h,l,left=3){const out=[];const start=Math.max(left,h.length-left-5);for(let i=start;i<h.length;i++){let ph=true,pl=true;for(let j=Math.max(0,i-left);j<i;j++){if(h[j]>=h[i])ph=false;if(l[j]<=l[i])pl=false}if(ph)out.push({i,type:'H',price:h[i],status:'provisional'});if(pl)out.push({i,type:'L',price:l[i],status:'provisional'})}return out.slice(-4)}
function classify(ps){let lastH=null,lastL=null;return ps.map(p=>{let label=p.type;if(p.type==='H'){label=lastH==null?'H':p.price>lastH?'HH':'LH';lastH=p.price}else{label=lastL==null?'L':p.price>lastL?'HL':'LL';lastL=p.price}return{...p,label}})}
function structureEvents(ps,c,v,vs,times){const e=[];let swingHigh=null,swingLow=null,trend='neutral';for(let i=0;i<c.length;i++){for(const p of ps.filter(x=>x.i===i)){if(p.type==='H')swingHigh=p.price;else swingLow=p.price}const vr=vs[i]?v[i]/vs[i]:null;if(swingHigh&&c[i]>swingHigh){const prev=trend;e.push({i,type:prev==='down'?'CHOCH':'BOS',dir:'up',level:swingHigh,breakPrice:c[i],confirmation:'close',confirmationTime:times[i],confirmed:true,volumeRatio:vr,retestStatus:'pending',barsSinceEvent:c.length-1-i});trend='up';swingHigh=null}if(swingLow&&c[i]<swingLow){const prev=trend;e.push({i,type:prev==='up'?'CHOCH':'BOS',dir:'down',level:swingLow,breakPrice:c[i],confirmation:'close',confirmationTime:times[i],confirmed:true,volumeRatio:vr,retestStatus:'pending',barsSinceEvent:c.length-1-i});trend='down';swingLow=null}}for(const ev of e){for(let j=ev.i+1;j<c.length;j++){const crossed=ev.dir==='up'?c[j]<ev.level:c[j]>ev.level;if(crossed){ev.retestStatus='failed';ev.retestTime=times[j];break}const near=Math.abs(c[j]-ev.level)/Math.max(ev.level,1e-12)<=.004;if(near){ev.retestStatus='tested';ev.retestTime=times[j]}}}return e.slice(-20)}
function divergence(ps,rr){const lows=ps.filter(x=>x.type==='L').slice(-8),highs=ps.filter(x=>x.type==='H').slice(-8),out=[];for(let k=1;k<lows.length;k++){const a=lows[k-1],b=lows[k];if(Number.isFinite(rr[a.i])&&Number.isFinite(rr[b.i])&&b.price<a.price&&rr[b.i]>rr[a.i]+2)out.push({type:'bullish',from:a.i,to:b.i,priceFrom:a.price,priceTo:b.price,rsiFrom:rr[a.i],rsiTo:rr[b.i],status:'confirmed'})}for(let k=1;k<highs.length;k++){const a=highs[k-1],b=highs[k];if(Number.isFinite(rr[a.i])&&Number.isFinite(rr[b.i])&&b.price>a.price&&rr[b.i]<rr[a.i]-2)out.push({type:'bearish',from:a.i,to:b.i,priceFrom:a.price,priceTo:b.price,rsiFrom:rr[a.i],rsiTo:rr[b.i],status:'confirmed'})}return out.slice(-6)}
function trendlines(ps){const hs=ps.filter(x=>x.type==='H').slice(-3),ls=ps.filter(x=>x.type==='L').slice(-3),line=a=>a.length>=2?{from:{i:a[0].i,price:a[0].price},to:{i:a.at(-1).i,price:a.at(-1).price},slope:(a.at(-1).price-a[0].price)/(a.at(-1).i-a[0].i||1),touches:a.length}:null;return{resistance:line(hs),support:line(ls)}}
function zones(ps,close,atrNow,currentIndex){const tol=Math.max(close*.0025,atrNow*.35),groups=[];for(const p of ps.slice(-30)){let g=groups.find(x=>Math.abs(x.center-p.price)<=tol);if(!g){g={center:p.price,values:[],pivots:[]};groups.push(g)}g.values.push(p.price);g.pivots.push(p);g.center=g.values.reduce((s,v)=>s+v,0)/g.values.length}return groups.map(g=>{const low=Math.min(...g.values)-tol*.45,high=Math.max(...g.values)+tol*.45,touches=g.values.length,lastI=Math.max(...g.pivots.map(p=>p.i)),age=Math.max(0,currentIndex-lastI),reaction=g.pivots.filter(p=>p.label==='HL'||p.label==='LH'||p.label==='HH'||p.label==='LL').length,strength=Math.round(clamp(touches*18+reaction*8-Math.min(age,80)*.25));return{type:g.center>=close?'resistance':'support',low,high,center:g.center,touchCount:touches,reactionCount:reaction,strengthScore:strength,source:'confirmed_swing_cluster',ageBars:age,zoneWidthAtr:atrNow?(high-low)/atrNow:null}}).filter(z=>z.touchCount>=2).sort((a,b)=>Math.abs(a.center-close)-Math.abs(b.center-close)).slice(0,8)}
function biasScore(ps,events,c,e20,e60){const recent=ps.slice(-8),parts=[];let score=0;const bull=recent.filter(p=>p.label==='HH'||p.label==='HL').length,bear=recent.filter(p=>p.label==='LH'||p.label==='LL').length;if(bull>bear){score+=2;parts.push({reason:'최근 HH/HL 우세',points:2})}else if(bear>bull){score-=2;parts.push({reason:'최근 LH/LL 우세',points:-2})}const ev=events.at(-1);if(ev?.dir==='up'){score+=2;parts.push({reason:`최근 ${ev.type} up`,points:2})}else if(ev?.dir==='down'){score-=2;parts.push({reason:`최근 ${ev.type} down`,points:-2})}const close=c.at(-1);if(close>e20.at(-1)){score+=1;parts.push({reason:'가격 > EMA20',points:1})}else{score-=1;parts.push({reason:'가격 < EMA20',points:-1})}if(e20.at(-1)>e60.at(-1)){score+=1;parts.push({reason:'EMA20 > EMA60',points:1})}else{score-=1;parts.push({reason:'EMA20 < EMA60',points:-1})}return{score,label:score>=4?'bullish':score<=-4?'bearish':score>0?'neutral-bullish':score<0?'neutral-bearish':'neutral',components:parts}}
function scenario(close,zs,events,ps,atrNow,interval){const res=zs.filter(z=>z.type==='resistance'&&z.center>close).sort((a,b)=>a.center-b.center),sup=zs.filter(z=>z.type==='support'&&z.center<close).sort((a,b)=>b.center-a.center),lastH=ps.filter(x=>x.type==='H').at(-1),lastL=ps.filter(x=>x.type==='L').at(-1),trigger=res[0]?.high||lastH?.price||null,invalidation=sup[0]?.low||lastL?.price||null;return{up:{trigger,confirmation:`${interval} 종가가 trigger 위에서 마감`,volumeCondition:'Volume/SMA20 >= 1.2 권장 확인',retestCondition:'이후 1~3개 봉에서 trigger 재이탈 여부 관찰',targetZones:res.slice(1,4).map(z=>({low:z.low,high:z.high,strength:z.strengthScore}))},down:{invalidation,confirmation:`${interval} 종가가 invalidation 아래에서 마감`,observationZones:sup.slice(1,4).map(z=>({low:z.low,high:z.high,strength:z.strengthScore}))},distance:{toTriggerPct:trigger?(trigger/close-1)*100:null,toInvalidationPct:invalidation?(close/invalidation-1)*100:null,toTriggerAtr:trigger&&atrNow?(trigger-close)/atrNow:null,toInvalidationAtr:invalidation&&atrNow?(close-invalidation)/atrNow:null},latestEvent:events.at(-1)||null}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=15, stale-while-revalidate=30');try{const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase(),interval=String(req.query.interval||'15m'),limit=Math.max(150,Math.min(500,n(req.query.limit,300)));const raw=await getJson('/api/v3/klines',{symbol,interval,limit:String(limit)}),closed=raw.filter(k=>n(k[6])<Date.now()),times=closed.map(k=>n(k[0])),o=closed.map(k=>n(k[1])),h=closed.map(k=>n(k[2])),l=closed.map(k=>n(k[3])),c=closed.map(k=>n(k[4])),v=closed.map(k=>n(k[5])),rr=rsi(c),aa=atr(h,l,c),vs=sma(v,20),e20=ema(c,20),e60=ema(c,60),ps=classify(confirmedPivots(h,l,3,3)),provisional=provisionalPivots(h,l,3),events=structureEvents(ps,c,v,vs,times),atrNow=aa.at(-1)||0,zs=zones(ps,c.at(-1),atrNow,c.length-1),divs=divergence(ps,rr),lines=trendlines(ps),bias=biasScore(ps,events,c,e20,e60),sc=scenario(c.at(-1),zs,events,ps,atrNow,interval);res.status(200).json({ok:true,version:'3.12.1',symbol,interval,pivotRule:{left:3,right:3,confirmedDelayBars:3},candles:closed.map((k,i)=>({time:times[i],open:o[i],high:h[i],low:l[i],close:c[i],volume:v[i],rsi:rr[i],atr:aa[i],volSma20:vs[i]})),pivots:ps.slice(-28),provisionalPivots:provisional,events,zones:zs,trendlines:lines,divergences:divs,bias,scenario:sc,current:{price:c.at(-1),atr14:atrNow,ema20:e20.at(-1),ema60:e60.at(-1)},disclaimer:'Educational market-structure visualization only. Conditional scenarios are not price predictions or trading signals.'})}catch(e){res.status(502).json({ok:false,error:e.message})}}
