const BASES=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];
const n=v=>Number(v)||0,avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
async function getJson(path,p={}){let last;const q=new URLSearchParams(p).toString();for(const b of BASES){try{const r=await fetch(b+path+'?'+q,{headers:{'User-Agent':'PulseRadar-Pro/3.13-Techniques'}}),t=await r.text();if(!r.ok)throw Error('Binance '+r.status);return JSON.parse(t)}catch(e){last=e}}throw last||Error('Binance failed')}
function ema(a,p){if(!a.length)return[];const k=2/(p+1),o=[];let x=a[0];for(let i=0;i<a.length;i++){x=i?a[i]*k+x*(1-k):a[i];o.push(x)}return o}
function sma(a,p){const o=Array(a.length).fill(null);let s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)o[i]=s/p}return o}
function rsi(a,p=14){const o=Array(a.length).fill(null);if(a.length<=p)return o;let g=0,l=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=p;l/=p;o[p]=l?100-100/(1+g/l):100;for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(p-1)+Math.max(d,0))/p;l=(l*(p-1)+Math.max(-d,0))/p;o[i]=l?100-100/(1+g/l):100}return o}
function atr(h,l,c,p=14){const tr=h.map((x,i)=>i?Math.max(x-l[i],Math.abs(x-c[i-1]),Math.abs(l[i]-c[i-1])):x-l[i]);return ema(tr,p)}
function pivots(h,l,left=3,right=3){const out=[];for(let i=left;i<h.length-right;i++){let ph=1,pl=1;for(let j=i-left;j<=i+right;j++){if(j===i)continue;if(h[j]>=h[i])ph=0;if(l[j]<=l[i])pl=0}if(ph)out.push({i,type:'H',price:h[i],confirmedAt:i+right});if(pl)out.push({i,type:'L',price:l[i],confirmedAt:i+right})}return out.sort((a,b)=>a.confirmedAt-b.confirmedAt||a.i-b.i)}
function canonical(raw){const s=[];for(const p of raw){if(!s.length||s.at(-1).type!==p.type){s.push({...p});continue}const q=s.at(-1),ext=p.type==='H'?p.price>q.price:p.price<q.price;if(ext)s[s.length-1]={...p}}let H=null,L=null;for(const x of s){if(x.type==='H'){x.label=H==null?'H':x.price>H?'HH':'LH';H=x.price}else{x.label=L==null?'L':x.price>L?'HL':'LL';L=x.price}}return s}
function zones(ps,close,av){const tol=Math.max(close*.0025,av*.35),g=[];for(const p of ps.slice(-50)){let x=g.find(z=>Math.abs(z.center-p.price)<=tol);if(!x){x={center:p.price,vals:[],points:[]};g.push(x)}x.vals.push(p.price);x.points.push(p);x.center=avg(x.vals)}return g.filter(x=>x.points.length>=2).map(x=>({low:Math.min(...x.vals)-tol*.35,high:Math.max(...x.vals)+tol*.35,center:x.center,touches:x.points.length,lastIndex:Math.max(...x.points.map(p=>p.i))})).sort((a,b)=>Math.abs(a.center-close)-Math.abs(b.center-close)).slice(0,6)}
function divergence(ps,rv){const lows=ps.filter(x=>x.type==='L'&&Number.isFinite(rv[x.i])).slice(-4),highs=ps.filter(x=>x.type==='H'&&Number.isFinite(rv[x.i])).slice(-4),out=[];if(lows.length>=2){const a=lows.at(-2),b=lows.at(-1);if(b.price<a.price&&rv[b.i]>rv[a.i]+1.5)out.push({type:'bullish',kind:'regular',from:a.i,to:b.i,priceA:a.price,priceB:b.price,rsiA:rv[a.i],rsiB:rv[b.i]})}if(highs.length>=2){const a=highs.at(-2),b=highs.at(-1);if(b.price>a.price&&rv[b.i]<rv[a.i]-1.5)out.push({type:'bearish',kind:'regular',from:a.i,to:b.i,priceA:a.price,priceB:b.price,rsiA:rv[a.i],rsiB:rv[b.i]})}return out}
function fvgs(h,l,c){const out=[];for(let i=Math.max(2,c.length-120);i<c.length;i++){if(l[i]>h[i-2]){let filled=false;for(let j=i+1;j<c.length;j++)if(l[j]<=h[i-2]){filled=true;break}if(!filled)out.push({type:'bullish',from:h[i-2],to:l[i],index:i,sizePct:(l[i]/h[i-2]-1)*100})}if(h[i]<l[i-2]){let filled=false;for(let j=i+1;j<c.length;j++)if(h[j]>=l[i-2]){filled=true;break}if(!filled)out.push({type:'bearish',from:h[i],to:l[i-2],index:i,sizePct:(l[i-2]/h[i]-1)*100})}}return out.slice(-5).reverse()}
function sweeps(ps,h,l,c){const out=[];for(const p of ps.slice(-20)){for(let i=p.confirmedAt+1;i<Math.min(c.length,p.i+45);i++){if(p.type==='H'&&h[i]>p.price&&c[i]<p.price){out.push({type:'high-sweep',pivot:p.price,index:i,close:c[i]});break}if(p.type==='L'&&l[i]<p.price&&c[i]>p.price){out.push({type:'low-sweep',pivot:p.price,index:i,close:c[i]});break}}}return out.slice(-5).reverse()}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','s-maxage=30, stale-while-revalidate=60');try{const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase(),interval=String(req.query.interval||'1h'),limit=Math.max(250,Math.min(1000,n(req.query.limit)||600)),raw=(await getJson('/api/v3/klines',{symbol,interval,limit:String(limit)})).filter(k=>n(k[6])<Date.now());if(raw.length<200)throw Error('Not enough closed candles');const t=raw.map(k=>n(k[0])),o=raw.map(k=>n(k[1])),h=raw.map(k=>n(k[2])),l=raw.map(k=>n(k[3])),c=raw.map(k=>n(k[4])),v=raw.map(k=>n(k[5])),tb=raw.map(k=>n(k[9])),i=c.length-1,rv=rsi(c),aa=atr(h,l,c),e20=ema(c,20),e60=ema(c,60),vs=sma(v,20),ps=pivots(h,l).filter(p=>p.confirmedAt<=i),sw=canonical(ps),lastH=[...sw].reverse().find(x=>x.type==='H'),lastL=[...sw].reverse().find(x=>x.type==='L'),range=lastH&&lastL?{high:lastH.price,low:lastL.price,mid:(lastH.price+lastL.price)/2}:null,position=range?(c[i]>range.mid?'premium':c[i]<range.mid?'discount':'equilibrium'):'unknown',zs=zones(ps,c[i],aa[i]),div=divergence(sw,rv),fg=fvgs(h,l,c),sq=sweeps(sw,h,l,c),volRatio=vs[i]?v[i]/vs[i]:null,buyRatio=v[i]?tb[i]/v[i]:null;let structure='neutral';const last4=sw.slice(-4).map(x=>x.label);if(last4.includes('HH')&&last4.includes('HL'))structure='bullish';if(last4.includes('LH')&&last4.includes('LL'))structure='bearish';let bull=0,bear=0,reasons=[];if(structure==='bullish'){bull+=2;reasons.push('Canonical HH/HL 구조')}if(structure==='bearish'){bear+=2;reasons.push('Canonical LH/LL 구조')}if(c[i]>e20[i]&&e20[i]>e60[i])bull++;if(c[i]<e20[i]&&e20[i]<e60[i])bear++;if(div.some(x=>x.type==='bullish'))bull+=2;if(div.some(x=>x.type==='bearish'))bear+=2;if(sq[0]?.type==='low-sweep')bull++;if(sq[0]?.type==='high-sweep')bear++;if(volRatio>1.5&&buyRatio>.55)bull++;if(volRatio>1.5&&buyRatio<.45)bear++;const bias=bull>bear+1?'bullish':bear>bull+1?'bearish':'mixed';res.status(200).json({ok:true,version:'3.13.0',symbol,interval,lastClosedTime:n(raw[i][6]),price:c[i],indicators:{rsi:rv[i],atr:aa[i],ema20:e20[i],ema60:e60[i],volumeRatio:volRatio,takerBuyRatio:buyRatio},marketStructure:{state:structure,lastSwings:sw.slice(-8)},supportResistance:{zones:zs.map(z=>({...z,side:z.center<c[i]?'support':'resistance'}))},rsiDivergence:div,fairValueGaps:fg,liquiditySweeps:sq,premiumDiscount:{position,range},confluence:{bias,bullPoints:bull,bearPoints:bear,reasons},audit:{closedCandlesOnly:true,pivotsConfirmedOnly:true,canonicalAlternating:sw.every((x,j)=>!j||x.type!==sw[j-1].type)},note:'Educational structure analysis only. Confirmation/observation tool; no order execution or profit prediction.'})}catch(e){res.status(502).json({ok:false,error:e.message})}}
