const BASES=['https://api.binance.com','https://api-gcp.binance.com','https://data-api.binance.vision'];
const n=v=>Number(v)||0,avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null,med=a=>{if(!a.length)return null;const x=[...a].sort((a,b)=>a-b),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2},pct=(a,b)=>b?((a/b)-1)*100:null;
async function getJson(path,params={}){let last;const qs=new URLSearchParams(params).toString();for(const base of BASES){try{const r=await fetch(base+path+(qs?'?'+qs:''),{headers:{'User-Agent':'PulseRadar-Pro/3.12.3-TLStudy'}});const t=await r.text();if(!r.ok)throw Error(`Binance ${r.status}`);return JSON.parse(t)}catch(e){last=e}}throw last||Error('Binance failed')}
async function paged(symbol,interval,bars){let out=[],end;while(out.length<bars){const lim=Math.min(1000,bars-out.length),p={symbol,interval,limit:String(lim)};if(end)p.endTime=String(end);const a=await getJson('/api/v3/klines',p);if(!a.length)break;out=a.concat(out);end=Number(a[0][0])-1;if(a.length<lim)break}const seen=new Set();return out.filter(k=>{const t=n(k[0]);if(seen.has(t))return false;seen.add(t);return true}).sort((a,b)=>n(a[0])-n(b[0])).slice(-bars)}
function ema(a,p){const k=2/(p+1),o=[];let x=a[0]||0;for(let i=0;i<a.length;i++){x=i?a[i]*k+x*(1-k):a[i];o.push(x)}return o}
function atr(h,l,c,p=14){const tr=h.map((x,i)=>i?Math.max(x-l[i],Math.abs(x-c[i-1]),Math.abs(l[i]-c[i-1])):x-l[i]);return ema(tr,p)}
function pivots(h,l,left=3,right=3){const out=[];for(let i=left;i<h.length-right;i++){let ph=true,pl=true;for(let j=i-left;j<=i+right;j++){if(j===i)continue;if(h[j]>=h[i])ph=false;if(l[j]<=l[i])pl=false}if(ph)out.push({i,type:'H',price:h[i],confirmedAt:i+right});if(pl)out.push({i,type:'L',price:l[i],confirmedAt:i+right})}return out.sort((a,b)=>a.confirmedAt-b.confirmedAt)}
function fit(points){if(points.length<2)return null;const mx=avg(points.map(x=>x.i)),my=avg(points.map(x=>x.price));let a=0,b=0;for(const p of points){a+=(p.i-mx)*(p.price-my);b+=(p.i-mx)*(p.i-mx)}const slope=b?a/b:0;return{slope,intercept:my-slope*mx}}
const at=(L,i)=>L.intercept+L.slope*i;
function bestLine(ps,side,i,c,o,h,l,aa){const target=ps.filter(p=>p.confirmedAt<=i&&(side==='support'?p.type==='L':p.type==='H')).slice(-12);if(target.length<3)return null;let best=null;for(let a=0;a<target.length-1;a++)for(let b=a+1;b<target.length;b++){const A=target[a],B=target[b];if(B.i-A.i<8)continue;const m=(B.price-A.price)/(B.i-A.i),raw={slope:m,intercept:A.price-m*A.i};let touch=target.filter(p=>p.i>=A.i&&Math.abs(p.price-at(raw,p.i))<=Math.max(p.price*.002,(aa[p.i]||aa[i]||0)*.30));if(touch.length<3)continue;let L=fit(touch);touch=target.filter(p=>p.i>=A.i&&Math.abs(p.price-at(L,p.i))<=Math.max(p.price*.002,(aa[p.i]||aa[i]||0)*.30));if(touch.length<3)continue;L=fit(touch);const lastTouch=Math.max(...touch.map(x=>x.i)),span=lastTouch-Math.min(...touch.map(x=>x.i));if(i-lastTouch>40)continue;let bodyCross=0;for(let z=Math.max(B.i,0);z<=i;z++){const lp=at(L,z),lo=Math.min(o[z],c[z]),hi=Math.max(o[z],c[z]);if(lp>lo&&lp<hi)bodyCross++}const score=Math.min(40,touch.length*10)+Math.max(0,20-(i-lastTouch)*.5)+Math.min(20,span*.25)-bodyCross*2;if(!best||score>best.score)best={...L,score,touchCount:touch.length,lastTouch,side,id:`${side}-${touch[0].i}-${lastTouch}`}}return best}
function summary(a){return{n:a.length,mean:avg(a),median:med(a),positiveRate:a.length?a.filter(x=>x>0).length/a.length*100:null,min:a.length?Math.min(...a):null,max:a.length?Math.max(...a):null}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','s-maxage=60, stale-while-revalidate=120');try{const symbol=String(req.query.symbol||'BTCUSDT').toUpperCase(),interval=String(req.query.interval||'1h'),bars=Math.max(1500,Math.min(5000,n(req.query.bars)||3000)),raw=await paged(symbol,interval,bars);if(raw.length<300)throw Error('Not enough history');const t=raw.map(k=>n(k[0])),o=raw.map(k=>n(k[1])),h=raw.map(k=>n(k[2])),l=raw.map(k=>n(k[3])),c=raw.map(k=>n(k[4])),aa=atr(h,l,c),ps=pivots(h,l,3,3),events=[],lastEvent=new Map();for(let i=120;i<raw.length-41;i++){for(const side of ['support','resistance']){const L=bestLine(ps,side,i,c,o,h,l,aa);if(!L||L.score<60)continue;const lp=at(L,i),atrv=aa[i]||0;if(!atrv)continue;const dist=(c[i]-lp)/atrv,key=`${side}-${L.id}`;let kind=null,dir=1;if(Math.abs(dist)<=.30){kind=side==='support'?'TL_SUPPORT_RETEST':'TL_RESISTANCE_RETEST';dir=side==='support'?1:-1}else if(i>=1){const prev=(c[i-1]-at(L,i-1))/(aa[i-1]||atrv);if(side==='support'&&dist<-.50&&prev<-.50){kind='TL_SUPPORT_BREAK';dir=-1}else if(side==='resistance'&&dist>.50&&prev>.50){kind='TL_RESISTANCE_BREAK';dir=1}}if(!kind)continue;const lk=kind+'-'+L.id;if(i-(lastEvent.get(lk)||-999)<8)continue;lastEvent.set(lk,i);events.push({kind,dir,i,time:t[i],level:lp,score:Math.round(L.score),touchCount:L.touchCount,distanceAtr:dist})}}
const enriched=[];for(const e of events){const entry=o[e.i+1];if(!entry||e.i+40>=raw.length)continue;let maxH=-Infinity,minL=Infinity;for(let z=e.i+1;z<=e.i+40;z++){maxH=Math.max(maxH,h[z]);minL=Math.min(minL,l[z])}const ret=x=>e.dir*pct(c[e.i+x],entry);enriched.push({...e,entry,r10:ret(10),r20:ret(20),r40:ret(40),mfe40:e.dir===1?pct(maxH,entry):-pct(minL,entry),mae40:e.dir===1?pct(minL,entry):-pct(maxH,entry)})}const kinds=['TL_SUPPORT_RETEST','TL_RESISTANCE_RETEST','TL_SUPPORT_BREAK','TL_RESISTANCE_BREAK'],stats=kinds.map(kind=>{const a=enriched.filter(x=>x.kind===kind);return{kind,n:a.length,r10:summary(a.map(x=>x.r10).filter(Number.isFinite)),r20:summary(a.map(x=>x.r20).filter(Number.isFinite)),r40:summary(a.map(x=>x.r40).filter(Number.isFinite)),mfe40:summary(a.map(x=>x.mfe40).filter(Number.isFinite)),mae40:summary(a.map(x=>x.mae40).filter(Number.isFinite)),avgScore:avg(a.map(x=>x.score)),avgTouches:avg(a.map(x=>x.touchCount))}});res.status(200).json({ok:true,version:'3.12.3',symbol,interval,historyBars:raw.length,trendlineRule:'confirmed pivots only; min gap 8; >=3 touches; ATR .30 touch; score >=60; break ATR .50 for 2 closes',entryReference:'next candle open',note:'Educational event study. No TP/SL or execution simulation.',stats,events:enriched.slice(-120).reverse()})}catch(e){res.status(502).json({ok:false,error:e.message})}}
