'use strict';

const SAMPLE_LIBRARY=Object.freeze([
  {name:'ONE',label:'ONE · XOI/BSL 재공격형',expected:{archetype:['X','X+B','X+A','X+A+B'],sweep:['BSL_PROBE_REATTACK','DOUBLE_SWEEP'],time15:['ABSORPTION_TIME','LONG_REBUILD'],time1h:['FAST_RECLAIM','TIME_SYMMETRY'],xoi:true,takerExtreme:true}},
  {name:'CELR',label:'CELR · taker 장기잠복형',expected:{archetype:['B','X+B'],sweep:['NO_SWEEP_COMPRESSION','BSL_PROBE_REATTACK'],time15:['TIME_SYMMETRY','ABSORPTION_TIME'],time1h:['TIME_SYMMETRY','LONG_REBUILD'],takerExtreme:true}},
  {name:'AKE',label:'AKE · 청소→재구축 FAST형',expected:{archetype:['C','A+B','X+A+B'],sweep:['BSL_PROBE_REATTACK','FAILED_BREAK_REBUILD'],time15:['FAST_RECLAIM'],time1h:['LONG_REBUILD'],reset:['15M_RESET_5M_REIGNITION','HTF_RESET_LTF_REIGNITION','RESET_WAIT'],cleanup:true}},
  {name:'MYX',label:'MYX · OI 선행 흡수형',expected:{archetype:['A','A+B'],sweep:['BSL_PROBE_REATTACK','NO_SWEEP_COMPRESSION'],time15:['FAST_RECLAIM','TIME_SYMMETRY'],time1h:['ABSORPTION_TIME'],reset:['HTF_RESET_LTF_REIGNITION','15M_RESET_5M_REIGNITION'],takerExtreme:false}},
  {name:'XTZ',label:'XTZ · XOI+양방향 청소형',expected:{archetype:['X+B','X+A+B'],sweep:['DOUBLE_SWEEP','FAILED_BREAK_REBUILD'],time15:['FAST_RECLAIM'],time1h:['ABSORPTION_TIME'],xoi:true,takerExtreme:true}},
  {name:'CETUS',label:'CETUS · 하위완전청소→OI rebuild',expected:{archetype:['C','A+B'],sweep:['SSL_SWEEP_RECLAIM','DOUBLE_SWEEP','NO_SWEEP_COMPRESSION'],time15:['FAST_RECLAIM'],time1h:['LONG_REBUILD'],reset:['RESET_WAIT','15M_RESET_5M_REIGNITION'],cleanup:true}},
  {name:'TAG',label:'TAG · RVOL 선행 BSL 잠복형',expected:{archetype:['B','A+B'],sweep:['BSL_PROBE_REATTACK'],time15:['ABSORPTION_TIME'],time1h:['ABSORPTION_TIME','LONG_REBUILD'],takerExtreme:true}},
  {name:'THETA',label:'THETA · 양방향 청소→재구축형',expected:{archetype:['C','A+B'],sweep:['DOUBLE_SWEEP','FAILED_BREAK_REBUILD'],time15:['ABSORPTION_TIME'],time1h:['FAST_RECLAIM'],reset:['HTF_RESET_LTF_REIGNITION','15M_RESET_5M_REIGNITION'],cleanup:true}},
  {name:'PIEVERSE',label:'PIEVERSE · SSL+15m 리셋 FAST형',expected:{archetype:['A','B','C','NEUTRAL'],sweep:['SSL_SWEEP_RECLAIM'],time15:['FAST_RECLAIM'],time1h:['LONG_REBUILD'],reset:['15M_RESET_5M_REIGNITION','RESET_WAIT']}},
  {name:'MORPHO',label:'MORPHO · OI 선행 시간흡수형',expected:{archetype:['A','A+B','X+A'],sweep:['BSL_PROBE_REATTACK','NO_SWEEP_COMPRESSION'],time15:['ABSORPTION_TIME'],time1h:['TIME_SYMMETRY'],xoi:false}},
  {name:'PORTAL',label:'PORTAL · 정대칭 taker 잠복형',expected:{archetype:['B','C'],sweep:['NO_SWEEP_COMPRESSION','BSL_PROBE_REATTACK'],time15:['TIME_SYMMETRY'],time1h:['ABSORPTION_TIME'],reset:['RESET_WAIT','15M_RESET_5M_REIGNITION'],takerExtreme:true}},
  {name:'ESP',label:'ESP · cleanup→FAST squeeze형',expected:{archetype:['C','B','A+B'],sweep:['BSL_PROBE_REATTACK','SSL_SWEEP_RECLAIM','DOUBLE_SWEEP'],time15:['FAST_RECLAIM'],time1h:['ABSORPTION_TIME'],reset:['15M_RESET_5M_REIGNITION','HTF_RESET_LTF_REIGNITION'],cleanup:true,takerExtreme:true}},
  {name:'T',label:'T · MA압축→거래량→OI 구축형',expected:{archetype:['A','A+B','B'],maCluster:['TIGHT','NEAR'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','CLEAN_REBUILD'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED']}},
  {name:'JTO',label:'JTO · 리셋 하락봉 흡수형',expected:{archetype:['B','C','A+B'],reset:['RESET_WAIT','15M_RESET_5M_REIGNITION','HTF_RESET_LTF_REIGNITION'],maCluster:['TIGHT','NEAR'],volumeStage:['ABSORPTION','IGNITION'],flowType:['ABSORPTION','CLEAN_REBUILD']}},
  {name:'SKL',label:'SKL · 재압축→거래량 가속→OI형',expected:{archetype:['A','A+B','B'],maCluster:['TIGHT','NEAR'],volumeStage:['IGNITION','PRE_SPARK'],flowType:['DIRECT_BUILD','CLEAN_REBUILD'],takerExtreme:true}},
  {name:'ONG',label:'ONG · 15m 이평압축 선행점화형',expected:{archetype:['B','A+B','A'],maCluster:['TIGHT','NEAR'],volumeStage:['IGNITION','PRE_SPARK'],flowType:['DIRECT_BUILD','PRICE_LED','OBSERVE']}},
  {name:'GUN',label:'GUN · 4H 선행 이평전환형',expected:{archetype:['A','A+B','B'],maCluster:['TIGHT','NEAR'],volumeStage:['IGNITION','PRE_SPARK'],flowType:['DIRECT_BUILD','CLEAN_REBUILD'],htfTransition:['LTF_LEADS_HTF']}},
  {name:'BANK',label:'BANK · 장기선 압축 흡수/돌파형',expected:{archetype:['B','C','A+B'],maCluster:['TIGHT','NEAR'],volumeStage:['ABSORPTION','IGNITION'],flowType:['ABSORPTION','CLEAN_REBUILD','DIRECT_BUILD'],htfTransition:['LTF_LEADS_HTF','BASE_BUILD']}},
  {name:'CTSI',label:'CTSI · 멀티TF 이평압축 점화형',expected:{archetype:['A','A+B','B'],maCluster:['TIGHT','NEAR'],volumeStage:['IGNITION','PRE_SPARK'],flowType:['DIRECT_BUILD','CLEAN_REBUILD'],htfTransition:['HTF_ALIGNED','LTF_LEADS_HTF']}},
  {name:'ZIL',label:'ZIL · 3D/1D 전환 후 4H 점화형',expected:{archetype:['A','A+B','B'],maCluster:['TIGHT','NEAR'],volumeStage:['IGNITION','PRE_SPARK'],flowType:['DIRECT_BUILD','CLEAN_REBUILD'],htfTransition:['HTF_ALIGNED']}},
  {name:'PTB',label:'PTB · OI-led BUILD→RELOAD→REIGNITION형',expected:{archetype:['A','A+B','B'],maCluster:['TIGHT','NEAR','WIDE'],volumeStage:['IGNITION','EXPANSION','PRE_SPARK'],flowType:['DIRECT_BUILD','OBSERVE','ABSORPTION'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED'],takerExtreme:false}},
  {name:'ZETA',label:'ZETA · FLOW-led BUILD→직접 OI 확장형',expected:{archetype:['B','A+B','A'],maCluster:['TIGHT','NEAR','WIDE'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['PRICE_LED','DIRECT_BUILD','OBSERVE'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED'],takerExtreme:true}},
  {name:'PHA',label:'PHA · 구조돌파+OI 감소 숏커버 가속형',expected:{archetype:['B','A+B','C'],volumeStage:['IGNITION','EXPANSION'],flowType:['PRICE_LED','SQUEEZE','ABSORPTION'],htfTransition:['HTF_ALIGNED','LTF_LEADS_HTF']}},
  {name:'UAI',label:'UAI · 4H 돌파→1H 정렬 기술적 계단점화형',expected:{archetype:['A','A+B','B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['PRICE_LED','DIRECT_BUILD'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED']}},
  {name:'KMNO',label:'KMNO · 과매도 대량체결 흡수/SSL 스윕형',expected:{archetype:['C','B','A+B'],sweep:['SSL_SWEEP_RECLAIM','FAILED_BREAK_REBUILD','DOUBLE_SWEEP'],volumeStage:['ABSORPTION','IGNITION'],flowType:['ABSORPTION','CLEAN_REBUILD'],cleanup:true}},
  {name:'SEI',label:'SEI · OI 감소→taker 반전 디레버리징형',expected:{archetype:['C','B','A+B'],sweep:['SSL_SWEEP_RECLAIM','FAILED_BREAK_REBUILD'],volumeStage:['ABSORPTION','PRE_SPARK'],flowType:['SQUEEZE','ABSORPTION','CLEAN_REBUILD'],cleanup:true}},
  {name:'DRIFT',label:'DRIFT · 15m 거래량 폭발→눌림→OI 후행 재증가형',expected:{archetype:['A','A+B','B'],volumeStage:['IGNITION','PRE_SPARK'],flowType:['DIRECT_BUILD','CLEAN_REBUILD'],reset:['15M_RESET_5M_REIGNITION','RESET_WAIT']}},
  {name:'STRK',label:'STRK · 계단식 거래량 가속형',expected:{archetype:['A','A+B','B'],volumeStage:['PRE_SPARK','IGNITION'],maCluster:['TIGHT','NEAR'],flowType:['DIRECT_BUILD','OBSERVE']}},
  {name:'APT',label:'APT · 1차 점프 후 상단 유지형',expected:{archetype:['A+B','B','A'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],sweep:['NO_SWEEP_COMPRESSION','BSL_PROBE_REATTACK']}},
  {name:'WLD',label:'WLD · 1차 점프 후 상단 유지형',expected:{archetype:['A+B','B','A'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],sweep:['NO_SWEEP_COMPRESSION','BSL_PROBE_REATTACK']}},
  {name:'TIA',label:'TIA · 4H 계단식 추세 확장형',expected:{archetype:['A','A+B','B'],htfTransition:['HTF_ALIGNED','LTF_LEADS_HTF'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE']}},
  {name:'DYDX',label:'DYDX · 4H 계단식 추세 확장형',expected:{archetype:['A','A+B','B'],htfTransition:['HTF_ALIGNED','LTF_LEADS_HTF'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE']}},
  {name:'ZK',label:'ZK · 4H 계단식 추세 확장형',expected:{archetype:['A','A+B','B'],htfTransition:['HTF_ALIGNED','LTF_LEADS_HTF'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE']}},
  {name:'ETHFI',label:'ETHFI · 거래량 재가속 연속돌파형',expected:{archetype:['A+B','B'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],sweep:['BSL_PROBE_REATTACK','NO_SWEEP_COMPRESSION']}},
  {name:'SKY',label:'SKY · 거래량 재가속 연속돌파형',expected:{archetype:['A+B','B'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],sweep:['BSL_PROBE_REATTACK','NO_SWEEP_COMPRESSION']}},
  {name:'OP',label:'OP · 1차 급등 후 눌림 유지형',expected:{archetype:['A','B','C','A+B'],reset:['RESET_WAIT','15M_RESET_5M_REIGNITION'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['CLEAN_REBUILD','OBSERVE','DIRECT_BUILD']}},
  {name:'DOT',label:'DOT · 완만한 추세 확장형',expected:{archetype:['A','A+B'],htfTransition:['HTF_ALIGNED'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE']}},
  {name:'SUI',label:'SUI · 완만한 추세 확장형',expected:{archetype:['A','A+B'],htfTransition:['HTF_ALIGNED'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE']}},
  {name:'TAO',label:'TAO · 완만한 추세 확장형',expected:{archetype:['A','A+B'],htfTransition:['HTF_ALIGNED'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE']}},
  {name:'PENDLE',label:'PENDLE · 완만한 추세 확장형',expected:{archetype:['A','A+B'],htfTransition:['HTF_ALIGNED'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE']}},
  {name:'LSK',label:'LSK · 스윕 후 재구성형',expected:{archetype:['C','A','A+B'],sweep:['FAILED_BREAK_REBUILD','DOUBLE_SWEEP','SSL_SWEEP_RECLAIM'],reset:['RESET_WAIT','15M_RESET_5M_REIGNITION'],flowType:['CLEAN_REBUILD','ABSORPTION']}},
  {name:'BOME',label:'BOME · 상단 재압축 점화형',expected:{archetype:['A','A+B','B'],sweep:['NO_SWEEP_COMPRESSION','BSL_PROBE_REATTACK'],maCluster:['TIGHT','NEAR'],volumeStage:['PRE_SPARK','IGNITION']}},
  {name:'BOME-20260924',label:'BOME 2026-09-24 · 매도흡수→테이커 반전→저항돌파형',expected:{archetype:['A','A+B','B'],sweep:['SSL_SWEEP_RECLAIM','BSL_PROBE_REATTACK','FAILED_BREAK_REBUILD'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['ABSORPTION','DIRECT_BUILD','PRICE_LED'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED'],takerExtreme:true},observed:{sampledAt:'2026-09-24',source:'Binance spot + USDT perpetual',research:'research/surge-samples/BOME-2026-09-24-absorption-taker-reversal-breakout.md',dna:'BOME_ABSORPTION_TAKER_REVERSAL_BREAKOUT',t0:'2026-09-24T05:00:00Z',t0BarPct:5.68,t0Rvol20:5.03,breakoutLevel:0.0011567,t0Close:0.0011879,pre24hPricePct:0.46,pre24hOiPct:-4.79,pre24hTakerAvg:0.898,pre6hPricePct:9.66,pre6hOiPct:16.61,pre6hTakerAvg:0.916,first15mIgnition:'2026-09-24T02:15:00Z',first15mPct:3.37,first15mRvol:4.56,absorptionTakerLow:0.4899,takerCascade:[1.0759,1.2614,1.1547,1.4722,1.3447],spotConfirmed:true,btcRelativeStrength:true,postIgnitionOi6hPct:30.96,postIgnitionTaker6h:0.926,stage:'상승확장+상승함정감시',scannerRule:'이전 유동성 청소/회수 후 15m RVOL>=3, spot 동행, taker<=1인데 가격 유지/상승이면 흡수 후보; 이후 taker가 여러 구간 연속 1 이상으로 전환되고 저항을 종가 돌파하면 점화 확인',note:'초기에는 매도체결 우위에도 가격이 버티며 흡수했고 이후 taker가 순차적으로 1 이상으로 전환되며 현물과 함께 저항을 종가 돌파했다. 급등 후 OI 과밀은 별도의 상승함정 위험 상태로 분리한다.'}},
  {name:'EPIC-20260918',label:'EPIC 2026-09-18 · 현물동반 OI 선행 돌파형',expected:{archetype:['A','A+B','B'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],htfTransition:['HTF_ALIGNED'],takerExtreme:false},observed:{sampledAt:'2026-09-18',source:'Binance spot + USDT perpetual',research:'research/surge-samples/EPIC-2026-09-18-spot-supported-oi-lead.md',dna:'SPOT_SUPPORTED_OI_LEAD',t0:'2026-09-18T19:00:00Z',max24hPct:39.51,pre24hPricePct:8.94,pre24hOiPct:17.41,pre24hTakerAvg:1.046,pre6hPricePct:5.80,pre6hOiPct:13.43,pre6hTakerAvg:0.949,h4Rsi:92.4,h4Rvol:7.89,spotSupported:true,basisT0Pct:-0.028,stage:'돌파확인',scannerRule:'가격 진행 전에 OI 누적 + 현물 참여 증가 + basis 중립/할인 + HTF 거래량 돌파를 확인하는 OI 선행 경로'}},
  {name:'FARTCOIN-20260920',label:'FARTCOIN 2026-09-20 · 외부현물 선행 후보형',expected:{archetype:['B','A+B','A'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['PRICE_LED','OBSERVE'],htfTransition:['LTF_LEADS_HTF']},observed:{sampledAt:'2026-09-20',source:'Binance futures + index proxy',research:'research/surge-samples/FARTCOIN-2026-09-20-external-spot-led.md',dna:'EXTERNAL_SPOT_LEAD_CANDIDATE',t0:'2026-09-20T15:00:00Z',max24hPct:19.19,pre24hPricePct:3.10,pre24hOiPct:-3.95,pre24hTakerAvg:0.963,pre6hPricePct:1.22,pre6hOiPct:-0.66,pre6hTakerAvg:0.950,m15Rvol:2.40,m5Rvol:2.16,binanceSpotAvailable:false,stage:'점화초기',scannerRule:'Binance 선물 OI/taker 선행이 약해도 LTF 거래량 점화와 basis 비과열이면 외부 현물 교차검증 경로로 넘긴다',note:'외부 현물 선행은 후보 가설이며 거래소별 타임스탬프 현물 데이터가 없으면 확정하지 않는다.'}},
  {name:'FF-20260922',label:'FF 2026-09-22 · 미결제약정 청소→테이커 반전 점화형',expected:{archetype:['C','A','A+B'],reset:['RESET_WAIT','HTF_RESET_LTF_REIGNITION'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['CLEAN_REBUILD','PRICE_LED','SQUEEZE'],htfTransition:['LTF_LEADS_HTF'],takerExtreme:true},observed:{sampledAt:'2026-09-22',source:'Binance USDT perpetual',research:'research/surge-samples/FF-2026-09-22-deleveraging-ignition.md',dna:'DELEVERAGING_IGNITION',historicalT0:'2026-09-19T21:00:00Z',historical24hCloseMovePct:45.1,pre24hPricePct:-0.90,pre24hOiPct:-0.37,pre6hPricePct:0.05,pre6hOiPct:-1.55,pre6hTakerAvg:1.085,takerSequence:[0.6143,1.1781,1.2103,1.4682],oiRole:'점화 전 청소/정체, 점화 후 후행 증가',stage:'청소→점화',scannerRule:'OI 하락을 자동 탈락시키지 말고 가격 저점 안정+거래량 고갈+taker 반전 속도+종가 유동성 돌파+후행 OI 재증가를 별도 경로로 평가'}},
  {name:'FIL-20260922',label:'FIL 2026-09-22 · OI 선행→테이커 전파→유동성 돌파 감시형',expected:{archetype:['A-pre','A','A+B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED'],takerExtreme:true},observed:{sampledAt:'2026-09-22',source:'Binance USDT perpetual',research:'research/surge-samples/FIL-2026-09-22-oi-lead-taker-cascade.md',dna:'OI_LEAD_TAKER_CASCADE_LIQUIDITY_BREAK',outcome:'PENDING',oi5mPct:0.16,oi15mPct:4.45,oi1hPct:10.63,oi4hPct:9.49,taker5m:1.5156,taker15m:0.9040,taker1h:0.9698,firstLiquidity:0.9961,bosLevel:1.0166,invalidation:0.9437,stage:'점화감시',scannerRule:'가격 압축 대비 OI 가속이 선행하면 5m→15m→1H taker 전파와 종가 기준 유동성/BOS 돌파를 기다린다. 5m 단일 스파이크만으로 확정하지 않는다.'}},
  {name:'INTW-20260920',label:'INTW 2026-09-20 · 레버리지 청소→테이커 유지→5m 점화형',expected:{archetype:['C','A','A+B'],reset:['HTF_RESET_LTF_REIGNITION','15M_RESET_5M_REIGNITION'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['CLEAN_REBUILD','SQUEEZE','PRICE_LED'],htfTransition:['LTF_LEADS_HTF'],takerExtreme:true},observed:{sampledAt:'2026-09-20',source:'Binance futures + index proxy',research:'research/surge-samples/INTW-2026-09-20-futures-chase.md',dna:'DELEVERAGING_IGNITION_FUTURES_CHASE',t0:'2026-09-20T15:00:00Z',max24hPct:24.29,pre72hOiPct:-25.84,pre24hPricePct:3.13,pre24hOiPct:2.99,pre24hTakerAvg:1.201,pre6hPricePct:0.71,pre6hOiPct:-0.09,pre6hTakerAvg:1.306,m5Rvol:5.92,m15Rvol:1.36,stage:'점화초기',scannerRule:'큰 OI 청소 이후 taker가 1 이상 유지되고 OI가 안정화된 상태에서 5m RVOL 급증과 가격 점화가 나오면 재점화 경로로 승격'}},
  {name:'OPG-20260920',label:'OPG 2026-09-20 · 약한 캔들 속 테이커 흡수→점화형',expected:{archetype:['C','A','A+B'],reset:['RESET_WAIT','HTF_RESET_LTF_REIGNITION'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['ABSORPTION','CLEAN_REBUILD','DIRECT_BUILD'],htfTransition:['HTF_ALIGNED','LTF_LEADS_HTF'],takerExtreme:true},observed:{sampledAt:'2026-09-20',source:'Binance spot + USDT perpetual',research:'research/surge-samples/OPG-2026-09-20-taker-absorption.md',dna:'TAKER_ABSORPTION_IGNITION',t0:'2026-09-20T08:00:00Z',max24hPct:25.38,pre24hPricePct:0.36,pre24hOiPct:3.94,pre24hTakerAvg:1.082,pre6hPricePct:-1.42,pre6hOiPct:-1.18,pre6hTakerAvg:1.287,h4Rsi:66.2,h1Rsi:39.1,h1Rvol:2.01,stage:'기초흡수→점화',scannerRule:'즉시 캔들이 약해도 HTF 구조 유지 + 다시간 taker>1 가속 + OI 평탄화면 탈락시키지 말고 reclaim/MSS/BOS를 기다린다'}},
  {name:'PEPE-20260920',label:'PEPE 2026-09-20 · OI 구축→청소→현물지지→테이커 반전형',expected:{archetype:['A','A+B','B','C'],sweep:['SSL_SWEEP_RECLAIM','FAILED_BREAK_REBUILD'],reset:['HTF_RESET_LTF_REIGNITION','15M_RESET_5M_REIGNITION'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','CLEAN_REBUILD','PRICE_LED'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED'],takerExtreme:true},observed:{sampledAt:'2026-09-20',source:'Binance spot + USDT perpetual',research:'research/surge-samples/PEPE-2026-09-20-build-flush-spot-supported-ignition.md',dna:'OI_BUILD_FLUSH_SPOT_SUPPORTED_IGNITION',t0:'2026-09-20T15:00:00Z',max24hPct:28.70,oi72h:63964967.76,oi12h:87912152.44,oiT0:81158557.50,takerSequence:[1.5525,0.9333,1.4096,0.8014,1.4352],m5Rvol:2.73,m15Rvol:2.72,m5BuySharePct:64,m15BuySharePct:60,basisT0Pct:-0.124,spotSupported:true,fundingReset:true,stage:'청소후 점화',scannerRule:'HTF 유지 + 24~72H OI 구축 + 최근 3~12H OI 청소 + basis 중립/할인 + taker <1→>1.2 반전 + 5m/15m RVOL>=2 + 매수비중>=60%이면 고가치 점화 후보'}},
  {name:'PEPE',label:'PEPE · 밈 대확장/재점화 샘플',expected:{archetype:['A+B','B','A'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED','SQUEEZE']}},
  {name:'DOGE',label:'DOGE · 밈 대확장/재점화 샘플',expected:{archetype:['A+B','B','A'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED','SQUEEZE']}},
  {name:'BONK',label:'BONK · 밈 대확장/재점화 샘플',expected:{archetype:['A+B','B','A'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED','SQUEEZE']}},
  {name:'SHIB',label:'SHIB · 밈 대확장/재점화 샘플',expected:{archetype:['A+B','B','A'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED','SQUEEZE']}},
  {name:'XLM',label:'XLM · 스윙형 OI 선행축적 샘플',expected:{archetype:['A','A+B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE'],htfTransition:['HTF_ALIGNED','LTF_LEADS_HTF']}},
  {name:'NIL',label:'NIL · OI+taker 동시 선행→RVOL 점화형',expected:{archetype:['A','A+B','B'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED'],takerExtreme:true},observed:{sampledAt:'2026-09-23',source:'Binance USDT perpetual',dna:'NIL_OI_TAKER_PRE_SURGE',pre6hPricePct:3.19,pre6hOiPct:1.70,pre6hTakerAvg:1.31,t0BarPct:10.79,t0Rvol:9.52,note:'가격이 크게 움직이기 전 OI와 taker가 함께 선행한 정석 PRE-SURGE 샘플'}},
  {name:'CHR',label:'CHR · taker 선행→초대형 RVOL 점화형',expected:{archetype:['B','A+B','A'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['PRICE_LED','SQUEEZE','DIRECT_BUILD'],htfTransition:['LTF_LEADS_HTF'],takerExtreme:true},observed:{sampledAt:'2026-09-23',source:'Binance USDT perpetual',dna:'CHR_TAKER_VOLUME_IGNITION',pre3hPricePct:3.14,pre3hOiPct:-0.12,pre3hTakerAvg:1.39,pre24hOiPct:-2.65,t0BarPct:4.43,t0Rvol:28.90,note:'OI 비선행/감소 상태에서 taker가 먼저 강해지고 초대형 RVOL이 점화한 샘플'}},
  {name:'MET',label:'MET · 장기 taker 선행+OI 감소 돌파형',expected:{archetype:['B','C','A+B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['PRICE_LED','SQUEEZE','ABSORPTION'],htfTransition:['LTF_LEADS_HTF'],takerExtreme:true},observed:{sampledAt:'2026-09-23',source:'Binance USDT perpetual',dna:'MET_FLOW_DELEVERAGING_IGNITION',pre12hPricePct:-0.54,pre12hOiPct:-1.64,pre12hTakerAvg:1.32,pre24hTakerAvg:1.39,t0BarPct:4.92,t0Rvol:3.79,note:'OI가 줄어드는 동안 taker 매수 우위가 오래 선행한 뒤 거래량과 가격이 점화'}},
  {name:'4',label:'4 · 매도압력 흡수+OI 잠복 BUILD형',expected:{archetype:['C','A','A+B'],volumeStage:['ABSORPTION','PRE_SPARK','IGNITION'],flowType:['ABSORPTION','CLEAN_REBUILD','DIRECT_BUILD'],sweep:['NO_SWEEP_COMPRESSION','FAILED_BREAK_REBUILD'],cleanup:true},observed:{sampledAt:'2026-09-23',source:'Binance USDT perpetual',dna:'SELL_ABSORPTION_OI_BUILD',pre24hPricePct:0.31,pre24hOiPct:0.93,pre24hTakerAvg:0.85,t0BarPct:3.36,t0Rvol:3.69,note:'공격적 매도 우위에도 가격이 버티고 OI가 증가한 뒤 점화한 흡수형 샘플'}},
  {name:'SUPER',label:'SUPER · TAKE-lite taker 선행 점화형',expected:{archetype:['B','A+B','A'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['PRICE_LED','DIRECT_BUILD'],htfTransition:['LTF_LEADS_HTF'],takerExtreme:true},observed:{sampledAt:'2026-09-23',source:'Binance USDT perpetual',dna:'SUPER_TAKER_PRESPARK',pre3hPricePct:0.93,pre3hOiPct:-0.38,pre3hTakerAvg:1.23,t0BarPct:4.68,t0Rvol:5.55,note:'가격은 조용하고 OI는 비선행인 상태에서 taker가 먼저 강화된 TAKE-lite 샘플'}},
  {name:'TAKE',label:'TAKE · taker 선행 압축→RVOL/BOS→OI 후행확장형',expected:{archetype:['A','A+B','B'],sweep:['NO_SWEEP_COMPRESSION','BSL_PROBE_REATTACK'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['PRICE_LED','DIRECT_BUILD'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED'],takerExtreme:true},observed:{sampledAt:'2026-09-23',source:'Binance USDT perpetual',dna:'TAKE_TAKER_COMPRESSION_IGNITION',compressionPrice:'0.060~0.061',leadHours:2,triggerTaker:[1.6425,1.6312],triggerRule:'taker>=1.5 for 2 consecutive 1H windows while price remains compressed',preT0OiPct:0.24,t0Definition:'first abnormal-volume bullish displacement, not the later largest pump candle',t0BarPct:33.37,t0Rvol20:30.06,onset1hRvolLargestIgnition:42.73,oiRole:'confirmation/expansion rather than earliest lead signal',maxIgnition1hPct:64.35,observed24hPct:229.58,htfContext:'1D/12H bullish before ignition',smcPath:'NO_SWEEP_COMPRESSION -> BSL_BREAK -> BULLISH_DISPLACEMENT -> FVG/EXPANSION',bookNote:'single HTF rejection candle must not veto strong LTF flow confirmation',scannerRule:'taker>=1.5 x2 + price<=5% expansion + RVOL>=3 triggers early warning; OI rise upgrades ignition confirmation'}},
  {name:'ORCA',label:'ORCA · 장기저항 돌파→S/R Flip 리테스트→taker 재점화형',expected:{archetype:['B','A+B'],sweep:['SSL_SWEEP_RECLAIM','FAILED_BREAK_REBUILD','NO_SWEEP_COMPRESSION'],maCluster:['TIGHT','NEAR'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['PRICE_LED','DIRECT_BUILD','CLEAN_REBUILD'],htfTransition:['HTF_ALIGNED','LTF_LEADS_HTF'],takerExtreme:true},observed:{sampledAt:'2026-09-24',source:'Binance USDT perpetual',dna:'ORCA_SR_FLIP_TAKER_REIGNITION',breakoutLevel:1.498,retestLow:1.490,observedMark:1.54406,breakoutRvolMedian:17.83,retestVolumeRatio5dVsPrev20d:0.51,oi48hPct:5.24,oi12hPct:-0.20,oi3hPct:-0.02,oi1hPct:1.19,taker24hAvg:0.973,taker6hAvg:0.975,taker90mAvg:1.24,taker30mAvg:3.828,funding:-0.00000389,htfContext:'3D HH-HL; price above 1D EMA20/50/112/224; 1D retest above long breakout zone',ltfContext:'2H HH-HL; 1H volume contraction; 15m/5m bullish FVG around 1.524~1.537 and 5m HH-HL',bookPattern:'resistance breakout -> S/R flip retest -> volume contraction -> confirmation/re-ignition',smcPath:'BREAKOUT -> 1.490 liquidity probe/retest -> RECLAIM -> BULLISH FVG -> LTF REIGNITION',invalidation:'sustained 1H/4H closes below 1.490~1.498 weaken S/R flip thesis',scannerRule:'HTF resistance breakout with RVOL>=3; retest within ~2%; retest volume<=0.7x; then 15m/5m taker>1 while 12h OI is non-explosive',note:'장기 저항 돌파 때 거래량이 크게 증가한 뒤 돌파선 1.49~1.50을 재시험하고 거래량이 감소했다. 이후 단기 taker가 먼저 급증하고 OI는 장기 누적 대비 단기 중립에 가까운 재점화 초기 샘플.'}},
  {name:'SOON',label:'SOON · 1H 리셋→15m taker/OI 선행 재점화형',expected:{archetype:['B','A+B','A'],reset:['HTF_RESET_LTF_REIGNITION','15M_RESET_5M_REIGNITION','RESET_WAIT'],maCluster:['TIGHT','NEAR'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','PRICE_LED','CLEAN_REBUILD'],htfTransition:['LTF_LEADS_HTF'],takerExtreme:true},observed:{sampledAt:'2026-09-24',source:'Binance USDT perpetual',dna:'SOON_RESET_LTF_TAKER_OI_BUILD',stage:'IGNITION_WAIT',observedMark:0.19651961,h1Rsi:23.4,m15Rsi:66.2,m15Rvol:2.23,oi1hPct:0.74,oi3hPct:1.25,oi6hPct:1.89,taker15m:2.695,taker1hAvg:1.538,taker3hAvg:2.606,funding:0.00005,keySupport:0.1899,triggerZone:'0.1955~0.1960',spotAvailability:'NO_BINANCE_SPOT',htfContext:'1D above EMA20/60/120; 4H still below EMA20',ltfContext:'1H RSI reset 23.4 -> 15m EMA20/60 reclaim with RVOL 2.23x',scannerRule:'deep 1H reset + 15m RVOL>=2 + taker>=1.5 + gradual positive OI while 4H reclaim remains pending',note:'가격이 아직 크게 진행되지 않은 상태에서 1H 과매도 리셋 뒤 15m 거래량·taker·OI가 먼저 살아난 초기 점화대기 샘플. Binance 현물 부재로 현물 교차검증은 N/A.'}},
  {name:'IMX',label:'IMX · 현물+선물 확인 OI 재가속형',expected:{archetype:['A','A+B','B'],reset:['HTF_RESET_LTF_REIGNITION','15M_RESET_5M_REIGNITION','RESET_WAIT'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','PRICE_LED','CLEAN_REBUILD'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED'],takerExtreme:true},observed:{sampledAt:'2026-09-24',source:'Binance spot + USDT perpetual',dna:'IMX_SPOT_FUTURES_LTF_REACCEL',stage:'IGNITION_EARLY_REACCEL',d1RetPct:15.61,d1Rsi:64.0,d1Ema20DistPct:9.28,h1Rsi:34.3,h1FuturesRvol:1.93,h1SpotRvol:1.37,oi1hPct:1.09,oi3hPct:4.23,oi6hPct:4.91,taker15m:2.331,taker1hAvg:1.746,taker3hAvg:1.471,m15Rsi:72.1,keySupport:'0.1413~0.1418',triggerZone:'0.1491~0.1496',majorResistance:'0.1586~0.1587',htfContext:'1D already +15.61% with EMA20 distance +9.28%',ltfContext:'4H/1H pullback -> 15m/5m buyer flow recovery; spot 1H RVOL 1.37x confirms futures flow',scannerRule:'spot+futures volume confirmation + taker>1.5 + OI 3~6H build; discount when daily extension is already large',note:'현물과 선물이 동시에 확인되지만 일봉이 이미 진행된 상태라 SOON보다 초기성은 낮은 재가속 대조 샘플.'}},
  {name:'NIL-20260924',label:'NIL 2026-09-24 · OI 장기누적→가격확장형',expected:{archetype:['A','A+B','B'],volumeStage:['EXPANSION','IGNITION'],flowType:['DIRECT_BUILD','PRICE_LED'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',dna:'OI_BUILD_PRICE_EXPANSION',change24hPct:39.39,pre6hOiPct:7.09,pre24hOiPct:57.89,pre6hTakerAvg:1.008,t0BarPct:16.89,t0Rvol:2.38,stage:'EXPANSION_OVERHEATED'}},
  {name:'NOM-20260924',label:'NOM 2026-09-24 · OI 과축적+매도우위 폭발형',expected:{archetype:['C','A+B','B'],volumeStage:['IGNITION','EXPANSION'],flowType:['ABSORPTION','DIRECT_BUILD','PRICE_LED'],takerExtreme:false},observed:{sampledAt:'2026-09-24',dna:'OI_BUILD_SELL_SIDE_EXPANSION',change24hPct:36.97,pre6hOiPct:31.20,pre6hTakerAvg:0.883,t0BarPct:29.23,t0Rvol:9.05,stage:'EXPANSION'}},
  {name:'TAKE-20260924-LATE',label:'TAKE 2026-09-24 · 폭발 후 대되밀림 추격금지 대조형',expected:{archetype:['A+B','B','C'],volumeStage:['EXPANSION'],flowType:['PRICE_LED','SQUEEZE'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',dna:'BLOWOFF_POST_SPIKE_RETRACE_CONTROL',change24hPct:18.15,drawdownFrom24hHighPct:-66.8,pre6hOiPct:116.94,pre6hTakerAvg:1.115,t0BarPct:64.20,t0Rvol:35.91,stage:'POST_SPIKE_RETRACE'}},
  {name:'SAGA-20260924',label:'SAGA 2026-09-24 · 조용한 가격→OI 구축→RVOL 돌파형',expected:{archetype:['A','A+B','B'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',dna:'OI_BUILD_RVOL_BREAKOUT',change24hPct:17.97,pre6hPricePct:-1.64,pre6hOiPct:2.39,pre6hTakerAvg:0.990,t0BarPct:7.12,t0Rvol:3.27,stage:'EXPANSION'}},
  {name:'BTW-20260924',label:'BTW 2026-09-24 · OI 감소→가격 squeeze 확장형',expected:{archetype:['C','B','A+B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['SQUEEZE','PRICE_LED'],reset:['HTF_RESET_LTF_REIGNITION']},observed:{sampledAt:'2026-09-24',dna:'DELEVERAGING_SQUEEZE_PRICE_LED',change24hPct:10.07,pre6hPricePct:-1.41,pre6hOiPct:-3.55,pre6hTakerAvg:1.062,t0BarPct:4.87,t0Rvol:2.29,stage:'EXPANSION'}},
  {name:'ZRO-20260924',label:'ZRO 2026-09-24 · RVOL 돌파+OI 구축 상단유지형',expected:{archetype:['A','A+B','B'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],sweep:['BSL_PROBE_REATTACK','NO_SWEEP_COMPRESSION'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',dna:'RVOL_BREAKOUT_OI_BUILD',change24hPct:10.98,pre6hOiPct:2.20,pre6hTakerAvg:0.990,t0BarPct:4.77,t0Rvol:6.03,drawdownFrom24hHighPct:-0.9,stage:'CONTINUATION_NEAR_HIGH'}},
  {name:'KMNO-20260924',label:'KMNO 2026-09-24 · HTF 강세+LTF 리셋 재점화형',expected:{archetype:['C','B','A+B'],reset:['HTF_RESET_LTF_REIGNITION','15M_RESET_5M_REIGNITION'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['CLEAN_REBUILD','PRICE_LED'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',dna:'HTF_STRONG_LTF_RESET_CONTINUATION',change24hPct:8.50,pre6hPricePct:-0.68,pre6hOiPct:0.18,pre24hOiPct:-9.28,pre6hTakerAvg:0.967,t0BarPct:4.58,t0Rvol:1.40,stage:'REIGNITION'}},
  {name:'US-20260924',label:'US 2026-09-24 · 가격선행/파생확인 약한 돌파형',expected:{archetype:['B','A+B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['PRICE_LED','OBSERVE'],htfTransition:['LTF_LEADS_HTF']},observed:{sampledAt:'2026-09-24',dna:'PRICE_LED_LOW_DERIVATIVE_CONFIRMATION',change24hPct:9.33,pre6hOiPct:-0.71,pre6hTakerAvg:0.829,t0BarPct:2.90,t0Rvol:1.98,drawdownFrom24hHighPct:-0.6,stage:'CONTINUATION_NEAR_HIGH'}},
  {name:'CAP-20260924',label:'CAP 2026-09-24 · OI 구축+매도흡수 4H 돌파형',expected:{archetype:['C','A+B','B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['ABSORPTION','DIRECT_BUILD'],htfTransition:['LTF_LEADS_HTF']},observed:{sampledAt:'2026-09-24',dna:'OI_BUILD_SELL_ABSORPTION_BREAKOUT',change24hPct:6.98,pre6hOiPct:2.27,pre6hTakerAvg:0.854,t0BarPct:4.04,t0Rvol:2.26,stage:'LTF_EXPANSION_HTF_TRANSITION'}},
  {name:'STABLE-20260924',label:'STABLE 2026-09-24 · 약세가격+OI 구축→반전형',expected:{archetype:['C','A+B','B'],volumeStage:['ABSORPTION','PRE_SPARK','IGNITION'],flowType:['ABSORPTION','CLEAN_REBUILD'],htfTransition:['LTF_LEADS_HTF','BASE_BUILD']},observed:{sampledAt:'2026-09-24',dna:'OI_BUILD_SELL_ABSORPTION_REVERSAL',change24hPct:9.20,pre6hPricePct:-3.19,pre6hOiPct:3.10,pre6hTakerAvg:0.941,t0BarPct:3.90,t0Rvol:2.29,stage:'EARLY_HTF_TRANSITION'}},
  {name:'LSK-20260924',label:'LSK 2026-09-24 · HTF 눌림 후 OI 감소 squeeze 재구성형',expected:{archetype:['C','A','A+B'],sweep:['FAILED_BREAK_REBUILD','SSL_SWEEP_RECLAIM'],reset:['RESET_WAIT','HTF_RESET_LTF_REIGNITION'],flowType:['SQUEEZE','CLEAN_REBUILD'],volumeStage:['PRE_SPARK','IGNITION']},observed:{sampledAt:'2026-09-24',dna:'SQUEEZE_REBUILD_AFTER_HTF_PULLBACK',change24hPct:7.45,pre6hOiPct:-3.18,pre6hTakerAvg:0.982,t0BarPct:4.46,t0Rvol:2.24,stage:'REBUILD'}},
  {name:'RAYSOL-20260924',label:'RAYSOL 2026-09-24 · 대규모 OI 구축+매도흡수 확장형',expected:{archetype:['C','A+B','A'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['ABSORPTION','DIRECT_BUILD'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',dna:'HEAVY_OI_BUILD_SELL_ABSORPTION',change24hPct:8.69,pre6hOiPct:36.76,pre24hOiPct:48.65,pre6hTakerAvg:0.872,t0BarPct:4.21,t0Rvol:2.80,stage:'EXPANSION_WITH_LEVERAGE'}},
  {name:'ZEST-20260924',label:'ZEST 2026-09-24 · OI 구축 후 과열확장형',expected:{archetype:['A','A+B','B'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',dna:'OI_BUILD_PRICE_EXPANSION',change24hPct:8.23,pre6hOiPct:8.11,pre24hOiPct:32.0,pre6hTakerAvg:0.924,t0BarPct:4.62,t0Rvol:2.54,stage:'OVERHEATED_EXPANSION'}},
  {name:'XNY-20260924',label:'XNY 2026-09-24 · OI+taker 동시선행→42x RVOL 점화형',expected:{archetype:['A','A+B','B'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],htfTransition:['LTF_LEADS_HTF','HTF_ALIGNED'],takerExtreme:true},observed:{sampledAt:'2026-09-24',dna:'OI_TAKER_PRE_SURGE_RVOL_IGNITION',change24hPct:5.81,pre6hPricePct:3.94,pre6hOiPct:7.13,pre6hTakerAvg:1.427,pre24hTakerAvg:1.171,t0BarPct:11.53,t0Rvol:42.08,stage:'POST_IGNITION_PULLBACK'}},
  {name:'TRIA-20260924',label:'TRIA 2026-09-24 · OI 선행+초대형 RVOL 초기확장형',expected:{archetype:['A','A+B','B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','PRICE_LED'],htfTransition:['LTF_LEADS_HTF']},observed:{sampledAt:'2026-09-24',dna:'OI_BUILD_HUGE_RVOL_BREAKOUT',change24hPct:6.64,pre6hOiPct:6.01,pre6hTakerAvg:1.073,t0BarPct:1.87,t0Rvol:33.14,stage:'EARLY_EXPANSION'}},
  {name:'STEEM-20260924',label:'STEEM 2026-09-24 · OI 급감→17x RVOL 숏스퀴즈형',expected:{archetype:['C','B','A+B'],volumeStage:['IGNITION','EXPANSION'],flowType:['SQUEEZE','PRICE_LED'],sweep:['SSL_SWEEP_RECLAIM','FAILED_BREAK_REBUILD']},observed:{sampledAt:'2026-09-24',dna:'DELEVERAGING_SHORT_SQUEEZE_IGNITION',change24hPct:7.50,pre6hPricePct:-0.45,pre24hPricePct:-3.61,pre6hOiPct:-7.26,pre24hOiPct:-19.12,pre6hTakerAvg:1.045,t0BarPct:8.55,t0Rvol:17.65,drawdownFrom24hHighPct:-0.5,stage:'FRESH_BREAKOUT_NEAR_HIGH'}},
  {name:'NIL-20260924-SCAN2',label:'NIL 2026-09-24 S2 · 뉴스+RVOL 선행→OI 후행 폭증형',expected:{archetype:['A','A+B','B'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',source:'Binance spot + USDT perpetual',dna:'NEWS_RVOL_LEAD_OI_LATE_EXPANSION',change24hPct:45.382,spotChange24hPct:39.162,futuresQuoteVol24h:414075576.96,spotQuoteVol24h:36731187.95,futuresSpotVolumeRatio:11.27,t0Kst:'2026-09-22 17:00',t0BarPct:3.04,t0Rvol:2.50,pre6hPricePct:2.92,pre6hOiPct:1.20,pre6hTakerAvg:0.972,currentOi1hPct:2.60,currentOi3hPct:22.07,currentOi6hPct:87.79,currentTaker1hAvg:1.034,d1Rvol:25.55,catalystType:'PROJECT_ROADMAP_PLUS_FLOW',catalyst:'Nillion Encrypted Markets/Dusk roadmap; Ethereum mainnet milestone scheduled for Sep 28, then leverage expanded after volume breakout',catalystUrl:'https://nillion.com/roadmap/',stage:'OVERHEATED_EXPANSION'}},
  {name:'NOM-20260924-SCAN2',label:'NOM 2026-09-24 S2 · OI 폭증+매도흡수 확장형',expected:{archetype:['A','A+B','C'],volumeStage:['IGNITION','EXPANSION'],flowType:['ABSORPTION','DIRECT_BUILD','PRICE_LED'],takerExtreme:false},observed:{sampledAt:'2026-09-24',source:'Binance spot + USDT perpetual',dna:'OI_SURGE_SELL_ABSORPTION_EXPANSION',change24hPct:35.331,spotChange24hPct:37.356,futuresQuoteVol24h:57344775.26,spotQuoteVol24h:15101354.43,futuresSpotVolumeRatio:3.80,t0Kst:'2026-09-23 18:00',t0BarPct:3.36,t0Rvol:3.96,pre6hPricePct:0.51,pre6hOiPct:1.53,pre6hTakerAvg:0.935,currentOi1hPct:2.28,currentOi3hPct:51.49,currentOi6hPct:57.28,currentTaker1hAvg:0.951,catalystType:'FLOW_DRIVEN_NO_VERIFIED_FRESH_NEWS',catalyst:'No same-day project catalyst verified; price expansion occurred while taker stayed sell-dominant and OI exploded, consistent with passive absorption plus leveraged squeeze',stage:'EXPANSION_LEVERAGE_HEAVY'}},
  {name:'TAKE-20260924-SCAN2',label:'TAKE 2026-09-24 S2 · 본폭발 후 OI 청산 되밀림형',expected:{archetype:['C','B','A+B'],volumeStage:['EXPANSION'],flowType:['PRICE_LED','SQUEEZE'],reset:['RESET_WAIT']},observed:{sampledAt:'2026-09-24',source:'Binance USDT perpetual; Binance spot N/A',dna:'POST_BLOWOFF_OI_UNWIND_CONTROL',change24hPct:18.121,spotAvailability:'NO_BINANCE_SPOT',t0Kst:'2026-09-23 14:00',t0BarPct:33.37,t0Rvol:36.74,pre6hPricePct:0.51,pre6hOiPct:0.73,pre6hTakerAvg:1.079,currentOi1hPct:4.84,currentOi3hPct:-9.93,currentOi6hPct:-12.30,currentTaker1hAvg:0.960,h1Rsi:7.4,high24h:0.2147,currentArea:0.071,catalystType:'PRIOR_FLOW_IGNITION_POST_SURGE',catalyst:'Current +24h print is residual from the earlier explosive TAKE episode; price has already retraced sharply while multi-hour OI unwinds',stage:'POST_SURGE_RETRACE'}},
  {name:'SAGA-20260924-SCAN2',label:'SAGA 2026-09-24 S2 · 디레버리징→숏커버 확장형',expected:{archetype:['C','B','A+B'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['SQUEEZE','PRICE_LED','CLEAN_REBUILD'],reset:['HTF_RESET_LTF_REIGNITION']},observed:{sampledAt:'2026-09-24',source:'Binance spot + USDT perpetual',dna:'DELEVERAGING_SHORT_COVER_EXPANSION',change24hPct:18.005,spotChange24hPct:18.207,futuresQuoteVol24h:136634169.66,spotQuoteVol24h:24348135.95,futuresSpotVolumeRatio:5.61,t0Kst:'2026-09-23 01:00',t0BarPct:3.04,t0Rvol:2.87,pre6hPricePct:-3.45,pre6hOiPct:-4.70,pre6hTakerAvg:1.047,currentOi1hPct:-1.24,currentOi3hPct:-3.56,currentOi6hPct:-7.55,currentTaker1hAvg:1.002,catalystType:'FLOW_DRIVEN_NO_VERIFIED_FRESH_NEWS',catalyst:'Price rose while OI kept contracting and taker stayed near neutral; strongest fit is deleveraging/short-cover rather than fresh long build',stage:'SQUEEZE_EXPANSION'}},
  {name:'BTW-20260924-SCAN2',label:'BTW 2026-09-24 S2 · 디레버리징 리셋→OI 재구축형',expected:{archetype:['C','A','A+B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['SQUEEZE','CLEAN_REBUILD','DIRECT_BUILD'],reset:['HTF_RESET_LTF_REIGNITION']},observed:{sampledAt:'2026-09-24',source:'Binance USDT perpetual; Binance spot N/A',dna:'DELEVERAGE_RESET_OI_REBUILD',change24hPct:13.876,spotAvailability:'NO_BINANCE_SPOT',t0Kst:'2026-09-23 14:00',t0BarPct:4.87,t0Rvol:2.40,pre6hPricePct:-3.07,pre6hOiPct:-3.55,pre6hTakerAvg:1.062,currentOi1hPct:-1.33,currentOi3hPct:1.14,currentOi6hPct:3.57,currentTaker1hAvg:1.033,catalystType:'FLOW_DRIVEN_NO_VERIFIED_FRESH_NEWS',catalyst:'Initial cleanup/deleveraging was followed by price recovery and modest OI rebuild; no fresh same-day project catalyst verified',stage:'REBUILD_CONTINUATION'}},
  {name:'ZRO-20260924-SCAN2',label:'ZRO 2026-09-24 S2 · 기관 스테이블코인 내러티브+RVOL/OI 확장형',expected:{archetype:['A','A+B','B'],volumeStage:['IGNITION','EXPANSION'],flowType:['DIRECT_BUILD','PRICE_LED'],sweep:['BSL_PROBE_REATTACK','NO_SWEEP_COMPRESSION'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',source:'Binance spot + USDT perpetual',dna:'NARRATIVE_RVOL_OI_CONTINUATION',change24hPct:11.070,spotChange24hPct:10.994,futuresQuoteVol24h:144728633.40,spotQuoteVol24h:34550512.40,futuresSpotVolumeRatio:4.19,t0Kst:'2026-09-22 21:00',t0BarPct:5.18,t0Rvol:3.80,pre6hPricePct:0.92,pre6hOiPct:1.13,pre6hTakerAvg:1.043,currentOi1hPct:3.66,currentOi3hPct:11.78,currentOi6hPct:7.80,currentTaker1hAvg:1.019,catalystType:'VERIFIED_PROJECT_NEWS_PLUS_FLOW',catalyst:'Anchorage Digital selected LayerZero as preferred interoperability layer for regulated stablecoin issuance; breakout volume and OI expansion amplified the repricing',catalystUrl:'https://layerzero.network/blog/anchorage-selects-layerzero-for-stablecoins',stage:'CONTINUATION_NEAR_HIGH'}},
  {name:'US-20260924-SCAN2',label:'Talus US 2026-09-24 S2 · 깊은 디레버리징→매도흡수 반등형',expected:{archetype:['C','B','A+B'],volumeStage:['ABSORPTION','PRE_SPARK','IGNITION'],flowType:['ABSORPTION','SQUEEZE','CLEAN_REBUILD'],reset:['HTF_RESET_LTF_REIGNITION']},observed:{sampledAt:'2026-09-24',source:'Binance USDT perpetual; Binance spot N/A',dna:'DEEP_DELEVERAGING_SELL_ABSORPTION_REVERSAL',change24hPct:9.897,spotAvailability:'NO_BINANCE_SPOT',t0Kst:'2026-09-22 20:00',t0BarPct:2.87,t0Rvol:2.38,pre6hPricePct:-7.51,pre6hOiPct:-7.27,pre6hTakerAvg:0.669,currentOi1hPct:1.55,currentOi3hPct:0.19,currentOi6hPct:2.48,currentTaker1hAvg:0.677,m15Rvol:3.75,catalystType:'FLOW_DOMINANT_WITH_BACKGROUND_AI_NARRATIVE',catalyst:'No same-day catalyst verified. Deep leverage cleanup plus price resilience despite sell-dominant taker suggests passive absorption/short-cover; Talus AI-agent mainnet/API updates are background narrative only',catalystUrl:'https://blog.talus.network/talus-protocol-v2-0-release-trustworthy-ai-agents-live-on-sui-mainnet/',stage:'ABSORPTION_SQUEEZE'}},
  {name:'STABLE-20260924-SCAN2',label:'STABLE 2026-09-24 S2 · OI 선행→taker 전환 신규롱 점화형',expected:{archetype:['A','A+B','C'],volumeStage:['ABSORPTION','PRE_SPARK','IGNITION'],flowType:['ABSORPTION','DIRECT_BUILD','CLEAN_REBUILD'],htfTransition:['LTF_LEADS_HTF','BASE_BUILD']},observed:{sampledAt:'2026-09-24',source:'Binance USDT perpetual; Binance spot N/A',dna:'OI_BUILD_TAKER_FLIP_IGNITION',change24hPct:9.336,spotAvailability:'NO_BINANCE_SPOT',t0Kst:'2026-09-24 04:00',t0BarPct:3.90,t0Rvol:2.28,pre6hPricePct:-2.85,pre6hOiPct:3.10,pre6hTakerAvg:0.941,currentOi1hPct:4.74,currentOi3hPct:6.83,currentOi6hPct:13.54,currentTaker15m:1.398,currentTaker1hAvg:1.253,h1Rvol:3.37,catalystType:'DERIVATIVES_LED_NO_VERIFIED_FRESH_NEWS',catalyst:'OI accumulated before the breakout, then taker flipped above 1 with rising 1H volume; no same-day project catalyst verified',stage:'FRESH_IGNITION'}},
  {name:'KMNO-20260924-SCAN2',label:'KMNO 2026-09-24 S2 · 거래량 선행 계단식 OI 구축형',expected:{archetype:['A','A+B','B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','CLEAN_REBUILD'],htfTransition:['HTF_ALIGNED','LTF_LEADS_HTF']},observed:{sampledAt:'2026-09-24',source:'Binance spot + USDT perpetual',dna:'VOLUME_FIRST_STAIRCASE_OI_BUILD',change24hPct:9.278,spotChange24hPct:9.314,futuresQuoteVol24h:13372239.19,spotQuoteVol24h:3888154.39,futuresSpotVolumeRatio:3.44,t0Kst:'2026-09-23 23:00',t0Definition:'highest volume-energy 1H bar; move was staircase rather than one explosive T0',t0BarPct:1.04,t0Rvol:6.10,pre6hPricePct:2.44,pre6hOiPct:2.53,pre6hTakerAvg:1.151,currentOi1hPct:8.49,currentOi3hPct:12.88,currentOi6hPct:12.51,currentTaker1hAvg:1.427,m15Rvol:3.49,catalystType:'FLOW_PLUS_INSTITUTIONAL_NARRATIVE',catalyst:'Volume expanded before price acceleration, then OI/taker built in steps. Recent institutional-expansion narrative is supportive but not treated as a proven same-day trigger',stage:'STAIRCASE_REIGNITION'}},
  {name:'RAYSOL-20260924-SCAN2',label:'RAY/RAYSOL 2026-09-24 S2 · 생태계 내러티브+OI 청산 squeeze형',expected:{archetype:['C','B','A+B'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],flowType:['SQUEEZE','PRICE_LED','CLEAN_REBUILD'],htfTransition:['HTF_ALIGNED']},observed:{sampledAt:'2026-09-24',source:'Binance RAYSOL perpetual + RAY spot proxy',dna:'NARRATIVE_DELEVERAGING_SQUEEZE_CONTINUATION',change24hPct:8.984,spotChange24hPct:8.608,futuresQuoteVol24h:112348011.24,spotQuoteVol24h:19572484.61,futuresSpotVolumeRatio:5.74,t0Kst:'2026-09-23 19:00',t0BarPct:2.74,t0Rvol:2.75,pre6hPricePct:-1.58,pre6hOiPct:-2.17,pre6hTakerAvg:1.087,currentOi1hPct:1.08,currentOi3hPct:-2.37,currentOi6hPct:-13.56,currentTaker1hAvg:1.022,h4Rvol:2.43,catalystType:'OLDER_PROTOCOL_CATALYST_PLUS_CURRENT_SQUEEZE',catalyst:'StonkFun routed launches through Raydium LaunchLab and fee/buyback narrative remained a tailwind; current leg shows OI contraction, so the immediate move is more squeeze/deleveraging than fresh long build',catalystUrl:'https://www.theblock.co/news/defi/2026-09-06-stonk-surges-250-to-140-million-market-cap-as-stock-paired-solana-launchpad-stonkfun-pulls-volume-to-raydium-and-jupiter-413621',stage:'SQUEEZE_CONTINUATION'}},
  {name:'LINK',label:'LINK · HTF 정렬 후 거래량 점화형',expected:{archetype:['A','A+B','B'],volumeStage:['PRE_SPARK','IGNITION'],flowType:['DIRECT_BUILD','OBSERVE'],htfTransition:['HTF_ALIGNED']}}
]);

const WEIGHTS=Object.freeze({archetype:24,sweep:18,time15:14,time1h:12,reset:14,cleanup:8,xoi:6,takerExtreme:4,maCluster:16,volumeStage:18,flowType:16,htfTransition:10});
function boolMatch(expected,actual){return expected===undefined?null:Boolean(expected)===Boolean(actual)}
function listMatch(expected,actual){if(!Array.isArray(expected)||!expected.length)return null;return expected.includes(actual)}
function compareOne(sample,features={}){
  const e=sample.expected||{}, checks=[
    ['archetype',listMatch(e.archetype,features.archetype)],
    ['sweep',listMatch(e.sweep,features.sweepKey)],
    ['time15',listMatch(e.time15,features.time15Key)],
    ['time1h',listMatch(e.time1h,features.time1hKey)],
    ['reset',listMatch(e.reset,features.resetKey)],
    ['cleanup',boolMatch(e.cleanup,features.cleanup)],
    ['xoi',boolMatch(e.xoi,features.xoi)],
    ['takerExtreme',boolMatch(e.takerExtreme,features.takerExtreme)],
    ['maCluster',listMatch(e.maCluster,features.maClusterKey)],
    ['volumeStage',listMatch(e.volumeStage,features.volumeStage)],
    ['flowType',listMatch(e.flowType,features.flowType)],
    ['htfTransition',listMatch(e.htfTransition,features.htfTransition)]
  ];
  let got=0,total=0;const matched=[],missed=[];
  for(const [k,result] of checks){if(result===null)continue;const w=WEIGHTS[k]||1;total+=w;if(result){got+=w;matched.push(k)}else missed.push(k)}
  const score=total?Math.round((got/total)*100):0;
  return{name:sample.name,label:sample.label,score,matched,missed};
}
const NEGATIVE_SAMPLE_LIBRARY=Object.freeze([
  {name:'ZAMA-CONTROL',label:'ZAMA 대조군 · 가격상승/OI 비동행',expected:{flowType:['SQUEEZE','PRICE_LED'],volumeStage:['EXPANSION','PRE_SPARK'],maCluster:['WIDE','NEAR']}},
  {name:'BCH-CONTROL',label:'BCH 대조군 · 파생 선행 거의 없는 현물/가격 돌파형',expected:{flowType:['PRICE_LED','OBSERVE'],volumeStage:['PRE_SPARK','IGNITION','EXPANSION'],maCluster:['NEAR','WIDE']},observed:{sampledAt:'2026-09-23',source:'Binance USDT perpetual',dna:'SPOT_PRICE_LED_CONTROL',pre24hPricePct:-0.29,pre24hOiPct:-0.82,pre24hTakerAvg:1.02,t0BarPct:1.34,t0Rvol:3.74,note:'OI/taker 선행이 거의 없어 파생 기반 스캐너가 놓칠 수 있는 대조군'}},
  {name:'BTW-CONTROL',label:'BTW 대조군 · RVOL 반복/OI 감소형',expected:{flowType:['SQUEEZE','PRICE_LED'],volumeStage:['EXPANSION','IGNITION','PRE_SPARK'],maCluster:['TIGHT','NEAR','WIDE']}}
]);
function compareSampleLibrary(features={},limit=3){
  return SAMPLE_LIBRARY.map(s=>compareOne(s,features)).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,Math.max(1,Number(limit)||3));
}
function compareNegativeSampleLibrary(features={},limit=2){
  return NEGATIVE_SAMPLE_LIBRARY.map(s=>compareOne(s,features)).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,Math.max(1,Number(limit)||2));
}
module.exports={SAMPLE_LIBRARY,NEGATIVE_SAMPLE_LIBRARY,compareSampleLibrary,compareNegativeSampleLibrary};
